### ISSUE TITLE
Grid: Cannot read property 'doSelection' of undefined

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/flow-components#1003]
**Problem**

Getting `(TypeError) : Cannot read property 'doSelection' of undefined` when selecting an item and detaching grid.

**Code to reproduce:**

```
List<String> list = Arrays.asList("one", "two", "three");
Grid<String> grid = new Grid<>();
grid.addColumn(String::toString);
grid.setItems(list);

grid.setSelectionMode(Grid.SelectionMode.MULTI);

NativeButton btRm = new NativeButton("detach", evt -> {
    // This line fixes the issue
    // grid.getDataProvider().refreshAll();
    grid.select(list.get(0));
    remove(grid);
});
NativeButton btattach = new NativeButton("attach", evt -> add(grid));

add(grid, btRm, btattach);
```

**Steps to reproduce**
1. Open the example 
2. Select second item (`two`)
3. Click `detach`
4. Click `attach`

**How it looks like:**
![bug-selection](https://user-images.githubusercontent.com/29372419/117963723-65ed1780-b329-11eb-9cc1-4e1e99f6f5ab.gif)

**Comment by hedyn** [comment]
I got the same case

**Comment by tomivirkki** [comment]
Confirmed this is still an issue in V23.1. The error occurs [here](https://github.com/vaadin/flow-components/blob/4ff9d1a5fb8f209925db908e19ff01ef79999586/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java#L2770): `this.$connector` doesn't yet exist when it's being accessed by the function call.

**Comment by estronque** [comment]
Hello, is there any new news about this issue? 
Is there any workaround to avoid this exception? 
Can we at least avoid the exception window on the top right?
