### ISSUE TITLE
TreeGrid scrollToIndex problem on large tree with expanded nodes

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/flow-components#1016]
### Description
TreeGrid scrollToIndex is not working properly on a large tree with expanded nodes. 

### Steps to reproduce
In a 14.4.10 project, add the following to a view and click on the button

```
TreeGrid<String> grid = new TreeGrid<>();
grid.addHierarchyColumn(String::toString).setHeader("Name");
TreeData<String> td = grid.getTreeData();
td.addItem(null, "root");
for (int i = 0; i < 100; i++) {
    td.addItem("root", "child " + i);
    for (int k = 0; k < 100; k++) {
        td.addItem("child " + i, "grand-child " + i + "-" + k);
    }
}
Button button = new Button("Expand and scroll to index 500", e -> {
    grid.expandRecursively(Stream.of("root"), 2);
    grid.scrollToIndex(500);
    // UI.getCurrent().beforeClientResponse(grid, ctx -> grid.scrollToIndex(500));
});
add(grid, button);
```

### Expected outcome
The tree expands and the scrolls to index 500

### Actual outcome
The tree expands, but no scrolling occurs.

A second button click is required to scroll to the index. Notice, also that workaround of calling `UI.getCurrent().beforeClientResponse(grid, ctx -> grid.scrollToIndex(500));` (which works in the case of shallow trees) doesn't seem to work with large trees with expanded nodes.

**Comment by sosa-vaadin** [comment]
Due to the difficulties encountered when using the `scrollToIndex(int)` method with `TreeGrid`, we're discouraging its use with `TreeGrid`. The official documentation for `TreeGrid` and the JavaDoc for the method were updated to warn users about these issues.

A [new issue](https://github.com/vaadin/web-components/issues/2228) was opened to eventually provide an implementation with predictable behavior.

**Comment by TatuLund** [comment]
Just pointing earlier comment https://github.com/vaadin/flow-components/issues/1016#issuecomment-829952022

> Introduce eager loading to the tree grid, so that children of an expanded node are always loaded eagerly [Github link](https://github.com/vaadin/vaadin-grid/issues/1914#issuecomment-683806711). That would allow gradually expanding nodes until the specific item is loaded. At that point the grid could identify the scroll position for that item.

This has been effectively done now: https://github.com/vaadin/flow-components/issues/2648
