### ISSUE TITLE
Adding a DateTimePicker to a form ALWAYS causes the binder to report as having changes

### ISSUE THREAD

**Issue by mmoser18** [vaadin/flow-components#1043]
I recently added a DateTimePicker to one of my forms - not to actually pick a date or time but just to display a timestamp (LocalDateTime), i.e. as read-only field.

As I had to learn, for some odd reason this field ALWAYS causes the binder to report as being changed! I only noticed that odd behavior because my app - when leaving the form and the data has changed without saving - will ask the user whether (s)he wants to save or abandon the change(s). As soon as I added the timestamp I am ALWAYS asked, even if I changed nothing.

To reproduce:

Add a DateTime-field to one of your entities (e.g. I used the "Contact"-entity in the Vaadin CRM example application). 
Add the below member variable:
`private LocalDateTime timestamp = LocalDateTime.now();`

If you don't use Lombok you will also have to add a getter-method.

Add a DateTimePicker-field to the corresponding form:
`DateTimePicker timestamp;`

Create and add the form using a read-only binding:
```
timestamp = new DateTimePicker("Timestamp"));
this.binder.forField(timestamp).bind(Contact::getTimestamp, null);
// dont forget to actually add the field to the form...
```
Add some indicator or a log-message that signals whether the binder's hasChanges() is true or false to verify. E.g. I simply switch the Save-button active/inactive depending on binder.hasChanges() - "save" is the Save-button:

`binder.addStatusChangeListener(e -> save.setEnabled(binder.isValid() && binder.hasChanges()));
`
The Save-Button is ALWAYS active because "hasChanges()" always reports true. This is NOT expected and esp. NOT WANTED behavior!

I also started to investigate. The "changed"-state seems to have to do with the fact that the value of the timestamp gets truncated (or rounded?) to minutes when displayed and thus probably isn't the same anymore when compared to the original value. As I said: this is most unwanted behavior and IMHO a bug!

**Comment by sissbruecker** [comment]
I can not reproduce this anymore with Vaadin 14.7.1. It might have been fixed as part of https://github.com/vaadin/flow-components/pull/2099.

I used the following reproduction for the issue:
```java
    public HelloWorldView() {
        TextField nameField = new TextField("Name");
        DateTimePicker dateTimePicker = new DateTimePicker("Date and time");

        Binder<Meeting> binder = new Binder<>(Meeting.class);
        binder.forField(nameField).bind(Meeting::getName, Meeting::setName);
        binder.forField(dateTimePicker).bind(Meeting::getDateTime, Meeting::setDateTime);

        Button setBean = new Button("Set bean", e -> {
            Meeting meeting = new Meeting();
            meeting.setName("Meeting 1");
            meeting.setDateTime(LocalDateTime.now());
            binder.readBean(meeting);
        });

        Button reportStatus = new Button("Report status", e -> {
            System.out.println("Binder has changes: " + binder.hasChanges());
        });

        add(nameField, dateTimePicker, setBean, reportStatus);
    }

    private static class Meeting {
        private String name;
        private LocalDateTime dateTime;

        public String getName() {
            return name;
        }
        public void setName(String name) {
            this.name = name;
        }
        public LocalDateTime getDateTime() {
            return dateTime;
        }
        public void setDateTime(LocalDateTime dateTime) {
            this.dateTime = dateTime;
        }
    }
```
Clicking on "Set bean", and then on "Report status" should print:
```
Binder has changes: false
```
It also works when setting the fields as readonly / not passing a setter to the binding.
