### ISSUE TITLE
Switch htmlValue and value

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/flow-components#1063]
Switch [`setValue`](https://github.com/vaadin/vaadin-flow-components/blob/b34675add5b11b3738aa109bce561360134106a7/vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java#L192), [`getValue`](https://github.com/vaadin/vaadin-flow-components/blob/b34675add5b11b3738aa109bce561360134106a7/vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java#L233) with [`AsHtml#getValue()`](https://github.com/vaadin/vaadin-flow-components/blob/b34675add5b11b3738aa109bce561360134106a7/vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java#L847), [`AsHtml#setValue(String)`](https://github.com/vaadin/vaadin-flow-components/blob/b34675add5b11b3738aa109bce561360134106a7/vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java#L804) logic in order to make it possible to set `htmlValue` by default on flow counter-part instead of operating with Delta.

Desired outcome: Possibility to set html value string with `setValue` and get it with `getValue`.

**Comment by rolfsmeds** [comment]
Should the WC value API be changes correspondingly?
