### ISSUE TITLE
header: joining cells from frozen and unfrozen columns results in weird horizontal scrolling

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow-components#1064]
### Description

Creating a header bar with all cells joined into one huge cell results in weird horizontal scrolling on Firefox 83 - the headers don't scroll at all, and the scrollbar "shrinks" as it is dragged towards the right side of the screen. Please see the attached video.

### Expected outcome
Either prevent joining cells from both frozen and unfrozen columns (by throwing an IllegalStateException), or support this case somehow, without breaking horizontal scrolling of the Grid.

### Actual outcome
The Grid's horizontal scrolling is broken on Firefox 83.0.

### Live Demo
See screen recording (attached below)

### Steps to reproduce
1. Unzip and run the attached app
2. Navigate to localhost:8080
3. Try to scroll the Grid horizontally

### Browsers Affected

- [ ] Chrome
- [X] Firefox 83.0
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by web-padawan** [comment]
Closing in favor of #5035 which is essentially the same but for more recent Vaadin version (24.0.5).
