### ISSUE TITLE
Setting server-side locale has no effect on date picker

### ISSUE THREAD

**Issue by vaadin-miki** [vaadin/flow-components#107]
### Code
```
        Locale polish = new Locale("pl", "PL");
        DateTimePicker dateTimePicker = new DateTimePicker(LocalDateTime.now(), polish);
```

### Expected
Date picker shows month names in Polish. It should be supported in Java - https://www.oracle.com/java/technologies/javase/jdk8-jre8-suported-locales.html

### Observed
Date picker shows month names in English. As such, the existence of locale parameter for example in constructor is very confusing.

**Comment by yuriy-fix** [comment]
Closing in favour of https://github.com/vaadin/web-components/issues/3383
