### ISSUE TITLE
[BUG] NPE when Select is configured for EmptySelectionAllowed

### ISSUE THREAD

**Issue by thorbjornsen** [vaadin/flow-components#1085]
**Describe the bug**
Configuring a Select component to allow/use an empty selection causes an NPE. 

**To Reproduce**
Set the flag to true on a select component -> select.setEmptySelectionAllowed( true );
Set the label generator (required for non String(y) objects) -> select.setItemLabelGenerator( <some method> );

Once the view/layout is constructed, the Select code tries to use the label generator on the empty selection item, which was constructed/set earlier in the Select code.. and contains a null object

Fix seems pretty easy -> Select.class in private void updateItem(VaadinItem<T> vaadinItem)

`
        if (this.getItemLabelGenerator() != null) {
            vaadinItem.getElement().setAttribute("label", this.getItemLabelGenerator().apply(item));
        } else if (item == this.emptySelectionItem) {
            vaadinItem.getElement().setAttribute("label", "");
        } else {
            vaadinItem.getElement().removeAttribute("label");
        }
`

Just need to put the check for the emptySelectionItem first, and then check for the label generator.

**Expected behavior**
This shouldn't NPE when trying to use an empty selection.

**Screenshots**

**Desktop (please complete the following information):**
This is going to happen no matter where it's executed.

**Additional context**

**Comment by sosa-vaadin** [comment]
What version of Vaadin got you this error?

**Comment by thorbjornsen** [comment]
Looks like I was using:

        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-spring-boot-starter</artifactId>
            <version>${vaadin.version}</version>
        </dependency>

        <vaadin.version>14.4.1</vaadin.version>

I hadn't tried to use a later version because the client wanted to stay with Vaadin 14.

**Comment by sosa-vaadin** [comment]
This behavior is intentional and we found there is a lack of proper documentation for these cases. We will make an effort to improve our documentation and the method's JavaDoc.

When using `ItemLabelGenerator`, be sure to make it null-safe by checking for null values and providing a label for those. An example will be provided in our docs soon and the related PRs will be linked to this issue for future reference.

I will close this issue once the documentation changes are completed.

**Comment by thorbjornsen** [comment]
Yeah, I worked around it some time ago. I just thought this isn't a case that should have to be worked around. My mistake, intentional behavior that can cause NPEs is an interesting stance ;) Thanks and cheers
