### ISSUE TITLE
Error when uploading a file -> (TypeError) : Converting circular structure to JSON

### ISSUE THREAD

**Issue by HannKes** [vaadin/flow-components#1101]
Hey! I am trying to deploy a Spring Boot and Vaadin 14.3.1 Application in OpenShift.

When i start my application locally, everything is fine. Even when i am building a jar of my application and execute it, i can normally accept files.

When I put this jar inside a container in OpenShift everything except the upload is working. When i drag a file inside the upload component or select one in the menu, my browser throws an error. This error appears Firefox as well as in Chrome and Edge.

Firefox says '(TypeError) : cyclic object value' and Chrome gives a longer message: 
(TypeError) : Converting circular structure to JSON
    --> starting at object with constructor 'M'
    |     property 'dtProps' -> object with constructor 'Object'
    |     property 'upload' -> object with constructor 'M'
    |     property 'dtProps' -> object with constructor 'Object'
    --- property 'Ph' closes the circle

Can anyone tell my, how this could be fixed? I could not find anyone with the same issue.

The problem occurs with and without compatibility mode and with and without production mode.

Unfortunately i can not analyze the error very well because the sourcemap is missing. Can anyone tell me, how i can make the generated JavaScript readable? The error appears in a file like client-xxxxxx.cache.js.

**Comment by web-padawan** [comment]
> The error appears in a file like client-xxxxxx.cache.js.

This means that the error comes from Flow client. Unfortunately, there is not enough information to investigate further.
Closing as stale. In case if anyone else faces this, please submit a new issue according to the template.
