### ISSUE TITLE
Naming of number field controls api is to general and deviating from other similar API

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow-components#1106]
Two things regarding the methods for number field step controls.

1. To activate the step buttons for a number field, the developer has to use the method "setHasControls()", which has a deviating naming regarding to `setClearButtonVisible()` or `setRequiredIndicatorVisible()`. 

2. Also the usage of the term "controls" is a bit too general. It is not clear out of the method names, what controls are meant exactly (since the clear button is somehow also a control). Parallel to that using such a name also blocks potential naming for other, future field controls, that might come.

Therefore the API should be set deprecated and for instance following methods should be added

* `boolean hasStepButtons()` (or `hasStepButtonsVisible()`)
* `void setStepButtonsVisible(boolean)`

**Comment by web-padawan** [comment]
Fixed in Vaadin 24 by the following PRs:

- https://github.com/vaadin/web-components/pull/4973
- https://github.com/vaadin/flow-components/pull/4046

Corresponding APIs are also added in 23.3.0. Closing.
