### ISSUE TITLE
Update to LitElement-based web component version

### ISSUE THREAD

**Issue by pekam** [vaadin/flow-components#1126]
- Bump the web component version to new major 2.0.
- Change the orientation API: remove the theme variant, add `set/getOrientation` methods
- Make sure everything works
  - [Earlier investigation](https://github.com/vaadin/components-team-tasks/issues/518#issuecomment-609713865) revealed that some workaround magic in `RadioButtonGroup::updateEnabled` causes problems when using `setItemEnabledProvider`. This can be noticed by a failing test case. It should be possible to change that logic to something more sensible, which hopefully fixes the bug as well.

**Comment by web-padawan** [comment]
Closing as stale.
