### ISSUE TITLE
Remove workaround in the setLocale() method (issue has been fixed in Chrome)

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/flow-components#1130]
in the current code for `setLocale()`, we have reported and workarounded an issue with using ill-formed locales. 

code=> https://github.com/vaadin/vaadin-date-picker-flow/blob/master/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java#L270-L283

the bug has been fixed: 
https://bugs.chromium.org/p/chromium/issues/detail?id=943544#c11

Tested:
```
chrome 80.0.3987.149
edge chromium 80.0.361.69
firefox 71.0
```

**Comment by yuriy-fix** [comment]
The code seems to be refactored. https://github.com/vaadin/flow-components/blob/b9d3b09bd3c74255fad6c86a02dfff983f6fabd6/vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java#L304
