### ISSUE TITLE
No constraint checking for minimum and maximum

### ISSUE THREAD

**Issue by vaadin-miki** [vaadin/flow-components#1139]
### Code
```
DateTimePicker dateTimePicker = new DateTimePicker(LocalDateTime.now());
dateTimePicker.setMin(LocalDateTime.now().plusWeeks(6));
dateTimePicker.setMax(LocalDateTime.now().plusWeeks(2));
```
### Observed
The component is rendered with red background indicating error (somewhat good). Date cannot be selected - date popup shows all dates as unavailable (good). Time can be selected (bad). Both date and time can be changed by manually typing them. Event is fired then, see vaadin/vaadin-date-time-picker-flow#27 

### Expected
* `IllegalArgumentException` when setting max that is less than min (or when setting min that is more than max - preferred, because exceptions are a good way of telling developers they did something wrong); *or*
* a log message about the fact that minimum and maximum are set wrong; *or*
* consistent behaviour between date and time pickers (time picker's entries should be disabled).

**Comment by yuriy-fix** [comment]
It's working as expected. The order of setting `min` and `max` should not matter, so we cannot throw an exception.
