### ISSUE TITLE
Adding a long text to a resizable dialog makes it expand too much

### ISSUE THREAD

**Issue by anasmi** [vaadin/flow-components#1140]
**Version**: 14.2.0.alpha9
**Scenario**: Add a textarea with a long text.
**Expected** : TextArea is added to the dialog. The dialog is still resizable and positioned as before. 
**Actual** : Dialog expands too much and content jumps. It's not possible to resize by dragging bottom/top of the dialog anymore

---

Code to reproduce: 

```
Dialog dialog=new Dialog();
dialog.setResizable(true);
dialog.add(new TextField("New TextField"));
dialog.add(new Button("Add a TextArea", e->{
     dialog.add(addTextArea());
  }));

Button open=new Button("Open dialog", e-> {
          //Jumps to the middle
           dialog.open();
});
add(open);
add(dialog);
```
![dialog_jumped](https://user-images.githubusercontent.com/15248706/77324259-29262180-6d1f-11ea-9f58-7981e0e3e4a7.JPG)

**Comment by tomivirkki** [comment]
This no longer happens with the latest Vaadin (22 and 14.8):

![Screenshot 2022-02-08 at 13 54 12](https://user-images.githubusercontent.com/1222264/152982170-366b824f-29b1-436f-b485-56e2c6adbed4.png)
