### ISSUE TITLE
Text Alignment API is not easy to use

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/flow-components#1141]
As a user, It is not easy to spot that the text alignment api is in `DTP.addThemeName()` and `algin-center/right/left` are not type safe. 

this API is also a new one compared with `Date-Picker` and `Time-Picker`, so no experience can be borrowed from previous vaadin component usage.

**Comment by web-padawan** [comment]
Fixed by https://github.com/vaadin/flow-components/pull/2887 where `DateTimePickerVariant` enum was added. The fix will land in Vaadin 23.1 (currently in alpha).
