### ISSUE TITLE
Mission Impossible: Theming the Editor & Its Content

### ISSUE THREAD

**Issue by anezthes** [vaadin/flow-components#1151]
The way this component is structured makes it really difficult to theme anything inside the editor slot.

I have my theme's building blocks in CSS (applicable with a Java API) but none of them can be used because of the nested web components. As a Java developer, this makes me incredibly sad. Really, really, sad. SAD!

Anyway we could simplify the structure?

**Comment by web-padawan** [comment]
In Vaadin 23 we changed CRUD to place editor in light DOM so the fields can be styled directly, see screenshots:

<details>
  <summary>Default editor position</summary>

![Screenshot 2022-04-26 at 13 47 11](https://user-images.githubusercontent.com/10589913/165283677-335b11f8-8744-49d4-969a-58774b53f588.png)

</details>

<details>
  <summary>Aside / Bottom editor position</summary>

![Screenshot 2022-04-26 at 13 48 09](https://user-images.githubusercontent.com/10589913/165283851-4f3861d5-12ac-4bc1-a283-2b100c7126b1.png)

</details>

Also the `vaadin-dialog-layout` mentioned above has been removed. Closing the issue as done.
