### ISSUE TITLE
Dialog theme variants and HasTheme missing from Java API

### ISSUE THREAD

**Issue by DiegoCardoso** [vaadin/flow-components#1155]
`<vaadin-dialog>` allows you to define a theme attribute and that is also mapped to its `<vaadin-dialog-overlay>`. 

Dialog Flow doesn't implements `HasTheme` interface and the only way to set a theme to it is by setting the attribute to the element with `dialog.getElement().setAttribute()`.

Suggestion would be to make dialog implements `HasTheme`.

**Comment by web-padawan** [comment]
Done by #589.
