### ISSUE TITLE
Entering invalid value to DatePicker does not show DatePicker as invalid in browser

### ISSUE THREAD

**Issue by tepi** [vaadin/flow-components#1158]
To reproduce the issue:

1. Create a new DatePicker
2. Enter "jksghk" and blur the DatePicker
3. DatePicker looks valid

Additionally, there is no easy way to validate invalid input from Java side and set the DatePicker into invalid mode.

**Comment by SonReimer** [comment]
Will this be available as a (what I think) necessary feature in LTS version 23 ?

**Comment by hfazai** [comment]
I'm using this workaround to fix the issue:
````KOTLIN
val datePicker = DatePicker()

datePicker.element.executeJs(
             """
              this.addEventListener("blur", event => {
                if (this.value == '' && this.$.input.inputElement.value != '') {
                  this.$.input.inputElement.value = ''
                }
              })
              """
)

````

**Comment by nittka** [comment]
Thanks for sharing the snippet. It gives feedback to the user - indicating that something is wrong, but it is not perfect from a user experience perspective: "I entered a value and it is gone..."

The latest date picker version supports custom date formats (primary format is displayed, others are used for alternative parsing) which solves one of our problems (user enters date in other format). THANKS!!
```
DatePicker dp = new DatePicker();
DatePickerI18n i18n = new DatePickerI18n();
i18n.setDateFormats("yyyy-MM-dd", "yy-MM-dd", "dd.MM.yy", "dd.MM.yyyy");
dp.setI18n(i18n);
```
For required date fields, this is OK. A date can be entered in different formats (e.g. copy/paste). If there are format problems the date value is null, the text is still visible and the field is marked as having an error.
For optional date fields the initial problem still persists. I will consider your workaround - maybe rather prefixing the input value with "ERROR" or something.
(Right now we use a wrapper component, replacing the datepicker's text field with a regular text field and the two components inform each other about changes. This is highly fragile and not satisfactory.)

I still consider this a major bug in a fundamental component and hope for a fix.

**Comment by hfazai** [comment]
@nittka You are right. My workaround doesn't provide a good UX.
Are you using vaadin-date-picker-light as a wrapper of a text field?

**Comment by nittka** [comment]
No, we wrote our own (java) component, a layout containing textfield and (default) picker, adapting the styling so that the picker's input field is not shown.

**Comment by cto828** [comment]
> Thank you for this.  I was able to use what you wrote and hack it to just disable the keyboard input on the textfield.  User needs to use the calendar to choose the date so it cannot be in a wrong format.

datePicker.getElement().executeJs("this.$.input.inputElement.readOnly='true'");

I added a else statement to your javascript code to set the text back to black on a good input but for some reason it doesnt seem too responsive and does not always work to change the text back to black.

There is also a addBlurListener (Vaadin 14) that seems to also capture the 'blur' event just fyi.  Hope they just expose the underlying TextField component or somehow make this DatePicker and TimePicker components more user friendly.  The value change event doesnt seem to fire on bad inputs.  -(

> I'm using this workaround to fix the issue:
> 
> ```kotlin
> val datePicker = DatePicker()
> 
> datePicker.element.executeJs(
>              """
>               this.addEventListener("blur", event => {
>                 if (this.value == '' && this.$.input.inputElement.value != '') {
>                   this.$.input.inputElement.value = ''
>                 }
>               })
>               """
> )
> ```
> 
> The value of the field is cleared when it is invalid.

**Comment by hfazai** [comment]
@cto828 Hi, I finally had to use `vaadin-date-picker-light`. Doc:
```
`<vaadin-date-picker-light>` is a customizable version of the `<vaadin-date-picker>` providing
 only the scrollable month calendar view and leaving the input field definition to the user.
```
I used it with a `TextField` which allow the value change event to fire on bad inputs.

**Comment by cdir** [comment]
Vaadin 23 is now released, but this major bug is still not fixed. Is it still on the roadmap for some patch version?

**Comment by hfazai** [comment]
@cto828 I discovered some bugs in `vaadin-date-picker-light` as well, so I don't recommend.
One bug that I'm struggling to fix:
Picking a date X -> Changing the date manually whithout using the picker -> Picking the first date (X) => Value change event is not fired.

@cdir This issue is opened since 4 Mar 2020 and I'm also wondering if there is any plan to be fixed!

**Comment by vursen** [comment]
FYI: We have just introduced new validation behavior aiming to solve many different validation issues that people were complaining about, including this one. The new behavior is available under the feature flag in v23.2 for several components including DatePicker.

To enable the feature flag in your application, add the following to `vaadin-featureflags.properties`:

```
com.vaadin.experimental.enforceFieldValidation=true
```

Any feedback would be highly appreciated. For more details, please refer to https://github.com/vaadin/platform/issues/3066.

**Comment by cdir** [comment]
I would say it works partially or I haven't quite figured out how it's supposed to work yet.

If I use a Binder and a DatePicker and simply set an object via setBean(...), the field becomes invalid as soon as I enter an invalid value. However, nothing is written to the model - I would have expected null to be written to the model. When I then call validate on the binder, it reports OK. If I enter a different value afterwards, the field remains invalid.

However, I don't use a binder in my framework, so it's quite possible that I used it incorrectly in my little test.

Without a binder (in my framework), I can register a ClientValidatedEventListener (addClientValidatedEventListener). This is correctly notified with the feature switch enabled when an invalid value is entered in the UI. (I write null in my model in this case.) However, if I subsequently change the value back to the last valid value, I don't get an event and the field remains invalid. For example: I enter "01/01/2022". I then enter "a01/01/2022" (field becomes invalid). Then I correct the value and remove the 'a', the field remains invalid and I get no event on the server.

I would expect the internal value of the field to be set to null as soon as an invalid entry is made. The incorrectly entered text should remain, otherwise the user will not be able to understand their mistake. However, the field should not simply assume that the last valid value is still the current value.

**Comment by vursen** [comment]
> I would expect the internal value of the field to be set to null as soon as an invalid entry is made.

Yes, that's how it should work and that's actually how it works for me (see the attached example). I tried it both with a binder and without. I wonder what I'm missing 🤔  

https://user-images.githubusercontent.com/5039436/194079879-adf87adc-5b24-4d41-b974-4a8cdedc06d3.mov

```java
@Route(value = "date-picker")
public class DatePickerView extends Div {
    public DatePickerView() {
        Div value = new Div();

        DatePicker datePicker = new DatePicker();
        datePicker.addValueChangeListener(event -> {
            value.setText("Value: " + datePicker.getValue());
        });

        add(datePicker, value);
    }
}
```

P.S When I type in `a1/1/2022`, DatePicker automatically corrects the input to `1/1/2022` which causes it to be valid as expected. Doesn't that work the same way for you?

**Comment by cdir** [comment]
Okay, that's weird. The difference:

    datePicker.setAutoOpen(false);

I hate that the picker always opens when I tab through my application, so I always set auto open to false. If I remove this line, it works. Please tell me how auto open correlates with validation behavior.

**Comment by jouni** [comment]
> I hate that the picker always opens when I tab through my application,

That’s not how it is supposed to work. “Auto open” should only affect “click to focus”, not “tab to focus”.

**Comment by cdir** [comment]
Ok, that's right. Maybe it was different in earlier versions (10 or 14), but this way we could possibly leave it enabled.

But apart from that, I don't understand why the field behaves differently when I disable auto-open. This is still a bug, isn't it?

**Comment by cdir** [comment]
Is it possible that the bug will be fixed? I would like to use the validation but leave auto-open at false.

**Comment by cdir** [comment]
We definitely need a fix in Vaadin 23!

**Comment by vursen** [comment]
> We definitely need a fix in Vaadin 23!

@cdir I apologize for the confusion. It is already there. Please, check out [V23.3.0.beta2](https://github.com/vaadin/platform/releases/tag/23.3.0.beta2)

**Comment by cdir** [comment]
@vursen I just tried vaadin 23.3. Unfortunately I still only get an error when autoOpen=true is set.

**Comment by vursen** [comment]
>  Unfortunately I still only get an error when autoOpen=true is set.

What kind of error did you get? Is it the same problem? Or is it different now?

**Comment by cdir** [comment]
I get no error. There is just no value change event when autoOpen=false while it is triggered with autoOpen=true. So, no different behavior.

**Comment by cdir** [comment]
@vursen sorry for the confusion. I found the problem, there was a version mismatch in my sample. Now it works as expected. Thank you very much.

**Comment by vursen** [comment]
> I found the problem, there was a version mismatch in my sample

I'm glad it worked out. Thank you for testing it.

**Comment by simasch** [comment]
The new feature flag solves this problem but adds another:
The validator is always called twice, and when doing some backend validation with the database, this can cause issues.

My situation:
- binder.setBean is called this executes the validation
- after that the validationStatusChanged event triggers the validation again

**Comment by vursen** [comment]
Hello @simasch! Thank you for your report. It is a sort of known issue for us. However, we haven't had a ticket for that, so there it is: https://github.com/vaadin/flow-components/issues/4390

**Comment by SonReimer** [comment]
@TatuLund :
Enabling feature
com.vaadin.experimental.enforceFieldValidation=true
things work for me as expected
regardless of mentioned #4390 and #4352

**Comment by vursen** [comment]
The issue has been resolved by the [new validation mechanism](https://github.com/vaadin/platform/issues/3066) which is enabled by default in Vaadin 24. For any further bugs, please create separate issues.
