### ISSUE TITLE
Align height width behavior with Vaadin Dialog

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/flow-components#1182]
Width and height API will be fixed to consider the padding in vaadin dialog https://github.com/vaadin/vaadin-dialog-flow/issues/144

Confirm Dialog behavior should behave in the same way.

**Comment by web-padawan** [comment]
Done in https://github.com/vaadin/web-components/pull/3673 and updated ConfirmDialog dimension ITs accordingly, see 041b37587c082b5d344b23ce57dd3c614fce4afa.
