### ISSUE TITLE
Grid recalculateColumnWidths doesn't recalculate on first attempt

### ISSUE THREAD

**Issue by weslowsk** [vaadin/flow-components#1186]
As described in this forum post...

https://vaadin.com/forum/thread/18059426/grid-recalculatecolumnwidths-doesn-t-recalculate-on-first-attempt

Grid does not recalculate column widths after calling it in the click listener of a button. It does recalculate it properly after clicking the button a second time.

**Comment by web-padawan** [comment]
Closing as fixed per above comment.
