### ISSUE TITLE
Bug: Initially invisible items break the layout when shown

### ISSUE THREAD

**Issue by gsedlacz** [vaadin/flow-components#1190]
Description:
When showing an initially hidden `FormItem` it misses the `style` attribute. Because of this its not being displayed correctly.

Example:
![image](https://user-images.githubusercontent.com/33100708/72985881-4144f780-3de7-11ea-92be-224934d6a292.png)

HTML:
![image](https://user-images.githubusercontent.com/33100708/72985663-b82dc080-3de6-11ea-89fc-6b0e7c19fd2a.png)

Code:
```
FormLayout fLayout = new FormLayout();
fLayout.setSizeFull();
fLayout.setResponsiveSteps(new ResponsiveStep("0px", 1));

FormItem brokenItem = fLayout.addFormItem(new Label("missing style attribute"), "bug");
brokenItem.setVisible(false);

fLayout.addFormItem(new Button("show bug", e -> brokenItem.setVisible(true)), "trigger");
        
add(fLayout);
```

**Comment by rolfsmeds** [comment]
This was actually fixed in https://github.com/vaadin/vaadin-form-layout/pull/123
