### ISSUE TITLE
Frozen columns in grid with multiple selection

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/flow-components#1198]
When a grid has multiple selection and the first column is frozen, the column with the checkboxes moves to the left when the grid is scrolled.

![frozen](https://user-images.githubusercontent.com/11554739/71998428-63068200-321e-11ea-9239-98114a322a3b.gif)

```
	Grid<String> grid = new Grid<>();
    	grid.setSelectionMode(SelectionMode.MULTI);
    	grid.addColumn(s->s).setWidth("400px").setHeader("First").setFrozen(true);
    	grid.addColumn(s->s).setWidth("400px").setHeader("Second");
    	grid.addColumn(s->s).setWidth("400px").setHeader("Third");
    	grid.addColumn(s->s).setWidth("400px").setHeader("Fourth");
    	grid.setItems("A","B","C");
```

**Comment by kkleinwi** [comment]
Bump in the hopes of getting someone to work on this.

**Comment by tomivirkki** [comment]
Hi, took another look and discovered there's already an [API for freezing the multi-selection column](https://vaadin.com/api/platform/14.8.2/com/vaadin/flow/component/grid/GridMultiSelectionModel.html#setSelectionColumnFrozen-boolean-):

Example:
```java
((GridMultiSelectionModel<?>) grid
  .setSelectionMode(Grid.SelectionMode.MULTI))
  .setSelectionColumnFrozen(true);
```

Closing

**Comment by kkleinwi** [comment]
Not exactly obvious, but it does indeed work. Thanks!
