### ISSUE TITLE
ListBox missing setCaption

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/flow-components#1211]
@bsutton commented on [Mon Jul 08 2019](https://github.com/vaadin/flow/issues/6033)

I'm using vaadin 14 rc3 and the ListBox component with a data provider.

I was expecting to find a method that allows me to set the caption of each item supplied by the provider. The closest I could find was the render which appears to be complete overkill for a caption.

Expected

```
        UserDao daoUser = new UserDao();
    	List<User> users = daoUser.getAllUsers();
    	
    	colleaguesField.setDataProvider(new ListDataProvider<User>(colleagues));

    	colleaguesField.setCaption(user -> user.getName());
```

**Comment by jcgueriaud1** [comment]
I think it's a duplicate for this https://github.com/vaadin/flow-components/issues/1631

**Comment by web-padawan** [comment]
Support for `listBox.setItemLabelGenerator()` was added in #2275 and will be available in Vaadin 23.
