### ISSUE TITLE
moving focus with tab skips over editor fields

### ISSUE THREAD

**Issue by tmattsso** [vaadin/flow-components#1213]
using editor, like here: https://vaadin.com/components/vaadin-grid/java-examples/grid-editor

If you focus an edit field, tab works on the row. If you move focus one step after the editor (to the next grid) and move back, then the editor fields are skipped completely. Same if you focus manually on anything outside the editor; you can't get back to the editor fields using tab.

**Comment by web-padawan** [comment]
The new demos for Grid editor work properly: https://vaadin.com/docs/latest/ds/components/grid#inline-editing-java-only 

1. When you start editing a row, grid switches to "interacting mode" so you can use <kbd>Tab</kbd> to switch fields,
2. When moving out of the editing row, grid then switches to "navigating" mode where you navigate the grid cells,
3. When moving back, you need to press <kbd>Enter</kbd> to use "interacting" mode again and focus the text field.

Closing as won't fix.
