### ISSUE TITLE
Documentation should show an example with a binder using html

### ISSUE THREAD

**Issue by bsutton** [vaadin/flow-components#1215]
If you use a Binder to bind to a RichTextField you get a Delta formatted object saved to the bean.

We need a documented example of how to use a binder which returns the html version of the field.

**Comment by web-padawan** [comment]
Starting from V24, for the `RichTextEditor` Flow component, the default is the HTML format, which is also used automatically when binding the component with Binder (see also [value format](https://vaadin.com/docs/latest/components/rich-text-editor#value-format) docs). Closing the issue as done.
