### ISSUE TITLE
asRequired method with Binder does not work properly with the tab button

### ISSUE THREAD

**Issue by shadikhani** [vaadin/flow-components#1232]
When I use the code below and I **use the tab button only to tab between components**, the `asRequired` method in binding does not work properly.

```
Person person = new Person();
Binder<Person> binder = new Binder<>();
binder.setBean(person);
TextField textField = new TextField("Name");
binder.forField(textField)
        .asRequired("Please enter your name")
        .bind(Person::getName,
                Person::setName);
```
First Demo:

![FirstDemo](https://user-images.githubusercontent.com/43351116/59509842-dc253d00-8eba-11e9-8942-5f213a2f4311.gif)
Second Demo: 

![SecondDemo](https://user-images.githubusercontent.com/43351116/59509852-e0515a80-8eba-11e9-8ffc-b970f78977b3.gif)

In the FirstDemo.gif when you click on the name field and enter a data and you delete it and you use your tab to go to another component the requirement is not checked.

In the secondDemo.gif when you click on the name field and enter some data and use your mouse to click somewhere out of that text-field area and then select the data and delete it the requirement validation will work.

**Comment by vursen** [comment]
The issue has been resolved by the [new validation mechanism](https://github.com/vaadin/platform/issues/3066) which is enabled by default in Vaadin 24. For any further bugs, please create new issues.
