### ISSUE TITLE
Missing method CheckboxGroup::setRenderer

### ISSUE THREAD

**Issue by FSchliephacke** [vaadin/flow-components#1240]
The title says it all. Most Components seem to have a possibility to set a custom renderer. That functionality is missing for the CheckboxGroup.

**Comment by web-padawan** [comment]
Here is an example of how this is implemented in `RadioButtonGroup`:

https://github.com/vaadin/flow-components/blob/0b2f16457f6957b410ee465a2b96fc44205518f0/vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java#L355-L359
