### ISSUE TITLE
The configure() method of AbstractAppRouterLayout should be called later

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/flow-components#1251]
Besides that calling abstract methods from a constructor could be considered a bad practice, if I need to access (for example) to spring-injected fields from inside it, it wouldn't be possible because the `SpringInstantiator` still didn't have a chance of doing it's magic.
Could be possible to call it later?

**Comment by web-padawan** [comment]
The `AbstractAppRouterLayout` is specific to Bakery starter and we don't have it in Flow components. Closing as stale.
