### ISSUE TITLE
removeAll + addPrimary should behave like initial setup of layout

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow-components#1256]
We have the use case, that initially a split layout only has set a primary component. The splitter is positioned on the right side and cannot be moved as expected.
Depending on user interaction, the secondary component for the split layout is set.

Until here everything is working fine.

In some cases, the split layout needs to be emptied and the primary component is reset. 
We're using `removeAll` and `addToPrimary` for that. The secondary part stays empty, but the splitter does not move back to the right side. Instead it keeps set at its previous position. 

Only adding an invisible placeholder component (e.g. a Span) as secondary component, resets the splitter to the right and let the layout look like as it was in the inital setup.

Expectation here is, that the splitter should be set back to the right position, when the previous components are removed and the primary component is set (without a secondary one)

**Comment by web-padawan** [comment]
Tested this with the latest version and `removeAll()` + `addToPrimary()` works fine. Could be fixed by #5750.
