### ISSUE TITLE
Details: add more constructors for summary text and content

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow-components#1258]
The constructor of the details should align with the constructors of other elements.

Following constellations should be supported:
- `String summaryText` (currently needs an empty constructor plus setSummaryText() call)
- `String summaryText, Component... content` (currently only one content component may be set)
- `Component... content`

**Comment by web-padawan** [comment]
The following constructors need to be added:

- `public Details(String summary)`
- `public Details(Component... components)`
- `public Details(String summary, Component... components)`
