### ISSUE TITLE
TreeGrid breaks when items have the same hashCode

### ISSUE THREAD

**Issue by TomRauchenwald** [vaadin/flow-components#1270]
Sample code:
```
@Route(value = "")
public class TreeTest extends VerticalLayout {
    private final TreeGrid<String> treeGrid = new TreeGrid<>();

    public TreeTest() {
        TreeData<String> stringTreeData = new TreeData<>();
        // "Aa".hashCode() == "BB".hashCode()
        stringTreeData.addItem(null, "Aa");
        stringTreeData.addItem("Aa", "BB");
        treeGrid.setDataProvider(new TreeDataProvider<>(stringTreeData));
        treeGrid.addHierarchyColumn(s -> s);
        treeGrid.expand("Aa");
        add(treeGrid);
    }
}
```

This fails on the client:
![Selection_358](https://user-images.githubusercontent.com/15888440/55380230-e375b500-551f-11e9-9898-5299315f31b3.png)

If one of the strings is changed, everything works fine.

In our application we have this problem with a TreeGrid that displays JPA entites. The user can create new entries in the tree (that do not have an identifier assigned by jpa yet), so they have the same hash code. We want to save those new entities only when the user clicks 'Save'.

It would also break with entities that follow the recommendation of the hibernate developer advocate for implementing hash code: https://vladmihalcea.com/how-to-implement-equals-and-hashcode-using-the-jpa-entity-identifier/

Tested with Vaadin 13.0.3.

**Comment by Traivor** [comment]
I hate to do a #METOO, but closing in on 3 years later, me too. I just reproduced this on 21.0.8.

**Comment by TatuLund** [comment]
The contract of Vaadin components with DataProvider is that bean identity is invariant. I.e. the identity of the bean should not change if the properties change. If you are not using DTO's, but data base entities themselves, typically this is achieved by using this kind of AbstractEntity and extend it by all entities. I.e. identity is defined by the id property alone.

```
@MappedSuperclass
public abstract class AbstractEntity {

    @Id
    @GeneratedValue
    private Integer id;

    public Integer getId() {
        return id;
    }    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public int hashCode() {
        if (id != null) {
            return id.hashCode();
        }
        return super.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof AbstractEntity)) {
            return false; // null or other class
        }
        AbstractEntity other = (AbstractEntity) obj;

        if (id != null) {
            return id.equals(other.id);
        }
        return super.equals(other);
    }
}
```

This is necessary, since otherwise, for example refreshItem or refreshAll methods of DataProvider cannot determine which items are updated. I will comment and close the ticket.

Now, if your data model and business logic is such, that you can't do the above, there is a possibility to define the identity provider in TreeGrid yourself. By extending TreeGrid and override get/setUniqueKeyProvider .

**Comment by javier-godoy** [comment]
The example uses two strings "Aa" and "BB" with the interesting property that `"Aa".hashCode() == "BB".hashCode()`.

I attempted to reproduce the issue with Vaadin 14.7.5 and the browser displayed a warning about the JS execution took too long (Chrome 96), but I wasn't able to obtain a "Maximum stack size exceeded" error.
![image](https://user-images.githubusercontent.com/11554739/145030654-b8440dcf-6f96-4f82-a1e3-95f33afd2ede.png)

**Comment by Traivor** [comment]
In my case equivalent hashCode results in incorrect display, not any noticeable JS errors.

Depending on hashCode to be unique is a bug. Hash collisions are a fact of life.

**Comment by TatuLund** [comment]
The following override can be used as workaround to set alternative identity provider

```
    class MyTreeGrid<T> extends TreeGrid<T> {
        @Override
        protected ValueProvider<T, String> getUniqueKeyProvider() {
            return item -> String.valueOf(getDataProvider().getId(item));
        }
    }
```
