### ISSUE TITLE
Setting splitter position before adding components does not work

### ISSUE THREAD

**Issue by tepi** [vaadin/flow-components#1271]
Given the following code I would expect the splitter to be at 40% but it remains at the default 50% setting:

```
upperSplit = new SplitLayout();
upperSplit.setSplitterPosition(40);
upperSplit.addToPrimary(new VerticalLayout());
upperSplit.addToSecondary(new VerticalLayout());
```

When I move the second line to the end of the snippet, it works as expected.

**Comment by bwajtr** [comment]
Cannot be reproduced anymore (tested on Vaadin 24.4-SNAPSHOT)
Fixed very likely long time ago with https://github.com/vaadin/vaadin-split-layout-flow/pull/80
