### ISSUE TITLE
Align Select constructors with ComboBox

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow-components#1275]
`new TextField("Name");`  creates a `TextField` with `Name` as the label
`new TextArea("Name");`  creates a `TextArea` with `Name` as the label
`new PasswordField("Name");`  creates a `PasswordField` with `Name` as the label
`new Checkbox("Name");` creates a `CheckBox` with `Name` as the label
`new ComboBox("Name");` creates a `ComboBox` with `Name` as the label

`new Select("Name");`creates a `Select` with a `Name` option

**Comment by web-padawan** [comment]
Here is the only constructor `Select` provides:
https://github.com/vaadin/flow-components/blob/0b2f16457f6957b410ee465a2b96fc44205518f0/vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java#L147-L151

We should align it with the `ComboBox`:

https://github.com/vaadin/flow-components/blob/0b2f16457f6957b410ee465a2b96fc44205518f0/vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java#L329-L332

https://github.com/vaadin/flow-components/blob/0b2f16457f6957b410ee465a2b96fc44205518f0/vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java#L344-L348

https://github.com/vaadin/flow-components/blob/0b2f16457f6957b410ee465a2b96fc44205518f0/vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java#L361-L365

**Comment by krissvaa** [comment]
There is a problem with creating such constructors without breaking existing uses of `public Select(T... items) {...}` as using this constructor with String type parameters is a quite common case. 
For now, the plan is to deprecate the constructor.
After a while remove it and introduce new Select costructors that will align with ComboBox:
`public Select(String label) {...} `
`public Select(String label, Collection<T> items) {...} `
`public Select(String label, T... items) {...} `

**Comment by krissvaa** [comment]
Starting from 23.1 Select constructor `public Select(T... items) {...}` is deprecated.
Empty constructor `public Select() {...}` and `setItems(items)` method should be used instead.
