### ISSUE TITLE
String constructor should be used for label

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow-components#1276]
`new TextField("Name");`  creates a `TextField` with `name` as the label
`new TextArea("Name");`  creates a `TextArea` with `name` as the label
`new PasswordField("Name");`  creates a `PasswordField` with `name` as the label
`new Checkbox("Name");` creates a `CheckBox` with `name` as the label
`new ComboBox("Name");` creates a `ComboBox` with `name` as the label

`new RichTextEditor("Name");`creates a `RichTextEditor` with `name` as the value

**Comment by ugur-vaadin** [comment]
Note: If label support is added to the component in the future, a constructor with (label & change listener) will probably be required. That constructor will have the same signature with the current constructor of (initial value & change listener). It will have to be another breaking change. We decided to keep the current methods for v24.

**Comment by Legioth** [comment]
Would it make sense to deprecate or maybe even remove the inconsistent `RichTextEditor` constructors now (i.e. for Vaadin 24) so that it would be less disruptive when the day comes that we want to have String constructors with labels?
