### ISSUE TITLE
Can't use 'key' as a property in a TemplateRenderer

### ISSUE THREAD

**Issue by edler-san** [vaadin/flow-components#1303]
I'm using a  flow combobox with a TemplateRenderer and if I define a property named `key`, no selection event is fired if I select an entry. If I use `mykey` instead of `key` (or anything else) it works.

This is not necessarily a bug but should probably be documented.

**Comment by tomivirkki** [comment]
TemplateRenderer has been deprecated (and later removed) in favour of LitRenderer, which doesn't have this limitation, closing.
