### ISSUE TITLE
ComponentRenderer fails when filtering moves the item in the overlay

### ISSUE THREAD

**Issue by pekam** [vaadin/flow-components#1304]
Steps to reproduce:
1. [Open the demo that uses ComponentRenderer](https://vaadin.com/components/vaadin-combo-box/java-examples/using-components)
2. Type a filter so that it matches only the second or third item, eg. "sc"
-> now "Sculpted" becomes the first item in the overlay
3. Hit backspace to remove the filter
-> now "A V Club Disagrees" becomes the first item and "Sculpted" is moved downwards, but it loses its content

Now if you find the `<flow-component-renderer>` in the dom and call `_attachRenderedComponentIfAble()` on it, it will be re-rendered.

So it seems that re-organizing the items in the overlay is done in a way that the `<flow-component-renderer>` doesn't know to re-attach the component.

**Comment by yuriy-fix** [comment]
Let's verify if it's still reproducible on the latest version.

**Comment by web-padawan** [comment]
Tested the examples with both `ComponentRenderer` and `TemplateRenderer` and it works on master and 14.8:
![renderer](https://user-images.githubusercontent.com/10589913/168810860-a606126c-dd23-43da-90c7-bc4e9373b07a.gif)

**Comment by web-padawan** [comment]
As mentioned above, the problem described here is fixed in Vaadin 14 onwards. We no longer backport fixes to Vaadin 10, except for critical bugs and security vulnerabilities. Therefore I'm closing this issue as stale.

**Comment by knoobie** [comment]
The problem is still / again present in V24. @web-padawan 

```java
add(new Button("Open Dialog", e -> {

      var combobox = new ComboBox<String>("Open me");
      combobox.setItems(List.of("AA", "AB", "AC"));
      combobox.setRenderer(new ComponentRenderer<>(s -> new Span("Awesome " + s)));

      var dialog = new Dialog("Test", combobox);
      dialog.open();

}));
```

https://github.com/vaadin/flow-components/assets/3968629/31f290d9-ed79-4ad8-bbe3-42fde9a3cda3
