### ISSUE TITLE
vaadin-chart (v6.1.0) exports are completely black images.

### ISSUE THREAD

**Issue by DabhiGhanshyam** [vaadin/flow-components#1325]
Hello,

I have updated vaadin-charts-flow to version 6.1.0 by upgrading project from vaadin-10 to vaadin-11.

_Vaadin chart export black image issue is resolved._

But I am facing new issue while opening my application for mobile view or minimizing the browser.

Error: **_TypeError: Cannot read property 'textOverflow' of undefined_**

While my application opened successfully in **Mac OS High Sierra version 10.13.5 with Safari version 11.1.1** configuration.

Please Help.

**Comment by web-padawan** [comment]
Closing as stale. If anyone else faces this problem, please submit a new issue with a code example to reproduce.
