### ISSUE TITLE
No file name attribute in ProgressUpdateEvent

### ISSUE THREAD

**Issue by oberhoff** [vaadin/flow-components#1328]
There is no file name attribute in ProgressUpdateEvent like for example in SucceededEvent or FinishedEvent. It would be necessary for customized progress indication (per file).

**Comment by FollowSteph** [comment]
Any updates on this? Looks like it's been requested for 4 years now. That's the exact reason I made the request. I'm trying to add an upload button on top of a table where the Upload component's status is not suitable and as a result there's no way to make a custom upload.

**Comment by theshoeshiner** [comment]
I don't currently have a fix, but from what I can tell one of the issues with this upload component is that the events getting sent back to the server don't contain all the intended DOM event detail properties (including file name, among others). It appears that this is related to some of those properties being inherited. The "file" object that is attached to the vaadin-upload-file component inherits many core properties from the parent "File" type, and it's those inherited properties that are not being sent. Im not sure if ignoring inherited properties is by-design or not, but resolving that issue would allow us to use custom DOM event listeners as a work-around.

**Comment by jsalts** [comment]
I just wanted to add a note here that it is possible to work around this bug by extending UploadElement on the client side, overriding _addfile, and manually firing your own CustomEvent using dispatchEvent. On the server side you can addEventListener() for your new event, but the secret sauce is using addEventData("event.detail") to express interest in the event data. The limitations with File fields like name getting dropped still apply, but you can just remap file.name to your own fileName field.

**Comment by rolfsmeds** [comment]
Related very old PR: https://github.com/vaadin/vaadin-upload-flow/pull/160
