### ISSUE TITLE
Server-side ComboBox changes cause multiple value change events

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/flow-components#1333]
With two ComboBoxes in one view, there is strange behavior with the value change events.

Example app has two simple ComboBoxes, ComboBox1 and ComboBox2. The value change event handler of ComboBox1 
* updates the items of ComboBox2 to a list of ["1","2","3","4","5"] (typical scenario where changing one ComboBox changes the items in a second one)
* sets the value of ComboBox2 to "2", a fixed value from the items list. 

A TextArea component in the example is used to display the contents of the events from both ComboBoxes.

When the ComboBox1 is manually changed for the first time, the application works as expected: there is one isFromClient=true event from ComboBox1 and one isFromClient=false event from the ComboBox2.

When the ComboBox1 is manually updated for the second time, there are 4 *new* events fired: 
* one isFromClient=true event from ComboBox1  (this is ok)
* one isFromClient=false event from ComboBox2 (isFromClient=false is ok, but event's value is null)
* one isFromClient=false event from ComboBox2 (this is ok)
* one isFromClient=true event from ComboBox2 (isFromClient=true and event's value is null, both are wrong)

The correct behavior occurs again when you choose a value manually from ComboBox1 for the third time and the incorrect behavior occurs when you choose a fourth value from ComboBox1. And so on, with the wrong behavior every even turn.

Sample project:
[v10comboboxvaluechange.zip](https://github.com/vaadin/vaadin-combo-box-flow/files/2290423/v10comboboxvaluechange.zip)

**Comment by web-padawan** [comment]
As mentioned above, the problem described here is fixed in Vaadin 14 onwards. We no longer backport fixes to Vaadin 10, except for critical bugs and security vulnerabilities. Therefore I'm closing this issue as stale.
