### ISSUE TITLE
Data generator design used in ComboBox is extremely not obvious

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow-components#1341]
We have an issue vaadin/vaadin-combo-box-flow#97.
Which is going to be fixed via explicit `refresh` once the new renderer is set.

The problem with the code: it's extremely not obvious WHY you need to `refresh` once the renderer is updated.

I spent a lot of time trying to understand that. There is a comment now why but it should not be needed to have any comment.

The design of the logic should be somehow changed so that it's either absolutely obvious why you need to `refresh` or the code needs to be completely redesigned.

There should be totally clear connection between logic inside `refresh` (with all its variables) and any other part of the code which somehow depends on `refresh`.

**Comment by web-padawan** [comment]
Closing as outdated and no longer relevant (the issue was for V10 version and the code has been refactored since then).
