### ISSUE TITLE
Add File remove listener, or something similiar

### ISSUE THREAD

**Issue by lolytxd** [vaadin/flow-components#1342]
Vaadin version: 10.0.0

### Description
When I add Upload component with uploaded file preview component, like in section ```Filtered multi file upload for images``` in [https://vaadin.com/components/vaadin-upload/java-examples](https://vaadin.com/components/vaadin-upload/java-examples), how can I find out, which file was removed, so I can remove file preview?

I see that there is ```.addPropertyChangeListener("files",...``` but I think it doesn't work. It fires only at start and then nothing.

**Comment by TatuLund** [comment]
See also: https://github.com/vaadin/flow-components/issues/2965
