### ISSUE TITLE
Timeline fires extremes changed events without user interaction

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/flow-components#1362]
I noticed my computer fans spinning up and started investigating. Turned out that my Vaadin Chart was continuously readjusting itself ever so slightly without any interaction from me. See screen recording below: 

![magic-events](https://user-images.githubusercontent.com/883698/41177775-260ec2c6-6b1a-11e8-869d-f51ef1a7d04e.gif)

Charts 6.0.0.rc1

**Comment by web-padawan** [comment]
Closing as stale. If anyone else faces this problem, please submit a new issue with a code example to reproduce.
