### ISSUE TITLE
Cannot attach date-picker from java

### ISSUE THREAD

**Issue by alexberazouski** [vaadin/flow-components#1365]
Assume the following component structure:
MyView
--MyPolymerComponent created on server
---DatePicker created on server and attached to the component

In such case I got a client side exception:
`Uncaught TypeError: Cannot read property 'input' of undefined`

Is reproduced in flow spring skeleton.
Tried rc2 and rc3 versions.

**Comment by web-padawan** [comment]
This appears to be the same as https://github.com/vaadin/vaadin-date-picker-flow/issues/100 which was fixed https://github.com/vaadin/vaadin-date-picker-flow/pull/118. Closing.
