### ISSUE TITLE
Add setMargin(boolean)

### ISSUE THREAD

**Issue by Wnt** [vaadin/flow-components#1385]
Add Java API for adding theme specified amount of margin around FormLayout:
```java
public class CustomerForm extends Composite<FormLayout> {
    public CustomerForm() {
        getContent().setMargin(true);
```
Currently the only way I have found to do this is to wrap the FormLayout e.g. in a VerticalLayout and add the margin there:
```java
public class CustomerForm extends Composite<VerticalLayout> {
    public CustomerForm() {
        FormLayout root = new FormLayout();
        getContent().add(root);
        getContent().setMargin(true);
        // add all content to the inner FromLayout, not directly to the composition root
```

**Comment by paodb** [comment]
Hello, a possible workaround is to use Element API, and set the margin like:

```java
formLayout.getElement().getStyle().set("margin", "var(--lumo-size-m)");
```
var(--lumo-size-m) is the same value that margin theme uses when setting setMargin(true)

**Comment by web-padawan** [comment]
Duplicate of https://github.com/vaadin/web-components/issues/1175 (except the fact that this one is for Java API). Closing.
