### ISSUE TITLE
add(Tab... tabs) seems unnecessary

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow-components#1391]
`Tab` is a `Component` and `add(Tab... tabs)` only forwards to `default void add(Component... components)` in `HasComponents`. Why does `add(Tab... tabs)` exist?

**Comment by web-padawan** [comment]
The usage of `HasComponents` has been removed in https://github.com/vaadin/flow-components/pull/4486 and the old `add(Component... components)` method is deprecated since V24 (to be removed in the next major) so I think we can close the issue.
