### ISSUE TITLE
`disableOnClick` does not work after a Button is detached and re-attached

### ISSUE THREAD

**Issue by HermanBovens** [vaadin/flow-components#1401]
### Description of the bug
`disableOnClick` does not work after detach and re-attach of the `Button`.
This can happen for example when a `Dialog` containing this button is closed and then reopened.

### Minimal reproducible example
- Create a `Dialog` subclass that has a button that shows a `Notification` and then closes the dialog when clicked.
- Call 'setDisableOnClick(true)` when the button is created.
- Create a UI with 1 instance of this dialog and a `Button` to open it.
- Run the application.
- Press the button to open the dialog.
- Double-click the button to close the dialog.  The notification will only show once.
- Press the button to open the dialog again.
- Double-click the button to close the dialog again.

### Expected behavior
The notification should again only show once.
### Actual behavior
The notification is shown twice.

This is because a hack is used to add a client-side event handler to disable on click:

```
/**
 * Initialize client side disabling so disabled if immediate on click even
 * if server-side handling takes some time.
 */
private void initDisableOnClick() {
    if (!disableOnClickConfigured) {
        getElement().executeJs("var disableEvent = function () {"
                + "if($0.getAttribute('disableOnClick')){"
                + " $0.setAttribute('disabled', 'true');" + "}" + "};"
                + "$0.addEventListener('click', disableEvent)");
        disableOnClickConfigured = true;
    }
}
```

This is gone after the button has been detached.
And it doesn't help to call `disableOnClick(true)` again because `disableOnClickConfigured` will still be `true` so the `executeJs` part is skipped.

I guess it would be best that the client-side `vaadin-button` component supports the `disableOnClickConfigured` property itself.

Also, I'm surprised that the second click event is handled because the first click already closes the `Dialog` so should detach the button.  Are click events for detached buttons still handled on the server side?  I never experienced this in Vaadin 8.

See https://stackoverflow.com/questions/63634513/reliability-of-button-disableonclick-in-vaadin-14/63635292?noredirect=1#comment112614454_63635292.

### Versions:
    - Vaadin / Flow version: 14.3.4

**Comment by TatuLund** [comment]
I tested the case with this view and I cannot reproduce the problem

```
@Route("disable-on-click")
public class DisableOnClick extends VerticalLayout {

    int count = 0;
    Dialog dialog = new Dialog();
    
    public DisableOnClick () {
        Button testButton = new Button("Click me");
        testButton.setDisableOnClick(true);
        testButton.addClickListener(event -> {
            Span span = new Span("Enabled");
            count++;
            span.setId("enabled-"+count);
            add(span); 
        });
        testButton.setId("test-button");
        Button remove = new Button("Remove");
        Button add = new Button("Add");
        remove.addClickListener(event -> {
            remove(testButton);
        });
        add.addClickListener(event -> {
            addComponentAsFirst(testButton);
        });
        remove.setId("remove-button");
        add.setId("add-button");

        Button dialogButton = new Button("Click me");
        dialogButton.setDisableOnClick(true);
        dialogButton.addClickListener(event -> {
            Span span = new Span("Enabled");
            count++;
            span.setId("dialog-"+count);
            add(span); 
        });        
        testButton.setId("dialog-button");
        
        dialog.add(dialogButton);
        Button openDialog = new Button("Open");
        openDialog.addClickListener(event -> {
           dialog.open(); 
        });

        add(testButton,remove,add,openDialog,dialog);
    }

}
```

**Comment by NicolasJuanF** [comment]
The problem is that after re-attaching de button, it does not longer disables on click. 
I tried this case: 
```java
Button buttonWithDisableOnClick = new Button("Button with disable on click");
buttonWithDisableOnClick.setId("button-with-disable-on-click");
buttonWithDisableOnClick.setDisableOnClick(true);
buttonWithDisableOnClick.addClickListener(event -> {
    try {
        Thread.sleep(1500);
    } catch (InterruptedException e) {
        e.printStackTrace();
    } finally {
        event.getSource().setEnabled(true);
    }
});

add(
        new Button("Remove button from view", event -> remove(buttonWithDisableOnClick)),
        new Button("Add button to view", event -> add(buttonWithDisableOnClick)),
        buttonWithDisableOnClick
);
```
After removing and adding the button to the view, it no longer disables after a click. It behaves the same way even if you implement a custom button with: 
```java
    @Override
    protected void onAttach(AttachEvent attachEvent) {
        setDisableOnClick(true);
    }
```
