### ISSUE TITLE
Value not retained after filter is applied

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow-components#1403]
Vaadin 14.3.4, radio-button-flow-2.1.0. Let's have the following RadioButtonGroup with four values:
```
        RadioButtonGroup<String> buttongroup = new RadioButtonGroup<>();
        buttongroup.setItems("foo", "bar", "baz", "foobar");
        add(buttongroup);
```
Let's select the "foobar" option and then let's apply a filter:
```
            ListDataProvider<String> provider = (ListDataProvider<String>) buttongroup.getDataProvider();
            provider.addFilter(item -> item.startsWith("foo"));
```
This will deselect all radio buttons and make the radio button group return `null` value. What should happen instead is that the value of "foobar" should have been preserved.

Example project follows.

**Comment by sissbruecker** [comment]
This should be doable now with setting the respective selection preservation mode:
```java
radioButtonGroup.setSelectionPreservationMode(SelectionPreservationMode.PRESERVE_EXISTING);
```
