### ISSUE TITLE
Bug: About submodals after refresh with @StyleSheet

### ISSUE THREAD

**Issue by netbeansuser2019** [vaadin/flow-components#1405]
14.3.4

if page is refreshed when it is kept opened submodal (modal in other modal) then submodal ignores such styling defined via annotation (@StyleSheet) on main application layout (RouterLayout;@PreserveOnRefresh) up to time:

1) user closes (e.g. click outside) and then user invoke another page refresh (F5) and then user click to opened it again.
2) close that e.g. by onDetach() to not be opened during refresh

Expected behavior after refresh (F5) with opened dialog:
It is properly style by style that arrives with @StyleSheet.

General suggestion:
If there is no event for "page reload" operated by logic due to @PreserveOnRefresh then it should be added, because I do not think that it is the best option to recognize that e.g. via onDetach().

**Comment by tomivirkki** [comment]
Hi @netbeansuser2019 
I tried creating a Vaadin 14.8.2 application following the issue description
- A view with a submodal and content styling (the red outline on the button) applied with `@StyleSheet`
- The view is part of an application layout with `RouterLayout` and `@PreserveOnRefresh`

...but couldn't find a way to reproduce the styling issue:

https://user-images.githubusercontent.com/1222264/150792810-6a0034c6-b2cd-4d5c-9904-c4554aff17ee.mp4

Closing. If this is still an issue, please let us know and attach an example project which we can use to reproduce the mentioned styling bug.
