### ISSUE TITLE
Add missing shorthand constructors to RadioButtonGroup

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow-components#1415]
Other Vaadin select components have shorthand constructors for creating the component with a specific label and optionally also some specific items. `RadioButtonGroup` has no such constructors.

**Comment by web-padawan** [comment]
See `ComboBox` for an example of such missing constructors:

https://github.com/vaadin/flow-components/blob/0b2f16457f6957b410ee465a2b96fc44205518f0/vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java#L329-L332

https://github.com/vaadin/flow-components/blob/0b2f16457f6957b410ee465a2b96fc44205518f0/vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java#L344-L348

https://github.com/vaadin/flow-components/blob/0b2f16457f6957b410ee465a2b96fc44205518f0/vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java#L361-L365
