### ISSUE TITLE
Disalignment when using images

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/flow-components#1451]
## Vaadin version
14.2.0
## vaadin-radio-button-flow version
2.0.4
## Description of the problem
When using component renderer with images with certain sizes, the radio button appears to be vertical misaligned as shown in this screenshot:
![image](https://user-images.githubusercontent.com/28312758/83897261-bfb58c80-a72b-11ea-9697-c7a1e11e0f8a.png)
## Expected behavior
Radio buttons should appear vertically centered in relation to images.
## Code to reproduce the issue:
```
@Route
public class MainView extends VerticalLayout {

	public MainView() {
		RadioButtonGroup<String> rbg = new RadioButtonGroup<>();
		rbg.setRenderer(new ComponentRenderer<>(item-> {
			Image image = new Image();
			image.setSrc(item);
			image.setAlt(item);
			return image;
		}));
		rbg.addThemeVariants(RadioGroupVariant.LUMO_VERTICAL);
		rbg.setItems("https://dummyimage.com/71x26/000/fff","https://dummyimage.com/114x27/000/fff");
		add(rbg);
	}
}
```

**Comment by web-padawan** [comment]
Closing in favor of https://github.com/vaadin/web-components/issues/3342. As mentioned there, we use baseline alignment intentionally.
