### ISSUE TITLE
In Safari (MacOS as well as iOs) TextArea and TextField look broken

### ISSUE THREAD

**Issue by wfischlein** [vaadin/flow-components#1452]
Have these two put into a VerticalLayout and test on Safari:
![image](https://user-images.githubusercontent.com/16917619/83882055-779d6680-a739-11ea-809a-9a0661661113.png)

**Comment by rolfsmeds** [comment]
Closing, as https://github.com/vaadin/vaadin-ordered-layout/issues/95 is no longer reproducible in Safari, I presume this issue to have been resolved as well.
