### ISSUE TITLE
Radio button not working on iPhone's Safari

### ISSUE THREAD

**Issue by t0920008899** [vaadin/flow-components#1455]
Hi, I am using V14.2, and I got a problem for radio button for iPhone's Safari. I defined a `<vaadin-radio-group id="mp" required></vaadin-radio-group>` in the polymer template, and I had a `@Id( "mp" )`
`private RadioButtonGroup< String > mp;` definition in the server side. When running, all browsers including Mac's Safari were all fine. However, the iPhone's Safari could not allow user to click/select the radio buttons. Why is that?

**Comment by tomivirkki** [comment]
Created a `PolymerTemplate` -based view on the latest Vaadin 14.8, following the instructions in the issue description.
Ran it with iOS 13.4 (simulator) and didn't face any issues:

https://user-images.githubusercontent.com/1222264/151187033-2cd686ed-05e0-4aad-a7cd-ac4c56198044.mp4

If you still can reproduce this issue with the latest Vaadin 14, please let us know and attach an example project with the issue reproduces. Closing.
