### ISSUE TITLE
Autowidth does not respect Header content

### ISSUE THREAD

**Issue by F43nd1r** [vaadin/flow-components#1457]
![Screenshot](https://user-images.githubusercontent.com/10252708/83083255-f5040f80-a085-11ea-88a4-182006f438d0.png)

As seen in this screenshot, rows with small content can lose their header title partially (marked yellow) or fully (both columns marked red). I would instead expect autowidth to consider the size of anything in any header row, especially text in the default header row.

**Comment by knoxyz** [comment]
I need also a fix of this bug.

**Comment by tomivirkki** [comment]
Based on the image in the description, this seems to be a duplicate of https://github.com/vaadin/web-components/issues/483 which was already fixed by https://github.com/vaadin/web-components/pull/2964 Closing
