### ISSUE TITLE
Locale not inherited from UI

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow-components#1466]
The `Component.getLocale()` javadoc says that `It returns the {@link UI} locale if it has been set.`. This makes sense - generally the app should retrieve the locale from user's browser, then set it to the UI, which should automatically make all visible attached components properly localized to that locale (unless the component has been explicitly set to a different locale).

However, DatePicker breaks this contract and introduces its own locale setting independent of UI. Example code:

```
        final DatePicker datePicker = new DatePicker(LocalDate.of(2020, 1, 30));
        UI.getCurrent().add(datePicker);
        UI.getCurrent().setLocale(Locale.ITALIAN);
        System.out.println(datePicker.getLocale());
```

This should print `it_IT` but will print `en_US` instead.

This will prevent the DatePicker from properly inheriting the locale from the UI, causing confusion for the programmer, since the DatePicker's locale will not be changed when a different locale is set to the UI. Possibly related issue: https://github.com/vaadin/vaadin-date-picker-flow/issues/135

This can be fixed by `DatePicker` implementing the `LocaleChangeObserver`.

**Comment by rolfsmeds** [comment]
Closing as fixed
