### ISSUE TITLE
Required text field does not show validation error upon losing focus when not using a binder  

### ISSUE THREAD

**Issue by edler-san** [vaadin/flow-components#1468]
When using a plain TextField with a required indicator the indicator does not trigger upon entering and leaving the text field (Vaadin 14.1.28)

```
        TextField txtTest = new TextField();
        txtTest.setLabel("Label");
        txtTest.setRequiredIndicatorVisible(true);
        txtTest.setClearButtonVisible(true);
        txtTest.setErrorMessage("Please enter a value.");
```
![shown](https://user-images.githubusercontent.com/19165931/81928090-09a3ca80-95e5-11ea-8deb-8401b61fe525.gif)

As a workaround you can add
```
        txtTest.addAttachListener(attachEvent -> txtTest.getElement().executeJs("this.validate = function() { return !(this.invalid = !this.checkValidity()); };"));
```
and it works as expected
![expected](https://user-images.githubusercontent.com/19165931/81928143-1c1e0400-95e5-11ea-8a29-9de8c46c3c4f.gif)

**Comment by Haprog** [comment]
This can be seen in this Docs demo as well (when viewing the Java version): https://vaadin.com/docs/latest/ds/components/input-fields#required

The error message is only displayed if you first edit the value to be not empty, unfocus, then clear the value and unfocus again, then the error is shown.

**Comment by vursen** [comment]
FYI: We have just introduced new validation behavior aiming to solve many different validation issues that people were complaining about, including this one. The new behavior is available under the feature flag in v23.2 for several components including TextField.

To enable the feature flag in your application, add the following to `vaadin-featureflags.properties`:

```
com.vaadin.experimental.enforceFieldValidation=true
```

Any feedback would be highly appreciated. For more details, please refer to https://github.com/vaadin/platform/issues/3066.

**Comment by higgsja** [comment]
Using 23.3.4 with java 17. Is this still required? If so, I do not understand where to add the given line. Can you clarify what file, e.g., .pom and in what section?

Thanks!

**Comment by vursen** [comment]
> Using 23.3.4 with java 17. Is this still required? If so, I do not understand where to add the given line. Can you clarify what file, e.g., .pom and in what section?

In v23, the feature is experimental, so using the feature flag is still required. There are more details on how to configure feature flags in Flow applications in the [documentation](https://vaadin.com/docs/latest/configuration/feature-flags/#editing-the-properties-file).

**Comment by higgsja** [comment]
Thanks!

**Comment by vursen** [comment]
The issue has been resolved by the [new validation mechanism](https://github.com/vaadin/platform/issues/3066) which is enabled by default in Vaadin 24. For any further bugs, please create separate issues.
