### ISSUE TITLE
Explicit new row in GeneratedVaadinFormLayout

### ISSUE THREAD

**Issue by vlipovetskii** [vaadin/flow-components#1504]
https://vaadin.com/api/platform/12.0.3/com/vaadin/flow/component/formlayout/GeneratedVaadinFormLayout.html

> Explicit New Row
> Use the <br> line break element to wrap the items on a new row:

It works correctly in Google Chrome in all cases, but not always in Firefox, Edge. After changing browser window size it doesn't work.

**Comment by web-padawan** [comment]
Closing as stale. If someone else encounters this problem, please submit a new issue with a code example to reproduce.
