### ISSUE TITLE
Pin menu window to target - set a fixed position

### ISSUE THREAD

**Issue by CookedApps** [vaadin/flow-components#1510]
Hello. 
We use the context menu to build a custom ComboBox in combination with a button as target (which works great). But the menu always pops up at the current mouse position (as expected). It would be nice if we could "pin" the position of the popup window to the target component, so it only pops up at the position of the target.
Is that possible with the Java API?

Or is that somehow possible with the low level API of [`<vaadin-context-menu>`](https://github.com/vaadin/vaadin-context-menu)?

Thank you in advance.

**Comment by web-padawan** [comment]
We now have `vaadin-popover` component released in v24.5.0 which covers this use case. Closing.
