### ISSUE TITLE
Split layout get splitter-position after moving the splitter manually

### ISSUE THREAD

**Issue by EvaGillen** [vaadin/flow-components#1517]
I am trying to get the position of the splitter after moving the splitter manually.
I know how to set the position. And I know that I can get the position with e.g. `primaryComponent.getElement.getStyle.get(ElementConstants.STYLE_HEIGHT)`. But that's just the position I set on server-side.

I need the new position after moving the splitter.

**Comment by enver-haase** [comment]
Dear @vaadin-bot , please remove the 'enhancement' label as it is a severe usability bug, which I am encountering in a migration project from Vaadin 7 (!) to Vaadin 20 (!).
@pleku

**Comment by Frettman** [comment]
For me this is also a missing feature during a Vaadin 7/8 migration (to 23). As others have pointed out, the `SplitterDragendEvent` is quite pointless without the splitter position. So I'd also consider this a flaw and not just an enhancement. Anyway, thank you for the provided workarounds. They seem simple enough which makes it even more strange that this hasn't been fixed yet.

**Comment by chkpnt** [comment]
Thanks for the cookbook entry. Nevertheless, I think that the splitter position should be available in `SplitterDragendEvent`.
