### ISSUE TITLE
Gives Script Error in Mobile Browsers

### ISSUE THREAD

**Issue by ugurdoksan** [vaadin/flow-components#1524]
👍Timepicker works very fine in Web browsers. 

👎But gives a script error on mobile just after the page loaded.

**Here is the info:**
_Vaadin Version: 12.0.5_
_Mobile Phone: iPhone 7_
_Mobile Browsers: Safari, Chrome (Last Stable Versions)_

**Here is the code:**
`
TimePicker tp = new TimePicker( label );
tp.setRequired( true );
if( width != null ) tp.setWidth( width );
if( value != null ) tp.setValue( value );
tp.setStep( Duration.ofMinutes( 15 ) );
tp.setLocale( new Locale( "tr", "TR" ) );
if( removeMargin ) tp.getStyle( ).set( "margin", "0px" );
`

**Here is the screenshot:** 
TimePickers are hidden under the error :)

![007b21dd-37d7-4cdf-a565-edf4083dc6a4](https://user-images.githubusercontent.com/24225109/51999003-b8d09700-24b1-11e9-817f-1e522e554d70.png)

**Comment by web-padawan** [comment]
The original issue was related to connector initialization timings and fixed by https://github.com/vaadin/vaadin-time-picker-flow/pull/79. Closing.
