### ISSUE TITLE
Render empty Div in ComponentRenderer and IconRenderer when given null

### ISSUE THREAD

**Issue by TatuLund** [vaadin/flow-components#1549]
For use cases of conditional cell content, it would be helpful to render empty Div in ComponentRenderer and IconRenderer when given null value.

This is request for convenience and improved DX. It is possible to give empty Div already now as a component.

https://vaadin.com/forum/thread/17439129/grid-icon-column

**Comment by knoobie** [comment]
I think @mstahv fixed this in https://github.com/vaadin/flow-components/pull/4361

**Comment by mstahv** [comment]
Oh yes 😎
