### ISSUE TITLE
Make it possible to remove/clear existing uploads programmatically

### ISSUE THREAD

**Issue by mstahv** [vaadin/flow-components#1572]
If you upload a file, it is shown in the UI forever (unless developer clicks clear). Developer should have an API to programmatically clear the uploaded file.

**Comment by mvysny** [comment]
Use-case to clear the list of files:
* The Upload is a part of a wizard. When the user goes back in the wizard, the Upload needs to be cleared, to allow the user to upload a different set of configuration files/backups.

**Comment by rolfsmeds** [comment]
Acceptance criteria: https://github.com/vaadin/platform/issues/2600

**Comment by mstahv** [comment]
There has been a good PR to fix this issue for almost 3 months to fix this nasty issue. Why can't we just take it it? I think I have never used this component without facing this issue. At least for me a better default would actually be not to show the handled uploads there at all.
