### ISSUE TITLE
Add option to display the year with two digits

### ISSUE THREAD

**Issue by Wnt** [vaadin/flow-components#1575]
Use 2-digit year representation in the client-side formatter
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString#Parameters

> year
>     The representation of the year. Possible values are "numeric", "2-digit".

**Comment by rolfsmeds** [comment]
Closing, as the formatting and parsing can now be customized (from V22 onward)
