### ISSUE TITLE
(TypeError) : Cannot read property 'a' of undefined

### ISSUE THREAD

**Issue by Eitraz** [vaadin/flow-components#1577]
When setting a progress bar to visible "to fast" in a separate thread for a newly attached progress bar, a JavaScript error ((TypeError) : Cannot read property 'a' of undefined) is displayed in the browser.

I have a component that will either load content from a backend API or use cached data previously loaded. When the data needs to be fetched from backend the progress bar should be displayed, otherwise not.

I have attached a project where the error is shown (at least on my computer) when clicking the button.

My work around for now is to override _ProgressBar.setVisible_ with `getElement().getStyle().set("visibility", visible ? "visible" : "hidden");`

Regards,
Petter
[vaadin-progress-bar-issue.tar.gz](https://github.com/vaadin/vaadin-progress-bar-flow/files/2565337/vaadin-progress-bar-issue.tar.gz)

**Comment by tomivirkki** [comment]
It no longer reproduces with the latest Vaadin. Closing.
