### ISSUE TITLE
NullPointerException in Grid

### ISSUE THREAD

**Issue by shadikhani** [vaadin/flow-components#1579]
When `Grid::addColumn(String)` is called for nested properties, e.g. `grid.addColumn("address.postalCode");`, the property `address` should not be null, otherwise, an NPE is thrown and the stacktrace doesn’t help well, so it’s difficult to find the root cause. I think it should be mentioned in the javadoc of the addColumn method.
I’m using Vaadin 11.0.0.

**Comment by TatuLund** [comment]
This has been fixed by https://github.com/vaadin/flow-components/pull/217

**Comment by web-padawan** [comment]
Closing per above comment.
