### ISSUE TITLE
Mission Impossible: Scrollable Content

### ISSUE THREAD

**Issue by anezthes** [vaadin/flow-components#1580]
I'd like to create a dialog with a header, scrollable content and a footer. The issue I keep running into is that the whole dialog becomes scrollable.

I'll provide sample code tomorrow.

**Comment by web-padawan** [comment]
> I'd like to create a dialog with a header, scrollable content and a footer.

Done in https://github.com/vaadin/flow-components/pull/2982 and will be available since Vaadin 23.1 (currently in alpha).
