### ISSUE TITLE
Support for prefix/suffix component

### ISSUE THREAD

**Issue by heruan** [vaadin/flow-components#1594]
It would be useful to set prefix and suffix components in the same way it's done with `TextField`.

In the [advanced demos](https://vaadin.com/components/vaadin-combo-box/html-examples/combo-box-advanced-demos) there is a similar example using `vaadin-combo-box-light`, but there's no Flow component for that.

P.S. Not sure if this is more appropriate in the Web Component repo, if so I'll open an issue there referencing this.

**Comment by mvysny** [comment]
Also the examples at https://vaadin.com/components/vaadin-date-picker/html-examples should mention the possibility to set a component to the prefix slot.
