### ISSUE TITLE
connector assumes that the element is attached to the dom

### ISSUE THREAD

**Issue by manolo** [vaadin/flow-components#1597]
Since this change https://github.com/vaadin/vaadin-combo-box-flow/commit/757fec6b4ee146d53aedc8c958c534e79a7ddb15#diff-457231bc4349d550c284f120d6873bd1R250  `combo-box` cannot be initialized if the first combo-box passed to `initLazy` is not yet in the dom.

If fails in CCDM when using client-side routing in flow, but also when the combo-box in java is attached to a detached element.

Solution should be to delay the `_isItemSelected` until the `connectedCallback ` in `comboBox`

**Comment by web-padawan** [comment]
Fixed by #2487
