### ISSUE TITLE
Tickle a Grid with DnD and heightByRows makes it giggle every time.

### ISSUE THREAD

**Issue by haiwan** [vaadin/flow-components#1610]
1. Use the code demo from here https://vaadin.com/components/vaadin-grid/java-examples/drag-and-drop
2. set heightByRows to be true.
3. Tickle the grid by dragging a row to the end of the grid
4. Grid giggles. See the attached gif.
![2019-11-25 09-50-19 2019-11-25 09_51_19](https://user-images.githubusercontent.com/3388675/69522959-56c6ae00-0f6b-11ea-8a3b-b6f2761ae942.gif)

**Comment by javier-godoy** [comment]
Another workaround is adding the following style:
```
#table {padding-bottom: 2px;}
```

**Comment by MathiasAugstein** [comment]
@javier-godoy From the example code I cannot understand at which element you add a padding. It looks like you add the id "table" in your code. Can you please show which element has the id "table" in your case?

**Comment by javier-godoy** [comment]
@MathiasAugstein `#table` is the actual `<table>` in the shadow DOM of `vaadin-grid` (for the workaround, the CSS should be added as a [component-specific](https://vaadin.com/docs/v14/flow/styling/importing-style-sheets) style for `vaadin-grid`)

![image](https://user-images.githubusercontent.com/11554739/126637627-b8e8d19b-a234-4439-b5f7-df09d4e180da.png)
