### ISSUE TITLE
Empty properties in UploadI18N cause client side errors

### ISSUE THREAD

**Issue by tulioag** [vaadin/flow-components#1615]
If you set an `I18n` object, but leave fields empty, client side exceptions are shown.
```java
@Route
@PWA(name = "My Application", shortName = "My Application")
public class MainView extends VerticalLayout {

    public MainView() {
        Upload upload = new Upload();
        upload.setI18n(new UploadI18N());
        add(upload);
    }
}
```
![upload_error](https://user-images.githubusercontent.com/28783969/68760616-f35b8880-061a-11ea-86df-398bc35548ad.png)

**Comment by web-padawan** [comment]
Fixed by #1906 which enabled setting partial `UploadI18n` and prevented the error from being thrown. Closing.
