### ISSUE TITLE
Request for styling tutorial

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow-components#1622]
I tried to accomplish a simple task (in Java with CssImport): Style the menu bar to the not very complex CI of a customer and I failed miserably due to the complex structure of the menu bar inner parts. 

The CI is not very complicated, in the end it has some custom height and text color for the buttons, a specific background color for the bar (that part I got) and an active styling for the item representing the current route.

Biggest problem for non UX guys here is that we have the menu bar, that has in its shadow dom a menu bar button, that uses somehow a button and the context menu for some representation, all with their own shadow doms. In all that shadow doms its hard to apply the basic shadow dom styling tutorials, that we provide. On top of that, when adding a css class to the menu item, it is applied to the context menu item. 

Thus it would be good to have some easy to understand examples, of how to style a simple menu bar like this one.

![image](https://user-images.githubusercontent.com/36725474/67834841-bb1b5c80-fae8-11e9-833a-e37f452bfb9c.png)

**Comment by web-padawan** [comment]
> Biggest problem for non UX guys here is that we have the menu bar, that has in its shadow dom a menu bar button

This has been changed in V24 and `vaadin-menu-bar-button` elements are no longer in the shadow DOM of `MenuBar`.
See also [stylable parts and states reference](https://vaadin.com/docs/latest/components/menu-bar/styling) and the [styling guide](https://vaadin.com/docs/latest/components/menu-bar#styles) in the component docs. If you think that something important is missing from those, please create a new issue in the docs repo. Closing this issue as no longer relevant.
