### ISSUE TITLE
Implementation of HasStyle

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow-components#1624]
A normal use case for a menu bar in an app is to show the current active page by highlighting the representing entry in the menu for instance by setting a css class.

Currently this is only possible indirectly by using the Element API `menuItem.getElement().getClassList().add("highlight")`.

Since we have HasStyle for components for that, it would be nice to have that also on the MenuItem, to simply use `menuItem.addClassName("highlight")`.

**Comment by rolfsmeds** [comment]
Closing in favor of https://github.com/vaadin/flow-components/issues/880
