### ISSUE TITLE
HorizontalLayout and VerticalLayout are messed up on Safari Browsers

### ISSUE THREAD

**Issue by blafoo** [vaadin/flow-components#1626]
I am using the HorizontalLayout and VerticalLayout of Vaadin 14. They are displayed as expected with Firefox (or Edge) but not with Safari.

A good example is geocaching.blafoo.de

**Comment by web-padawan** [comment]
Closing as stale. If anyone encounters this problem, please submit a new issue with a code example and steps to reproduce.
