### ISSUE TITLE
Make getView package protected

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/flow-components#1632]
https://github.com/vaadin/vaadin-crud-flow/blob/ccc61fa71d2b8d51e6ef0f28e636929631170440/vaadin-crud-flow/src/main/java/com/vaadin/flow/component/crud/BinderCrudEditor.java#L98

Should become package protected with the **next major**.

Related: https://github.com/vaadin/vaadin-crud-flow/issues/161

**Comment by ugur-vaadin** [comment]
Closing this issue as the context for the issue does not seem to be relevant anymore.
