### ISSUE TITLE
DateTimeFormatter locale

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/flow-components#1634]
Remove possibility to set `min / max` values with `locale`:
https://github.com/vaadin/vaadin-time-picker-flow/blob/54f18dc7f66c1d161e82465e450a9d92a0a42d5f/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java#L498
The fields should always be in in ISO 8601 formats aligned with webcomponent:

- `hh:mm`
- `hh:mm:ss`
- `hh:mm:ss.fff`

**Comment by web-padawan** [comment]
The `setMin()` and `setMax()` have been changed in #2246 to use `LocalTime` so the `locale` is no longer used. Closing.
