### ISSUE TITLE
Tabs.add(String) exists, but using it causes an exception

### ISSUE THREAD

**Issue by johannesh2** [vaadin/flow-components#1636]
`IllegalStateException` is thrown at some point when using Tabs.add(String).

**Comment by rolfsmeds** [comment]
Tabs should not implement `HasOrderedComponents` or `HasComponents`, as the component has never supported adding arbitrary content, only `Tab`s, so these interfaces should simply be removed from `Tabs` (and certain methods from them, like `remove` and `removeAll` should be re-implemented in the component itself).

The upcoming `TabSheet` component will support adding arbitrary content at the start and end of the tab row, however.
