### ISSUE TITLE
Ellipsis button shown when unnecessary

### ISSUE THREAD

**Issue by heruan** [vaadin/flow-components#1648]
Sometimes the `MenuBar` shows an unnecessary ellipsis button:

```
MenuBar menu = new MenuBar();
menu.addItem(Icons.PLUS);
```

This looks good when page loads, but during in-app navigation the ellipsis button appears:

<img width="276" alt="Screenshot 2019-10-02 at 17 21 57" src="https://user-images.githubusercontent.com/851745/66057799-9d82c380-e539-11e9-90ca-39ee972899fb.png">

**Comment by web-padawan** [comment]
Closing in favor of #2810 which describes the same problem but reproduced with `vaadin-avatar` instead of icon.
