### ISSUE TITLE
CustomField should implement BlurNotifier<CustomField<T>>, not BlurNotifier<CustomField>

### ISSUE THREAD

**Issue by zanonmark** [vaadin/flow-components#1653]
As per subject, IMHO CustomField behaviour should be homogeneous to those of other classes (e.g.: ComboBox).

Thanks,
MZ

**Comment by zanonmark** [comment]
Could we please fix this in the new Vaadin 21?

Thanks,
MZ

**Comment by zanonmark** [comment]
Hi,

I see this hasn't slipped into Vaadin 23.

Maybe for the next LTS?

Thanks,
MZ

**Comment by jouni** [comment]
> Maybe for the next LTS?

Side note: “LTS” is no longer a thing we use for versioning. See https://vaadin.com/blog/a-better-release-model

From now on, we encourage everyone to use the latest major version.
