### ISSUE TITLE
Weird condition in setLocale function in datepickerConnector.js

### ISSUE THREAD

**Issue by tltv** [vaadin/flow-components#1659]
Please check out this 'if' block with condition like `datepicker.i18n.parseDate !== 'undefined'`. it does not look like it is inline with the web-component logic which expects it to be function or undefined/null. `'undefined' !== undefined`.
https://github.com/vaadin/vaadin-date-picker-flow/blob/146a9b0f29419adbc9b8b926da5e08fa862b7f6a/vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js#L78

I found this when I tried to disable date parsing by setting `parseDate` function to 'undefined' and turned out that web-component gives error with it, but connector code works (Or other way around with undefined):
https://github.com/vaadin/vaadin-date-picker/blob/95e2a2ae8151088a28010eedc9d65338248792f8/src/vaadin-date-picker-mixin.html#L663

**Comment by web-padawan** [comment]
This logic was removed while adding custom format support (#1975 for V22+ and #2002 for v14.8). Closing as fixed.
