### ISSUE TITLE
ColumnTextAlign is not applied to all header rows

### ISSUE THREAD

**Issue by jmycka** [vaadin/flow-components#1673]
Vaadin 14.0.2

### Description
Parameter ColumnTextAlign is applied only to last header row (first footer row). 

### Expected outcome
Text inside all headers (footers) cells should be aligned accordingly.

### Code snippet
```
final Grid<String> g = new Grid<>();
final Column<?> col = g.addColumn(String::toString).setHeader("Header 1").setTextAlign(ColumnTextAlign.END);

g.prependHeaderRow().getCell(col).setText("Header 0");
g.appendHeaderRow().getCell(col).setText("Header 2");
g.appendHeaderRow().getCell(col).setText("Header 3");

g.appendFooterRow().getCell(col).setText("Footer 0");
g.appendFooterRow().getCell(col).setText("Footer 1");
g.appendFooterRow().getCell(col).setText("Footer 2");
```

### Actual outcome
![Capture](https://user-images.githubusercontent.com/15838198/64101355-fbbb5b80-cd6d-11e9-8db3-d535f9392e37.PNG)

**Comment by johannest** [comment]
This is still present in V14.7.4

**Comment by MacInGithub** [comment]
Maybe I was the one who caused the 2019 ticket.
Anyway, I still have the error and it would be great if it was fixed.

**Comment by web-padawan** [comment]
Sorry about the fact this hasn't been addressed for a while. We will do our best to fix such annoying issues.

**Comment by tomivirkki** [comment]
Here's a workaround for the issue:

```java
// Get the parent of the column (column group)
var columnGroup = col.getParent();
// Itereate all the column groups in the hierarchy
while (columnGroup.isPresent() && columnGroup.get() != g) {
    // Set the text align property of the column group to match that of the column
    columnGroup.get().getElement().setProperty("textAlign", col.getElement().getProperty("textAlign"));

    columnGroup = columnGroup.get().getParent();
}
```

Result:
![Screenshot 2022-12-07 at 9 54 03](https://user-images.githubusercontent.com/1222264/206120276-a7929a4e-0a56-4745-b16f-b4af50d3a32e.png)

**Comment by rolfsmeds** [comment]
I'd argue that if the _last_ header row _does_ get the alignment applied, this is a bug either way:

- bug A) it's a bug that _only_ the last header row's cells get the alignment
- bug B) it's a bug that _any_ header row cell gets the alignment

Or to put it another way, if a new API like `HeaderCell::setTextAlign` is needed to support this, surely that implies that `Column::setTextAlign` should _not_ affect header cells.

If we do decide that this is bug A above, we need to decide how it should work in cases where header or footer cells span multiple columns:

- behavior A) Simply don't apply alignments to cells that span > 1 column
- behavior B) Apply the _first_ spanned column's alignment to the multi-column cell

**Comment by tomivirkki** [comment]
Agreed, it could probably be assumed that if joined columns aren't used, then `column.setTextAlign()` would affect all the header/footer cells on that column (Bug A)

> If we do decide that this is bug A above, we need to decide how it should work in cases where header or footer cells span multiple columns:

> behavior A

Could be an issue if there's no way at all to change the alignment for a spanned header cell

> behavior B

Not sure if this is a safe assumption to make. What's nice is that it would align with the bug fix.

**Comment by yuriy-fix** [comment]
The issue was triaged and currently added to the backlog priority queue for further investigation.

**Comment by DiegoCardoso** [comment]
I started investigating the issue and will work on the fix.
