### ISSUE TITLE
No api for getting header cell component after it has been set

### ISSUE THREAD

**Issue by petrixh** [vaadin/flow-components#1676]
In the v14 grid, after setting header row components (like filters) there is no way to get the component after the fact (like clearing it or getting its value). 

A workaround is to store them in a local map that will eventually go out of sync or override the Grids default column factory, extend the default column and add: 

`

	public class MyColumn<T> extends Column<T>{
            private Component headerComponent;

            @Override
		protected void setHeaderComponent(Component component) {
			super.setHeaderComponent(component);
			headerComponent = component;
		}

		public Component getHeaderComponent() {
			return headerComponent;
		}
}`

would be nice to have this in the public API just like we had in the V8 Grid.

Tested with Vaadin 14.0.1

**Comment by tangomannX** [comment]
Any progress here? This "feature" is absolutely necessarry in order to write unit tests. Why is the vaadin team hiding so much information in your new api? Update from vaadin 8 to flow (23) is a real pain!

**Comment by yuriy-fix** [comment]
Dear @tangomannX,
The issue didn't get prioritised over others.
Could you please provide a use-case (code sample) where this API would be needed, so the issue priority could be reconsidered?

**Comment by tangomannX** [comment]
`@Test`
`void testingIsEssentialForRealBusinessApplicationsWithGreaterScopeThanBakerySampleApp() {`
`   var grid = new GridThatAddsSmartFilterComponentsNotOnlyTextfiledsLikeVaadinCRUD(SomeBean.class);`
`  assertThat(grid.getColumnByKey("xyz").getHeaderComponent(), isInsanceOf(NameAnyCompomentThatSuitsBetterThanTextfiledMaybeComboboxForEnum.class)) `
`}`

While I do understand issues need priority I can not understand why adding a simple getter to the API did not fit in any sprint in the last three years.
