### ISSUE TITLE
ConfirmDialog: disable close on Esc 

### ISSUE THREAD

**Issue by gianluca-valentini** [vaadin/flow-components#1678]
I'm using Vaadin 13.0.13.

Is there a way to use ConfirmDialog and disable the close on esc button?

I don't want that user can close the Dialog using esc o clicking out of it. Is this possible?
Gianluca

**Comment by jouni** [comment]
I’m still wondering why there’s a need to disabled cancelling a confirm dialog with the Esc key. I’m interested in hearing about a concrete use case, why it would be considered beneficial from the end user’s perspective.
