### ISSUE TITLE
Value objects which change equals/hashCode lead to weird editing issues

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow-components#1680]
Quoting a customer:

I've spent about 2 hours tracking down a problem involving GridPro (which might apply to any editable Grid) and I'd like to share my experience if you please.

I'm trying to use a GridPro to edit a Value Object (VO) class: a simple POJO with getters and setters per field.

Our application was originally developed under EJB2. When converting to EJB3, we understood at the time that every entity should return .equals() false when tested against a vanilla copy from the database if any field has been updated. This (misunderstanding?) has resulted in a lot of VO classes (many of which are used in entity class definitions) that compare all fields in the equals() method.

With GridPro, when you update the VO through a custom editor, it seems to use the getId() to identify which object has been updated [presumably by a call to refreshItem(vo)]. In the default DataProvider implementation, this didn't find the original row in the table because it uses the VO's .equals() method, and a field has been edited.
The result is that the VO becomes "detached" from the editor after the first edit: you can still edit the cell: but a custom renderer will display the original value, or the default renderer will display blank; and subsequent updates in the editor don't update the value. There is no error thrown (even though the presumed refreshItem() could not have found the item to refresh). This use of refreshItem() doesn't seem to be documented, so I was looking for the problem in the wrong place. (Most strictly, getId() documents that it's used to "determine equality between two items"; arguably it shouldn't be called here because there is only 1 item involved).

It's an easy fix (override DataProvider.getId()). But the behaviour of the custom editor is different to the built-in editors (which appear to work in this case), and it feels like there should be an error thrown or warning logged if the edited value suddenly "disappears" from the DataProvider. It was certainly not easy to identify the problem from the symptoms, even with the aid of a debugger.

As an aside: GridPro.createEditColumn() should not be protected. You cannot usefully override it, because whichever column you create would not then be added to the private idToColumnMap field - unless using a custom renderer.

This is my original description of the problem, which appeared as a framework bug:

I'm taking another look at GridPro, but I have a problem editing a numeric value using a "custom" editor (a NumberField); the rendered value disappears when I commit the edit.

Initially the value in the cell is 20.00
I can tell from the debugger that the renderer's ItemLabelGenerator is being called after the edit, the value set on the VO and returning the updated value (20.01). But the UI isn't updated to reflect the change.
Opening the editor again seems to return the updated value (20.01). If I edit this to 25.00 and commit the change, the display returns to 20.00 and the VO's setter is not called.
Editing the cell a second time opens the editor with 20.01.
There are no exceptions in the Javascript console, or server log, and adding a catch-all exception breakpoint doesn't reveal any server-side errors either.

If I take out the explicit renderer (which I only put in to force 2 decimal places) then the cell appears blank outside edit mode after the first edit.

There's no validation or further work; it's just a BigDecimal rounded to 2 decimal places and stored in a field in the bean backing the table row.
Yet when I try to replicate this again using without using the existing Vo class, it works as expected.

**Comment by yuriy-fix** [comment]
Could be related https://github.com/vaadin/flow-components/issues/1095
