### ISSUE TITLE
Add setItemLabelGenerator shorthand to RadioButtonGroup

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow-components#1681]
In case `item.toString()` is not suitable and you cannot override that method, you currently have to do `group.setRenderer(new TextRenderer<>(item -> getTextForItem(item)));`. While this technically works, it not completely obvious compared to the `setItemLabelGenerator` shorthand that is available in e.g. `ComboBox`.

**Comment by rolfsmeds** [comment]
Acceptance criteria: https://github.com/vaadin/platform/issues/2601

**Comment by mvysny** [comment]
Workaround: use RadioButtonGroupCompat from https://github.com/mvysny/karibu-migration/
