### ISSUE TITLE
set...Button(Element element) methods append buttons to slot instead of replacing the current button with the new button

### ISSUE THREAD

**Issue by spikeon** [vaadin/flow-components#1695]
set...Button(Element element) methods append buttons to slot instead of replacing the current button with the new button.

Use case:  I want to change the button's icon.  Since there isn't a  getConfirmButton for me to use to edit the button, I decided I would run setConfirmButton to replace it.  Instead of replacing the existing button, it added the new button next to the old one: 

![image](https://user-images.githubusercontent.com/6240857/57726223-cdd9cc00-7643-11e9-9c2c-5282c0cc5f2f.png)

Using "set" as a prefix tells the developer that there is a single value and running the method will "set" that value.  

Suggestion: setConfirmButton(Element element), setRejectButton(Element element), and setCancelButton(Element element) should remove all elements from the slot before adding the new element.

**Comment by yuriy-fix** [comment]
Should be verified with the latest Vaadin version.

**Comment by yuriy-fix** [comment]
Make sure the Flow counterpart is adding right buttons on re-attaching.

**Comment by sissbruecker** [comment]
Checked this in the latest version, and this specific issue does not occur anymore. However there are some related issues that came up, so I'm closing this in favor of those:
https://github.com/vaadin/flow-components/issues/2709
https://github.com/vaadin/flow-components/issues/2710
