### ISSUE TITLE
Can't open a DatePicker in a ComponentRenderer for a RadioButtonGroup

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/flow-components#1697]
Vaadin 14.6.1

If you put a DatePicker inside a RadioButtonGroup's ComponentRenderer, trying to open the DatePicker flickers and closes the overlay.
```
        RadioButtonGroup<String> radioButtonGroup = new RadioButtonGroup<>();
        radioButtonGroup.setItems("foo", "bar");
        radioButtonGroup.setRenderer(new ComponentRenderer<>( s -> new DatePicker()));
```
![rbg](https://user-images.githubusercontent.com/15027701/119309039-6ca75300-bc76-11eb-8584-8e72c249f230.gif)

Tested on Chrome and Firefox on Windows 10.

**Comment by rolfsmeds** [comment]
RadioButtonGroup's renderer is not intended to be used with interactive elements. There is a fundamental conflict between the radio button's interactivity (in which the button's label acts as a trigger for the button) and interactive elements inside the label.
