### ISSUE TITLE
remove powermock test

### ISSUE THREAD

**Issue by manolo** [vaadin/flow-components#1708]
Vaadin products  [must only depend](https://vaadin.com/docs/latest/guide/contributing/flow-unit-testing/#mocking) on mockito. 
We need to remove the [PowerMockTest](https://github.com/vaadin/flow-components/blame/master/vaadin-app-layout-flow-parent/vaadin-app-layout-flow/src/test/java/com/vaadin/flow/component/applayout/PowerMockTest.java) in app layout component.

**Comment by web-padawan** [comment]
Fixed by #2657
