### ISSUE TITLE
bom 17.0.1: / by Zero in DataCommunicator

### ISSUE THREAD

**Issue by hannes-angst** [vaadin/flow-components#1709]
Use `setDataProvider(DataProvider.ofCollection(items))` (e.g. when `setItem(<collection)` on dropdown component).
When dropdown is clicked error is thrown.

```
java.lang.ArithmeticException: / by zero
	at com.vaadin.flow.data.provider.DataCommunicator.fetchFromProvider(DataCommunicator.java:719) ~[flow-data-4.0.1.jar:4.0.1]
	at com.vaadin.flow.data.provider.DataCommunicator.activate(DataCommunicator.java:1100) ~[flow-data-4.0.1.jar:4.0.1]
```

Why:
`pagesize = 0` and `pagingEnabled = true` by default.

**Comment by rolfsmeds** [comment]
Hi, sorry about the delay in reacting to this issue.
Could you check if this still persists in V20, and which component it relates to?

**Comment by vlukashov** [comment]
I'm closing this ticket as there is not enough information to proceed.
Please feel free to re-open if this issue reappears and you could provide more details.
