### ISSUE TITLE
Charts should log some hint when turbo mode is enabled

### ISSUE THREAD

**Issue by sissbruecker** [vaadin/flow-components#1728]
Charts have a (well hidden) feature called "turbo" which is intended to improve performance when handling series with lots of data points. While turbo mode makes things go faster, it is limited in which series configurations and types of data points it supports. That means if turbo mode kicks in and your configuration does not match what it expects the chart just breaks. By default turbo mode activates when there are more than 1000 data points, it can be deactivated if the user chooses to. All of this is only documented in the code / API, there is no mention of it in the docs.

I would suggest to add some logging when turbo mode kicks in so that it is easier to discover by the developer. As soon as they know about the issue they might at least have a clue on what to look for in the API docs, or what to ask about when requesting support.

**Comment by rolfsmeds** [comment]
- [ ] Add dev-mode console output when turbo mode is engaged that briefly explains what it is and how to disable it.
- [ ] Add a section explaining Turbo Mode to the charts docs (https://vaadin.com/docs/latest/ds/components/charts/java-api/data and corresponding page for other platform versions)
