### ISSUE TITLE
NumberField ignores scientific notation

### ISSUE THREAD

**Issue by BTIJannis** [vaadin/flow-components#1731]
### Description
`NumberField` returns wrong value when user enters a number in scientific notation.

### Expected outcome
1.0e-2 should return 0.01

### Actual outcome
1.0 is returned. The exponent is ignored.

### Steps to reproduce
1. Put a `vaadin-number-field` element in the page.
2. Type number with scientific notation.
3. `getValue()` ignores exponent.

**Comment by TatuLund** [comment]
If is actually on the "e" that does not work. "E" works correctly.

E.g. "1.0E-2" or "2E2" gives the expected value.

**Comment by vursen** [comment]
Closing in favor of #4620
