### ISSUE TITLE
Disabled anchor should use proper styles

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow-components#1738]
See https://github.com/vaadin/flow/issues/10924.
The part for Flow is fixed in the Flow repo (`href` is removed for disabled anchor).

Themes should apply styles for disabled anchor properly (Lumo, etc.).

See https://github.com/vaadin/flow/issues/10924#issuecomment-834230053
https://github.com/vaadin/flow/issues/10924#issuecomment-834320736

**Comment by rolfsmeds** [comment]
Closing in favor of https://github.com/vaadin/web-components/issues/1594.
