### ISSUE TITLE
TextField (and ComboBox) do not allow to translate ARIA label of 'Clear' button

### ISSUE THREAD

**Issue by felixfontein** [vaadin/flow-components#1747]
The TextField web component has a `i18n` field for the Aria label of the Clear button: https://github.com/vaadin/web-components/blob/master/packages/vaadin-text-field/src/vaadin-text-field-mixin.js#L218 It is not possible to define it on the Java side.

The ComboBox is internally (on the web component side) using a `vaadin-text-field`, and doesn't seem to expose the i18n feature, so I'm afraid there's not much that can be done on the Java side.

**Comment by yuriy-fix** [comment]
The desired outcome could be achieved with `comboBox.getElement().executeJs("$0.inputElement.i18n = {'clear': $1}", comboBox.getElement(), "Custom Value");`.

**Comment by vlukashov** [comment]
Closing this as a duplicate of https://github.com/vaadin/web-components/issues/1115

**Comment by felixfontein** [comment]
@vlukashov is this really a duplicate? For the other component, the ARIA label is hardcoded in the web component. For `TextField`, the ARIA label is configurable in the web component, but the corresponding flow component does not give access to that API.

**Comment by vlukashov** [comment]
@felixfontein, you are right these issues are different. It was a mistake to claim that one is a duplicate of the other. I'm reopenning this issue now.

**Comment by web-padawan** [comment]
In Vaadin 22 we updated text field and related components to hide clear button from screen readers. The main reason is that announcing clear / toggle buttons was confusing as they aren't keyboard focusable. So the `i18n` object was removed.

Closing as wontfix.
