### ISSUE TITLE
Frontend build for integration tests broken locally in 14.6, 14.7 when running Flow in non-compatibility mode

### ISSUE THREAD

**Issue by sissbruecker** [vaadin/flow-components#1764]
### Description

Currently it's not possible to run integration tests in the 14.6 and 14.7 branches locally, because the test pages do no render correctly. Instead the pages show this error message:
```
java.lang.IllegalStateException: Unable to determine mode of operation. To use npm mode, ensure 'flow-build-info.json' exists on the classpath. With Maven, this is handled by the 'prepare-frontend' goal. To use compatibility mode, add the 'flow-server-compatibility-mode' dependency. If using Vaadin with Spring Boot, instead set the property 'vaadin.compatibilityMode' to 'true' in 'application.properties'.
```

To verify:
- check out 14.6
- run `mvn clean  in repo root`
- `cd vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/`
- `run mvn jetty:run -DskipTests=true`
- then open a page in the browser (eg: `http://localhost:8080/vaadin-date-picker`)

Instead of a correctly rendered test page the error above is shown. This also makes integration tests fail, since they only see error pages. This seems to only affect the integration test modules that are not using the Flow compatibility mode. The Maven modules for running ITs in the Flow compatibility mode (`pom-bower-mode.xml`) seem to work. This seems to affect all 14.x branches.

--- 

After investigating with @ZheSun88 we found that:
1. The `build-frontend` profiles in the integration test modules are likely missing the `flow:prepare-frontend` and `flow:build-frontend` goals
2. The version for the flow-maven-plugin is not explicitely specified, which makes it use the (latest?) version that is available in the local Maven repo.

Applying the changes above makes the integration tests pass successfully. The complete fixed profile looks like this:
```
    <profile>
      <id>build-frontend</id>
      <activation>
        <property>
          <name>!skipFrontend</name>
        </property>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>com.vaadin</groupId>
            <artifactId>flow-maven-plugin</artifactId>
            <version>${flow.version}</version> <!-- NEW -->
            <executions>
              <execution>
                <goals>
                  <goal>prepare-frontend</goal> <!-- NEW -->
                  <goal>build-frontend</goal> <!-- NEW -->
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
```

**Comment by ZheSun88** [comment]
fixes in #1766 and CP in #1771
