### ISSUE TITLE
Chain Components' Methods by Returning Component Itself

### ISSUE THREAD

**Issue by felix-seifert** [vaadin/flow-components#1791]
I want to request a change in the functionality of components' methods which increases developers' joy. The idea of chaining method calls is not new and should be available for Vaadin components as well.

Currently, the mentioned methods return `void`.  The change is that a component's method should return the component itself again to allow other method calls on this component.

## Examples

The following example illustrates how the methods have to be used now and how the can be chained. This then removes the need of assigning specific storage to the components.

### Example With Current State

```
VerticalLayout createContent() {
    VerticalLayout verticalLayout = new VerticalLayout(component1, component2, component3);
    verticalLayout.setClassName("class-name");
    verticalLayout.setHeightFull();
    verticalLayout.setPadding(false);
    verticalLayout.setMargin(false);
    return verticalLayout;
}
```

### Example With Chaining

```
VerticalLayout createContent() {
    return new VerticalLayout(component1, component2, component3)
        .setClassName("class-name")
        .setHeightFull()
        .setPadding(false)
        .setMargin(false);
}
```

### Reference to Existing Implementation

The described chaining is already implemented for `Grid<>`. 

```
grid.addColumn(Entity::getValue).setHeader("Value Label")
                .setAutoWidth(true).setSortable(true);
```

**Comment by vlukashov** [comment]
Thanks for sharing your idea, @felix-seifert! It's not the first time when someone suggests making Vaadin APIs _fluent_, and I think it would be a nice improvement for the developer experience in some cases.

I'll merge this issue into https://github.com/vaadin/flow/issues/486, so that we do not have multiple GitHub issues open for the same idea.
