### ISSUE TITLE
Grid doesn't appear if We add it in a dialog

### ISSUE THREAD

**Issue by hfazai** [vaadin/flow-components#1843]
### Description

I'm adding a grid to a dialog. This is what it gives me:
<img src="https://user-images.githubusercontent.com/57005249/123136386-c738f800-d44a-11eb-907b-eb9b15313e17.png" width="120">

The width of the grid is very thin and it needs to be set manually to appear. 

### Expected outcome

The width of the dialog grows so that we can see the grid
<img src="https://user-images.githubusercontent.com/57005249/123137070-81c8fa80-d44b-11eb-9058-5609a3b06ba9.png" width="500">

### Steps to reproduce

1. Create a Grid component and configure columns to autoWidth = true
2. Add the Grid to a dialog.
3. Open the dialog.

### Workaround

I finally ended with a workaround based on columns width.
I retrieve the width of the column from client using javascript call. And then I set the grid width to the addition of the columns widths:

Here is a code sample (in kotlin):
````KOTLIN
    val ui = UI.getCurrent()
    var width = ""
    table.headerComponents.forEach { header ->
      header.element.addAttachListener {
        Thread {
          synchronized(width) {
            val headerWidth = getWidth(header.parent.get().element, ui)

            if (width == "") {
              width = headerWidth.orEmpty()
            } else if(headerWidth != null && headerWidth.isNotEmpty()){
              width = "$width + $headerWidth"
            }
            ui.access {
              widthStyler.width = "calc(calc($width) + 20px)"
              widthStyler.minWidth = "calc(calc($width) + 20px)"
            }
          }
        }.start()
      }
    }

  fun getWidth(element: Element?, ui: UI): String? {
    val future = CompletableFuture<String>()

    ui.access {
      ui.page
        .executeJs("return $0.width", element)
        .then(String::class.java) { value ->
          future.complete(value)
        }
    }

    return future.get()
  }
````

### Environment

- v18.0.3
- Fedora 32

### Browsers Affected

- [ ] Chrome

**Comment by rolfsmeds** [comment]
Hi, this behaves as expected, since the Grid's default width is not derived from its columns, but is simply 100% of its container (implicitly, by being a block element). The Dialogs default width, meanwhile, is based on its contents. So Grid expects its behavior to determine its width and the container expects the Grid to deteremine _its_ width, thus resulting in essentially an undefined width. So you need to explicitly set a width either on the Grid or the Dialog.

There's a separate enhancement request about making the Grid default its width based on its columns: https://github.com/vaadin/web-components/issues/1905.

**Comment by hfazai** [comment]
Hi @rolfsmeds There is no "standard" value that we can set to the width of the Grid/Dialog. That's because the width of the columns is variable and data changes.

Allowing the contents to automatically define the width of a Grid is a good idea for better user experience.

**Comment by rolfsmeds** [comment]
I agree, but that's already covered by the ticket I linked.
