### ISSUE TITLE
RadioButtonGroup hasProperty("readonly") returns false

### ISSUE THREAD

**Issue by AlexeiBugai** [vaadin/flow-components#1851]
### Description
RadioButtonGroup getElement().hasProperty("readonly") returns false

### Expected outcome

RadioButtonGroup getElement().hasProperty("readonly") should return true

### Actual outcome

RadioButtonGroup getElement().hasProperty("readonly") returns false

### Minimal reproducible example

		RadioButtonGroup<String> field1 = new RadioButtonGroup<>();
		field1.setReadOnly(true);
		field1.setItems("Option one", "Option two", "Option three");
		field1.setValue("Option one");
   	        
      System.out.println(field1.getElement().hasProperty("readonly"));

### Steps to reproduce

1. Add a RadioButtonGroup component to a page.
2. Get getElement().hasProperty("readonly")

### Environment

- v20.0.3
- Windows 10

### Browsers Affected

All

**Comment by DiegoCardoso** [comment]
Hi @AlexeiBugai 

This is the expected behavior, since `setReadOnly` uses a different logic to set the state on the component.

To get the current state of the component, `isReadOnly` should be used instead.

**Comment by AlexeiBugai** [comment]
@DiegoCardoso but all other components has this property, it will be nice to have same logic

**Comment by DiegoCardoso** [comment]
Hi @AlexeiBugai 

You're correct. That's a current known limitation. We have on our backlog an [issue](https://github.com/vaadin/web-components/issues/822#issue-894986937) to support this property properly.
