### ISSUE TITLE
Datetime picker on a form does not overwrite (clear) value after first use

### ISSUE THREAD

**Issue by HayoBaanAtHand** [vaadin/flow-components#1868]
### Description

The date time picker exhibits some really weird behaviour when used on a form. Not only does it chop seconds/milliseconds (see #1428), it also maintains its value when it should be cleared when the entity that is bound to it has a null value.

The weird thing is that this happens ONLY the first time, after (manually) clearing the value, it behaves fine.

### Expected outcome

Value should be cleared.

### Actual outcome

Value remained stuck with previous value.

### Minimal reproducible example

See attached zip.
[DateTimePickerBug.zip](https://github.com/vaadin/flow-components/files/6758205/DateTimePickerBug.zip)

### Steps to reproduce

- Run application from attached zip e.g. with `SPRING_PROFILES_ACTIVE=native mvn -U spring-boot:run -Dspring-boot.run.arguments='--spring.config.location=file:config/bootstrap.properties'`.
- Enter some name and password, “login”, navigate to entity page.
- Click on the first entry in the grid. The form will open with the entity.
- Now click on the second entry in the grid to switch the form editor to the second entity. Notice the Date A field is not cleared even though it should have been!
- If you now attempt to switching entries, you get a warning stating you have unsaved changes.
- Manually clear the Date A field.
- Click Save
- Select the first grid entry again and when you now switch to the second item, the date A is cleared as expected.

### Environment

- Vaadin 14.6.x
- Mac OS 11.4

### Browsers Affected

Verified with (others not tested):
- [ ] Chrome
- [X] Firefox
- [X] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by DiegoCardoso** [comment]
I was able to verify the wrong behavior. I tried to reproduce it with my own V14 project with `Binder` + `DateTimePicker`, but I wasn't able to see the same issue there. Not sure yet what different on the OP's project that is causing this issue to emerge.

**Comment by HayoBaanAtHand** [comment]
Glad you can reproduce this (were you able to reproduce #1428 too?). Not sure what could be different either. I've modelled our application (and this demo) after the default Spring project pretty closely…

Hope this gets resolved soon; this bug is preventing our projects to use the datetime picker in these cases and we really need to ☹️.
