### ISSUE TITLE
`flow-component-renderer` breaks the notification CSS cascade

### ISSUE THREAD

**Issue by vursen** [vaadin/flow-components#1876]
## Description

While working on [the Flow examples](https://vaadin.com/docs/latest/ds/components/notification) for `vaadin-notification`, I noticed that the basic TypeScript example and the equivalent Flow example are displayed differently.

The reason is that Flow renders the notification content through the intermediate `flow-component-renderer` component that breaks the layout and prevents the [`[part='content'] ::slotted(vaadin-button)`](https://github.com/vaadin/web-components/blob/master/packages/vaadin-notification/theme/lumo/vaadin-notification-styles.js#L37-L40) selector to apply.

Look at the examples:

### TypeScript
```js
<vaadin-notification
  opened
  .renderer="${guard([], () => (root: HTMLElement) => {
    render(
      html`
        <div>Content</div>
        <vaadin-button>Click me!</vaadin-button>
      `,
      root
    );
  })}"
></vaadin-notification>
```

![image](https://user-images.githubusercontent.com/5039436/124562658-f5a1d480-de47-11eb-9d37-fdff3e4fcb93.png)

DOM structure:
```
[part='content'] > vaadin-button
```

### Flow

```java
Notification notification = new Notification();
notification.setOpened(true);
notification.add(
  new Div(new Text("Content")),
  new Button("Click me")
);
add(notification);
```

DOM structure:
```
[part='content'] > flow-component-renderer > div > vaadin-button
```

![image](https://user-images.githubusercontent.com/5039436/124563743-fe46da80-de48-11eb-9d68-63a3d74d2a06.png)

## Expected outcome

The notification content **looks the same** in the TypeScript example and the equivalent Flow example.

## Actual outcome

The notification content **looks different** in the TypeScript example and the equivalent Flow example.

## Live Demo

https://user-images.githubusercontent.com/5039436/124568139-4a941980-de4d-11eb-8d45-f2891469ac37.mov

### Java

```java
package com.vaadin.demo.component.notification;

import com.vaadin.flow.component.Text;
import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.notification.Notification;
import com.vaadin.flow.router.Route;
import com.vaadin.demo.DemoExporter; // hidden-source-line

@Route("notification-basic")
public class NotificationBasic extends Div {
  public NotificationBasic() {
    Notification notification = new Notification();
    notification.setOpened(true);
    notification.add(
      new Div(new Text("Content")),
      new Button("Click me")
    );
    add(notification);
  }

  public static class Exporter extends DemoExporter<NotificationBasic> { // hidden-source-line
  } // hidden-source-line
}
```

### TypeScript

```ts
import 'Frontend/demo/init'; // hidden-source-line
import '@vaadin/vaadin-template-renderer/src/vaadin-template-renderer'; // hidden-source-line (Legacy template renderer)

import { html, LitElement, render } from 'lit';
import { customElement, state } from 'lit/decorators';
import { guard } from 'lit/directives/guard';
import '@vaadin/vaadin-button/vaadin-button';
import '@vaadin/vaadin-notification/vaadin-notification';
import { applyTheme } from 'Frontend/generated/theme';

@customElement('notification-basic')
export class Example extends LitElement {
  protected createRenderRoot() {
    const root = super.createRenderRoot();
    // Apply custom theme (only supported if your app uses one)
    applyTheme(root);
    return root;
  }

  render() {
    return html`
      <vaadin-notification
        opened
        .renderer="${guard([], () => (root: HTMLElement) => {
          render(
            html`
              <div>Content</div>
              <vaadin-button>Click me!</vaadin-button>
            `,
            root
          );
        })}"
      ></vaadin-notification>
    `;
  }
}
```

## Related issues

https://github.com/vaadin/flow/issues/5056

**Comment by web-padawan** [comment]
As you can see the [flow-component-renderer](https://github.com/vaadin/flow/blob/fad444d1da43169da98d38a413890bfcc4d48da0/flow-data/src/main/resources/META-INF/resources/frontend/flow-component-renderer.js#L9-L18) does not set any display on itself which implies `display: inline`.
We could consider using [display: contents](https://caniuse.com/css-display-contents) or make it inherit some properties.

**Comment by vursen** [comment]
@web-padawan Good point! I think it is a possible solution to fix the layout. 

However, the `[part='content'] ::slotted(vaadin-button)` selector still won't work.

**Comment by web-padawan** [comment]
Yes, this is basically the same as not being able to style icons slotted in tabs with anchors (which is also quite annoying).
I would say it could be only fixed by making a breaking change to how we approach composition of components.

**Comment by DiegoCardoso** [comment]
Note that from the user perspective, to style the Notification content, it is preferable to do it through a global CSS instead of a custom theme, since `::slotted()` is quite limited to what it can do. 

There's still going to be the issue with `flow-component-renderer` being an inline element that needs to workaround. There's [one issue reported](https://github.com/vaadin/flow/issues/5056) on the Flow repo about it.

**Comment by vursen** [comment]
To work around this issue for the time being, add the following CSS snippet globally:

```css
vaadin-notification-card flow-component-renderer,
vaadin-notification-card flow-component-renderer > div {
  display: contents;
}
```
