### ISSUE TITLE
Select all check box does not work in the UI

### ISSUE THREAD

**Issue by MrMaavin** [vaadin/flow-components#1905]
### Description
I have a grid with a datprovider and lazy loading, therefore my data is not in memory.

My Code looks like this:
```
Grid<CustomClass> grid;
...
// set selection mode
grid.setSelectionMode(SelectionMode.MULTI);
// make select all check box visible
GridSelectionModel<CustomClass> selectionModel = grid.getSelectionModel();
((GridMultiSelectionModel<CustomClass>) selectionModel)
    .setSelectAllCheckboxVisibility(SelectAllCheckboxVisibility.VISIBLE);
```

If i log the selected items with the following code the check box works as expected (e.g. if i have 32 rows the size of hte selected items is 32)
```
grid.addSelectionListener(l -> {
    log.info("selected: " + l.getAllSelectedItems().size());
});
```

_Vaadin Version 14.6.2_

### Expected outcome
The check boxes in all rows are checked
![image](https://user-images.githubusercontent.com/49553486/125930318-b55d091c-9c4b-4e0a-9583-0da0c52d35fd.png)

### Actual outcome
The check boxes in all rows are not checked
![image](https://user-images.githubusercontent.com/49553486/125929740-fb4cd05a-4a49-42c1-bfef-3091c7ea5c0d.png)

**Comment by MrMaavin** [comment]
The solution is to call  `dataPovider.refreshAll()` in the listener.

grid.addSelectionListener(l -> {
    ...
     dataPovider.refreshAll();
    ...
});

**Comment by TatuLund** [comment]
Is this related to https://github.com/vaadin/flow-components/issues/2154 ? Does this happen still with Vaadin 14.7.5 ?

**Comment by hdamr** [comment]
It is probably fixed by [this](https://github.com/vaadin/flow-components/pull/2231), because it takes into account `DataProvider`, please let us know if your issue is fixed by updating to latest version.

**Comment by yuriy-fix** [comment]
Closing as stale. Feel free to re-open if still valid.
