### ISSUE TITLE
Remove demo module from master in Flow components

### ISSUE THREAD

**Issue by web-padawan** [vaadin/flow-components#193]
Starting from V15 java components can't be demoed in vaadin.com making the demo artifact useless.
Verify the IT module has all the needed views for tests, if needed move the demo UI to IT module

---

Originally reported at https://github.com/vaadin/components-team-tasks/issues/508 but I could not transfer the issue from a private repo.

**Comment by tomivirkki** [comment]
This is now finished. Closing.
