### ISSUE TITLE
Grid editor: second editItem request is not working

### ISSUE THREAD

**Issue by hfazai** [vaadin/flow-components#1997]
### Description

When calling `editItem()` many times, only the first one is taking effect.

### Expected outcome

All `editItem` are called and eventually the last one is taking effect.

### Minimal reproducible example

```KOTLIN
    class P(val col: String)

    val grid = Grid<P>()

    grid.addColumn(P::col)
      .setHeader("header")
      .editorComponent = TextField()
    grid.editor.binder = Binder()
    val a = P("foo")
    val b = P("bar")
    grid.setItems(a, b)
    add(Button("Edit B") {
      grid.editor.editItem(a)

// DO things ...

      grid.editor.editItem(b)
    })

    add(grid)
```

### Expected

When I click on the button, I expect it to edit the item `b` but `grid.editor.editItem(b)` is not working because an edit item request for the item `a` is not finished yet.

### Environment

- v18.0.3
- Fedora 32

### Browsers Affected

- Chrome

**Comment by hdamr** [comment]
If you can, please provide a working example created from start.vaadin.com, I find it difficult to set up a full demo app with intended behaviour. But based on investigation I had, each call to `editItem` is assuming that we are only editing one item and we want to have the effect of this edit being reflected on the UI and any further call to `editItem` has no effect, look [here](https://github.com/vaadin/flow-components/blob/e49fcddf292d9683c6c4e761abf52746800cac2a/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/editor/EditorImpl.java#L135), so assuming that two edit operations will be handled in go is not right here.

**Comment by yuriy-fix** [comment]
Closing as stale.
