### ISSUE TITLE
Paddingless read-only TextArea gets a scrollbar on Chrome on Windows

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/flow-components#2008]
### Description

A read-only TextArea with no padding will get a scrollbar on Chrome on Windows but not on other browsers.

### Expected outcome

The scrollbar should not appear on any browser.

### Actual outcome

TextArea gets a scrollbar, on Chrome on Windows.

### Live Demo (optional)

Chrome on Windows:
![image](https://user-images.githubusercontent.com/15027701/129677797-131cee7f-07f5-4a19-b3a4-a4e6bcbb6d30.png)

Chrome on Mac:
![image](https://user-images.githubusercontent.com/15027701/129677854-63531dcb-165a-4932-841d-e33f1bf32492.png)

### Minimal reproducible example

[my-app.zip](https://github.com/vaadin/flow-components/files/6997687/my-app.zip)

### Steps to reproduce

1. Create a TextArea t
2. Set it to be readonly
3. Set width to e.g. 20rem: t.setWidth("20rem");
3. Set two lines of content like t.setValue("Abrakadabra asgasdfasdf adsasd\nWdsfasdags asgasdgasd jsdafg");

### Environment

- v20.0.6
- Windows 10

### Browsers Affected

- [x] Chrome
- [ ] Firefox (tested)
- [ ] Safari
- [x] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by darmro** [comment]
Hi!
**In Vaadin 20.0.4 everything was ok**. The problem appeared when the `TextArea `component was changed (a new extra div `textarea-wrapper` was introduced in shadow dom). 
And this is causing the problem:
```
.textarea-wrapper::after {
    content: attr(data-replicated-value) ' ';
    white-space: pre-wrap;
    visibility: hidden;
}
```
So workaround for this is setting:
`  content: ''; `

**Comment by web-padawan** [comment]
The change that caused this regression was rolled back by https://github.com/vaadin/web-components/pull/2456, now it works properly:

![Screenshot 2022-02-08 at 11 52 39](https://user-images.githubusercontent.com/10589913/152962415-9cd91a71-0acc-43eb-8778-84206e0a22ff.png)

The same fix for Vaadin 14 was done in https://github.com/vaadin/vaadin-text-field/pull/581. Closing as fixed.
