### ISSUE TITLE
method for triggering reflow in the charts component

### ISSUE THREAD

**Issue by fhdhsni** [vaadin/flow-components#2021]
The charts component automatically reflows when the window resizes, but if the container is resized without a window resize event [`__reflow()`](https://github.com/vaadin/web-components/blob/21.0/packages/vaadin-charts/src/vaadin-chart.js#L923-L929) should be called explicitly. Because of that, I think `__reflow()` should be public and have a Flow counterpart method as well.

see https://github.com/vaadin/web-components/pull/2351

**Comment by web-padawan** [comment]
Updated the web component to use `ResizeObserver` in https://github.com/vaadin/web-components/pull/3463 so this is no longer needed. The improvement will land in the upcoming Vaadin 23 stable release.
