### ISSUE TITLE
Grid with initial Multisorting only loads first page from DataProvider

### ISSUE THREAD

**Issue by dskbrd** [vaadin/flow-components#2069]
### Description

When creating a Grid with multisorting only the first page is loaded from the Dataprovider.

(it seems like this is an issue when filling and sorting the Grid happens in one roundtrip to the frontend)

### Expected outcome

The Grid should load all rows that are currently visible

### Actual outcome

Only the first page is loaded.
Using keyboard navigation the user can select the unloaded rows which results in JS-exceptions.
You have to scroll to the end of the grid and back to force it to load the missing elements.

### Live Demo

![image](https://user-images.githubusercontent.com/20167536/131333114-04b0190a-7ed8-49a7-9e88-bae0454bc9f9.png)

### Minimal reproducible example

I have an example here: https://github.com/dskbrd/vaadin-grid-bug/
I used an example generated from https://start.vaadin.com and just added sorting with this [commit](https://github.com/dskbrd/vaadin-grid-bug/commit/a27b4cc)

### Steps to reproduce

* first you need Grid component with a DataProvider that uses Pagination
* enable Multisorting for the Grid
* sort the Grid by two or more columns from the java code

See this [commit](https://github.com/dskbrd/vaadin-grid-bug/commit/a27b4cc) for the exact changes.

### Environment

- Vaadin v14.6.8
- Windows 20H0 64bit

### Browsers Affected

- [x] Chrome
- [x] Firefox

Firefox and Chrome are the only browsers I could test with but i suspect it does not depend on the browser.

**Comment by web-padawan** [comment]
Confirmed with Vaadin 14.8.3 - some rows aren't initially rendered and only become rendered after window resize.
This issue does not occur with Vaadin 22.0.4 where all the rows are rendered properly, so no errors are thrown.

**Comment by TatuLund** [comment]
Here is simplified test scenario.

When this view is opened using Vaadin 14.8.x the "loading" attribute of vaadin-grid is not removed (you can check it with Chrome inspector). This indicates that loading-changed event is not fired. When you use the same view with Vaadin 21 or 22, the attribute is cleared correctly.

```
@Route("grid-multisort-test")
public class GridMultisortTest extends VerticalLayout {

    private static final long serialVersionUID = 1L;

    public GridMultisortTest() {
        setAlignItems(Alignment.STRETCH);

        final Grid<Kommunikationsweg> grid = new Grid<>();

        grid.addThemeVariants(GridVariant.LUMO_COLUMN_BORDERS, GridVariant.LUMO_WRAP_CELL_CONTENT);
        grid.setMultiSort(true);
        grid.setHeightByRows(true);
        grid.setWidthFull();

        final Grid.Column<Kommunikationsweg> kommunikationsartColumn =
            grid.addColumn(Kommunikationsweg::getKommunikationsart)
                .setHeader("Kommunikationsart")
                .setSortable(true)
                .setComparator(Comparator.comparing(Kommunikationsweg::getKommunikationsart, String.CASE_INSENSITIVE_ORDER));
        final Grid.Column<Kommunikationsweg> kommunikationColumn =
            grid.addColumn(Kommunikationsweg::getKommunikation)
                .setHeader("Kommunikation")
                .setSortable(true)
                .setComparator(Comparator.comparing(Kommunikationsweg::getKommunikation, String.CASE_INSENSITIVE_ORDER));
        grid.addColumn(Kommunikationsweg::getBemerkung)
            .setHeader("Bemerkung")
            .setSortable(true)
            .setComparator(Comparator.comparing(Kommunikationsweg::getBemerkung, Comparator.nullsFirst(String.CASE_INSENSITIVE_ORDER)));

        grid.sort(Arrays.asList(new GridSortOrder<>(kommunikationsartColumn, SortDirection.ASCENDING),
                                new GridSortOrder<>(kommunikationColumn, SortDirection.ASCENDING)));

        grid.setItems(new ArrayList<>());

        grid.setDataProvider(new ListDataProvider<>(new ArrayList<>()));

        add(grid);
    }

    public static class Kommunikationsweg {

        private String kommunikationsart;
        private String kommunikation;
        private String bemerkung;

        public String getKommunikationsart() {
            return kommunikationsart;
        }

        public void setKommunikationsart(String kommunikationsart) {
            this.kommunikationsart = kommunikationsart;
        }

        public String getKommunikation() {
            return kommunikation;
        }

        public void setKommunikation(String kommunikation) {
            this.kommunikation = kommunikation;
        }

        public String getBemerkung() {
            return bemerkung;
        }

        public void setBemerkung(String bemerkung) {
            this.bemerkung = bemerkung;
        }
    }

}
```

**Comment by timbo86** [comment]
Now in 14.8.3 this event is never fired at all, when data is returned. No matter if multi sort is used or not. And also not depending on the amount of data received.

**Comment by tomivirkki** [comment]
> Here is simplified test scenario.
> When this view is opened using Vaadin 14.8.x the "loading" attribute of vaadin-grid is not removed

@TatuLund 
I tried running your example with the following Vaadin versions: 14.8.0, 14.8.4, 14.6.8 In all cases there was no "loading" attribute on the "vaadin-grid":

![Screenshot 2022-02-08 at 12 22 55](https://user-images.githubusercontent.com/1222264/152968648-b31ff31a-d70a-4044-86c2-168d65af3384.png)

**Comment by timbo86** [comment]
Yes, now in 14.8 the attribute is set correctly, but the 'loading-changed' event is never fired.

**Comment by tomivirkki** [comment]
Fixed by https://github.com/vaadin/flow-components/pull/2635
