### ISSUE TITLE
Vaadin Rich Text Editor behaves as if 1 char wide on Safari browser

### ISSUE THREAD

**Issue by tinomatic** [vaadin/flow-components#2070]
### Description

Under certain circumstances typed characters appear beneath each other in a 1 char wide column rather than horizontally across the screen when using the **Safari browser**.

The editor renders correctly and functions normally. However, when deleting chars, if you delete the last char and hit backspace again, typed characters render vertically. 

### Expected outcome

Expectation is that it is possible to hit backspace without any effect when there are no chars in the editor text area without subsequently affecting functionality.

### Actual outcome

If deleting text and then hitting backspace again, the cursor appears to jump to the beginning of the text area and any chars typed then appear after the cursor, which does not move from the top left of the text area. Characters are added and displayed vertically.

If you move the cursor to follow a character, the text area functions normally again.

### Minimal reproducible example

Try it here: https://demo.vaadin.com/invoice-editor-app/

Highlight all the text in the editor, hit backspace twice, type some characters.

### Steps to reproduce

1. Type some text into a vaadin RTE using the Safari browser on a mac.
2. Hit backspace to delete the tech character by character.
3. Hit backspace once again and the cursor will locate to the very top left corner of the text area
4. Type some character - The cursor remains in the top left while the character track down the screen.
5. Backspace does nothing. The delete key deletes the text. 

### Environment

- Vaddin 14.6.3 and 14.6.8 tested
- Big Sur - macOS 11.5.2 (Safari 14.1.2)

### Browsers Affected

Tested on Chrome, FF and Safari - Only manifest on Safari
- [ ] Chrome
- [ ] Firefox
- [X] Safari

- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by sissbruecker** [comment]
I can not reproduce the issue anymore with either Vaadin 14.7.1 (current LTS) or Vaadin 22.0.0-alpha5. It might have been fixed as part of https://github.com/vaadin/web-components/pull/2590.

Unfortunately the invoice editor app is very much out-of-date (using Vaadin 19). I tested with projects created from start.vaadin.com, and added the following lines from the invoice editor app:
```java
        RichTextEditor rte = new RichTextEditor();
        rte.setThemeName("compact");
        rte.setValue(
                "[{\"attributes\":{\"bold\":true},\"insert\":\"Team lunch participants:\"},{\"insert\":\" Manolo, Joonas, and Matti\\nTraveling in Antwerp:\\nMetro from the hotel to the venue\"},{\"attributes\":{\"list\":\"bullet\"},\"insert\":\"\\n\"},{\"insert\":\"Taxi from the airport to the hotel\"},{\"attributes\":{\"list\":\"bullet\"},\"insert\":\"\\n\"}]");
        this.add(rte);
```

I'll proactively close the ticket, please notify if you still experience this issue with a maintained Vaadin version.
