### ISSUE TITLE
LoginOverlay doesn't open when `setOpened(true)` is called in a view's `onAttach`

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/flow-components#2087]
### Description

LoginOverlay does not open when you call `setOpened(true)` in an `onAttach` method. This used to work in 14.x, and is broken in 21.0.0.rc3 . Calling the same method in the view's constructor works as expected.

### Expected outcome

LoginOverlay should open

### Actual outcome

`<vaadin-login-overlay>` does not get the `opened` property.

### Minimal reproducible example

```
@Route(value = "login")
public class LoginView extends FlexLayout implements AfterNavigationObserver {

    private final LoginOverlay login;

    public LoginView(){
        login = new LoginOverlay();
        login.setForgotPasswordButtonVisible(false);
        login.setAction("login");
        // uncommenting this will make the overlay open normally
        // login.setOpened(true);
        add(login);
    }

    @Override
    protected void onAttach(AttachEvent attachEvent) {
        super.onAttach(attachEvent);
        login.setOpened(true);
    }
}
```

[my-app.zip](https://github.com/vaadin/flow-components/files/7105288/my-app.zip)

### Steps to reproduce

1. Run the attached project
2. Nothing shows

### Environment

- Vaadin platform.: 21.0.0.rc3
- Windows 10

### Browsers Affected

- [x ] Chrome

**Comment by OlliTietavainenVaadin** [comment]
Possibly related: https://github.com/vaadin/web-components/issues/2125

**Comment by mshabarov** [comment]
I overlooked the repo is `flow-components` and though it was `flow`, thus, gave the severity and impact labels. Feel free to change them if you disagree.
