### ISSUE TITLE
ComboBox should implement HasTheme

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow-components#2090]
Vaadin 14.6.8. ComboBox doesn't implement the HasTheme interface. It should since it has theme variants, according to https://vaadin.com/components/vaadin-combo-box/java-examples/theme-variants

**Comment by web-padawan** [comment]
Duplicate of #1074, sorry about the fact that it's open for so long.

**Comment by web-padawan** [comment]
UPD: sorry the issue was wrong, here is the correct one https://github.com/vaadin/flow-components/issues/454
