### ISSUE TITLE
column-size is to small if setAutoWidth and sorting is enabled (header name are cutted)

### ISSUE THREAD

**Issue by knoxyz** [vaadin/flow-components#2092]
### Description
if setAutoWidth & sorting are enabled and the column cell-text short,
the header name from a grid column is strong cutted like "abc...".

### Expected outcome

The setAutoWidth should also consider the size from the header-name **and** the sorting icon.

### Actual outcome

setAutoWidth seems to be only consider the size from the cell-text.

### Environment

- vaadin flow 14.6.8
- Windows 10.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by knoxyz** [comment]
![grid-column-header-name-cutted](https://user-images.githubusercontent.com/30576590/132030788-c95ffb88-7d96-492e-a519-cdfa3f4baf54.png)

**Comment by knoxyz** [comment]
The same issue was already report on 28 May 2020, but without any response until today :-(
https://github.com/vaadin/flow-components/issues/1457

**Comment by yuriy-fix** [comment]
Sorry, we are aware of the issue, but it wasn't prioritized. 
Closing this in favour of https://github.com/vaadin/flow-components/issues/1457. If you have any additional information on the issue, please add it to https://github.com/vaadin/flow-components/issues/1457
