### ISSUE TITLE
Setting steps after initializing DateTimePicker truncates time value

### ISSUE THREAD

**Issue by sissbruecker** [vaadin/flow-components#2101]
### Description

Changing the steps setting some time after the DateTimePicker was initialized, leads to seconds and milliseconds being removed from the value, or just not being displayed correctly, when setting a value from the server-side.

### Expected outcome

When setting a value from the server-side, the DateTimePicker displays the correct values for seconds and the milliseconds.

### Actual outcome

The DateTimePicker displays `00` for seconds, or `000` for milliseconds.

There is a small ficker in the current version, where the correct values are displayed, before being changes to zeros.

### Live Demo (optional)

https://user-images.githubusercontent.com/357820/132477730-5162ed9f-324a-4456-92df-d48873806212.mp4

### Minimal reproducible example

```java
public class HelloWorldView extends VerticalLayout {

    public HelloWorldView() {
        DateTimePicker dateTimePicker = new DateTimePicker();

        Button setStepsButton = new Button("Set second precision", e -> {
            dateTimePicker.setStep(Duration.of(30, ChronoUnit.SECONDS));
        });

        Button setValueButton = new Button("Set current date time", e -> {
            dateTimePicker.setValue(LocalDateTime.now());
        });

        add(dateTimePicker, setStepsButton, setValueButton);
    }
}
```

### Steps to reproduce

1. Add a DateTimePicker to a page.
2. Add button that changes the steps to 30 seconds
3. Add button that sets the current date and time
4. Run, open in browser
5. Click button to change steps
6. Click button to set current date and time

### Additional notes

The issue does not occur when setting the steps immediately after constructing the DateTimePicker:
```
DateTimePicker dateTimePicker = new DateTimePicker();
dateTimePicker.setStep(Duration.of(30, ChronoUnit.SECONDS));
```

The web component doesn't seem to be affected by this, and changing the value on the client side works as well.

### Environment

- Vaadin 14.6.8
- MacOS

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari

**Comment by nSharifA** [comment]
"The issue does not occur when setting the steps immediately after constructing the DateTimePicker:"
Only if you set the unit to seconds, with milliseconds the problem still occurs even if you set it immediatly after constructing the DateTimePicker.

It's a serious problem should be fixed as soon as possible.
