### ISSUE TITLE
Context-Menu -- completely different behaviour between add(...) and addItem(...)

### ISSUE THREAD

**Issue by F0rce** [vaadin/flow-components#2131]
### Description

Completely different and unintended behevaior of two exactly same componentes between being added to a context-menu via add(...) and addItem(...).

### Expected outcome

Same behaviour between add(...) and addItem(...).

### Actual outcome

Clicking on an item added via add(...) works perfeclty fine in all cases, but when clicking on an item added via addItem(...) it's mostly not working properly.

### Live Demo (optional)

https://preview.f0rce.de/tmp/context-menu-bug

### Minimal reproducible example

https://github.com/F0rce/preview.f0rce.de/tree/main/tmp/context-menu-bug

### Steps to reproduce

*(Assuming you are using the code-example above)*

Mozilla/Chrome/Safari:
- Clicking on the first and second item (added via add(...)) -> works completely normal and as intended on tested browsers

- Clicking on the third and fourth item (added via addItem(...)) -> works sometimes or doesnt work at all
➙ When clicking on the Anchor added as addItem(...) you get redirected to a page saying not found. But when you open the browser's page inspector (F12), and click on the href in the Anchor HTML Object, you will download the file correctly
➙ When clicking on the DynamicFileDownloader (DFD) added as addItem(...) it sometimes gets downloaded correctly, but in most cases the downloaded file is completely empty, or has some wierd html in it

### Environment

- Vaadin 14.6.9
- Windows 10 Pro 21H1 (19043.1165) & macOS Big Sur 11.5.2 (20G95)

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by rolfsmeds** [comment]
This is actually completely intended behavior, by design:

- `addItem` adds a selectable menu item to the menu, and interactive elements inside the menu item are not supported because the menu item itself is selectable by clicking.
- `add` is the correct method to use for adding arbitrary elements inside the menu, including interactive ones, that are not selectable as menu items.

We will rephrase the javadocs for these methods to make the distinction more clear.

**Comment by F0rce** [comment]
@rolfsmeds thanks for the clarification.

Is there maybe a way to add the style changes to a element added via `add` ?

Because `addItem` is looking a lot better than `add`.

If not, thanks for your help :)

David

**Comment by rolfsmeds** [comment]
I don't think we want to do that, as elements added with add are not menu items, so showing the same kind of hover etc styling for them would be wrong. However, as that element is your own implementation, you could probably apply corresponding styling to it manually.

**Comment by F0rce** [comment]
Thank you very much, have a nice week :)
