### ISSUE TITLE
Cant create columns in Grid based on bean properties and set rednerers for columns later

### ISSUE THREAD

**Issue by domingo78** [vaadin/flow-components#2144]
In Vaadin 8 I can create a Grid passing to its constructor bean properties and in other step set special renderer to some columns. In Vaadin Flow I cant do this.

Vaadin 8:

```
objectsGrid=new Grid<>(getDataClass());
			for (ColumnDescriptor cd:columns) {
				column=objectsGrid.getColumn(cd.getAttribute());
				if (column!=null) {
					column.setExpandRatio(cd.getExpandRatio());
					
					if (cd.getRenderedProvider()!=null) {
						column.setRenderer(cd.getRenderedProvider().getRendered());
					}
				}
			}
```

In Vaadin Flow I can do column.setRenderer(...). I need this feature because I use some XML files to configure grids, columns, renderers. etc.

**Comment by yuriy-fix** [comment]
Closing as a duplicate of https://github.com/vaadin/flow-components/issues/1494.
