### ISSUE TITLE
Autoselecting the record from the dataprovider in combobox, when the list contains only one item.

### ISSUE THREAD

**Issue by shivakumar2008** [vaadin/flow-components#2146]
Can we set the only record, when only one record is fetched from the filtering callback method of dataprovider, without raising an error in the combobox UI?
![image](https://user-images.githubusercontent.com/45589716/133280487-55ec63c2-b864-4c30-a508-dc4f892aa10c.png)

**Comment by vursen** [comment]
@shivakumar2008 An abstract code cannot be considered as a minimal reproducible example. 

Please, provide a minimal reproducible example and clear steps which could help us to reproduce your issue.

Check out [the issue template](https://github.com/vaadin/flow-components/issues/new?assignees=&labels=i%3A+needs+triage&template=bug_report.md&title=) for more details.

**Comment by yuriy-fix** [comment]
Closing as stale.
