### ISSUE TITLE
Enums for Lumo's text styles

### ISSUE THREAD

**Issue by anezthes** [vaadin/flow-components#2149]
If you want to apply `color: var(--lumo-secondary-text-color);` to a component, you either have to call `component.getStyle().set("color", "var(--lumo-secondary-text-color)");` or `component.addClassName("custom-style");` and then write some CSS for `custom-style`.

Preferably we'd offer the text styles in some kind of Enum, akin to this: `component.addClassName(Lumo.Typography.SECONDARY_TEXT);`.

**Comment by jouni** [comment]
This is naturally related to the CSS utility classes in Vaadin 21.

**Comment by yuriy-fix** [comment]
Closing in favour of https://github.com/vaadin/flow-components/issues/2410
