### ISSUE TITLE
Calling Notification.close() on a Dialog also closes the Dialog

### ISSUE THREAD

**Issue by FollowSteph** [vaadin/flow-components#2184]
### Description

In some cases I have a popup Dialog which has a small form that may required validation.  An example is if you want to select say a tenant from a combobox but it's a new one so you click on the "New" button just beside it and the software presents you with a popup Dialog with just a few holder fields to save. In this case you may want to validate that the name is present. Yes you can use a Binder but there may also be some logic that has to be done outside of the binder, such a multi-field validation. However because it's a validation it can be good to add a close button so that the user has the time to assess the issue.

However if you add a Close button to the Notification and then close that Notification it will also close the Dialog which is NOT what is desired because the user can then not correct the validations and has to restart from scratch.

The following code reproduces the issue consistently:

```
Notification notification = new Notification();
notification.add(new Button("Close validation message", event -> notification.close()));
notification.setPosition(Notification.Position.MIDDLE);

Dialog dialog = new Dialog();
dialog.add(new Button("Validate Form in Dialog", click -> notification.open()));
dialog.open();

```

Notice that the notification.close() also closes the Dialog rather than just the Notification.

### Expected outcome

See above

### Actual outcome

See above.

### Minimal reproducible example

See code above to reproduce issue. 

### Steps to reproduce

See above.

### Environment

Vaadin versions 14 to 21.

### Browsers Affected

- [x ] Chrome
- [ x] Firefox
- [ x] Safari
- [ x] Edge
- [ x] IE 11
- [ x] iOS Safari
- [ x] Android Chrome

**Comment by sissbruecker** [comment]
See also: https://github.com/vaadin/web-components/issues/844

Workaround: Modeless / non-modal dialogs can be used to prevent the dialog from closing.

**Comment by FollowSteph** [comment]
Actually I'm still able to replicate this issue in the current version of Vaadin...
