### ISSUE TITLE
Dropdown selection is not cleared when removing value set using `setValue()`

### ISSUE THREAD

**Issue by paodb** [vaadin/flow-components#2222]
### Description

When setting a value to a ComboBox using method ```setValue()``` I observe the following behavior when trying to clear the value by using the clear button:
- If I clear the value via the clear button and then open the dropdown, it does not show the selected value anymore which is okay.
- But if before I click the clear button I open the dropdown (I see the selected value in the dropdown and in the input field) and then I close it again and I go and click the clear button,  I see the value cleared from the input field (so there's no selected value anymore) but if I open the dropdown again, the value is still shown as selected there. (See attachment below).

### Expected outcome

Clicking clear button after setting a value through ```setValue``` method should clear input value and selection value in dropdown.

### Actual outcome

Clicking clear button after setting a value through ```setValue``` method does not clear the selected value in dropdown.

### Live Demo
![combobox-clear-issue](https://user-images.githubusercontent.com/30666649/137350345-cc689095-0f61-4dd9-9035-f6c34e070264.gif)

### Minimal reproducible example
```
List<String> items = new ArrayList<>(Arrays.asList("Anna", "Thomas", "Annabella", "John", "Tom", 
"William", "Henry", "Johnatan", "Anthony", "Anne"));            
ComboBox comboBox = new ComboBox<>("Select", items);
comboBox.setClearButtonVisible(true);

comboBox.addValueChangeListener(e -> {
  if(e.getValue() != null) {
    message.setText("New selected value: " + e.getValue());
  } else {
    message.setText("No value selected");
  }        
});

comboBox.setValue("Tom");
```
### Steps to reproduce

1. Add a ComboBox component to a page.
2. Add a list of items to the ComboBox.
3. Set clear button visible for the component.
4. Use ```setValue()``` method to set a value from the list of items.
5. After loading, open the dropdown and see the value selected.
6. Close the dropdown.
7. Click clear button to clear the selected value.
8. Open dropdown again. Value is still shown as selected.

### Environment

Vaadin platform 14.7.1.

### Browsers Affected
Tested on Chrome.

**Comment by web-padawan** [comment]
Confirmed with the latest version of ComboBox (v23 alpha) - the dropdown checkmark isn't removed:

![clear](https://user-images.githubusercontent.com/10589913/149785267-b7b483d5-8098-4a68-8e08-283183d632eb.gif)

The issue seems to happen when using `filteredIems` which we do in Flow component. I will investigate.
