### ISSUE TITLE
GridPro: column widths and alignment breaking with new items added

### ISSUE THREAD

**Issue by drewharvey** [vaadin/flow-components#2288]
### Description

In some cases when new items are added to the grid, the new rows have incorrect column widths and are not aligned to previous rows.  It may also be true that some of the columns don't get inserted in at all.  Seems to have a higher chance of occurring when rapidly adding new items to the grid.  Personally was not able to repro this locally, but the customer was able to repro it several times live.  They were only able to repro it in Firefox (latest v93.0).  

**See the following video example and attached document for reproduction steps and multiple examples of the issue.**

GridPro
Firefox 93.0
Vaadin Flow 22.0.0.alpha8

### Document with repro steps and examples

[Column_alignment_issues_2021_10_28.docx](https://github.com/vaadin/flow-components/files/7436774/Column_alignment_issues_2021_10_28.docx)

### Live Demo (optional)

https://user-images.githubusercontent.com/2496955/139319784-4979db48-6922-4b23-8dd8-cc43b4325519.mp4

**Comment by yuriy-fix** [comment]
Dear @drewharvey, could you please provide a code snippet to reproduce the issue?
