### ISSUE TITLE
Add attribute generator API for Grid rows / cells

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/flow-components#2290]
### Describe your motivation

Grid's rows are difficult to directly access from Java code. There's already a `setClassNameGenerator` for Grid and in Grid.Column to help with setting a CSS class name (`class` attribute value) for the row or the cell. Sometimes, you might want to set the value to another attribute of the row or cell, too, such as `title`. There should be a similar API such as `setAttributeGenerator(attributeName, callback)` for setting the value of an arbitrary attribute.

### Describe the solution you'd like

Pseudocode example 1 - adding an attribute to the row element (or all td elements of the row):
```
Grid<Person> grid = new Grid<>(Person.class);
// add a "title" attribute with the value of each person's "description" on each row
grid.setAttributeGenerator("title", person -> person.getDescription()); 
```
Pseudocode example 2 - adding an attribute to a specific column:
```
Grid<Person> grid = new Grid<>();
grid.addColumn(Person::getFullName()).setAttributeGenerator("title", person -> person.getJobTitle());
```

### Additional context

Not intended as a full implementation of a "tooltip" API, but a building block

**Comment by rolfsmeds** [comment]
Now that we have tooltip support for Grid in V23.3, are there any other use cases that would be served by this?

**Comment by yuriy-fix** [comment]
Closing as stale. Feel free to re-open in case there are extra cases.
