### ISSUE TITLE
Dragged Disabled/ReadOnly TextArea freezes Firefox tab

### ISSUE THREAD

**Issue by MBablinski** [vaadin/flow-components#2296]
### Description of the bug / feature
I`m creating read only or disabled text area in my Vaadin 14 application, without drag and drop and when i'm clicking on it and try to move my mouse as if i was trying to drag it, then my firefox tab is freezing. I cant click anything in my application and i cant even change address in the address bar to another website like google for example. In another tabs everything is working fine until i do it again. I don't have this bug in chrome it occurs only in Firefox.

### Minimal reproducible example
```
    TextAreatextArea = new TextArea("something");
    textArea.setEnabled(false);
    add(textArea);
```
### Expected behavior
My application tab shouldn't stop to react to every action even loading new website from address bar.

### Actual behavior
My tab in browser stops responding to any action. Can't click anything, there is no style change when mouse hover any component. I can't even change to any website from my application in this browser tab.
 
### Versions:
Vaadin: 14.4.0
Java: 8
OS: Ubuntu 20.04.3 LTS
Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0

**Comment by sissbruecker** [comment]
Was able to reproduce this with the [latest docs](https://vaadin.com/docs/latest/ds/components/text-area) (using v22-beta1) as well. Both with the Typescript and Java examples.

**Comment by tomivirkki** [comment]
This seems to be caused by some regression in Firefox. Isolated the issue into the following minimal example:

https://jsbin.com/rufelafeve/edit?html,output

**Comment by DiegoCardoso** [comment]
Oh, I tried to test with `textarea` on a web component, but wasn't able to come up with a reproducible example. I searched a bit on [Bugzilla](https://bugzilla.mozilla.org/), but couldn't find any reported issue there.

**Comment by tomivirkki** [comment]
Reported here https://bugzilla.mozilla.org/show_bug.cgi?id=1739079

We'll try to find a workaround
