### ISSUE TITLE
Implement Grid.Column.setDescriptionGenerator()

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow-components#2315]
### Describe your motivation

Would help migration from Vaadin 8.

**Comment by TatuLund** [comment]
Related to https://github.com/vaadin/flow-components/issues/2290

**Comment by TatuLund** [comment]
Related to https://github.com/vaadin/web-components/issues/2528

**Comment by alvarezguille** [comment]
Closed as duplicate of vaadin/web-components#2528

**Comment by mvysny** [comment]
Why was this closed as a duplicate of web-components? The web-components ticket is meant to implement stuff in pure JavaScript side, while this repo is meant to have a Java bindings for the JavaScript functionality.
