### ISSUE TITLE
Error when sorting empty grid (Cannot read properties of undefined)

### ISSUE THREAD

**Issue by arenk** [vaadin/flow-components#2321]
### Description

When sorting an empty grid (either via grid.sort() or by clicking the sort arrows in the UI), the console throws an error:

```
There seems to be an error in Vaadin Grid:
Cannot read properties of undefined (reading 'index')
```

### Expected outcome

Nothing, just an updated sort indicator without any errors.

### Actual outcome

Error is thrown. More specifically, I think the error is thrown in line 327 in gridConnector.js ([referenced version](https://github.com/vaadin/flow-components/blob/418a33f519169750e2585e6450d45c87b99d9bd5/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js)), since visibleRows is empty in this case and there is no index 0. 
`let start = visibleRows[0].index;`

This line has recently been changed from `let start = grid._virtualStart;` in [PR #978](https://github.com/vaadin/flow-components/pull/978)

However, I'm not sure if this point should not even be reached in such a case.

### Steps to reproduce

Just use any grid with at least one sortable column, do not load any data (or use an empty data provider) and click the sort arrow in the UI (or sort via API).

### Environment
- v22.0.0.beta1
- OSX 12.0.1

### Browsers Affected
- Chrome
- Firefox
- Safari

**Comment by alvarezguille** [comment]
Alternative POV as an enhancement sorting controls could be disabled when grid is empty

**Comment by arenk** [comment]
Just an additional comment: It's not just the sorting controls in the UI. In our case, we initialize many grids with a default sorting, e.g.

```
grid = new Grid<>();

var col1 = grid.addColumn(...);

//Default sorting behavior
grid.sort(Collections.singletonList(new GridSortOrder<>(col1, SortDirection.ASCENDING)));
```

In case the data provider does not contain any data (could also happen due to filters), we get the same error as described above with v22.0.0.beta1 without any user action / input.

**Comment by arenk** [comment]
FYI: I locally added the following lines before line 327 in [gridConnector.js](https://github.com/vaadin/flow-components/blob/418a33f519169750e2585e6450d45c87b99d9bd5/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js) and everything is working fine now.

```
if(visibleRows.length == 0){
  fetch(0, grid.pageSize);
  return;
}
```
