### ISSUE TITLE
v14.7.4 : @PreserveOnRefresh + HasUrlParameter = $0.$connector is undefined

### ISSUE THREAD

**Issue by sebdavid** [vaadin/flow-components#2322]
### Description

A JS error is displayed : `$0.$connector is undefined`.
It occurs when the page is refreshed, while HasUrlParameter#setParameter is called and setting data in the grid.

A similar error has been created 2y ago, but the workaround with `grid.getDataProvider().refreshAll()` does not work.
https://vaadin.com/forum/thread/17527564/typeerror-cannot-read-property-dodeselector-of-undefined-vaadin-10

### Expected outcome

No JS error...

### Actual outcome

The JS error is displayed

### Minimal reproducible example

From Vaadin starter 14.7.4 :

* add @PreserveOnRefresh on MainLayout
* create the following class :

```java
package com.example.application.views;

import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.router.BeforeEvent;
import com.vaadin.flow.router.HasUrlParameter;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;

@PageTitle("Grid")
@Route(value = "grid", layout = MainLayout.class)
public class GridView extends HorizontalLayout implements HasUrlParameter<String> {

	private Grid<String> grid;

	public GridView() {
		setMargin(true);

		grid = new Grid<>();
		grid.addColumn(s->s);
		grid.setSelectionMode(Grid.SelectionMode.SINGLE);

		add(grid);
	}

	@Override
	public void setParameter(BeforeEvent e, String s) {


		grid.setItems("apple", "banana", "pear");
		grid.select(s);
	}
}
```

* In HelloWorldView, add the following at the end of the constructor :
```java
        add(
                new Button("select pear", e->e.getSource().getUI().ifPresent(u->u.navigate("grid/pear"))),
                new Button("select banana", e->e.getSource().getUI().ifPresent(u->u.navigate("grid/banana")))
        );
```

### Steps to reproduce

1. launch the application, 
2. click "select pear" button in the HelloWorld view, you will be redirected to the new view.
3. Hit F5 to reload the page. The following JS error occurs : `$0.$connector is undefined`

### Environment

- Windows
- FireFox 94.0.1
- Vaadin 14.7.4

### Browsers Affected

- [ x] Chrome
- [ x] Firefox

**Comment by TatuLund** [comment]
This is not a bug. The setParameter method is executed before view or Grid is attached. This is architectural decision for security purposes. Thus you should just process the value and store it e.g. class field. The after navigation event is executed later when the view is already attached, thus you can populate the Grid there and select the item.

```
@PageTitle("Grid")
@Route(value = "grid", layout = MainLayout.class)
public class GridView extends HorizontalLayout implements HasUrlParameter<String>, AfterNavigationObserver {

	private Grid<String> grid;
        private String value;
        
	public GridView() {
		setMargin(true);

		grid = new Grid<>();
		grid.addColumn(s->s);
		grid.setSelectionMode(Grid.SelectionMode.SINGLE);

		add(grid);
	}

	@Override
	public void setParameter(BeforeEvent e, String s) {
              value = s;
	}


       @Override
        public void afterNavigation(AfterNavigationEvent event) {
                grid.setItems("apple", "banana", "pear");
		grid.select(value);
	}
}
```

**Comment by sebdavid** [comment]
Thanks a lot for your answer.

As a suggestion, the javadoc of the setParameter method could be enhanced by telling something like "be careful, the components are not attached when this method is called, you should perform modifications on them in the afterNavigation method".

**Comment by mvysny** [comment]
@TatuLund Can you please explain why Grid can not be populated in the `setParameter()` function, or how does it relate to the `$0.$connector is undefined` error?
