### ISSUE TITLE
add setRenderer method for Grid Columns

### ISSUE THREAD

**Issue by BenWilsonI** [vaadin/flow-components#2329]
### Describe your motivation

feature completeness, flexibility to set after construction

### Describe the solution you'd like

setRenderer method

we have a 

getRenderer
getFooterRenderer
getHeaderRenderer
setFooterRenderer
setHeaderRenderer....

What is missing? => setRenderer

### Additional context

Would help Swing migrations also

**Comment by TatuLund** [comment]
Related: https://github.com/vaadin/flow-components/issues/1494

**Comment by yuriy-fix** [comment]
Closing in favour of #1494
