### ISSUE TITLE
Provide proper and unified theme api for all components, when supported from their client side [2 days]

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow-components#2343]
Currently some Flow components seem to support theming, but do not provide proper ThemeVariants, for instance DatePicker or DateTimePicker. On top of that, some seem to not even implement `HasTheme` (e.g. DatePicker).

This make them feel incomplete.

Request is, that all flow components, which have the ability to be themed should implement `HasTheme` and also provide ThemeVariant constants as for instance TextField does (`addThemeVariants(TextFieldVariant... variants)`).

**Comment by yuriy-fix** [comment]
We need to have a list of all of the components that are missing theme variants or have misaligned theme API. Could be done as a part of the investigation on this ticket.

**Comment by sissbruecker** [comment]
We might also want to introduce a common interface for the enums and for the `addThemeVariants(ComponentVariant... variants)` and `removeThemeVariants(ComponentVariant... variants)` methods that are currently implemented individually for each component. Looks like we could introduce an interface for all theme variant enums like:
```java
public interface ComponentVariant {
    String getVariantName();
}
```
and then make specific theme variant enums implement it:
```java
public enum MapVariant implements ComponentVariant {
    private final String variant;
    ...
    public String getVariantName() {
        return variant;
    }
}
```
Then we could add an interface to the component such as this:
```java
public interface HasComponentVariant<T extends ComponentVariant> extends HasTheme {
    default void addThemeVariants(T... variants) {
        getThemeNames().addAll(
                Stream.of(variants).map(T::getVariantName)
                        .collect(Collectors.toList()));
    }

    default void removeThemeVariants(T... variants) {
        getThemeNames().removeAll(
                Stream.of(variants).map(T::getVariantName)
                        .collect(Collectors.toList()));
    }
}
```
and use it like so:
```java
public class Map extends Component implements HasComponentVariant<MapVariant> {
...
```

**Comment by web-padawan** [comment]
Related: #1155

**Comment by web-padawan** [comment]
Related: #1273

**Comment by knoobie** [comment]
Some could argue a `vaadin-flow-components-common`could help here ;)

**Comment by web-padawan** [comment]
## Components missing `HasTheme`

- [ ] Charts (`monotone`, `gradient`, `classic` variants)
- [ ] CustomField - #1074
- [ ] GridPro - (`highlight-editable-cells`, `highlight-read-only-cells` variants)
- [ ] Select - #1273

## Components with Variant enums

The following components have `Variant` enums that could be updated as suggested above.

- `AvatarGroup`
- `Avatar`
- `Button`
- `CheckboxGroup`
- `ComboBox`
- `Crud`
- `DatePicker`
- `Details`
- `Dialog`
- `Grid`
- `Map`
- `MenuBar`
- `Notification`
- `ProgressBar`
- `RadioGroup`
- `RichTextEditor`
- `SplitLayout`
- `Tabs`
- `Tab`
- `TextArea`
- `TextField`

**Comment by web-padawan** [comment]
This has been covered for most of the remaining components - see PRs linked to this issue.
Submitted #2948 for the idea about common interface. Closing this issue.
