### ISSUE TITLE
FormLayout+HorizontalLayout=Misaligned Label

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow-components#2351]
### Description

Placing a HorizontalLayout into a FormLayout by using FormItem while
using `ResponsiveStep.LabelsPosition.ASIDE` will cause the label to be misaligned.

### Expected outcome

The label should be aligned.

### Actual outcome

The label is misaligned

![Screenshot from 2021-11-17 10-26-40](https://user-images.githubusercontent.com/254091/142163625-20829a29-8556-4b0b-b17b-c2ec1fa0cc2a.png)

### Minimal reproducible example

```java
package org.vaadin.example;

import com.vaadin.flow.component.formlayout.FormLayout;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.router.Route;

@Route("")
public class MainView extends VerticalLayout {

    public MainView() {
        FormLayout fl = new FormLayout();
        fl.setResponsiveSteps(new FormLayout.ResponsiveStep("0", 1, FormLayout.ResponsiveStep.LabelsPosition.ASIDE));
        fl.addFormItem(new HorizontalLayout(new TextField()), "foo");
        add(fl);
    }
}
```

Paste this into the skeleton-starter-flow project.

### Environment

- Version of the component / Vaadin platform: 21.0.6
- OS: Linux Ubuntu 21.10 x86-64

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by mvysny** [comment]
FormItem uses CSS Flexbox internally and aligns the components by their baseline. One workaround is to set the alignment to `center` instead:

```java
fl.addFormItem(new HorizontalLayout(new TextField()), "foo").getStyle().set("align-items", "center");
```

**Comment by rolfsmeds** [comment]
Unable to reproduce this in FF on Mac with 22.0.0. Could you try with 22.0 and see if the problem still occurs?

**Comment by mvysny** [comment]
I'll try, I'm ATM blocked by https://github.com/vaadin/skeleton-starter-flow/issues/519

**Comment by yuriy-fix** [comment]
Closing as stale. Feel free to re-open if still valid.
