### ISSUE TITLE
Row height does not adjust after setting new data in Grid when using AppLayout

### ISSUE THREAD

**Issue by TatuLund** [vaadin/flow-components#2363]
Grid row height does not adjust after setting new data, see picture

![image](https://user-images.githubusercontent.com/14309836/142609147-1f5d115f-4696-4f96-be4a-43b1626a2488.png)

Vaadin 21.0.x

Use the following app to replicate, click the button to set new data provider with new items

Use this sequence to replicate
- Click add button
- Scroll to bottom
- Click add button again

[grid-row-height-demo.zip](https://github.com/vaadin/flow-components/files/7569660/grid-row-height-demo.zip)

The workaround is to do delayed call to `grid.getElement().executeJs("this.__virtualizer.flush()");`

**Comment by yuriy-fix** [comment]
Before taking a look at the provided app, are you using `heightByRows`?

**Comment by tomivirkki** [comment]
Can't reproduce. Started up the attached application and it works as expected:

https://user-images.githubusercontent.com/1222264/152953857-1f346f38-5c3e-4b21-a75a-e281a002e5d2.mp4

**Comment by TatuLund** [comment]
> Can't reproduce. Started up the attached application and it works as expected:

My apologies, forgot to describe the exact replication sequence
