### ISSUE TITLE
GridPro: Frozen editor cell is transparent on hover (can see overlapping cell)

### ISSUE THREAD

**Issue by drewharvey** [vaadin/flow-components#2365]
### Description

Chrome latest
Vaadin 22 beta 3

If the last frozen column is a GridPro editor column, the cell becomes transparent when the mouse is hovered over.  You can actualy see the other cells behind it (if you scroll the non-frozen cells horizontally).  See the gif below.

### Live Demo (optional)

![gridpro-frozen-cell-passthru](https://user-images.githubusercontent.com/2496955/142690022-85bad9e5-e5e6-4d8a-a23a-3d51c615a4ef.gif)

### Minimal reproducible example

```
GridPro<String> grid = new GridPro<>();
grid.setWidth("500px");
grid.setHeight("200px");

ComboBox<String> editor = new ComboBox<>();
editor.setItems("John", "Terry", "Brandon", "Kevin");

// add some frozen editor columsn
grid.addEditColumn(item -> item)
        .custom(new TextField(), (v, t) -> {})
        .setHeader("Name")
        .setFrozen(true);

grid.addEditColumn(item -> item)
        .custom(new TextField(), (v, t) -> {})
        .setHeader("Name")
        .setFrozen(true);

grid.addEditColumn(item -> item)
        .custom(new TextField(), (v, t) -> {})
        .setHeader("Name")
        .setFrozen(true);

// add non frozen columns (enough to be able to scroll horizontally)
grid.addColumn(item -> item)
        .setHeader("DOB");

grid.addColumn(item -> item)
        .setHeader("DOB");

grid.addColumn(item -> item)
        .setHeader("DOB");

grid.setItems(Arrays.asList("Kevin", "John", "Ted"));

add(grid);
```

**Comment by tomivirkki** [comment]
Workaround:

theme-for: "vaadin-grid-pro"
```css
[part~='editable-cell']:hover,
[part~='editable-cell']:focus {
  background-clip: initial;
  background-color: var(--lumo-base-color);

  box-shadow: inset 0 100vh var(--lumo-contrast-5pct);
}
```

The issue is caused due to the [partly transparent background colors](https://github.com/vaadin/web-components/blob/03dc8b8999669c7853f507745396f3b50308f1e8/packages/grid-pro/theme/lumo/vaadin-grid-pro-styles.js#L24-L40) used for indicating editable cells.
Not sure if the above qualifies for a fix. @jouni ?

**Comment by jouni** [comment]
Ah, huge oversight on my part there, thanks for pointing it out.

I’d perhaps do the same as we do in other components: `background: var(--lumo-base-color) linear-gradient(var(--lumo-contrast-5pct), var(--lumo-contrast-5pct));`
