### ISSUE TITLE
TreeGrid: refreshAll() creates empty handles with items that changed their hashCode although getId is overridden

### ISSUE THREAD

**Issue by werwolfberlin** [vaadin/flow-components#2383]
When calling refreshAll() on a dataprovider which has items that changed their hashCode (and equals) the TreeGrid shows only expand/collapse handles, but nothing bleow although getId(Item) is overwritten. 

![image](https://user-images.githubusercontent.com/19834316/143589911-3321ab19-0437-4fdd-834e-883b85921d82.png)

See the minimal example file and add it as a view do a V14-V22 application.
We suspect that something is caching the hierarchy based on the beans hashCode/equals instead of getId(item).
I added some breakpoints in hasChildren(), getChildCount(...) and fetchChildren(...). only hasChildren() was hit because it was used to determin wether to show the expand/collapse handle or not.

Last position where we lost the trace in debugging because of lambdas was in TreeGrid.java:

`
        @Override
        public TreeGridUpdateQueue startUpdate(int sizeChange) {
            return (TreeGridUpdateQueue) updateQueueFactory.apply(data,  sizeChange);
        }
`

Code example:
`
package com.example.application.views.helloworld;

import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.notification.Notification;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.component.treegrid.TreeGrid;
import com.vaadin.flow.data.provider.InMemoryDataProvider;
import com.vaadin.flow.data.provider.hierarchy.AbstractHierarchicalDataProvider;
import com.vaadin.flow.data.provider.hierarchy.HierarchicalQuery;
import com.vaadin.flow.function.SerializableComparator;
import com.vaadin.flow.function.SerializablePredicate;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.router.PageTitle;
import com.example.application.views.MainLayout;
import com.vaadin.flow.router.RouteAlias;

import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.Collectors;
import java.util.stream.Stream;

@PageTitle("TreeGridIssue")
@Route(value = "tree-grid-issue", layout = MainLayout.class)
@RouteAlias(value = "", layout = MainLayout.class)
public class TreeGridIssue extends VerticalLayout {

    public TreeGridIssue() {

        MyDataProvider dataProvider = new MyDataProvider();
        dataProvider.generateData();
        TreeGrid<MyTreeItem> treeGrid = new TreeGrid<>();
        treeGrid.addHierarchyColumn(MyTreeItem::getName).setHeader("Name");
        treeGrid.setDataProvider(dataProvider);
        treeGrid.expandRecursively(dataProvider.getRootElements(), 10);

        add(new Button("Shuffle", e -> {
            System.out.println("refresh");
            dataProvider.updateData();
            dataProvider.refreshAll();
            treeGrid.getElement().executeJs("this.__virtualizer.update()");
        }), treeGrid);
    }

    public static class MyDataProvider
            extends AbstractHierarchicalDataProvider<MyTreeItem, SerializablePredicate<MyTreeItem>>
            implements InMemoryDataProvider<MyTreeItem>{

        List<String> names = Arrays.asList(
                "Hugo", "Jens", "Carol", "Matthieu", "Frederic", "Jonas", "Jennifer", "Tony", "Lisa", "Bart", "James");

        private List<MyTreeItem> items;
        Map<MyTreeItem, List<MyTreeItem>> data = new LinkedHashMap<>();

        public void generateData(){
            AtomicInteger looper = new AtomicInteger(0);
            items = names.stream().map(s -> new MyTreeItem(String.valueOf(looper.getAndIncrement()), s)).collect(Collectors.toList());

            data.put(null, Arrays.asList(items.get(0), items.get(7)));
            data.put(items.get(0), Arrays.asList(items.get(1), items.get(2)));
            data.put(items.get(1), Arrays.asList(items.get(3), items.get(4)));
            data.put(items.get(4), Arrays.asList(items.get(5), items.get(6)));
            data.put(items.get(7), Arrays.asList(items.get(8), items.get(9)));
            data.put(items.get(9), Arrays.asList(items.get(10)));
        }

        public void updateData(){
            AtomicInteger looper = new AtomicInteger(0);
            List<String> shuffledNames = new ArrayList<>(names);
            Collections.shuffle(shuffledNames);
            items.forEach(i -> i.setName(shuffledNames.get(looper.getAndIncrement())));

            data.clear();
            data.put(null, Arrays.asList(items.get(0), items.get(7)));
            data.put(items.get(0), Arrays.asList(items.get(1), items.get(2)));
            data.put(items.get(1), Arrays.asList(items.get(3), items.get(4)));
            data.put(items.get(4), Arrays.asList(items.get(5), items.get(6)));
            data.put(items.get(7), Arrays.asList(items.get(8), items.get(9)));
            data.put(items.get(9), Arrays.asList(items.get(10)));
        }

        @Override
        public Object getId(MyTreeItem item) {
            return item.getId();
        }

        @Override public SerializablePredicate<MyTreeItem> getFilter() {return null;}
        @Override public void setFilter(SerializablePredicate<MyTreeItem> serializablePredicate) {}

        @Override
        public SerializableComparator<MyTreeItem> getSortComparator() {
            return (o1, o2) -> o1.compareTo(o2);
        }

        @Override public void setSortComparator(SerializableComparator<MyTreeItem> serializableComparator) {}

        @Override
        public int getChildCount(HierarchicalQuery<MyTreeItem, SerializablePredicate<MyTreeItem>> hierarchicalQuery) {
            int size = data.getOrDefault(hierarchicalQuery.getParent(), Collections.emptyList()).size();
            System.out.println("Method fetchChildCount: Parent: " + hierarchicalQuery.getParent() + " child count: " + size);
            return size;
        }

        @Override
        public Stream<MyTreeItem> fetchChildren(HierarchicalQuery<MyTreeItem, SerializablePredicate<MyTreeItem>> hierarchicalQuery) {
            List<MyTreeItem> children = data.getOrDefault(hierarchicalQuery.getParent(), Collections.emptyList());
            System.out.println("Method fetchChildren: Parent: " + hierarchicalQuery.getParent() + " has Children: " + children);
            return children.stream();
        }

        public Collection<MyTreeItem> getRootElements(){
            return data.getOrDefault(null, Collections.emptyList());
        }

        @Override
        public boolean hasChildren(MyTreeItem myTreeItem) {
            boolean hasChildren = !data.getOrDefault(myTreeItem, Collections.emptyList()).isEmpty();
            System.out.println("Method hasChildren: " + myTreeItem + " hasChildren: " + hasChildren);
            return hasChildren;
        }
    }

    public static class MyTreeItem implements Comparable<MyTreeItem> {
        private String id;
        private String name;

        public MyTreeItem(String id, String name) {
            this.id = id;
            this.name = name;
        }

        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        @Override
        public int compareTo(MyTreeItem o) {
            return o == null ? 1 : id.compareTo(o.id);
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            MyTreeItem that = (MyTreeItem) o;
            return Objects.equals(id, that.id) && Objects.equals(name, that.name);
        }

        @Override
        public int hashCode() {
            return Objects.hash(id, name);
        }

        @Override
        public String toString() {
            return "MyTreeItem{" +
                    "id='" + id + '\'' +
                    ", name='" + name + '\'' +
                    '}';
        }
    }
}`

**Comment by TatuLund** [comment]
TreeGrid sets a default 'unique key provider'

`item -> String.valueOf(item.hashCode());`

The workaround is to override `get/setUniqueKeyProvider` inherited from the `Grid`, so that id property is used as a key in `TreeGrid`.

It is a borderline case whether it is a bug in code or bug in documentation. Nevertheless it is bad DX. It would be more convenient in any case that one just overrides the `getId `of the `DataProvider `and `TreeGrid `will use that for key provider. 

The workaround method of overriding the setting is not well documented. Simple solution would be making setter API public. 

More complex solution would be to modify `TreeGrid `to use `getId `of the data provider instead of `item -> String.valueOf(item.hashCode());`, so that you do not have that many API's you need to know to use in this kind of case (although not that common, or especially because it is not common). Minimum solution would be to document this workaround well.

**Comment by TatuLund** [comment]
Another note, the usage of item.hashCode() is prone to hash collision, although rare, still possible in special cases. See related issue

https://github.com/vaadin/flow-components/issues/1270
