### ISSUE TITLE
Firefox 94.0.2: submenus in MenuBar component not displayed correctly

### ISSUE THREAD

**Issue by igormilina** [vaadin/flow-components#2399]
### Description

MenuBar component is not displayed correctly in new Firefox 94.0.2. When opening submenus, the submenu sometimes become transparent, sometimes selected item (below the mouse) is not colored. Submenus also flicker when moving the mouse over the menu with submenus.

This is easily reproduced in any menu with submenus on page:
https://vaadin.com/docs/v14/ds/components/menu-bar

Worked fine in Firefox Firefox 93.0.0 and below

### Expected outcome

Them submenus should be displayed correctly.

### Actual outcome

Them submenus are not displayed correctly (especially when menu is set to open on hover ). They are sometimes transparent, sometimes selected item (below the mouse) is not colored. Submenus also flicker when moving the mouse over the menu with submenus.

### Live Demo (optional)

https://vaadin.com/docs/v14/ds/components/menu-bar

### Steps to reproduce

Just moving the mouse around, over the menu and submenus.

### Environment

- v14.4.0 and v14.7.7 (not tested with other versions)
- OS: Windows 10

### Browsers Affected

- [ ] Chrome
- [x] Firefox 94.0.2
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by yuriy-fix** [comment]
Dear @igormilina ,
I wasn't able to reproduce the issue on latest Firefox.
Are you using some extensions?
![menu-bar-ff](https://user-images.githubusercontent.com/29372419/145578764-16079f2c-4600-4897-a1dd-4ec3fa19874f.gif)

**Comment by igormilina** [comment]
You are right. I was able to reproduce this issue only on several specific developer laptops (same brand, OS and software installed). The firefox on those machines don't have any plugins. But these machines also have some other issues (other than displaying vaadin menu bar), so I would conclude that this is some other (unfortunately unknown) software issue.

I will close this issue, as it is probably not related to vaadin.
