### ISSUE TITLE
Grid: Enable multi-selection by dragging

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow-components#2422]
### Describe your motivation

Vaadin 8 allowed a multi-selection of rows by "dragging" the mouse cursor, see the attached video for details.

https://user-images.githubusercontent.com/254091/145785369-6bb9e0a3-36fb-412a-9480-42d0982d74cc.mp4

You can see that for yourself, by navigating to https://demo.vaadin.com/sampler/#ui/grids-and-trees/grid/features and setting the Selection Mode to MULTI. The same behavior doesn't work with Vaadin 22 Grid, as can be seen at https://vaadin.com/docs/latest/ds/components/grid

### Describe the solution you'd like

Enhancing the selection via dragging over the selection column should work out-of-the-box.

### Describe alternatives you've considered

https://vaadin.com/directory/component/selection-grid but it uses Shift/Ctrl instead of dragging, so it's not really a replacement.

**Comment by web-padawan** [comment]
Depends on [#2040](https://github.com/vaadin/web-components/issues/2040)

**Comment by yuriy-fix** [comment]
For extra details please check https://github.com/vaadin/web-components/issues/2040.

**Comment by tomivirkki** [comment]
Prototype in [this branch](https://github.com/vaadin/web-components/tree/proto/lasso-selection)
