### ISSUE TITLE
flow chart: gauges cause web console error 404: /VAADIN/exporter/highcharts.js 

### ISSUE THREAD

**Issue by MingjieZhu** [vaadin/flow-components#2445]
### Description

Vaadin 21.0.9. Java 8. Tomcat 8.5
adding a gauges cause web console error 404: /VAADIN/exporter/highcharts.js 
Only gauges has the issue. other charts does not cause the issue.

### Expected outcome

No error

### Actual outcome

Press F12 and see the error. Sometimes it also pop the error on upper right corner
![image](https://user-images.githubusercontent.com/24685289/146841597-6ce13e39-6389-4071-b623-ae87b8a4789e.png)

### Browsers Affected

- [ x] Chrome
- [ x] Firefox
- [ x] Edge

**Comment by sissbruecker** [comment]
@MingjieZhu Can you please add more detail? It's not clear whether you are trying to add a Flow Gauge chart to a page, or whether you are using the chart exporter.

In any case, please attach a code snippet, or a project, that reproduces the issue.

**Comment by sissbruecker** [comment]
Tested both scenarios with a starter template from start.vaadin.com using v22.02. Adding a Flow gauge chart to a page works, as does creating an SVG with the exporter. Though looking at the error it's probably not related to the charts exporter, the code for that is never loaded into the application page. I can not see where the `VAADIN/exporter/highcharts.js` URL would even come from, and can not find any reference to a similar URL. Ideally we would have a complete project setup to understand what's going on.

**Comment by MingjieZhu** [comment]
Ah, it's not from the source code. That was from an integration solution we had.  The reference was put into vaadin-6-92d...091e45.cache.js  which made me assuming it from Vaadin source code.
