### ISSUE TITLE
TextField's focus ring is clipped when placed in a scrollable container

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow-components#2456]
### Description

When a TextField is placed in a scrollable div, the focus ring is clipped. Please see screenshot for more details.

![focus-ring-clipping-bug](https://user-images.githubusercontent.com/254091/147068348-06c34826-fcb8-4b84-851a-d49e54638815.png)

The problem is that the TextField's focus ring extrudes from the TextField component itself, which is then clipped by parent Div having `overflow-x` of `auto`.

Setting `overflow-x` to `visible` doesn't help unfortunately, since `overflow-y: auto` or `overflow-y: scroll` (which you need when you want to scroll) will cause `overflow-x` to compute to `auto` as per https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-x

Related issues: https://github.com/vaadin/web-components/issues/494 and https://github.com/vaadin/web-components/issues/785

I'm not sure whether the solution even exists (e.g. shrinking the focus ring within the bounds of TextField could simply look ugly), I'm merely opening the ticket in hopes to have a good discussion for workarounds or solutions.

One quick and dirty solution I found is for the scrollable div to have a negative margin, offset by a positive padding:

```css
margin-left: -5px;
padding-left: 5px;
margin-right: -5px;
padding-right: 5px;
```

That will move the 'clipping point' beyond the focus ring of the TextField.

### Expected outcome

The TextField's focus ring should not be clipped somehow. Alternatively, Vaadin could provide a scrollable Panel component which somehow takes care of this issue.

### Actual outcome

The TextField's focus ring is clipped.

### Minimal reproducible example

Paste this class into the Skeleton Starter Flow project:

```java
package org.vaadin.example;

import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.router.Route;

@Route("")
public class MainView extends VerticalLayout {

    public MainView() {
        final Div panel = new Div();
        panel.setWidthFull();
        panel.getStyle().set("overflow-y", "auto");
        final TextField filterField = new TextField();
        filterField.setWidthFull();
        panel.add(filterField);
        add(panel);
        panel.add(new Button("Press tab and shift+tab to reproduce the issue"));
        filterField.focus();
    }
}
```

### Steps to reproduce

1. Run the Skeleton Starter Flow app with the MainView code above.
2. The TextField should be focused, but the focus ring may not be drawn.
3. Press TAB followed by SHIFT+TAB to keyboard-focus the TextField. Now the focus ring should be drawn and should be clipped, thus reproducing this issue.

### Environment

- Vaadin: 21.0.9
- OS. Ubuntu Linux 21.10 x86-64, Firefox 95.0.1

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

Should affect all browsers, but I only tested with Chrome and Firefox.

**Comment by rolfsmeds** [comment]
I think the most obvious solution is to just add some whitespace (e.g. a layout with margin or padding) around the fields (or apply padding to the scroll container itself). Without that whitespace, the resulting UI is likely to look ugly in many situations anyway, e.g. when the scrollbar is set to be always visible, it would be flush with the right end of the field.

**Comment by stefanbrenner** [comment]
We have the same problem in our project. Adding some white space breaks our component alignment and is therefore no option. So we changed the box-shadow to inset:

    box-shadow: inset 0 0 0 2px var(--lumo-primary-color-50pct);

The only drawback of this method are primary buttons. There we used a double box-shadow:

    box-shadow: inset 0 0 0 2px var(--lumo-primary-color-50pct), inset 0 0 0 3px var(--lumo-base-color);

**Comment by rolfsmeds** [comment]
Closing this as the solution is, and always will be, to account for focus rings by adding a bit of whitespace between input fields and their containers in cases where the container is configured to clip its contents.
