### ISSUE TITLE
Grid FooterRow sets tabIndex of the cell to 0, messing up the tab order, even though it has no contents

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow-components#2459]
### Description

Similar to #977 but slightly different, therefore I'm filing a new bug. I have a Grid with a FooterRow. The FooterRow is mostly empty but some columns show a static text (think sum labels). The footer should not be keyboard-focusable at all, but it is; the `<td>` element contains `tabindex=0` attribute even though there is no focusable content there.

![bug](https://user-images.githubusercontent.com/254091/147223913-c20902bf-8ad6-4659-b60b-db962a345a07.png)

### Expected outcome

The footer should have tabindex=-1

### Actual outcome

One of the footer cells have tabindex=0

### Minimal reproducible example

Please paste the code below into the Skeleton Starter Flow:

```java
package org.vaadin.example;

import com.vaadin.flow.component.grid.FooterRow;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

@Route("")
public class MainView extends VerticalLayout {

    public MainView() {
        final Grid<String> grid = new Grid<>();
        grid.addColumn(it -> it).setHeader("col1");
        grid.addColumn(it -> it).setHeader("col2");
        final FooterRow footerRow = grid.appendFooterRow();
        add(grid);
    }
}
```

### Steps to reproduce

Clear steps describing how to reproduce the issue.

1. Run Skeleton Starter Flow with the code above.
2. Press TAB couple of times.
3. Observe that the footer cell is selected.

### Environment

- Vaadin 21.0.9
- Ubuntu Linux 21.10 x86-64

### Browsers Affected
- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by rolfsmeds** [comment]
This is by design – the footer row needs to be focusable in order for screen readers to access it, and having the header, body and footer in separate tab stops is according to Web Accessibility Initiative best practices.
