### ISSUE TITLE
TreeGrid.expandRecursivelly(..) does not fire ExpandEvent

### ISSUE THREAD

**Issue by TatuLund** [vaadin/flow-components#2461]
Vaadin 14.8.0

Use the following code to demonstrate the issue

Expected: See Grid and Label with text "Expanded"

Actual: Label is not shown

```
@Route("tree-grid-cols")
public class TreeGridColumns extends VerticalLayout {

    TreeGrid<String> grid;

    public TreeGridColumns() {
        grid = new TreeGrid<>();
        grid.setWidth("350px");
        grid.setMaxHeight("300px");

        grid.addComponentHierarchyColumn(value -> new Label(value))
                .setHeader("Name").setAutoWidth(true);
        grid.addComponentColumn(value -> new Label(new Date().toString()))
                .setHeader("Datum");
        grid.addComponentColumn(value -> new Label(new Date().toString()))
                .setHeader("Datum 2");

        grid.addExpandListener(event -> {
            Label label = new Label("Expanded");
            label.setId("expanded");
            add(label);
        });

        TreeData<String> treeData = new TreeData<>();
        treeData.addRootItems("A");
        treeData.addItems("A", Arrays.asList("A 1", "B 1"));
        treeData.addItems("A 1", Arrays.asList(
                "Child A which may has a long title", "Child B", "Child C"));
        treeData.addItems("B 1",
                Arrays.asList("Child D", "Child E which may has a long title",
                        "Child C which may has a long title"));
        grid.setTreeData(treeData);

        grid.expandRecursively(Collections.singleton("A"), 2);

        add(grid);
    }
 }
```

**Comment by TatuLund** [comment]
/**
     * Expands the given items and their children recursively until the given
     * depth.
     * <p>
     * {@code depth} describes the maximum distance between a given item and its
     * descendant, meaning that {@code expandRecursively(items, 0)} expands only
     * the given items while {@code expandRecursively(items, 2)} expands the
     * given items as well as their children and grandchildren.
     * <p>
     * **This method will <i>not</i> fire events for expanded nodes.**
     *
     */

JavaDoc says it is not even supposed to be fired. This is however quite counterintuitive as the normal expand method does fire the expand event. Thusly issue is still valid as "enhancement" and I did relabel this so.

Now, there is API design question, what ExpandEvent should offer as items when fired from expandRecursively?

expandRecursively gets only the first level items as parameter. I would propose fire the event with items = null, which would make possible to detect that this event was fired by expandRecursively. I will update my PR so and let you decide how to proceed with that.

**Comment by yuriy-fix** [comment]
The original issue (https://github.com/vaadin/web-components/issues/3292) is fixed, so this enhancement is not needed anymore.
It works as expected as method documentation explicitly specifies that it doesn't fire an event.
