### ISSUE TITLE
Can not expand TreeGrid immediately

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow-components#2463]
### Description

When `TreeGrid.expandRecursively()` is called, the items are expanded gradually rather than immediately. This creates visual artifacts - the user watches as the tree slowly expands itself, instead of being presented with an already expanded TreeGrid.

The tree expansion is vastly slowed down as more and more component renderers are used, since the browser performs layouting and style recalculation on all cells on every level expansion.

### Expected outcome

TreeGrid should offer an API which would expand the tree grid immediately.

### Actual outcome

The TreeGrid is expanded in stages.

### Minimal reproducible example

Paste the following MainView.java to the Skeleton Starter Flow:

```java
package org.vaadin.example;

import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.button.ButtonVariant;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.html.Span;
import com.vaadin.flow.component.icon.VaadinIcon;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.treegrid.TreeGrid;
import com.vaadin.flow.function.ValueProvider;
import com.vaadin.flow.router.Route;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

@Route("")
public class MainView extends VerticalLayout {

    public MainView() {
        final TreeGrid<String> grid = new TreeGrid<>();
        add(grid);
        grid.setSizeFull();
        setSizeFull();

        grid.addComponentColumn(it -> createButtons()).setHeader("col2");
        grid.addHierarchyColumn(it -> it).setHeader("col1");
        grid.addComponentColumn(it -> new Span(it)).setHeader("col3");
        grid.addComponentColumn(it -> new HorizontalLayout()).setHeader("col4");
        grid.addColumn(it -> it).setHeader("col5");
        grid.addColumn(it -> it).setHeader("col6");
        grid.addColumn(it -> it).setHeader("col7");
        grid.addColumn(it -> it).setHeader("col8");

        final List<String> root = Arrays.asList("1", "2", "3");
        grid.setItems(root, (ValueProvider<String, Collection<String>>) s -> {
            if (s.length() < 10) {
                return IntStream.range(0, 4).mapToObj(it -> s + "/" + it).collect(Collectors.toList());
            }
            return new ArrayList<>();
        });

        grid.expandRecursively(root, 25);
        grid.setSelectionMode(Grid.SelectionMode.MULTI);
    }

    private HorizontalLayout createButtons() {
        final Button b1 = new Button(VaadinIcon.SEARCH.create());
        b1.addThemeVariants(ButtonVariant.LUMO_TERTIARY);
        final Button b2 = new Button(VaadinIcon.FILE_TEXT.create());
        b2.addThemeVariants(ButtonVariant.LUMO_TERTIARY);
        return new HorizontalLayout(b1, b2);
    }
}
```

### Steps to reproduce

1. Paste the class above to the Skeleton Starter Flow
2. start the project
3. Watch the TreeGrid expanding slowly.
4. Add more ComponentRenderers, to amplify the effect.

### Environment

- Vaadin 21.0.9
- Ubuntu Linux 21.10 x86-64

### Browsers Affected
- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

### Workarounds

1. Use as few ComponentRenderers as possible

**Comment by TatuLund** [comment]
Related or duplicate https://github.com/vaadin/flow-components/issues/1627 and https://github.com/vaadin/flow-components/issues/1050

**Comment by mvysny** [comment]
Thanks Tatu! I don't think this one duplicates either of those:

* #1627 deals with some kind of exceptions, and I'm not getting any.
* #1050 is about expansion state keeping

**Comment by mvysny** [comment]
Implementing the eager fetching as mentioned at https://github.com/vaadin/flow-components/issues/1627#issuecomment-683806711 should definitely help.

**Comment by rolfsmeds** [comment]
Although #1627 does mention some exceptions as well, the underlying issue is the same, has been discussed a lot, and a solution has been planned. Closing this as a duplicate.
