### ISSUE TITLE
Server-side date parsing

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/flow-components#2466]
### Describe your motivation
Some applications use various specialized strings for quickly entering dates, such as `+1` or `tomorrow` for tomorrow. While we can extend the parsing formats supported by Date Picker via date-fns in the future, it is likely that there will always be custom, application-specific strings that even date-fns does not support. Providing a solution for server-side parsing of dates, that allow developers to provide their own parsing, would solve these use cases.

### Describe the solution you'd like
A way to provide server-side date parsing as a fallback (if the parsing formats provided are unable to parse the entered string). The API could be something along the lines of
```
DatePicker dp = new DatePicker();
dp.setFallbackParser(s -> {
  // custom logic for parsing the input string, e.g.
  if (s.equals("tomorrow")) {
    return LocalDate.now().plusDays(1);
  } else {
    return null;
}
```

**Comment by knoobie** [comment]
Flow has `Converter` (https://github.com/vaadin/flow/blob/master/flow-data/src/main/java/com/vaadin/flow/data/converter/Converter.java) for this kind of things - the generic lambda could probably be some kind of "one way" (or two way) Converter to allowing the `Result` to contain an error for failed fallback parsing.

```java

public void setFallbackParser(Converter<String, LocalDate> fallbackParser);

```

**Comment by vursen** [comment]
Depends on
- #5537

**Comment by vursen** [comment]
We are considering going with Rolf's original API design where the parser returns either a `LocalDate` or `null`. A `null` return value will indicate unparsable input and trigger the i18n error message for bad input.

```java
datePicker.setI18n(new DatePickerI18n()
  .setBadInputErrorMessage("Invalid date format")); // Will be displayed if the parser returns `null`

datePicker.setFallbackParser(s -> {
  if (s.equals("tomorrow")) {
    return LocalDate.now().plusDays(1);
  } else {
    return null;
}
```

The reason for not adding error message support to the parser now is that we already have two existing approaches: i18n and setErrorMessage(). Adding a third approach would make the error handling mechanism harder to understand. However, even without direct support, it will still be possible to display different error messages based on the parser logic using this workaround:

```java
datePicker.setFallbackParser(s -> {
  if (s.equals("tomorrow")) {
    return LocalDate.now().plusDays(1);
  } else if (s.equals("tomo")) {
    datePicker.getI18n().setBadInputErrorMessage("Must be tomorrow");
    return null;
  } else {
    datePicker.getI18n().setBadInputErrorMessage("Invalid date format");
    return null;
  }
}
```

If you have a different view, please feel free to share your perspective and a use case.

**Comment by knoobie** [comment]
While I agree that "yet" another error handling mechanism is harder to understand - the mentioned "another" error handling mechanismn is the standard mechanism to be used in every flow project when you use validator or converter  with Binder where the result (`Result.ok(date)` or `Result.error("String")`) is used. Additionally your workaround looks like it could create interesting side effects because it relies on the fact that getI18n() is properly updated (in time!) before the return value is evaluated.. and I doubt that anyone is going to find that "workaround" ;) 

@simasch I think we talked about this feature in the past.. you might be interested in this as well

**Comment by simasch** [comment]
I share @knoobie opinion. The fallback parser should not set the error message directly but return the error message or a date.
