### ISSUE TITLE
[map] Default theme

### ISSUE THREAD

**Issue by sissbruecker** [vaadin/flow-components#2506]
### Motivation

Map should have a look and feel that matches other Vaadin components. That means visual controls inside the map (added by OpenLayers), should be themed so that they match the surrounding application.

Scope to be clarified, this might only include a Lumo theme variant for now.

**Comment by jouni** [comment]
Theme implementation in https://github.com/vaadin/web-components/pull/3374.

Both the Lumo and Material themes define a "borderless" variant, which should be available for the Flow component.
