### ISSUE TITLE
There seems to be an error in Vaadin Grid: can't access property "style", rowData.item is undefined 

### ISSUE THREAD

**Issue by garehira** [vaadin/flow-components#2517]
### Description

When using the Grid, in the console, tab Log, the following error message appears:
There seems to be an error in Vaadin Grid: can't access property "style", rowData.item is undefined 
This appears already when I log my page and dont interact at all.

Vaadin
    22.0.2
Flow
    9.0.2
Java
    Amazon.com Inc. 11.0.11
OS
    amd64 Windows 10 10.0
Browser
    Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0

**Comment by web-padawan** [comment]
Closing as inactive. @garehira if you are able to reproduce this issue, please provide a code example and we'll investigate.
