### ISSUE TITLE
CustomValueSetListener gets called "million times" if dropdown don't get opened while typing

### ISSUE THREAD

**Issue by mstahv** [vaadin/flow-components#2524]
### Description

CustomValueSetListener gets called "million times" if dropdown don't get opened while typing and lazy data binding is in use.

### Expected outcome

CustomValueSetListener should get called once with the new value

### Actual outcome

CustomValueSetListener gets called eternally in a loop.

### Minimal reproducible example

```
package com.mycompany.v22.test;

import com.vaadin.flow.component.combobox.ComboBox;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;
import java.util.ArrayList;

@Route
public class MainView extends VerticalLayout {

    ArrayList<String> backend = new ArrayList<>();
    ComboBox<String> cb = new ComboBox<>();
    
    public MainView() {
        
        backend.add("foo");
        
        listItems();
        
        cb.addCustomValueSetListener(e-> {
            final String newItem = e.getDetail();
            backend.add(newItem);
            System.err.println("custom value listener called with " + newItem);
            listItems();
            cb.setValue(newItem);
        });
        
        add(cb);
        
    }

    private void listItems() {
        cb.setItems(e -> {
            return backend.stream()
                    .skip(e.getOffset())
                    .limit(e.getPageSize());
        });

    }
}
```

### Steps to reproduce

1. Run the above code and navigate to that UI
2. Hit tab to navigate to combox
3. With reasonable speeed type "jorma" to the field and hit enter. Then open the option list using mouse or keyboard.
4. Notice that the new value is not in the list, which is actually empty.
5. Close the dropdown and re-open
6. Notice that you already have a dozen of new items and the listener on the server side is called repeatedly

### Environment

Vaadin: 22.0.2
Flow: 9.0.2
Java: Eclipse Adoptium 17
OS: aarch64 Mac OS X 12.0.1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
Live reload: Java unavailable: Front end active

### Browsers Affected

At least Chrome and Safari

**Comment by tomivirkki** [comment]
This issue consists of two separate issues
1. The custom value set listener getting called multiple times
2. The dropdown not opening after the items get set again

The first one was fixed by https://github.com/vaadin/web-components/pull/3302 and the second one is isolated and reported separately in https://github.com/vaadin/flow-components/issues/2532
