### ISSUE TITLE
Grid horizontal scroll bar position is not preserved

### ISSUE THREAD

**Issue by paodb** [vaadin/flow-components#2530]
### Description

When having different views of an application that are open in different browser tabs, and one of the views has a grid displaying a horizontal scroll bar, if scroll position is changed, going to another tab and then returning to the tab/view that has the grid, shows the scroll bar back to the initial position. This behavior does not always happen but I was able to reproduce it in the attached example.

### Expected outcome

When going back to a tab/view with a grid with an horizontal scroll bar, the scroll bar should retain the previous position.

### Actual outcome

Grid Horizontal scroll bar does not always retain previous position.

### Live Demo

![scroll](https://user-images.githubusercontent.com/30666649/149998303-cd32213f-1c92-4329-9a61-e7c122a1708f.gif)

### Minimal reproducible example

- View with a grid: 
```
@Route("grid")
public class GridView extends Div {
    
    public GridView() {
        this.setSizeFull();

        Grid<TestData> grid = new Grid<>();
        grid.setItems(getItems());
        grid.addColumn(TestData::getCol1).setHeader("Column 1").setKey("name").setWidth("700px");
        grid.addColumn(TestData::getCol2).setHeader("Column 2").setWidth("700px");
        grid.addColumn(TestData::getCol3).setHeader("Column 3").setWidth("700px");
        grid.addColumn(TestData::getCol4).setHeader("Column 4").setWidth("900px");
        add(grid);
    }

    private List<TestData> getItems() {
        List<TestData> items = new ArrayList<>();
        for (int i = 0; i < 20; i++) {
            int c = i+1;
            items.add(new TestData("col1 - " + c, "col2 - " + c, "col3 - " + c, "col4 - " + c));
        }
        return items;
    }
}

class TestData {    
    private String col1;
    private String col2;
    private String col3;
    private String col4;

    public TestData(String col1, String col2, String col3, String col4){
        this.col1 = col1;
        this.col2 = col2;
        this.col3 = col3;
        this.col4 = col4;
    }
    public String getCol1() {
        return col1;
    }
    public String getCol2() {
        return col2;
    }
    public String getCol3() {
        return col3;
    }
    public String getCol4() {
        return col4;
    }
}
```
- A second view:
```
@Route
public class MainView extends VerticalLayout {

    public MainView() {
        Button button = new Button("Click me",
                event -> Notification.show("Clicked!"));
        add(button);
    }
}
```

### Steps to reproduce

1. Create an example with the attached views.
2. Move the horizontal scroll position in GridView.
3. Go to MainView and then go back to GridView.
4. Observe the horizontal scroll position going back to the initial position.

Note: Step 4 happens randomly, so repeat 2 to 4 again if it's not happening.
(see attached video)

### Environment

- Vaadin 14.8.1

### Browsers Affected
- Chrome
- Firefox

**Comment by web-padawan** [comment]
Seems to be the same as #5088. Scrolling the grid on `focusin` was fixed by https://github.com/vaadin/web-components/pull/7323 (backported to v23.3 by https://github.com/vaadin/web-components/pull/7333). Closing, please reopen if this is still valid with the latest version.
