### ISSUE TITLE
Select dropdown arrow is positioned in a wrong place if there is a long(ish) item selected.

### ISSUE THREAD

**Issue by mstahv** [vaadin/flow-components#2536]
### Description

Select dropdown arrow is positioned in a wrong place if there is a long(ish) item selected. 

<img width="244" alt="Screenshot 2022-01-19 at 23 11 04 " src="https://user-images.githubusercontent.com/1478052/150214332-329f2288-1a17-4647-b7ec-89a174126400.png">

### Expected outcome

Dropdown should always be in correct position.

### Actual outcome

Dropdown is not always be in correct position.

### Minimal reproducible example

```
package com.mycompany.v22.test;

import com.vaadin.flow.component.combobox.ComboBox;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.select.Select;
import com.vaadin.flow.router.Route;

@Route
public class MainView extends VerticalLayout {

    private static final String LONG_TEXT = "Matin pumppu ja imu";
    
    public MainView() {
        
        ComboBox sender = new ComboBox("this is combobox, it works unlike the Select below");
        sender.setItems(LONG_TEXT);
        sender.setValue(LONG_TEXT);

        Select sender2 = new Select();
        sender2.setItems(LONG_TEXT);
        sender2.setValue(LONG_TEXT);
        
        add(sender);
        add(sender2);
        
    }

}
```

### Steps to reproduce

1. Deploy the example code
2. Compare the Select component to correctly working ComboBox

### Environment

Vaadin: 22.0.3
Flow: 9.0.3
Java: Eclipse Adoptium 17
OS: aarch64 Mac OS X 12.0.1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
Live reload: Java unavailable: Front end active

**Comment by web-padawan** [comment]
Fixed by https://github.com/vaadin/web-components/pull/3305 and will be released in the next patch.

![Screenshot 2022-01-25 at 14 11 24](https://user-images.githubusercontent.com/10589913/150974781-3f597635-0e5f-4577-a280-c432de6888b3.png)
