### ISSUE TITLE
Checkbox: getLabel() does not work after setLabelAsHtml()

### ISSUE THREAD

**Issue by enver-haase** [vaadin/flow-components#2546]
### Description of the bug

When I set HTML-enabled label text, getLabel() returns an empty string.

### Expected behavior

Don't know. Maybe return the HTML text?

### Minimal reproducible example

checkkbox.setLabelAsHtml("foo");
String l = checkbox.getLabel();

### Versions

- Vaadin / Flow version: Vaadin 22
- Java version:
- OS version:
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by TatuLund** [comment]
This is duplicate of https://github.com/vaadin/flow-components/issues/1667

**Comment by TatuLund** [comment]
See https://github.com/vaadin/flow-components/issues/1667#issuecomment-627918272

**Comment by yuriy-fix** [comment]
Closing as a duplicate of #1667
