### ISSUE TITLE
Add ValueChangeListener to the upload component

### ISSUE THREAD

**Issue by ImOlli** [vaadin/flow-components#2661]
### Describe your motivation

I would like to get notified when the value of the upload component changes. Especially when someone clicks on the "x" button of a uploaded file.

### Describe the solution you'd like
A listener that gets notified when an uploaded file gets removed by the "x" button or when a new files is done with uploading.

### Describe alternatives you've considered
I tried to use a custom Receiver. But the receiver dont get notified when removing an uploaded file.

**Comment by yuriy-fix** [comment]
Closing in favour of https://github.com/vaadin/flow-components/issues/1342
