### ISSUE TITLE
[chart] Legend does not honor series color

### ISSUE THREAD

**Issue by knoobie** [vaadin/flow-components#2669]
### Description

The legend of the chart does not honor the color defined in the series item.

### Expected outcome

The dot should have a yellow color.

### Actual outcome

No blue dot inside the legend.

### Live Demo (optional)

![image](https://user-images.githubusercontent.com/3968629/154026338-755e24c3-f112-42b9-afd4-8aef61b8f742.png)

### Minimal reproducible example

```java
    var chart = new Chart();
    var configuration = chart.getConfiguration();
    configuration.getChart().setType(ChartType.BAR);

    var myYellowSerie = new DataSeries("<-- Yellow? :(");
    IntStream.range(1, 20).forEach( i -> {
      myYellowSerie.add(new DataSeriesItem("Yellow " + i, i, SolidColor.YELLOW));
    });
    configuration.setSeries(myYellowSerie);
    add(chart);
```

### Environment

- v23.0.0-beta2

### Workaround

- Create custom `MyDataSeries` with:

```java

  private class MyDataSeries extends DataSeries {
    @Getter
    @Setter
    private String color; //  has to match the highchart color property of `series`

    public MyDataSeries(String name) {
      super(name);
    }
  }

```

**Comment by TatuLund** [comment]
This seems to be "normal" behavior of Highcharts https://www.highcharts.com/forum/viewtopic.php?t=34302

**Comment by TatuLund** [comment]
It could be that DataSeries would be more intuitive place for setting series color. Now the API is PlotOptions, e.g. this works

```
@PageTitle("Chart")
@Route(value = "chart", layout = MainLayout.class)
public class ChartView extends Div {

    public ChartView() {
        var chart = new Chart();
        var configuration = chart.getConfiguration();
        configuration.getChart().setType(ChartType.BAR);
        PlotOptionsBar plotOptions = new PlotOptionsBar();
        plotOptions.setColor(SolidColor.YELLOW);
        configuration.setPlotOptions(plotOptions);

        var myYellowSerie = new DataSeries("<-- Yellow? :(");
        IntStream.range(1, 20).forEach( i -> {
            myYellowSerie.add(new DataSeriesItem("Yellow " + i, i));
        });
        configuration.setSeries(myYellowSerie);
        add(chart);
    }
}

```

**Comment by TatuLund** [comment]
In case of multiple series, one needs to define plot options per serie, not at configuration.

@PageTitle("Chart")
```
@Route(value = "chart", layout = MainLayout.class)
public class ChartView extends Div {

    public ChartView() {
        var chart = new Chart();
        var configuration = chart.getConfiguration();
        configuration.getChart().setType(ChartType.BAR);
        
        var myYellowSerie = new DataSeries("<-- Yellow? :(");
        IntStream.range(1, 20).forEach(i -> {
          myYellowSerie.add(new DataSeriesItem("Yellow " + i, i));
        });
        PlotOptionsBar plotOptionsYellow = new PlotOptionsBar();
        plotOptionsYellow.setColor(SolidColor.YELLOW);
        myYellowSerie.setPlotOptions(plotOptionsYellow);

        var myBlueSerie = new DataSeries("<-- Blue? :(");
        IntStream.range(1, 20).forEach(i -> {
          myBlueSerie.add(new DataSeriesItem("Blue " + i, i));
        });
        PlotOptionsBar plotOptionsBlue = new PlotOptionsBar();
        plotOptionsBlue.setColor(SolidColor.BLUE);
        myBlueSerie.setPlotOptions(plotOptionsBlue);

        configuration.setSeries(myYellowSerie, myBlueSerie);
        add(chart);
    }
}

```

![image](https://user-images.githubusercontent.com/14309836/154228128-ce4421a8-2088-472f-9897-5c65c1d1be49.png)

**Comment by sissbruecker** [comment]
Sorry for the late reply. As was already pointed out by Tatu, setting the color for individual series items does not affect the color of the series itself. The proper way to configure a color for a series is indeed to configure plot options for the series. Thanks again to @TatuLund for providing helpful examples. I can see how this is hard to discern from the current documentation, and I've made an attempt to improve the documentation for Chart Configuration / Plot Options to at least improve the situation a bit: https://github.com/vaadin/docs/pull/1285

As this is not an issue, I'll close the ticket for now. Please comment if you feel that something is unresolved.
