### ISSUE TITLE
CheckboxGroup.getDataProvider.refreshAll() clears selected values

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/flow-components#2674]
The same issue described in #1674, #2593 (both triaged as `bug`) applies to `CheckBoxGroup` in Vaadin 22.0.4

https://github.com/vaadin/flow-components/blob/184cf30596ee41166e4d3493a2a288b9ccb3daad/vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java#L466-L468

### Description

Selected values are cleared after calling `getDataProvider().refreshAll()` 

### Expected outcome

[There should be some easy way of making a component reflect updates in the items (e.g. adding items or updating the contents of some item)](https://github.com/vaadin/flow-components/issues/1674#issuecomment-734810174)

### Actual outcome

Calling `getDataProvider().refreshAll()`  clears the value and one needs to set the old value after `refreshAll()` is called.

### Minimal reproducible example

```
@Route
public class MainView extends VerticalLayout {

    private RandomString rnd = new RandomString(3);

    public MainView(MultiSelect<CheckboxGroup<String>, String> listBox) {
        CheckboxGroup<String> group = new CheckboxGroup<>();

        List<String> items = new LinkedList<>(Arrays.asList("foo", "bar"));

        CheckboxGroupListDataView<String> dataView = group.setItems(items);

        Button button = new Button("Update items", e -> {           
            String newItem = rnd.nextString();
            dataView.addItem(newItem);
            dataView.refreshAll();  
        });

        add(group, button);

    }
}
```

**Comment by sissbruecker** [comment]
Some concerns raised during triage:
- Ideally the behaviour between components should be consistent, either clear value or retain value
- Changing the behavior from clearing to retaining might introduce BC breaks for applications that rely on the fact that refreshing items clears the value
- Aligning other components might introduce breaking changes as well
- Retaining value might not work, or might result in unexpected behavior, for components that use lazy-loading. When refreshing the data provider, how would a lazy-loading component know if the current value still exists in the data? Would a developer expect the component to have a value that doesn't even exist in the data provider (IMO no)?

**Comment by enver-haase** [comment]
> * Retaining value might not work, or might result in unexpected behavior, for components that use lazy-loading. When refreshing the data provider, how would a lazy-loading component know if the current value still exists in the data? Would a developer expect the component to have a value that doesn't even exist in the data provider (IMO no)?

I wonder if 'getValue()' could trigger the data provider to verify if the value still is in the data set, when it is not in the cache. And then either return the value or raise some ValueNotInDatasetException with getValue() as a method of said exception class.

**Comment by sissbruecker** [comment]
This should be doable now with setting the respective selection preservation mode:
```java
select.setSelectionPreservationMode(SelectionPreservationMode.PRESERVE_EXISTING);
```

**Comment by enver-haase** [comment]
Is there any now any documented and consistent solution across our HasValue implementation along the ideas you sketched, @sissbruecker ?

https://github.com/vaadin/flow-components/issues/2674#issuecomment-1047758661

**Comment by sissbruecker** [comment]
There are a number of components that have exactly the same API, though unfortunately there are some exceptions. Not sure about documentation, my assumtion is there is none.
