### ISSUE TITLE
Reattaching grid ignores setDeselectAllowed(false)

### ISSUE THREAD

**Issue by paodb** [vaadin/flow-components#2696]
### Description
Setting `GridSingleSelectionModel#setDeselectAllowed(false)` doesn't work after grid is reattached. The grid seems to ignore that `setDeselectAllowed` is false and behaves as if it is true after reattachment.

### Expected outcome

`setDeselectAllowed(false)` should still prevent deselection after grid is reattached.   

### Actual outcome

`setDeselectAllowed(false)` allows deselection after grid is reattached.   

### Live Demo 

![deselection](https://user-images.githubusercontent.com/30666649/154689092-259ce045-f313-4576-8ba8-5fd34168e0a9.gif)

### Minimal reproducible example

```
private Grid<String> grid = new Grid<>();

public DeselectNotAllowedView() {

    grid.setSelectionMode(SelectionMode.SINGLE);
    GridSingleSelectionModel<String> singleSelect =
        (GridSingleSelectionModel<String>) grid.getSelectionModel();
    singleSelect.setDeselectAllowed(false);
    
    add(new Button("Attach", e -> add(grid)));
    add(new Button("Detach", e -> remove(grid)));
    
    grid.setItems("A", "B", "C");
    grid.addColumn(x -> x).setHeader("Col");
    grid.select("A");

    add(grid);
}
```

### Steps to reproduce

1. Create a project with the attached example.
2. Click on selected item and see deselection not happening.
2. Click "detach" button to remove the grid.
3. Click "attach" button to reattach the grid.
4. Click on selected item and see deselection happening.

### Environment

- Vaadin version 22.0.5.

### Browsers Affected
- [X] Chrome
- [X] Firefox

**Comment by web-padawan** [comment]
Confirmed. The issue appears to be caused by the fact that `grid.$connector` instance is not preserved on re-attach.
