### ISSUE TITLE
Grid.asMultiSelect() doesn't work well within a FormLayout

### ISSUE THREAD

**Issue by archiecobbs** [vaadin/flow-components#2707]
### Description

Vaadin 22.0.5.

Background: I want to create a form in Vaadin 22 with a multi-select input.

With newer Vaadin the old `ListSelect` is gone and so [we're supposed to use `Grid.asMultiSelect()` instead](https://stackoverflow.com/questions/70962635/what-is-the-replacement-for-listselect-in-vaadin-22). Bleh.

But `Grid.asMultiSelect()` has several bugs when used within a `FormLayout`:

1. The vertical alignment of the component in the form is wrong. The MultiSelect component is aligned too high vertically, i.e., flush top instead of middle.
2.  The vertical alignment of the component's label in the form is wrong. The label is aligned too low vertically, i.e., flush bottom instead of middle.
3. The component never displays any error indication when validation of its value fails.

### Expected outcome

1. The vertical alignment of the component in the form is middle
2. The vertical alignment of the component's label in the form is middle
3. The component displays an error indication when validation of its value fails

### Actual outcome

1. The vertical alignment of the component in the form is wrong. The MultiSelect component is aligned too high vertically, i.e., flush top instead of middle.
2.  The vertical alignment of the component's label in the form is wrong. The label is aligned too low vertically, i.e., flush bottom instead of middle.
3. The component never displays any error indication when validation of its value fails.

### Live Demo (optional)

See movie below which shows all three problems.

For problem 1: note how the "Favorite Colors" multi-select is too high and much closer to the "Name" field than the "Birthday" field.

For problem 2: I thought the component labels were always supposed to be centered vertically. At least, that's how the old `FormLayout` used to work.

For problem 3: The "Favorite Colors" has a validation requirement of at least one color chosen. But this error is never visible.

https://user-images.githubusercontent.com/545866/155190268-4f48cabd-f049-4097-a702-cb1610420c27.mov

### Minimal reproducible example

https://github.com/archiecobbs/vaadin-flow-bugs/tree/GridMultiSelectOffset

### Steps to reproduce

```
$ git clone git@github.com:archiecobbs/vaadin-flow-bugs.git
$ cd vaadin-flow-bugs
$ git checkout GridMultiSelectOffset
$ mvn package jetty:run
```

Then connect to `http://localhost:8090/demo/` (note trailing slash).

### Environment
Vaadin 22.0.5
MacOS 12.1
Firefox 97.0
Java 8

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

Haven't tested the others.

**Comment by yuriy-fix** [comment]
Grid is not considered to be an input element. It's not a supported use-case to use grid inside form-layout. Will leave this ticket opened to be considered as an enhancement.

**Comment by archiecobbs** [comment]
Hi @yuriy-fix,

> Grid is not considered to be an input element. It's not a supported use-case to use grid inside form-layout. 

According to [Vaadin's own documentation](https://vaadin.com/docs/latest/ds/components/list-box/#best-practices), you are wrong:

> Best Practices
> 
> List Box is not designed to be used as an input field in forms, and lacks features like label, helper, and validation errors. See related components below for better options for use in forms.
> 
> ...
> 
> Grid - A more advanced list component for cases where multiple columns, filtering or lazy loading is required.

Or are you saying Vaadin that doesn't provide any multi-select input at all??

**Comment by web-padawan** [comment]
Have you considered using `CheckboxGroup`? It supports selecting multiple options as well as label and validation.

**Comment by knoobie** [comment]
Looks more like an error in the docs page - the recommend way of selecting multiple values is (currently) the [CheckBoxGroup](https://vaadin.com/docs/latest/ds/components/checkbox)

**Comment by archiecobbs** [comment]
Yeah that works just great...

<img width="401" alt="Screen Shot 2022-03-01 at 10 03 18 AM" src="https://user-images.githubusercontent.com/545866/156203989-a44c2443-a525-4298-ba0c-dade71f75e05.png">

**Comment by knoobie** [comment]
You probably have to change the styling of the CheckBoxes with css and apply the sizing and overflow properties there.

**Comment by archiecobbs** [comment]
> You probably have to change the styling of the CheckBoxes with css and apply the sizing and overflow properties there.

Thanks - but that kindof misses the point.

Of course you can fix anything with enough HTML and CSS, but then what's the point of Vaadin flow?

If I put component X inside component Y, it's supposed to fit.

If I tell a component `setHeight("150px")`, it's supposed to have height 150 pixels.

I've counted two bugs here so far:

1. Documentation bug: Need to clearly document what is the officially blessed way to put a multi-select supporting more than a trivial number of items inside a form. Still waiting on an answer to this one by the way.
1. `CheckboxGroup` doesn't know how to scrollbar itself when using `CheckboxGroupVariant.LUMO_VERTICAL` and there are more items than fit in its height.

**Comment by TatuLund** [comment]
FormLayout is designed for small fields. The problem with Grid and CheckboxGroup is that they are big. Thus it is hard to make FormLayout look nice when there are both big and small components. There are two approaches to solve this

1. Build layout using something else than FormLayout, or use combination of other layouts and have only the small fields in FormLayout

2. Wrap the big component to button - dialog mechanism, i.e. popup field. I have example of this here (ListEdit is actually field that uses Grid) PopupListEdit is a button, that popups ListEdit, and works like a field. This way the footprint in the layout is small, and works nicely in FormLayout https://github.com/TatuLund/ProtoTools/blob/master/src/main/java/org/vaadin/addons/tatu/prototools/PopupListEdit.java

**Comment by archiecobbs** [comment]
Hi @TatuLund,

Your PopupListEdit is a promising idea. It seems like it might be a good compromise for this situation.

So let me try to summarize the current situation.

Please tell me if you (dis)agree with any of these statements...

1. Sometimes people need to multi-select from a list of options in a form.
2. Sometimes the list of options has more than a few choices, where they don't all fit on the screen at the same time.
3. This is a basic and common need. There is nothing exotic about it.
4. Because this is a very basic and very common need, it is therefore appropriate for Vaadin to provide a standard widget that does this - for same reason Vaadin provides `ComboBox`, which is a standard widget for single-select.
5. Vaadin once did provide such a thing, it was called `ListSelect`.
6. Vaadin no longer provides a standard widget that does this.

The suggestions so far, using CSS tricks, and your prototype `PopupListEdit`, are not really helpful. Yes, they are answers to the question "Is it technically possible to do this?" But of course we already knew that, because we used to have `ListSelect` that worked just fine.

None of them are answers to the question _Why the heck doesn't Vaadin provide a standard way to put a multi-select in a form?_

If you think `PopupListEdit` is the answer, that sounds great! Please add it to Vaadin Flow components!

Right now though there's no good answer for the mere mortals like myself who are just trying to stick a multi-select into a form and get on with their lives.

**Comment by TatuLund** [comment]
One more approach is a ComboBox with multiselect function, in Directory there are two versions of this idea

https://vaadin.com/directory/component/multiselect-combo-box

https://vaadin.com/directory/component/multicombobox-component

And for simpler use cases there is multiple select. which does not have filter functionality

https://vaadin.com/directory/component/multiple-select

These also have small size as they are based on TextField.

> If you think PopupListEdit is the answer, that sounds great! Please add it to Vaadin Flow components!

Just noting that this field is a list editor, not a selector. But by reducing some functionality one can make version of it that uses Grid as multiselect.

Yet another pattern of multiselection is "list builder" or so called twin col select

https://vaadin.com/directory/component/twincolselect

But with this concept again challenge is the size. One naturally could again wrap this as popup for better fit with FormLayout.

**Comment by archiecobbs** [comment]
You guys are the UI experts. _Please just pick one and make it standard!_

Nobody should have to hunt around for something so basic. As soon as you say "Vaadin directory" you've already missed the point.

**Comment by web-padawan** [comment]
> Please just pick one and make it standard!

We do have plans to make `MultiSelectComboBox` part of our official set of components.
Currently it's not yet started, but we expect to deliver this component in Vaadin 23.1

**Comment by archiecobbs** [comment]
> We do have plans to make MultiSelectComboBox part of our official set of components. Currently it's not yet started, but we expect to deliver this component in Vaadin 23.1

That's great news - thank you!

**Comment by archiecobbs** [comment]
Any news on `MultiSelectComboBox`?

23.1.7 is released and no sign of it yet...

**Comment by knoobie** [comment]
It's stilled planned for 23.2 in the beginning of September.

**Comment by archiecobbs** [comment]
OK great - thanks.

**Comment by rolfsmeds** [comment]
Actually the `vaadin-multi-select-combo-box` web component _did_ ship in 23.1, but the Java API didn't make it, so that's coming in 23.2. The roadmap board is a good resource for this type of info: https://github.com/orgs/vaadin/projects/9

**Comment by web-padawan** [comment]
Now when we have [`MultiSelectComboBox`](https://vaadin.com/docs/latest/components/multi-select-combo-box) available, I believe this issue can be closed as stale.
