### ISSUE TITLE
Click listener invoked twice in Buttons with ClickShortcut and focus

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/flow-components#2717]
### Description

If I create a button and add a click listener and also add a click shortcut, when getting the focus to this button and activating the shortcut (ie: pressing enter), it will execute the listener twice.

### Expected outcome

The click listener should only be invoked once.

### Actual outcome

The click listener is invoked two times.

### Minimal reproducible example

```
@Route
@PWA(name = "My Application", shortName = "My Application")
public class MainView extends VerticalLayout {

    ShortcutRegistration sr;

    public MainView() {
        Button button = new Button("Enter");
        button.addClickListener(e -> {
            Notification.show("clicked");
            button.setEnabled(true);
        });
        button.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        button.setDisableOnClick(true);
        sr = button.addClickShortcut(Key.ENTER);
        add(button);
    }
}
```

### Steps to reproduce

Clear steps describing how to reproduce the issue.

1. Add a button
2. Add a click listener that shows a notification
3. Add a click shortcut with Key.ENTER
4. Start the application, press tab until the button gets the focus and press Enter
5. You will see the notification two times

### Environment

- Vaadin 14.8.4

### Browsers Affected

- [X] Chrome
- [X] Firefox

**Comment by knoobie** [comment]
Sadly it's not a bug.. see https://github.com/vaadin/flow/issues/8037#issuecomment-789674976

**Comment by mlopezFC** [comment]
Thanks for the info, I'm then closing this one then.
