### ISSUE TITLE
Clicking button in Details will cause JavaScript exception on console

### ISSUE THREAD

**Issue by TatuLund** [vaadin/flow-components#2727]
Vaadin 23.0.0.rc1 and Vaadin 22.0.6

How to reproduce
- Open attached MasterDetailView
- Click a row to see details
- Click the button
- Check the error in the console

masterdetail:6 There seems to be an error in Vaadin Grid:
Unexpected value for section: details
Please submit an issue to https://github.com/vaadin/flow-components/issues/new/choose
console.error @ masterdetail:6
eval @ FlowBootstrap.js?f80c:67
_onContentFocusIn @ vaadin-grid-keyboard-navigation-mixin.js?709a:734

Code to reproduce

@PageTitle("Master-Detail")
@Route(value = "masterdetail")
public class MasterDetailView extends Div {

	private Grid<Vector<String>> grid = new Grid<>();

	public MasterDetailView() {
		setSizeFull();

		// Configure Grid
		grid.addColumn(item -> item.get(0)).setAutoWidth(true);
		grid.addColumn(item -> item.get(1)).setAutoWidth(true);

		grid.setItems(createData());
		grid.addThemeVariants(GridVariant.LUMO_NO_BORDER);
		grid.setHeightFull();

		grid.setItemDetailsRenderer(createPersonDetailsRenderer());

		add(grid);

	}

	private List<Vector<String>> createData() {
		Random rand = new Random();
		return IntStream.range(0, 20).mapToObj(i -> {
			Vector<String> vector = new Vector<>(2);
			vector.add("email" + i + "@domain.com");
			vector.add("" + rand.nextInt(20));
			return vector;
		}).collect(Collectors.toList());
	}

	private ComponentRenderer<PersonDetailsFormLayout, Vector<String>> createPersonDetailsRenderer() {
		return new ComponentRenderer<>(PersonDetailsFormLayout::new, PersonDetailsFormLayout::setPerson);
	}

	private class PersonDetailsFormLayout extends VerticalLayout {
		private final TextField emailField = new TextField("Email address");
		private final TextField phoneField = new TextField("Phone number");

		public PersonDetailsFormLayout() {
			Stream.of(emailField, phoneField).forEach(field -> {
				add(field);
			});

			Button btn = new Button("do it");
			btn.addClickListener(e -> {
				Notification.show("clicked");
			});
			add(btn);
		}

		public void setPerson(Vector<String> person) {
			emailField.setValue(person.get(0));
			phoneField.setValue(person.get(1));
		}
	}
}

**Comment by darmro** [comment]
![image](https://user-images.githubusercontent.com/56316289/155950862-e63eacb1-e4a1-473f-80a1-e989d20623d5.png)

**Comment by tomivirkki** [comment]
This is a regression from https://github.com/vaadin/flow-components/pull/822

The connector expects the `eventContext.section` to be one of `header`, `body`, `footer`. If the section is `details` ([also a valid value for the event context section](https://github.com/vaadin/web-components/blob/d8339237891cb15eb216b1fc3d47d6ca222524c1/packages/grid/src/vaadin-grid-event-context-mixin.d.ts#L10)), an exception is [manually thrown](https://github.com/vaadin/flow-components/blob/fa48bc00619c1333a06c44873f45eb053674cc4f/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js#L1040).
