### ISSUE TITLE
Let LitRenderer use (some of) Lit's built-in directives

### ISSUE THREAD

**Issue by Frettman** [vaadin/flow-components#2753]
### Describe your motivation

I'm populating a TreeGrid and would like formatted text for certain columns. It's not possible to send the HTML from the server-side (not without workarounds anyway), so I have to use a renderer. To avoid any negative performance or memory impact I'm trying to avoid ComponentRenderer and use LitRenderer instead. The idea is to send a list of strings and let the renderer surround some of them with `<em>` and then join them into a comma separated list.
Lit has a built-in `join` directive for such use cases, but it's apparently not available.
This is my template:
```
LitRenderer.<Entry> of(
        "${join(item.slots.map((slot) => slot == 'default' ? html`<em>${slot}</em>` : html`${slot}`), html`,`)}")
        .withProperty("slots", entry -> entry.getSlots())
```
which results in the following error:
```
There seems to be an error in Vaadin Grid:
join is not defined
```

### Describe the solution you'd like

Make Lit's built-in directives - maybe just those from the [Loops and Conditionals](https://lit.dev/docs/templates/directives/) category - available to use in the LitRenderer.

### Describe alternatives you've considered

JavaScript's `join` function on Array is not an alternative as it will basically turn all of Lit's html objects into strings.

I considered creating a web component to show server-generated unsafe HTML as described [here](https://stackoverflow.com/questions/71302820/dynamic-html-using-a-vaadin-litrenderer), but that seems like a last resort. For security reasons (even though my content isn't user generated) and to avoid having to manually escape stuff.

**Comment by knoobie** [comment]
A quick workaround suggest by Artur in discord some days ago would be to use `.innerHTML` as property.

**Comment by tomivirkki** [comment]
Here's one way to use directives with `LitRenderer`:

Create file `frontend/directives.js`:
```js
import {map} from 'lit/directives/map.js';

window.directives = {
    map
};
```

Import the file in your view
```java
@JsModule("./directives.js")
public class MyView extends Div {
```

Use the directive in your LitRenderer template:

```java
LitRenderer.of("<ul>${directives.map([1,2], (i) => html`<li>${i}</li>`)}</ul>"
```

**Comment by tomivirkki** [comment]
You can also write the renderer completely in a js/ts file:

Create file frontend/renderers.js:

```js
import { map } from "lit/directives/map.js";
import { html } from "lit";

window.myListRenderer = (item) => {
  return html`
    <ul>
      ${map([1, 2], (i) => html`<li>Item: ${item} (${i})</li>`)}
    </ul>
  `;
};
```

Import the file in your view
```java
@JsModule("./renderers.js")
public class MyView extends Div {
```

Use the renderer in your LitRenderer template:

```java
LitRenderer.<String>of("${myListRenderer(item)}")
```

**Comment by Frettman** [comment]
> A quick workaround suggested by Artur in discord would be to use `.innerHTML` as property.

The idea was to let the client do the work. But it's actually hard to tell if preparing and sending the data for the LitRenderer saves performance compared to just building the sending the finished HTML.
`innerHTML` is what `com.vaadin.flow.component.Html` uses. So using that property would require a ComponentRenderer after all, right?
`Html` sure is convenient, although it adds some performance overhead by parsing and formatting the HTML using Jsoup; which doesn't seem too terrible when building larger numbers of them. However, all of these Components are kept in memory, which is why the use of ComponentRenderers (escpecially in Grids) was discouraged in one of Vaadin's [blog posts](https://vaadin.com/blog/top-5-most-common-vaadin-performance-pitfalls-and-how-to-avoid-them). But a single `Html` Component is definitely less problematic than building a Component hierarchy via the Java API. So I'd still not dismiss `Html` outright; it's just too convenient :)
Anyway, the LitRenderer-based workarounds are quite interesting. The second one seems rather cumbersome, but could be worth it for more complex formatting, as it helps readability of the template _a lot_. The first one seems like something I will use at some point unless Vaadin adds the directives first ;)

**Comment by knoobie** [comment]
It's possible without a ComponentRenderer; here is the code that was produced with Artur's tip: 

https://github.com/komunumo/komunumo-server/blob/54922dff768f5d3f6164fc11e115a4b1aa21aacb/src/main/java/org/komunumo/ui/view/admin/events/EventsView.java#L148

**Comment by web-padawan** [comment]
> unless Vaadin adds the directives first

There are two main problems here:

1. How do we choose which directives to add? The whole point is that Lit users can import directives lazily so that only those that are actually used get included to the bundle. Adding all of those 20 directives would increase bundle size.
2. Even if we add directives, they will need to be exposed globally somehow. In order to keep the usual syntax, we would have to introduce separate global variable for each directive e.g. `window.join` - IMO we should not do that.

**Comment by Frettman** [comment]
> 2\. Even if we add directives, they will need to be exposed globally somehow. In order to keep the usual syntax, we would have to introduce separate global variable for each directive e.g. `window.join` - IMO we should not do that.

I see. This is definitely a show stopper for this ticket. And if an altered syntax for the directives is okay, I might as well create the `directives.js` from above myself, with exactly the directives I need.

I'll also check out the `.innerHTML` property in a LitRenderer. Seems like it has the same effect as the [unsafeHTML](https://lit.dev/docs/templates/directives/#unsafehtml) directive. Sounds like I might have an `HtmlRenderer` soon :)

So, I guess I should close this ticket now. Thank you everyone for all the useful information and workarounds :)
