### ISSUE TITLE
Incorrect code in Dialog docs

### ISSUE THREAD

**Issue by JS-E** [vaadin/flow-components#2775]
### Describe the bug

There is a small fault in the docs for Dialog in vaadin flow.

The code there is -> 

Dialog dialog = new Dialog();
button.setModal(false);

however this should be 

Dialog dialog = new Dialog;
dialog.setModal(false);

### Expected-behavior

The copied code from that doc should be spot on

### Reproduction

As explained in the bug description

### System Info

As explained in the bug description

**Comment by jouni** [comment]
Thanks for the report! 

Fixed in https://github.com/vaadin/docs/commit/8394f1922a307b1e063cd6d6b4f1e32dee756282 (latest) and https://github.com/vaadin/docs/commit/6a2c0eb3e44adb05a9ffccfff92015f534f2d24d (v22)
