### ISSUE TITLE
Grid with ItemClickListener inside of Details "jumps"

### ISSUE THREAD

**Issue by roastedcpu** [vaadin/flow-components#2805]
### Description

Grid with ItemClickListener inside of Details "jumps" up if focus is on another external component

### Expected outcome

What did you expect to happen?

Grid should keep scrolling position

### Actual outcome

Grid jumps back and forth after the event

### Live Demo (optional)

https://gifyu.com/image/SM4eq

### Minimal reproducible example

```java

@Route("")
public class MainView extends VerticalLayout {

    public MainView() {
        setWidthFull();
        add(new Label("Steps to reproduce:"));
        add(new Label("1. Reduce the height of the browser window so that a vertical page scrollbar appears"));
        add(new Label("2. Click on the 'Focus me' field to focus it"));
        add(new Label("3. Scroll down using the page scrollbar until the Details header is no longer visible"));
        add(new Label("4. Click on any name entry to trigger the item click listener\n\n" +
                "-> the page will jump up to display the Detail header, then jump back down to the clicked entry without " +
                "triggering the item click listener. Now that the component actually has the focus, click the item again " +
                "and this time the  item click listener will respond correctly without jumping"));


        add(new TextField("Focus me"));
        Details details = new Details("Scroll the page down until I'm no longer visible", buildGrid());
        details.setOpened(true);
        add(details);
    }

    private Grid<SimpleUser> buildGrid() {
        final List<SimpleUser> users = IntStream.range(1, 100).mapToObj(val -> new SimpleUser("User" + val)).collect(Collectors.toList());

        Grid<SimpleUser> userGrid = new Grid<>(SimpleUser.class);
        userGrid.setWidthFull();
        userGrid.setHeight(2000, Unit.PIXELS); // just a quick way to enforce a vertical browser scrollbar without having to reduce the browser window size. Not really necessary.
        userGrid.setDataProvider(new ListDataProvider<>(users));

        userGrid.addItemClickListener(ev -> Notification.show("Item clicked!"));
        userGrid.addComponentColumn(e -> {
            Button button = new Button("Buttons seem to work");
            button.addClickListener(ev -> Notification.show("Button clicked!"));
            return button;
        });

        return userGrid;
    }
}

public class SimpleUser {
    private String name;
    public SimpleUser(String name) {
        this.name = name;
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
}

```

### Steps to reproduce

1. Reduce the height of the browser window so that a vertical page scrollbar appears
2. Click on the 'Focus me' field to focus it
3. Scroll down using the page scrollbar until the Details header is no longer visible
4. Click on any name entry to trigger the item click listener
5. the page will jump up to display the Detail header, then jump back down to the clicked entry without triggering the item click listener. Now that the component actually has the focus, click the item again and this time the  item click listener will respond correctly without jumping

### Environment

- v14/23
- Chrome Version 98.0.4758.102 (Official Build) (64-bit) and 99.0.4844.51 (Official Build) (64-bit)
- Windows 11

**Comment by web-padawan** [comment]
Same as https://github.com/vaadin/web-components/issues/561. As a workaround, you can wrap grid in a `Div` element and set `tabindex` on it to `-1` as suggested here https://github.com/vaadin/web-components/issues/561#issuecomment-1032448600 - this will prevent jumping when focusing the details content.

**Comment by sissbruecker** [comment]
Can confirm this bug, thanks to Serhii for pointing to the relevant issue. I can also confirm that the workaround avoids the issue.

For now I've added my thoughts to the web components ticket here: https://github.com/vaadin/web-components/issues/561#issuecomment-1066656815

@roastedcpu While we are trying to find a proper solution to this issue, can you please check if the provided workaround would solve the issue for the customer?
