### ISSUE TITLE
MenuBar displays empty overflow menu under specific circumstances

### ISSUE THREAD

**Issue by Frettman** [vaadin/flow-components#2810]
### Description

Under rather specific circumstances, the MenuBar displays an empty overflow menu. The only menu item (containing an Avatar) is still visible, yet the overflow menu is shown anyway; clicking on it does nothing.
I think the minimum reproducible example below is the best way to describe the circumstances. I cut out everything that is not absolutely needed to reproduce the problem. I added comments about what alternatives I tried.
However, there one thing that I should explain beforehand: It's related to [web-components#3503](https://github.com/vaadin/web-components/issues/3503). A recent change gave the MenuBar `width: 100%` which will be reverted in a later release. To undo it right now, I set it explicitly back to `auto`. Unfortunately, this is relevant to the circumstances that trigger the issue...

### Expected outcome

I expected the MenuBar to not show it's overflow menu as every menu item is visible.

### Actual outcome

The MenuBar showed its overflow menu under the described circumstances.

### Live Demo (optional)

![image](https://user-images.githubusercontent.com/24453813/157020906-d01712bf-ef7e-45d7-b994-24a1f0baa778.png)

### Minimal reproducible example

```
import com.vaadin.flow.component.Component;
import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.avatar.Avatar;
import com.vaadin.flow.component.menubar.MenuBar;
import com.vaadin.flow.component.menubar.MenuBarVariant;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.router.Route;


@Route(value = "menubar")
public class MenuBarView
  extends Composite<Component>
{

  @Override
  protected Component initContent()
  {
    // HorizontalLayout, FlexLayout triggers the issue; VerticalLayout doesn't
    HorizontalLayout content = new HorizontalLayout();

    MenuBar menuBar = new MenuBar();
    content.add(menuBar);

    // primary, default or regular tertiary doesn't trigger the issue
    menuBar.addThemeVariants(MenuBarVariant.LUMO_TERTIARY_INLINE);

    // https://github.com/vaadin/web-components/issues/3503
    // disables the ":host { width: 100%; }" and restores the old behavior (fix not yet included in any release at this point)
    menuBar.getStyle().set("width", "auto");

    // anything below approx. 0.22rem will trigger the issue
    // 0.1875rem is from the Lumo Editor when setting "Space" from "Medium" to "Small"
    menuBar.getStyle().set("--lumo-space-xs", "0.1875rem");

    // other components don't seem to trigger the issue
    menuBar.addItem(new Avatar());

    return content;
  }

}
```
### Steps to reproduce

Simply open the above view in your browser.

### Environment

- Vaadin 23.0.0 (earlier versions had it too).
- Windows 10

### Browsers Affected

Tested and reproduced with Chrome and Firefox.

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by web-padawan** [comment]
Confirmed on master branch (23.0.1) where `width: 100%` is reverted, using web components only:

```html
<vaadin-horizontal-layout>
  <vaadin-menu-bar theme="tertiary-inline" style="--lumo-space-xs: 0.1875rem"></vaadin-menu-bar>
</vaadin-horizontal-layout>

<script type="module">
  import '@vaadin/avatar';
  import '@vaadin/horizontal-layout';
  import '@vaadin/menu-bar';

  const menuBar = document.querySelector('vaadin-menu-bar');
  menuBar.items = [
    { component: document.createElement('vaadin-avatar') },
  ];
</script>
```

The current behavior is clearly wrong. I will investigate to see why the overflow button is shown.
