### ISSUE TITLE
Regression: CRUD: Cannot edit an Item passed as a URL parameter

### ISSUE THREAD

**Issue by manolo** [vaadin/flow-components#2815]
### Description

Cannot use `BeforeEnterObserver` in my view for directly editing an item specified in the URL

### Expected outcome

Open the editor with the selected item

### Actual outcome

No editor opened (apparently it opens a dialog that closes inmediatelly)

### Live Demo (optional)

![crud](https://user-images.githubusercontent.com/161853/157051517-18ef74f8-4a01-49ee-8c1c-e532ce70f719.gif)

### Minimal reproducible example

[my-app.zip](https://github.com/vaadin/flow-components/files/8198340/my-app.zip)

### Steps to reproduce

1.- Go to https://start.vaadin.com (and authenticate)
2.- Add master-detail to the app
3.- Download the app and run it
4.- Replace `MasterDetailView.java` content with [1]
5.- Run the app `mvn run`
6.- Navigate to `http://localhost:8080/master-detail`
7.- Edit an item
8.- Reload the page `Cmd+R` 

[1]
```
@PageTitle("Master Detail")
@Route(value = "master-detail/:samplePersonID?/:action?(edit)", layout = MainLayout.class)
@Uses(Icon.class)
public class MasterDetailView extends Div implements BeforeEnterObserver {

    private final String SAMPLEPERSON_ID = "samplePersonID";
    private final String SAMPLEPERSON_EDIT_ROUTE_TEMPLATE = "master-detail/%s/edit";

    private Crud<SamplePerson> crud;
    private TextField firstName;
    private TextField lastName;
    private TextField email;
    private TextField phone;
    private DatePicker dateOfBirth;
    private TextField occupation;
    private Checkbox important;
    private FormLayout form;
    private BeanValidationBinder<SamplePerson> binder;
    private SamplePersonService samplePersonService;

    public MasterDetailView(@Autowired SamplePersonService samplePersonService) {
        this.samplePersonService = samplePersonService;
        addClassNames("crud-view", "flex", "flex-col", "h-full");
        
        // Configure Form
        binder = new BeanValidationBinder<>(SamplePerson.class);
        // Create Form
        createEditor();
        // Bind fields. This is where you'd define e.g. validation rules
        binder.bindInstanceFields(this);

		crud = new Crud<>(SamplePerson.class, new BinderCrudEditor<>(binder, form));
		
		crud.setDataProvider(new AbstractBackEndDataProvider<SamplePerson, CrudFilter>() {
			protected Stream<SamplePerson> fetchFromBackEnd(Query<SamplePerson, CrudFilter> query) {
				return samplePersonService.list(PageRequest.of(query.getPage(), query.getPageSize(),
						VaadinSpringDataHelpers.toSpringDataSort(query))).stream();
			}
			protected int sizeInBackEnd(Query<SamplePerson, CrudFilter> query) {
				return samplePersonService.count();
			}
		});
        
		crud.addDeleteListener(e -> {
			samplePersonService.delete(e.getItem().getId());
			UI.getCurrent().navigate(this.getClass());
		});
		crud.addSaveListener(e -> {
			samplePersonService.update(e.getItem());
			UI.getCurrent().navigate(this.getClass());
		});
		crud.addEditListener(e -> {
			UI.getCurrent().navigate(String.format(SAMPLEPERSON_EDIT_ROUTE_TEMPLATE, e.getItem().getId()));
		});
		crud.addCancelListener(e -> {
			UI.getCurrent().navigate(this.getClass());
		});
        add(crud);
        
    }
    
    @Override
    public void beforeEnter(BeforeEnterEvent event) {
        Optional<UUID> samplePersonId = event.getRouteParameters().get(SAMPLEPERSON_ID).map(UUID::fromString);
        if (samplePersonId.isPresent()) {
            Optional<SamplePerson> samplePersonFromBackend = samplePersonService.get(samplePersonId.get());
            if (samplePersonFromBackend.isPresent()) {
            	crud.edit(samplePersonFromBackend.get(), EditMode.EXISTING_ITEM);
            } else {
                Notification.show(
                        String.format("The requested samplePerson was not found, ID = %s", samplePersonId.get()), 3000,
                        Notification.Position.BOTTOM_START);
                // when a row is selected but the data is no longer available,
                // refresh grid
                event.forwardTo(this.getClass());
            }
        }
    }

    private void createEditor() {
        firstName = new TextField("First Name");
        lastName = new TextField("Last Name");
        email = new TextField("Email");
        phone = new TextField("Phone");
        dateOfBirth = new DatePicker("Date Of Birth");
        occupation = new TextField("Occupation");
        important = new Checkbox("Important");
        form = new FormLayout(firstName, lastName, email, phone, dateOfBirth, occupation, important );
    }
}

```

### Environment

- Version of the component / Vaadin platform. 23.0.0

**Comment by manolo** [comment]
After further investigation, there are two issues here that can be reproduced in bakery:

*NOTE*: I needed npm 14 in order not to have problems when running old vaadin versions.


### Normal behavior 
```
git clone git@github.com:vaadin/bakery-app-starter-flow-spring.git
cd bakery-app-starter-flow-spring
git checkout v14
mvn -Dpnpm.enable=true
```
![1](https://user-images.githubusercontent.com/161853/157219611-b1c6db65-d2d6-4a2b-a2d6-4fe0ca387919.gif)

### Regression 1 (missing components in dialog)
```
rm -rf package.json *lock* node_modules/ 
mvn versions:set-property -Dproperty=vaadin.version -DnewVersion=14.6.7
mvn -Dpnpm.enable=true
```

In this case the problem is most probably because of changes in `crud-1.3.1` https://github.com/vaadin/web-components/pull/2254 https://github.com/vaadin/flow-components/issues/1794 

![2](https://user-images.githubusercontent.com/161853/157219637-3e677325-3d8b-45b2-bc1a-a74b7ae81d42.gif)

### Regression 2 (dialog autocloses)
```
rm -rf package.json *lock* node_modules/
git checkout .
git checkout v15
mvn -Dpnpm.enable=true
```
Not sure about what is the cause, but seems related to how bootstraps the dom in v15+

![3](https://user-images.githubusercontent.com/161853/157219668-27b7dd7c-f5a0-4759-af00-95d674c908ec.gif)

**Comment by vursen** [comment]
> Regression 1 (missing components in dialog)

Confirmed that the problem is reproducible in pretty much all the versions and it is indeed caused by https://github.com/vaadin/web-components/pull/2254. The main trouble is that the current CRUD's implementation doesn't teleport the new slotted elements in the case they are added after the overlay has been opened already. They only get teleported at the moment of opening the overlay.

> Regression 2 (dialog autocloses)

It is a known regression and there is already a separate ticket https://github.com/vaadin/flow-components/issues/2979 and a PR https://github.com/vaadin/web-components/pull/3648 (confirmed that it fixes the regression for the case of this ticket).
