### ISSUE TITLE
Validation message in CheckboxGroup does not appear directly on invalid selection and disappears when focusing out

### ISSUE THREAD

**Issue by RhonanMS** [vaadin/flow-components#2823]
### Description

Similar to the issue https://github.com/vaadin/vaadin-radio-button/issues/179 that affected RadioButtonGroups, the validation message for CheckboxGroups disappears when focusing out of the component. It also does not appear directly when an invalid selection is preselected after adding a Binder.

### Expected outcome

What did you expect to happen?

The validation message should appear directly if an invalid selection is done. It also should stay on-screen when changing focus from the CheckboxGroup. 

### Actual outcome

The validation message does not appear directly below a CheckboxGroup when an invalid selection is preset. It also disappears when focusing out of the CheckboxGroup.

### Minimal reproducible example

This is a sample code for the checkbox group.
```java
CheckboxGroup<String> cbg = new CheckboxGroup<>();
cbg.setItems("valid 1", "valid 2", "invalid");

Binder<AtomicReference<Set<String>>> cbgBinder = new Binder<>();
cbgBinder.forField(cbg)
		.withValidator(values -> !values.contains("invalid"), "This selection is invalid!")
		.bind(AtomicReference::get, AtomicReference::set);

cbg.select("invalid");

this.add(cbg, new TextField());
```

The following is a sample reference code for the behaviour of a RadioButtonGroup, which behaves differently:
```java
RadioButtonGroup<String> rbg = new RadioButtonGroup<>();
rbg.setItems("valid 1", "valid 2", "invalid");

Binder<AtomicReference<String>> rbgBinder = new Binder<>();
rbgBinder.forField(rbg)
		.withValidator(value -> !"invalid".equals(value), "Value is invalid")
		.bind(AtomicReference::get, AtomicReference::set);

rbg.setValue("invalid");

this.add(rbg, new TextField());
```

### Steps to reproduce

1. Create a CheckboxGroup and set items .
2. Add a binder that displays an error message when the invalid selection is selected.
3. Programmatically set an invalid selection
4. Change focus to the textfield, e.g. by clicking on it or by tabbing out.

### Environment

- vaadin-checkbox-flow (14.8.1) / Vaadin Flow 14.8.1
- Windows 10

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Safari (not tested)
- [x] Edge
- [ ] IE 11 (not tested)
- [ ] iOS Safari (not tested)
- [ ] Android Chrome (not tested)

**Comment by RhonanMS** [comment]
> I’m curious, and would like to know about the use case you have. When do you need to show a validation/error message on a Checkbox Group or a Radio Button Group?

Sure, no problem. Our use case is getting a customer's consent before a legally binding contract (e.g. an insurance). This can be done by either a checkbox (selected = customer consents, deselected = customer does not consent) or by two radio buttons ("I consent" / "I do not consent") and showing a validation message ("We need your consent before we can continue.") if the selected option is "no consent".

Our applications are currently working along different UI/UX designs, so both variants are required.

**Comment by jouni** [comment]
Okay, thanks a lot for the use case description! Makes perfect sense. So it’s basically a "required field" validation.

**Comment by RhonanMS** [comment]
Yep, exactly.

**Comment by juuso-vaadin** [comment]
There are other CheckboxGroup use cases in which hiding the error message when selection is present is problematic.
- Maybe poor design, but combination of selections may be invalid in some cases.
- CBG can have cross field validation with other form fields resulting it to become invalid.

Ideally the developer should have control to set the component in invalid state regardless if there is a selection or not.
