### ISSUE TITLE
Closing one of several stacked modal dialogs can cause all modal dialogs to be closed

### ISSUE THREAD

**Issue by willemv** [vaadin/flow-components#2845]
### Description

Since the fix for #2608 in Vaadin Flow 23.0.0.rc1, modal dialogs no longer behave correctly when there are multiple on screen.

In this situation, calling `close()` on one of the modal dialogs can cause all dialogs to be closed, somehow.

You can find a reproduction project here: https://github.com/datadobi/vaadin-repro-modal-dialogs

### Expected outcome

Calling `close()` on a modal dialog closes only _that_ dialog.

### Actual outcome

Other modal dialogs are closed as well.

### Minimal reproducible example

https://github.com/datadobi/vaadin-repro-modal-dialogs

### Steps to reproduce

See the repro project:
* create one modal dialog but don't `open()` it yet
* immediately create another modal dialog, and `open()` that
* `open()` the first dialog
* sometime later, in response to a background event, `close()` the second dialog and show a third dialog

Result: all three dialogs are closed, even though we would expect only the second dialog to close.

### Environment

- Version of the component / Vaadin platform: 23.0.1
- OS: any 

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge

**Comment by willemv** [comment]
Note: in our project we event get additional client-side errors, completely freezing the application. I haven't been able to reproduce that in the standalone project, but I think this is closely related.

The client-side error we get is this one:
```
The error has occurred in the JS code: '$0, $1, $2, return (function() { this.$.overlay.$.overlay.style[$0]=$1}).apply($2)'
```

I think this JS execution is triggered from this side on the `Dialog` flow java class : https://github.com/vaadin/flow-components/blob/38f33a0e2b5ff869781603c7feb13686ba7754fa/vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java#L691

**Comment by sissbruecker** [comment]
Simplified reproduction:
```java
Dialog firstDialog = new Dialog(new Span("First"));
firstDialog.setWidth("400px");

NativeButton close = new NativeButton("Close", e-> {
    firstDialog.close();
});
Dialog secondDialog = new Dialog(close);
secondDialog.setWidth("200px");

NativeButton open = new NativeButton("Open", e -> {
    firstDialog.open();
    secondDialog.open();
});
add(open);
```

**Comment by jouni** [comment]
Ideally, modal dialogs are always on top of non-modal dialogs. I would consider anything else a bug, but perhaps this has been feature until now?

**Comment by jouni** [comment]
Yeah, changing this behavior sounds a bit risky.

**Comment by sissbruecker** [comment]
After spending some more time on this I think we should at least restore the behavior for modal dialogs. It's unfortunate that opening without manually adding to the UI works differently now, and I assume that most developers will use that approach. For opening non-modal dialogs on top of modal ones we can consider that an edge-case and document the behavior in the code, and maybe log a warning that you should explicitly add it to some component if a server-side modal exists.

**Comment by TatuLund** [comment]
> maybe log a warning that you should explicitly add it to some component if a server-side modal exists.

This will help greatly the code refactoring process.

Also some documentation needs to be added here: https://vaadin.com/docs/latest/upgrading/?from=14&to=23&isFlow=true&isFusion=true&isSpring=true&isTypeScript=true&isCustomStyling=true&isInstructionsDisplayed=true

**Comment by TatuLund** [comment]
I checked Dialog implementation. It would not be big effort either

1. Make setModality protected (and also change setModal to use it), so that one can extend Dialog and disable server side modality feature if so needed. This will make certain Vaadin 14 -> 23 migrations considerably easier.

or 

2. Or change setModal API to use enums e.g. CLIENT_SERVER, CLIENT, NONE and deprecate the old boolean API. This also would allow little bit smoother backwards compatibility.

**Comment by sissbruecker** [comment]
> I think we should at least restore the behavior for modal dialogs

We discussed this and for now we'll leave the behavior as is. It would be confusing if one type of dialog gets added as a child of a previous dialog, and gets removed together with the previous dialog, while another type of dialog does not. Instead we'll document the behavior in the component docs, and in the upgrade guide.

While I like the idea of logging a hint for developers that upgrade, I'm not sure how we would distinguish between providing helpful hints for developers upgrading to 23, and spamming logs for developers that just started on 23. The only solution I can think of is:
- when a dialog is opened, without adding it explicitely to the UI before
- and a modal dialog is already opened
- log a warning that the new dialog will be added as child of the previous one, discourage opening nested dialogs without explicitely adding them to the UI, and recommend to explicitely add it to the page, or the previous dialog

But even that could be annoying, if you are fine with dialogs just being nested.

**Comment by sissbruecker** [comment]
> I checked Dialog implementation. It would not be big effort either
> 
>     1. Make setModality protected (and also change setModal to use it), so that one can extend Dialog and disable server side modality feature if so needed. This will make certain Vaadin 14 -> 23 migrations considerably easier.
> 
> 
> or
> 
>     2. Or change setModal API to use enums e.g. CLIENT_SERVER, CLIENT, NONE and deprecate the old boolean API. This also would allow little bit smoother backwards compatibility.

@TatuLund 

Sure, you can file an enhancement about this to make upgrading easier. Alternatively I wonder if it shouldn't be possible to disable the whole feature in Flow instead.
