### ISSUE TITLE
Unify copyright headers and update year to 2022

### ISSUE THREAD

**Issue by web-padawan** [vaadin/flow-components#2896]
## Description

The license header comments are inconsistent: some of them use 2022 while others do not.

The year has been updated by https://github.com/vaadin/flow-components/pull/2470 but that PR did not cover some components.

### Correct header

Uses `Copyright 2000-2022 Vaadin Ltd.`

https://github.com/vaadin/flow-components/blob/bc8342debceb06d5944467bcdb187fd28536fbc8/vaadin-accordion-flow-parent/vaadin-accordion-flow/src/main/java/com/vaadin/flow/component/accordion/Accordion.java#L8

### Incorrect header

Uses `Copyright (C)` and some extra characters

https://github.com/vaadin/flow-components/blob/bc8342debceb06d5944467bcdb187fd28536fbc8/vaadin-app-layout-flow-parent/vaadin-app-layout-flow/src/main/java/com/vaadin/flow/component/applayout/AppLayout.java#L8-L12

## Proposed changes

1. Remove `(C)` to make further "find & replace" updates easier
2. Remove extra characters such as `#%L` and `%%`
3. Remove component names e.g. `Vaadin App Layout`, `Vaadin Crud` etc
4. Use `Vaadin Ltd.` with a dot instead of `Vaadin Ltd`

**Comment by krissvaa** [comment]
@web-padawan 
There is different starting years. Should all start from  2000 or leave those as they are?  
`* Copyright 2000-2022 Vaadin Ltd.`
vs 
`Copyright 2022 - 2022 Vaadin Ltd.`

example:
https://github.com/vaadin/flow-components/blob/bc8342debceb06d5944467bcdb187fd28536fbc8/vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/Map.java#L5-L10

**Comment by web-padawan** [comment]
> Should all start from 2000 or leave those as they are?

Let's leave them as they are. We also have different starting years in the web components monorepo.
Using `2000` as a starting point is apparently copied from Flow where it makes more sense.
