### ISSUE TITLE
[map] add styleable label to MarkerFeature

### ISSUE THREAD

**Issue by jgoderbauer** [vaadin/flow-components#2898]
### Describe your motivation

When there are several markers at the same time visible, it is hard for the end user to see what a marker is actually representing in the real world. 
While this can be improved with custom icons, its not enough if there are several markers closeby.

### Describe the solution you'd like

It should be possible to add a label to a marker.

Here is screenshot of how this could look alike:
![image](https://user-images.githubusercontent.com/54622999/160557770-b9f98e8b-8386-4f50-95ea-e1a6532507d8.png)
In this example there is a marker (blue dot) and above a label that provides information for that given marker.

The label also should be styleable via the flow api (provide information how to to style the label regards to the font, color, size, hover-color and so on and the relativ position to the marker like top, bottom, etc.). This is necessery to keep a consitant look of the marker and it's label.

What may be a challenge is the position (x,y, and z) of the label, especially when several labels are overlapping.

### Describe alternatives you've considered

Maybe it would be better if the solution is: create and add a Label to _any_ Feature (via the flow api).

### Additional context

Example of this may could be done in OpenLayers (but maybe there is a better way?)

```javascript
var iconFeature = new Feature({
  geometry: new Point([0, 0]),
  name: 'Water',
});

var vectorSource = new VectorSource({
  features: [iconFeature],
});
 vectorSource.on('addfeature', function() {
  map.getView().fit(vectorSource.getExtent());
}); 

var iconStyle = new ol.style.Style({
        image:  new ol.style.Circle({
            radius: 6,
            stroke: new ol.style.Stroke({
                color: '#fff'
            }),
            fill: new ol.style.Fill({
                color: '#3399CC'
            })
        })
    });
var labelStyle = new ol.style.Style({
  text: new ol.style.Text({
    font: '12px Calibri,sans-serif',
    overflow: true,
    fill: new ol.style.Fill({
      color: '#000'
    }),
    stroke: new ol.style.Stroke({
      color: '#fff',
      width: 3
    }),
    offsetY: -12
  })
});
var style = [iconStyle, labelStyle];
var vectorLayer = new VectorLayer({
  source: vectorSource,
  style: function(feature) {
        labelStyle.getText().setText(feature.get('name'));
        return style;
      }
});

var map = new Map( {
        target: 'map',
        layers: [
          new ol.layer.Tile({
            source: new ol.source.OSM()
          }),
          vectorLayer
        ],
        view: new ol.View({
          center: [0, 0],
          zoom: 6
        })
      });
```

**Comment by sissbruecker** [comment]
@PhoenixGody Thanks for reporting this and the other well written map enhancements. However for this ticket specifically it's not 100% clear for me what you want to accomplish, and it might be the same for other developers that might want to request such an enhancement or maybe vote for it. I think it would be helpful if you could attach an image / mockup that demonstrates what you want to accomplish.

**Comment by sissbruecker** [comment]
Thanks!
