### ISSUE TITLE
Add missing theme variants enum to GridPro

### ISSUE THREAD

**Issue by web-padawan** [vaadin/flow-components#2925]
### Description

Add `GridProVariant` enum that would contain all the `Grid` variants plus the following (Lumo only):

- [`highlight-editable-cells`](https://github.com/vaadin/web-components/blob/531a82cb01593dbb57d917684e2d71902e176147/packages/grid-pro/theme/lumo/vaadin-grid-pro-styles.js#L32)
- [`highlight-read-only-cells`](https://github.com/vaadin/web-components/blob/531a82cb01593dbb57d917684e2d71902e176147/packages/grid-pro/theme/lumo/vaadin-grid-pro-styles.js#L44)

Also, override `addThemeVariants` and `removeThemeVariants` methods to use this enum.

**Comment by rolfsmeds** [comment]
Here's a branch with documentation for these: https://github.com/vaadin/docs/commit/e9e5eccd397b22c1fb1d7c02a2815117cc7e3ecc
Component samples are still missing there though.
