### ISSUE TITLE
Document Java API for Lumo utility classes

### ISSUE THREAD

**Issue by web-padawan** [vaadin/flow-components#2927]
### Description 

We need to update existing documentation: https://vaadin.com/docs/latest/ds/foundation/utility-classes

There needs to be a new section with a code example of using Java API.
It needs to contain `since` admonition to explain that this feature is only available since Vaadin 23.1

**Comment by rolfsmeds** [comment]
Would probably make sense to add a column to the existing listing, next to the CSS classname column, for listing the Java constants.
