### ISSUE TITLE
TreeGrid: rendering and selection breaks if two beans have the same toString() values

### ISSUE THREAD

**Issue by drewharvey** [vaadin/flow-components#2938]
### Description

Vaadin 22.0.10

If multiple items in a TreeGrid have equal `toString()` output values it causes the following issues:
 - Click one item selects all of them
 - Only one of the items gets rendered (others are blank)

_Note: I have confirmed this happens even if the items have different `hashCode` and are not equal based on the `equals` method._

### Live Demo (optional)

Demo shows how one of the items does not render and selecting one row selects both.  See the code example below.

![treegrid-tostring-issue](https://user-images.githubusercontent.com/2496955/160181138-5af93e3b-7590-4289-b3f7-2b00f0cd7b01.gif)

### Minimal reproducible example

UI:
```
TreeData<DummyTreeData> data = new TreeData<>();
data.addRootItems(
        new DummyTreeData("Tim", true),
        new DummyTreeData("Tim", false));

TreeGrid<DummyTreeData> grid = new TreeGrid<>();
grid.addComponentHierarchyColumn(i -> new Label(i.getName()));
grid.addColumn(DummyTreeData::isSmart);

grid.setTreeData(data);
grid.setSelectionMode(Grid.SelectionMode.MULTI);

add(grid);
```

Bean:
```
public static class DummyTreeData {
    private String name;
    private boolean isSmart;

    public DummyTreeData(String name, boolean isSmart) {
        this.name = name;
        this.isSmart = isSmart;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public boolean isSmart() {
        return isSmart;
    }

    public void setSmart(boolean smart) {
        isSmart = smart;
    }

    @Override
    public String toString() {
        if (name != null)
            return name;
        return "";
    }
}
```

**Comment by vursen** [comment]
Based on what @TatuLund said, this behavior can be considered expected. If you wish to override `toString()`, you have to guarantee that it will return a unique value for each record. In your example, it returns the same "Tim" identifier for both records. 

It is expected behavior, so I'm closing the issue.
