### ISSUE TITLE
[context-menu] ContextMenu TS example is broken on iOS using Vaadin 23

### ISSUE THREAD

**Issue by vges** [vaadin/flow-components#2951]
### Description

A long touch pressure in a Grid Item under Vaadin 23 displayed on iOS  has no effect - in particular, a context menu is not displayed when pressing the item. This behavior is reproducible on an iPad with iPadOS 15.4. With Vaadin 14 on iOS this works fine, the same goes for an Android device both for Vaadin 14 and Vaadin 23.

### Expected outcome

The display of the Context Menu.

### Actual outcome

Context Menu is not shown.

### Minimal reproducible example

Try the Context Menu example on Vaadin documentation site [https://vaadin.com/docs/latest/ds/components/grid#context-menu](url) with an iOS device.

To reproduce, take an iOS device and

1. try a  long touch on an item  with Docs set to V23 
2. compare with long touch on an item  Docs set to V14 

### Environment

- V23.0.1
- iPadOS 15.4.

### Browsers Affected

checked with: 

Firefox, iOS Safari

**Comment by sissbruecker** [comment]
Can confirm this issue with an iPhone, iOS 15.2.1 and Safari. In V23 the context menu does show up, but it's empty:
![IMG_0141](https://user-images.githubusercontent.com/357820/164031126-496432be-092e-4659-add0-e90951679b83.PNG)

Compared to V14:
![IMG_0142](https://user-images.githubusercontent.com/357820/164031174-d49af71f-ee9c-42a0-bea6-63ed7cbacd21.PNG)
