### ISSUE TITLE
grid scrollbar problem when grid inside sliders on Firefox

### ISSUE THREAD

**Issue by garehira** [vaadin/flow-components#2952]
### Description

When dragging the slider, mouseposition and slider position are not in sync, see
https://apps.xerai.biz/cloud/public/screenshot/VaadinGridScrollBug.mp4

Error happens only on Firefox. This did work with 22.0.7, now on 23.0.2 error happed.

Vaadin
    23.0.2
Flow
    23.0.2
Java
    AdoptOpenJDK 11.0.11
OS
    amd64 Windows 10 10.0
Browser
    Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0

**Comment by sissbruecker** [comment]
Could not reproduce this in a basic example with Windows 10, Firefox 99.

Please provide a minimal reproducable example of the issue that we can test.

**Comment by garehira** [comment]
Unfortunately, I didnt get the time from management to dive into this.
