### ISSUE TITLE
display: block in vaadin-grid-tree-toggle prevents content form using the full width

### ISSUE THREAD

**Issue by simasch** [vaadin/flow-components#2956]
Hi,

We use addComponentHierarchyColumn and the fix for this issue https://github.com/vaadin/flow-components/issues/2429 broke our code.

This is the problematic CSS

```
slot {
          display: block;
          overflow: hidden;
          text-overflow: ellipsis;
        }

```

Now it's no longer possible to use the full width.
`width: 100%; ` has no effect.

**Comment by sissbruecker** [comment]
@simasch Can you please provide a minimal reproducable example, and maybe a screenshot to demonstrate the problem? It's not clear what you want to achieve, and what isn't working.

**Comment by yuriy-fix** [comment]
Closing as stale.
Feel free to provide more details in the comments, so we will re-open the issue.
