### ISSUE TITLE
[dialog] Dialog immediately closes when opened in view initialization

### ISSUE THREAD

**Issue by sissbruecker** [vaadin/flow-components#2979]
### Description

Explicitly adding a dialog to the UI, and then opening it, all within the constructor of a view, causes the dialog to briefly show up, and then close immediately. Both modal and non-modal dialogs are affected.

Interestingly, not adding the dialog to the UI and opening works. This is also reproducable in 22, so this is not a regression from the server-side modality feature.

### Expected outcome

The dialog should stay open unless closed by the user, or programmatically.

### Actual outcome

The dialog closes immediately, on its own.

### Minimal reproducible example

```java
@PageTitle("Dialog")
@Route(value = "dialog", layout = MainLayout.class)
public class DialogView extends Div {
    public DialogView() {
        Dialog dialog = new Dialog(new Span("Dialog"));
        add(dialog);
        dialog.open();
    }
}
```

### Steps to reproduce

1. Open the example above
2. Notice how the dialog briefly shows up, and then closes immediately

### Environment

- [x] 23.0.4
- [x] 22.0.12
- [ ] 14.8.7

**Comment by sissbruecker** [comment]
This is caused by vaadin/router of all things. What's happening is basically:
- Flow application renders into the body
- As part of that, dialog gets created, `opened` is set to `true`, dialog is added to DOM, dialog opens overlay
- After that vaadin-router renders and relocates the root node of the Flow app to the outlet (might not be 100% correct, but in any case, the root node of the app is moved for some reason) (https://github.com/vaadin/router/blob/01ec83e31e639192aebdfa1b620ec62b3a57328d/src/router.js#L792)
- That means the root node, and the dialog in it, will be disconnected, before being added to the new parent node
- As part of that the disconnected callback in dialog is called, which closes the dialog: https://github.com/vaadin/web-components/blob/dc8cca223fd1747c7a34755238cc746c935191d9/packages/dialog/src/vaadin-dialog.js#L570-L573

Hard to say whether that is a problem with Flow, or the router. On the other hand the dialog closing because it, or its parent node, is moved to another node doesn't seem right.

**Comment by web-padawan** [comment]
Note, the same problem applies to `LoginOverlay`: #2087
