### ISSUE TITLE
[time-picker] Provide event listener for opened change

### ISSUE THREAD

**Issue by SonReimer** [vaadin/flow-components#2993]
## Motivation

The original motivation comes from implementing a workaround for time picker to force server-side validation in case the user entered a value that does not pass client-side validation. In that case the value will not be changed on the server, but the input is also not marked as invalid. The workaround involves listening for events that indicate an input value change (such as opened changed), and then use executeJs to retrieve the client validation state, and set the component's validity based on that.

## Proposed solution

The Flow TimePicker should have an API for listening to opened changed events from the time pickers internal combo box.

The request above has been adapted according to the discussion below, original request:
>It would help a lot to have access to the internal <vaadin-time-picker-combo-box> element via a corresponding java-Component or an alternative way.
>I wanted to apply the workaround mentioned by @mvysny in issue https://github.com/vaadin/flow-components/issues/2176 to TimePicker, but i can't add a PropertyChangeListener to the combo-box - opened property which I need for revalidation when combo-box is closed.

**Comment by SonReimer** [comment]
Other issue with time-picker:
When initially typing invalid string as 'fkfdgk' it is accepted with no error, when opening combo-box, selecting a value, and typing 'fkfdgk' again, it is removed, then again typing 'fkfdgk' it is accepted again.

It seems to me as if an invalid String is only removed after valid value from the combobox was filled in.

Setting setPreventInvalidInput(true) and setPattern('[0-9][0-9]:[0-9][0-9]') does not change the described behavior above.

**Comment by rolfsmeds** [comment]
Actually that internal combo box is no longer there after refactoring the component in V22, so that's not going to happen.

I think a better approach is to try to address the underlying issue. In the meantime we'll see if we can find a different way to achieve the same workaround.

**Comment by SonReimer** [comment]
But what is it, I see here:
![grafik](https://user-images.githubusercontent.com/46707079/162943037-0c2a5dbf-9c21-46cb-96a5-3a61a8a84290.png)
![grafik](https://user-images.githubusercontent.com/46707079/162943350-16842766-08d6-4425-9312-4bd514f8b286.png)
![grafik](https://user-images.githubusercontent.com/46707079/162943584-11f7ecdd-2227-455e-adcf-fb0475ce4cbc.png)

**Comment by jouni** [comment]
Looks like pre Vaadin 22. The component implementation was refactored in v22.

**Comment by rolfsmeds** [comment]
Ah, apologies, I misread your original description. There is still an element called `<vaadin-time-picker-combo-box>` even though the Time Picker no longer contains an actual Combo Box component. Providing API access to internal elements like that is still risky as it either prevents us from modifying the component's implementation later, or forces us to introduce breaking changes at some point, which will then break your application. So we'll see if we can find an alternate solution for you.

**Comment by jouni** [comment]
> The same I see on https://vaadin.com/docs/latest/ds/components/time-picker

Ah, my mistake, I was not looking carefully enough.

**Comment by sissbruecker** [comment]
Updated the description to reflect the discussion and clarify the use-case.

**Comment by web-padawan** [comment]
Closing in favor of #5419 which is essentially a duplicate.
