### ISSUE TITLE
VaadinIcon not showing up after upgrading from 14.x to 23.0.4

### ISSUE THREAD

**Issue by mikethomas77055** [vaadin/flow-components#3001]
### Describe the bug

I followed the guide for upgrading from Vaadin 14.x to 23.0.4.  Since upgrading none of my icons are showing up.  I have various grids that all use the same shared method to add an edit button to each row.  I have another grid that uses a paper-clip icon.  None are showing up.  I've played around with adding icons in other locations, with the same result.  Here's a screenshot of the code that is shared to add the icons where needed.

![image](https://user-images.githubusercontent.com/38060296/162485404-f72fed7e-25f3-4694-9155-86972a28d515.png)

here's what I get in the browser.  The box to the left of "Acuity" should be an edit icon.

![image](https://user-images.githubusercontent.com/38060296/162486243-235ec859-71fe-4358-9dfb-b6987f9dbffa.png)

### Expected-behavior

icons show up when added to the screen.

### Reproduction

I'm embedding icons in buttons.  So "new Button(new Icon(VaadinIcon.EDIT))" should reproduce this.  See code example below.

![image](https://user-images.githubusercontent.com/38060296/162485538-41079df0-f614-4310-b05a-1c979826c9d3.png)

### System Info

Server 2019
Vaadin 23.0.4
Tried with Chrome/Edge.

**Comment by TatuLund** [comment]
I can't reproduce this. 

Plain version works

```
        Button btn = new Button();
        btn.setIcon(new Icon(VaadinIcon.PAPERCLIP));
        add(btn);
```
 
 Also using the newest version 4.0.0 of the download button wrapper works
 
```
         Button btn = new Button();
        btn.setIcon(new Icon(VaadinIcon.PAPERCLIP));
        FileDownloadWrapper btnWrapper = new FileDownloadWrapper(new StreamResource("hello.txt", () -> new ByteArrayInputStream("Lorem ipsum".getBytes())));
        btnWrapper.wrapComponent(btn);
```

![image](https://user-images.githubusercontent.com/14309836/162679092-80bf062d-1b99-4791-bef1-4f7bef8da07e.png)

**Comment by mikethomas77055** [comment]
I resolved by node and frontend issues, and it's working as expected.  Sorry for the mixup.
