### ISSUE TITLE
Custom component in GridPro should support HasValueAndElement instead of AbstractField

### ISSUE THREAD

**Issue by probert94** [vaadin/flow-components#3023]
### Describe your motivation

I would like to use custom editor components in the `GridPro` and some of those components extend `Composite` or `AbstractCompositeField`. Unfortunately the `GridPro` only accepts `AbstractField` as custom editor component.

### Describe the solution you'd like

After taking a look at the source, it seems like `HasValueAndElement` could be used instead of `AbstractField`.
`HasValueAndElement` supports all the needed methods (`getElement`, `getValue`, `setValue`) and as it is an interface, it could be used for every component.
As `AbstractField` already implements `HasValueAndElement`, the change should be compatible with the current version.

### Describe alternatives you've considered

The only alternative seems to be to rewrite all the components to extend `AbstractField`. In the worst case this is not even possible, as the components might come from a third party library.

**Comment by juuso-vaadin** [comment]
A customer has requested this in order to be able to use LookupField add-on in GridPro.
