### ISSUE TITLE
[grid-pro] CellEditStartedEvent should have a getter for editor component.

### ISSUE THREAD

**Issue by TatuLund** [vaadin/flow-components#3042]
### Describe your motivation

I can write code that needs reference to editor when I am using custom editor in the edit column.

    // Use custom editor
    EmailField emailField = new EmailField();
    emailField.setWidth("100%");
    emailField.addThemeName("grid-pro-editor");
    grid.addEditColumn(Person::getEmail)
            .custom(emailField, (item, newValue) -> {
                item.setEmail(newValue);
            }).setHeader("E-mail ");
    // Use edit started listener to set the field conditionally enabled
    grid.addCellEditStartedListener(event -> {
        if (!event.getItem().isSubscriber()) {
            emailField.setReadOnly(true);
        } else {
            emailField.setReadOnly(false);
        }
    });

Full code here: https://cookbook.vaadin.com/grid-pro-conditional-edit

However I can't do that with built in editors.

### Describe the solution you'd like

A method like `CellEditStartedEvent#getComponent()` which returns a reference to editor component used.

**Comment by rolfsmeds** [comment]
This would be very difficult since the built-in editors are not reflected on the server side at all. I think adding a built-in feature for dynamically determining cell editability, as proposed in https://github.com/vaadin/web-components/issues/3464 would be a better idea.

**Comment by rolfsmeds** [comment]
Closing in favor of https://github.com/vaadin/web-components/issues/3464, please reopen if you feel that a different solution would provide better value or if I misunderstood the feature proposed here.
