### ISSUE TITLE
Notification showing multiple times when auto-added to reused modal

### ISSUE THREAD

**Issue by probert94** [vaadin/flow-components#3085]
### Description

I have a modal dialog that I reuse, so I call `open` and `close` multiple times.
Now I added a `Notification` that is shown, when I open the `Dialog` in a certain context.
When I close the `Dialog` before the `Notification` is closed, the `Notification` is shown everytime I open the `Dialog` again.
To fix that, I have to wait for the `Notification` to close and close the `Dialog` after that.
The reason for this is, that the `Notification` is removed from the `Dialog` in the `opened-changed` listener. However, that listener is never notified, as the parent is already detached when it is fired.

The same problem _might_ occur in other circumstances, whenever an overlay is added to a modal and the modal is closed before the child-overlay is closed.

### Expected outcome

The `Notification` should not be shown when I reopen the dialog

### Minimal reproducible example

```java
public class MainView extends VerticalLayout {
    private Dialog formDlg;
    private NumberField tfId;
    private TextField tfName;
    public MainView() {
        Grid<Person> grid = new Grid<>();
        grid.addColumn(p -> p.id).setHeader("ID");
        grid.addColumn(p -> p.name).setHeader("Name");
        grid.addColumn(new ComponentRenderer<>(p -> new Button(VaadinIcon.EDIT.create(), e -> {
            getOrCreateDialog(p).open();
            if (p.id == 1) {
                Notification.show("Cannot edit " + p.name);
                tfId.setReadOnly(true);
                tfName.setReadOnly(true);
            }
        })));
        grid.setItems(
            new Person(1, "John Doe"),
            new Person(2, "Jane Doe"),
            new Person(3, "Joe Ordinary"),
            new Person(4, "Mary Major")
        );
        add(grid);
    }
    private Dialog getOrCreateDialog(Person p) {
        if (formDlg == null) {
            formDlg = new Dialog();
            formDlg.add(new VerticalLayout(
                tfId = new NumberField("ID"),
                tfName = new TextField("Name")
            ));
        }
        tfId.setReadOnly(false);
        tfName.setReadOnly(false);
        tfId.setValue((double)p.id);
        tfName.setValue(p.name);
        return formDlg;
    }
    private static class Person {
        private final int id;
        private final String name;

        private Person(int id, String name) {
            this.id = id;
            this.name = name;
        }
    }
}
```

### Steps to reproduce

1. Add the above code to the main view of a new vaadin starter
2. Open the app and click the "edit" button on the first item in the grid. The `Notification` will be shown.
3. Close the dialog before the `Notification` disappears.
4. Open the `Dialog` by clicking the "edit" button on another item, the same `Notification` will be shown again.
5. Wait until the `Notification` disappears and close the `Dialog`.
6. Open the `Dialog` by clicking the "edit" button on another item. This time the `Notification` won't be shown.

### Environment

Vaadin version(s): 23.0.6
OS: Windows 10 x64

**Comment by vursen** [comment]
Simplified the reproduction example:

```java
package com.example.application.views;

import com.vaadin.flow.component.dialog.Dialog;
import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.component.html.NativeButton;
import com.vaadin.flow.component.notification.Notification;
import com.vaadin.flow.router.Route;

public class MainView extends Div {
    public MainView() {
        Dialog dialog = new Dialog();
        dialog.add("Dialog 1");

        NativeButton button1 = new NativeButton("Open Dialog and Notification", (event) -> {
            dialog.open();
            Notification.show("Notification");
        });

        NativeButton button2 = new NativeButton("Open Dialog", (event) -> {
            dialog.open();
        });
        add(button1, button2);
    }
}
```

1. Click the "Open Dialog and Notification" button.
2. Close the dialog before the notification hides.
3. Click the "Open Dialog" button.
