### ISSUE TITLE
LitRenderer getValueProviders returns an empty map even if ValueProviders have been added

### ISSUE THREAD

**Issue by drtadmin** [vaadin/flow-components#3086]
### Describe the bug

I am not sure if this is by design, but if you add ValueProviders to a LItRenderer with the "withProperty" method, those ValueProviders are added to a local private map in the LitRenderer instance.  However, if you subsequently call "getValueProviders", the method returns an empty map.  This is because the parent class "getValueProviders" method is not overridden to report the correct map.

### Expected-behavior

getValueProviders in LitRender should accurately report the ValueProviders that have been added to the LitRenderer in an unmodifiable map.

### Reproduction

Create a LitRenderer using LitRenderer.of(....), add a ValueProvider using the "withProperty("name", valueprovider) method, then call "getValueProviders" on that LitRenderer.  The get method will return an empty map, but there should be a value provider returned.

### System Info

Windows 10, Vaadin 23.0.6

**Comment by yuriy-fix** [comment]
Dear @drtadmin, could you please share a use-case where you need this?

**Comment by jcgueriaud1** [comment]
The in memory sorting is not working when you are using a LitRenderer with the correct property, for example:
```
LitRenderer<Person> personLitRenderer = LitRenderer.<Person>of(
                "<span>${item.name}</span>")
        .withProperty("name", Person::getName);
if (personLitRenderer.getValueProviders().isEmpty()) {
    System.out.println("Is it normal ?");
}
Grid.Column<Person> personNameColumn = grid.addColumn(personLitRenderer).setHeader("Name Sort OK");
personNameColumn.setSortProperty("name"); // not working for in Memory
// You need to add your own value provider: c.setComparator(Person::getName);
```

According to this code, it _should_ work this way (if the Map valueProviders is filled correctly, I think the name will be picked to set the comparator but it's hard to be sure without building and running a "fixed" example):
https://github.com/vaadin/flow-components/blob/master/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java#L1898

I don't think if it's documented, so I'm not sure of the _correct_ behavior.

It's a bit confusing to see that the Renderer.java class is mostly deprecated except getValueProviders() (but all the methods to fill this Map are deprecated). Should it be deprecated?

**Comment by jcgueriaud1** [comment]
```
        Comparator<T> combinedComparator = (a, b) -> 0;
        Comparator nullsLastComparator = Comparator
                .nullsLast(Comparator.naturalOrder());
        for (String sortProperty : matchingSortingProperties) {
            ValueProvider<T, ?> provider = valueProviders.get(sortProperty);
            combinedComparator = combinedComparator.thenComparing((a, b) -> {
                Object aa = provider.apply(a);
                if (!(aa instanceof Comparable)) {
                    return 0;
                }
                Object bb = provider.apply(b);
                return nullsLastComparator.compare(aa, bb);
            });
        }

```
I guess I'm wrong since the `combinedComparator` is not used at all in the method: https://github.com/vaadin/flow-components/blob/master/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java#L1898
