### ISSUE TITLE
Add the ability to get the filename from the Upload component on FileRejectedEvent

### ISSUE THREAD

**Issue by FollowSteph** [vaadin/flow-components#3087]
### Describe your motivation

The method `getFilename()` is available on the `SucceededEvent `but not the `FileRejectedEvent`. This would be very useful to be able to display an error message to let the user know which files failed. Yes it is displayed in the component but in my case I'm trying to separate out the progress bar because it's a button (the upload component) on the top of a grid where displaying the files uploaded, etc. is not necessarily appropriate. See this Stackoverflow question for more details: https://stackoverflow.com/questions/72006963/is-there-a-way-to-separate-out-the-progress-bar-from-the-upload-component-in-vaa

### Describe the solution you'd like

`FileRejectedEvent `adds the method `getFileName()` the same as `SucceededEvent `offers.

### Describe alternatives you've considered

There is currently no way to know what file failed to upload.

**Comment by yuriy-fix** [comment]
Could be related: https://github.com/vaadin/flow-components/issues/1328

**Comment by FollowSteph** [comment]
Yes it appears to be the same.
