### ISSUE TITLE
GridElement.getLastVisibleRowIndex() should return -1 on empty Grid

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow-components#3110]
### Description

I have an empty Grid with no items on the page; I'm calling `GridElement.getLastVisibleRowIndex()` on it. I'd expect the function to return `-1` indicating that there's no visible row; instead the function returns `0`.

### Expected outcome

`GridElement.getLastVisibleRowIndex()` should return `-1` if the grid is empty.

### Minimal reproducible example

```java
@Route("")
public class MainView extends VerticalLayout {

    public MainView() {
        Grid<String> grid = new Grid<String>();
        grid.setItems();
        grid.setId("grid");
        grid.addColumn(it -> it).setHeader("foo");
        add(grid);
    }
}
public class MainViewIT extends AbstractViewTest {

    @Test
    public void myTest() {
        GridElement grid = $(GridElement.class).first();
        System.out.println(grid.getLastVisibleRowIndex());
    }
}
```

### Steps to reproduce

1. Add the MainView class to Skeleton Starter Flow
2. Add MainViewIT class to Skeleton Starter Flow IT tests and run

### Environment

Vaadin version(s): 14.7.5
Reproduced on Firefox, untested on other browsers.

### Browsers

Firefox

**Comment by mvysny** [comment]
Workaround:
```java
public class MyGridElement extends GridElement {
    @Override
    public int getLastVisibleRowIndex() {
        return getRowCount() == 0 ? -1 : super.getLastVisibleRowIndex();
    }
}
```

**Comment by tomivirkki** [comment]
Thanks for letting us know @brunovianarezende. Closing the issue.

**Comment by TatuLund** [comment]
Fixed by this https://github.com/vaadin/flow-components/pull/5156
