### ISSUE TITLE
CustomField required indicator is not updated correctly

### ISSUE THREAD

**Issue by TatuLund** [vaadin/flow-components#3132]
### Description

CustomField Flow implementation does not use client side value at all. Thus the update of the has-value attribute done by web-component is not effective.

### Expected outcome

When setting/ inputing value to custom field required indicator should disappear in Vaadin 14. (Note from Vaadin 23.1 onwards expected outcome is to indicator to stay as behavior has been changed to be sticky)

### Minimal reproducible example

Use the code 

Workaround is to add value change listener to toggle the attribute.

```
@Route(value = "binder")
public class BinderDemoView extends VerticalLayout {
    private Binder<Pojo> binder = new Binder<>();
    private Pojo pojo;

    public BinderDemoView() {
        pojo = new Pojo("Pojo example", "value1", "value2");
        buildUI();
    }

    private void buildUI() {
        add(new Span("Binder demo"));

        CustomTextField name = new CustomTextField();
        name.setLabel("Name");
        CustomTextField field1 = new CustomTextField();
        field1.setLabel("Field 1");
        TextField field2 = new TextField();
        field2.setLabel("Field 2");

        add(name, field1, field2);

        binder.forField(name).bind(Pojo::getName, Pojo::setName);
        binder.forField(field1).asRequired("is Required").bind(Pojo::getField1,
                Pojo::setField1);
        binder.forField(field2).asRequired("is Required").bind(Pojo::getField2,
                Pojo::setField2);

        Button setBean = new Button("Set Bean", event -> {
            setBean();
        });

        add(setBean);
    }

    public void setBean() {
        binder.setBean(pojo);
    }

    public static class CustomTextField extends CustomField<String> {
        private TextField mainComponent = new TextField();

        public CustomTextField() {
            add(mainComponent);
            // Workaround
//            this.addValueChangeListener(event -> {
//                if (event.getValue() != null && !event.getValue().isEmpty()) {
//                    getElement().setAttribute("has-value", true);
//                } else {
//                    getElement().removeAttribute("has-value");
//                }
//            });
        }

        @Override
        public void setInvalid(boolean invalid) {
            super.setInvalid(invalid);
            mainComponent.setInvalid(invalid);
        }

        @Override
        protected String generateModelValue() {
            if (mainComponent.getValue().isEmpty()) {
                return null;
            }
            return mainComponent.getValue();
        }

        @Override
        protected void setPresentationValue(String newPresentationValue) {
            if (newPresentationValue == null) {
                newPresentationValue = "";
            }
            mainComponent.setValue(newPresentationValue);
        }
    }

    public static class Pojo {
        private String Name;
        private String field1;
        private String field2;

        public Pojo(String name, String field1, String field2) {
            Name = name;
            this.field1 = field1;
            this.field2 = field2;
        }

        public String getName() {
            return Name;
        }

        public void setName(String name) {
            Name = name;
        }

        public String getField1() {
            return field1;
        }

        public void setField1(String field1) {
            this.field1 = field1;
        }

        public String getField2() {
            return field2;
        }

        public void setField2(String field2) {
            this.field2 = field2;
        }
    }
}
```

### Steps to reproduce

Use the above code to reproduce. Compare behavior of the TextField and CustomTextField to see the difference.

### Environment

Vaadin version(s): Vaadin 14.8

**Comment by TatuLund** [comment]
I made ticket about this. But then I become to second thoughts that is this a bug.

I could add checking of value being null in the CustomField to toggle has-value, but that is not perfect for all scenarios, as there are potentially other values that should be interpreted empty, but CustomField is having type T, and I can't assume anything else than null case.

This makes me think, that is this just a documentation issue and we should add just a note, that that updating of has-value attribute should be handled by developer based what is appropriate based on value type used.

**Comment by yuriy-fix** [comment]
`Custom-field` webcomponent toggles `has-value` attribute when its value changes (in [`value` observer](https://github.com/vaadin/vaadin-custom-field/blob/3676aef30dc1ac4843c692e1c6450ddb20619631/src/vaadin-custom-field.html#L191))
The value for `custom-field` is updated whenever `change` event is dispatched from [wrapped inputs](https://github.com/vaadin/vaadin-custom-field/blob/3676aef30dc1ac4843c692e1c6450ddb20619631/src/vaadin-custom-field.html#L44). 
`Custom-field` allows wrapping native inputs, so it cannot always rely on `value-changed`, moreover it allows wrapping inputs with other data types (i.e. `date-picker`), so it cannot always rely on `input` event either.

In case of `text-field`, it's toggling `has-value` also when its value changes, however for `text-field` value changes on [`input` event](https://github.com/vaadin/vaadin-text-field/blob/e79c31879a53ab4a8759c9dd0224f7688112b74b/src/vaadin-text-field-mixin.html#L436).

Even without workaround applied the provided example follows the logic described above:

- `custom-field` (Field 1) receives `change` event and setting `has-value` when value is typed and input is blurred. 
- `text-field` (Field 2) setting `has-value` when value is typed.
 
![field](https://user-images.githubusercontent.com/29372419/168574446-2e5fd85c-f4be-48b6-a65d-da1d253fb26b.gif)

Written above is applied to Vaadin 14 version of components.

**Comment by TatuLund** [comment]
The documentation has been updated https://vaadin.com/docs/v14/ds/components/custom-field/#required-field-indicator-visibility
