### ISSUE TITLE
GridPro + Quarkus not working

### ISSUE THREAD

**Issue by AbdullahGheith** [vaadin/flow-components#3135]
### Description

I've setup a very basic quarkus project with nothing but a simple GridPro component.
The console gives alot of errors, including one saying to report the bug.

If i simply change the GridPro to Grid, it works.

### Expected outcome

I would expect the grid to appear

### Minimal reproducible example

N/A

### Steps to reproduce

1. Download the quarkus example code
2. Add gridpro component somewhere in your code
3. Build and run
4. Navigate to whereever the gridpro component is.
5. Nothing is the grids place.

### Environment

Vaadin version(s): 23
OS: Windows 11

**Comment by yuriy-fix** [comment]
@mshabarov , could you please help us reproducing the issue?

**Comment by mshabarov** [comment]
Might be the license issue. I'll try quarkus with grid pro on my side and get back to you soon.

**Comment by AbdullahGheith** [comment]
> Might be the license issue. I'll try quarkus with grid pro on my side and get back to you soon.

I am not sure if you mean theres a problem with my license, but i've since downloaded the spring boot starter project and copied the same gridpro code, and it works fine in spring.

**Comment by taefi** [comment]
@AbdullahGheith thanks for reporting this issue. 

The reason for this misbehavior is that GridPro is not present in the `jandex.idx` (`vaadin-core-jandex` dependency). Adding the following to the `application.properties` would alleviate the issue for now, until a patch comes out: 
```
quarkus.index-dependency.vaadin-grid-pro.group-id=com.vaadin
quarkus.index-dependency.vaadin-grid-pro.artifact-id=vaadin-grid-pro-flow
```

**Comment by AbdullahGheith** [comment]
Thank you. Both solutions work.
