### ISSUE TITLE
Cannot use Select in editable Grid

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/flow-components#3177]
### Description

When clicking on the select button inside of an editable grid, the select component opens and closes immediately

### Expected outcome

I would expect that the click event does not propagate (and the ItemClickEvent is not fired), so that the select remains open.

### Minimal reproducible example

```
    Binder<Bean> binder = new Binder<>(Bean.class);
    Select<String> select = new Select<>();
    select.setItems("foo", "bar");

    Grid<Bean> grid = new Grid<>();
    grid.addColumn(Bean::getValue).setEditorComponent(select);

    grid.addItemClickListener(ev -> grid.getEditor().editItem(ev.getItem()));
    binder.forField(select).bind(Bean::getValue, Bean::setValue);
    grid.getEditor().setBinder(binder);
    grid.setItems(new Bean());

    add(grid);
 ```
![select](https://user-images.githubusercontent.com/11554739/168116060-af50c515-a9ec-446e-8c04-f97f74c9d2db.gif)

### Steps to reproduce

1. Double click the item row in order to enter edition mode
2. Click the select button in order to open the overlay

### Environment

Vaadin version(s): 23.0.9

**Comment by web-padawan** [comment]
Confirmed, here is an updated example from Grid ITs that can be used for testing:

```java
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.component.select.Select;
import com.vaadin.flow.data.bean.Person;
import com.vaadin.flow.data.binder.Binder;
import com.vaadin.flow.data.renderer.TemplateRenderer;
import com.vaadin.flow.router.Route;

@Route("vaadin-grid/column-path")
public class ColumnPathPage extends Div {

    public ColumnPathPage() {
        Grid<Person> grid = new Grid<>();

        grid.setItems(new Person("Person 1", null, null, 42, null, null),
                new Person("Person 2", null, null, 42, null, null));

        Select<String> select = new Select<>();
        select.setItems("Person 1", "Person 2", "Person 3");

        grid.addColumn(Person::getFirstName)
                .setHeader("First name (editable)")
                .setEditorComponent(select);

        grid.addItemClickListener(ev -> grid.getEditor().editItem(ev.getItem()));
        Binder<Person> binder = new Binder<>(Person.class);
        grid.getEditor().setBinder(binder);

        add(grid);
    }
}
```

Note, the dropdown always closes when clicking toggle button, but not always when clicking input field:

![select-editor](https://user-images.githubusercontent.com/10589913/168255729-9d3be830-7137-487e-8cdd-f5d46908bad1.gif)

**Comment by simasch** [comment]
I have another issue that may be related.

If I add a `grid.getEditor().addOpenListener()` and have a Select in the Grid the open event is fired multiple times even if the editor is already open!

This was working in 14 but not in 23.
