### ISSUE TITLE
[spreadsheet] Merge cells functionality is not working correctly

### ISSUE THREAD

**Issue by DiegoCardoso** [vaadin/flow-components#3186]
### Description

_Found when migrating MergeTests from FW8 to flow-components_

It seems that the merge functionality is broken on Spreadsheet, when trying to merge/unmerge cells from the context menu.

At a first glance it looks like the state of merged cells is not being correctly saved because merging cells work only on the second try (and only if the cells are different from the first try). And because if this inconsistency, trying to unmerge cells lead to unexpected results, like other cells being unmerged instead of the ones currently selected.

https://user-images.githubusercontent.com/262432/168300853-3cde50b1-5afb-4cb9-b1ee-6e609ef5ad95.mp4

### Expected outcome

User is able to merge/unmerge cells as expected

### Minimal reproducible example

```java
var spreadsheet = new Spreadsheet();
add(spreadsheet);
```

### Steps to reproduce

1. Run the spreadsheet IT module with `mvn jetty:run`
2. Click on "Create new" button
3. Select two or more cells and then, click with the right button and select "Merge cells"
4. Repeat step (3) a few more times
5. Right click on a merged cell and select "Unmerge cells"
6. Repeat step (5) a few more times

### Environment

Vaadin version(s): 23.1-SNAPSHOT
OS: mac OS

### Browsers

Chrome, Edge

**Comment by manolo** [comment]
Seems some unitialised state in the server side the first time, see logs
```
[qtp1163471607-40] ERROR com.vaadin.flow.server.DefaultErrorHandler -
java.lang.IndexOutOfBoundsException: Index: -1, Size: 0
	at java.base/java.util.ArrayList.rangeCheckForAdd(ArrayList.java:788)
	at java.base/java.util.ArrayList.add(ArrayList.java:513)
	at com.vaadin.flow.component.spreadsheet.Spreadsheet.createMergedRegionIntoSheet(Spreadsheet.java:3330)
```
