### ISSUE TITLE
Default unique key provider in TreeGrid leaks memory

### ISSUE THREAD

**Issue by pepijnve** [vaadin/flow-components#3201]
### Description

When adding new items to a TreeGrid the default unique key provider will compute a new numeric id and store this in a HashMap using the item id as key. When removing that item again, the corresponding entry in the HashMap is never removed. A hard reference to the item id gets stuck in the HashMap forever as a consequence which can cause memory leaks. Typically these ids will be relatively small, but you still end up accumulating a potentially unbounded amount of objects in this HashMap.

### Expected outcome

The internal unique key map is cleaned up as objects are removed.

### Minimal reproducible example

Add and remove items to the TreeData of a grid in a loop assigning for instance a random UUID as item id.

### Steps to reproduce

See above

### Environment

Vaadin version(s): 23.0.7
OS: macOS (n/a)

### Browsers

Safari

**Comment by knoobie** [comment]
This is probably a duplicate of an already planned enhancement: https://github.com/vaadin/flow-components/issues/3156

**Comment by pepijnve** [comment]
@knoobie you're right, the same problem is described there as well. Closing this one as a duplicate.
