### ISSUE TITLE
Allow subclasses to access the key set of AbstractGridMultiSelectionModel#selected

### ISSUE THREAD

**Issue by pepijnve** [vaadin/flow-components#3246]
### Describe your motivation

The subclassed selection model we use in our application implements logic to fetch a recent copy of each selected item based on the item id rather than using the (possible stale) copy that's referenced by the selection model. To avoid unnecessary work it would be nice to be able to get hold of the key set of the internal selection hash map.

### Describe the solution you'd like

Add a protected final method

```
protected final Set<Object> getSelectedItemIds() {
        return Collections.unmodifiableSet(this.selected.keySet());
}
```

### Describe alternatives you've considered

Implement the same logic as (stream for brevity)

```
getSelectedItems().stream().map(getGrid().getDataCommunicator().getDataProvider()::getId).collect(Collectors.toSet())
```

This will effectively do the same thing, but causes quite a bit of unnecessary work.

**Comment by willemv** [comment]
This is labeled as a new feature at the moment, does that mean it will not be backported to 23.1 ?

**Comment by web-padawan** [comment]
Generally, we don't backport new features to minor versions. So yes, this PR should land in 23.2.
The current plan is to release 23.2 RC next week and then stable release in early September.

**Comment by willemv** [comment]
OK, thanks for your reply
