### ISSUE TITLE
[spreadsheet] Spreadsheet doesn't fill the viewport with cells on resize

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/flow-components#3249]
When the spreadsheet visible viewport is increased, it's not refilled with new cells

https://user-images.githubusercontent.com/1222264/171168604-ef079fbd-2d21-459a-b7fa-35247c3d73ef.mp4

**Comment by manolo** [comment]
There were couple of issues during the 6wp that seem related, they could help as reference
https://github.com/vaadin/spreadsheet/issues/773
https://github.com/vaadin/spreadsheet/issues/791
