### ISSUE TITLE
Grid context menu not working on iOS in Vaadin 23

### ISSUE THREAD

**Issue by thomaskiesl** [vaadin/flow-components#3296]
### Description of the bug

Why is event.getItem() not present within the Safari browser? It is working on Windows (Chrome) but not on my ipad/iphone:

        GridContextMenu<T> contextMenu = grid.addContextMenu();
        contextMenu.addItem("test", event -> {
            if (event.getItem().isPresent()) {
                // ....
            }
        });

I do not know whether it is related to Safari or to iOS.

### Versions

- Vaadin / Flow version: 23.0.10
- Java version: 17
- OS version: CentOs
- Browser version (if applicable): Safari

**Comment by web-padawan** [comment]
Thanks for the issue. Closing in favor of #2951 which appears to be the same.

**Comment by web-padawan** [comment]
Reopened as #2951 appears to be an issue with TS example in the docs. Let's keep this one as the actual Flow component issue.
