### ISSUE TITLE
[combo-box] Dropdown shows placeholders when auto-opened is disabled

### ISSUE THREAD

**Issue by sissbruecker** [vaadin/flow-components#3321]
### Description

When setting auto-opened to disabled, then entering a value manually, and opening the dropdown afterwards, the dropdown shows placeholders for the first page. Also the loading state is never cleared.

This applies to `ComboBox` and `MultiSelectionComboBox`. This is not a regression from the recent changes from introducing the multi select combo box, see affected versions below.

https://user-images.githubusercontent.com/357820/173047832-43ca844a-adcd-42a0-8f38-1611013c2dcf.mp4

### Expected outcome

The combo box should load and display the first page of items.

### Minimal reproducible example

```java
MultiSelectComboBox<String> comboBox = new MultiSelectComboBox<>(
        "Items");
List<String> items = IntStream.range(0, 100)
        .mapToObj(i -> "Item " + (i + 1)).collect(Collectors.toList());
comboBox.setItems(items);
comboBox.setAutoOpen(false);
```

### Steps to reproduce

1. Add the snippet above to a page
2. Focus the combo box
3. Enter "item 2", wait for a bit for the data provider to respond
4. Hit enter to select the item
5. Open the dropdown

### Environment

Vaadin version(s): 22.0, 23.0, 23.1, 23.2-SNAPSHOT

14.8 is not affected

### Browsers

Issue is not browser related

**Comment by vursen** [comment]
The web component has apparently a related issue when using a data provider + `auto-open-disabled`.

When you open the dropdown after typing a filter query, the filter query doesn't apply to the dropdown list:

https://user-images.githubusercontent.com/5039436/174588846-ca462830-b30a-42fc-907a-4cbd5bd204e1.mov

**Comment by web-padawan** [comment]
See the original web component issue: https://github.com/vaadin/vaadin-combo-box/issues/1000 and a fix https://github.com/vaadin/vaadin-combo-box/pull/1001
The current logic was apparently based on my suggestion https://github.com/vaadin/vaadin-combo-box/pull/1001#discussion_r586451305

To me it looks like the code that I proposed back then is wrong, and needs to be fixed.
