### ISSUE TITLE
[spreadsheet] Unintentional public API

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/flow-components#3348]
The Flow Spreadsheet class seems to have [quite a lot of public API](https://github.com/vaadin/flow-components/blob/883c18b3e468bedcf7292741e37b940802c08b5d/vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/Spreadsheet.java#L320-L830) that's probably there unintentionally.

![Screenshot 2022-06-15 at 16 43 35](https://user-images.githubusercontent.com/1222264/173843087-545667bb-cf66-49bb-994a-0ac725201f30.png)

**Comment by DiegoCardoso** [comment]
Another thing that came across my mind is whether `Spreadsheet` should implement `HasComponents` or not.

**Comment by Artur-** [comment]
Unlikely that it should. What would `spreadsheet.add(new Button())` mean?
