### ISSUE TITLE
RadioButtonGroup readonly state not probably render if radio button is checked

### ISSUE THREAD

**Issue by dirkey** [vaadin/flow-components#3359]
### Description

If a RadioButtonGroup is set to readonly, the selected element is still in read/write (enable) state. Relevant code:
`
private void updateEnabled(RadioButton<T> button) { ... 
    if (this.isReadOnly() && !button.isCheckedBoolean()) ...
`

### Expected outcome

If the radio button group is disabled, the selected radio button should rendered with the disable attribute. Otherwise it is not possible to distinguish the disable state while styling the component.

### Minimal reproducible example

RadioButtonGroup rbg = ....
rbg.setValue(...)
rbg.setReadonly(true)

### Steps to reproduce

No need, because the problem is quite obvious. See code in description of the bug.

### Environment

Vaadin version(s): 23.1.0
OS: all

### Browsers

Issue is not browser related

**Comment by web-padawan** [comment]
Thanks for the issue. This is not a bug, vut intended behavior, see #2526. In case of `readonly` group, all the  radio buttons except the selected one are disabled. See also the [documentation](https://vaadin.com/docs/latest/components/radio-button/#states) for both `readonly` and `disabled` states.

**Comment by dirkey** [comment]
Yes, I read this stuff. But, how I be able to render it differently via CSS? It appears to be a normal input field. At least, it should add a readonly attribute, to be able for css selector rendering.

**Comment by dirkey** [comment]
After adding a "readonly" attribute to the vaadin-radio-button, I was able to render this element exactly the same as the disabled ones. Focus state is still working, so it complies to the documentation.
`
<vaadin-radio-button checked has-value has-label **readonly**>
`

**Comment by web-padawan** [comment]
Please note that `vaadin-radio-button` does not currently have a `readonly` state, see https://github.com/vaadin/web-components/issues/822
The reason for it is the fact that native `<input type="radio">` elements do not support `readonly` state:

> Only text controls can be made read-only, since for other controls (such as checkboxes and buttons) there is no useful distinction between being read-only and being disabled, so the [readonly](https://html.spec.whatwg.org/multipage/input.html#attr-input-readonly) attribute [does not apply](https://html.spec.whatwg.org/multipage/input.html#do-not-apply).

If you need to style the radio-buttons in `readonly` group  differently, you can apply the following style to `vaadin-radio-group`:

```css
:host([readonly]) ::slotted(vaadin-radio-button) {
   /* styles for all readonly buttons */
}

:host([readonly]) ::slotted(vaadin-radio-button[disabled]) {
   /* styles for not selected readonly buttons */
}
```

That said, personally I don't see a need for adding `readonly` attribute to `vaadin-radio-button` or `vaadin-checkbox`.

**Comment by dirkey** [comment]
I understand your concerns. The problem is, the radio button was invented much more as a button not an input field. Problem is: It is mainly used as an input field! But I didn't want to add the readonly parameter to the input field itself. An abstraction in a web component is total normal. Other frameworks also invent a readonly property on their radio button web component. It makes the abstraction in forms much more semantical correct. Also a barrier free implementation would be much easier. On other components it is normal to add attributes, which the base won't support (i.e. vaadin-text etc.).
So I don't see your complain fly. Would it not be better to have a common solution to this problem, instead each developer find it own solution (maybe wrong)?

**Comment by dirkey** [comment]
I try to implement your css solution, but I was not able to change the look of the input element itself (should look the same like the disabled element). Any styling is ignored and any more dedicated selector is not applied. If you got a solution, I will much appreciate an example. Thanks.

**Comment by vursen** [comment]
Hello @dirkey!

The input element of radio-buttons, as well as checkboxes, is not supposed to be styled directly. Instead, there are `[part=radio]` and `[part=checkbox]` respectively that can be used for adjusting the visual appearance of the control. Note that the input element is just a transparent overlay on top of them.

In case you want to style the input anyway, you can use a global CSS like that:

```css
vaadin-radio-group[readonly] > vaadin-radio-button {
  /* styles for the radio-button itself */
}

vaadin-radio-group[readonly] > vaadin-radio-button > input {
 /* styles for the radio-button's input element */
}
```

**Comment by vursen** [comment]
Closing as stale. Feel free to re-open if the above solution doesn't work for you.
