### ISSUE TITLE
Grid, column.setFrozenToEnd with prependHeaderRow().join isn't work as expecting.

### ISSUE THREAD

**Issue by w-tomasz** [vaadin/flow-components#3363]
### Description

Joining frozen columns with others to new header row, making bottom scroll not working at all. Scrolling data grid from left to right is not possible anymore. 

### Expected outcome

In ideal world i would like that newly created row (footer / header) is independent and have no impact to other grid elements behavior.

### Minimal reproducible example

```java
@Route(value = "test", layout = MainView.class)
@AnonymousAllowed
public class TestGridView extends VerticalLayout {

    public TestGridView() {
        List<Person> persons = new ArrayList();
        for (int i = 0; i < 100; i++) {
            persons.add(new Person());
        };

        Grid<Person> grid = new Grid<>(Person.class, false);
        grid.setSelectionMode(Grid.SelectionMode.MULTI);
        grid.addColumn(Person::getId).setHeader("Id").setAutoWidth(true).setFlexGrow(0);
        grid.addColumn(Person::getName).setHeader("Name").setAutoWidth(true);
        grid.addColumn(Person::getColumn0).setHeader("Column #0").setAutoWidth(true);
        grid.addColumn(Person::getColumn1).setHeader("Column #1").setAutoWidth(true);
        grid.addColumn(Person::getColumn2).setHeader("Column #2").setAutoWidth(true);
        grid.addColumn(Person::getColumn3).setHeader("Column #3").setAutoWidth(true);
        grid.addColumn(Person::getColumn4).setHeader("Column #4").setAutoWidth(true);
        grid.addColumn(Person::getColumn5).setHeader("Column #5").setAutoWidth(true);
        grid.addColumn(Person::getColumn5).setHeader("Column #5").setAutoWidth(true);
        grid.addColumn(Person::getColumn5).setHeader("Column #5").setAutoWidth(true);
        grid.addColumn(createActionRenderer()).setFrozenToEnd(true).setAutoWidth(true).setFlexGrow(0);

        var header = grid.prependHeaderRow();
        HeaderRow.HeaderCell headerCells = header.join(grid.getColumns().toArray(new Grid.Column[]{}));
        headerCells.setText("Grid header");

        grid.setItems(persons);
        grid.setSizeFull();
        setSizeFull();
        addAndExpand(grid);

    }

    private static Renderer<Person> createActionRenderer() {
        return LitRenderer.<Person>of("<vaadin-button theme=\"tertiary-inline\">Edit</vaadin-button>");
    }

    private class Person {
        private String id;
        private String name;
        private String column0;
        private String column1;
        private String column2;
        private String column3;
        private String column4;
        private String column5;

        public Person() {
            this.id = UUID.randomUUID().toString();
            this.name = UUID.randomUUID().toString();
            this.column0 = UUID.randomUUID().toString();
            this.column1 = UUID.randomUUID().toString();
            this.column2 = UUID.randomUUID().toString();
            this.column3 = UUID.randomUUID().toString();
            this.column4 = UUID.randomUUID().toString();
            this.column5 = UUID.randomUUID().toString();
        }

        public String getId() {
            return id;
        }

        public String getName() {
            return name;
        }

        public String getColumn0() {
            return column0;
        }

        public String getColumn1() {
            return column1;
        }

        public String getColumn2() {
            return column2;
        }

        public String getColumn3() {
            return column3;
        }

        public String getColumn4() {
            return column4;
        }

        public String getColumn5() {
            return column5;
        }
    }
}
```

### Steps to reproduce

_Please narrow your browser window to make current grid content not fit to your screen to be able observing this behavior._

### Environment

- Vaadin / Flow version: 23.1.1
- Java version: 17
- OS version: Linux 
- Application Server (if applicable):  Springboot

### Browsers

Chrome, Firefox

**Comment by web-padawan** [comment]
Confirmed the issue. The reason is the fact that setting `frozenToEnd` on a single column [applies to the whole group](https://github.com/vaadin/web-components/blob/1acf5cd03f7a95ea6f3bcf546930552f20cfd79a/packages/grid/src/vaadin-grid-column.js#L347-L349).
When using `grid.prependHeaderRow()`, all the columns are wrapped into a single `vaadin-grid-column-group`.

**Comment by web-padawan** [comment]
BTW, using `.setFrozen(true)` on the first column together with header row also makes the horizontal scrolling look broken:

https://user-images.githubusercontent.com/10589913/174796976-3c7756e2-282f-471d-abba-c4463b7b5498.mp4

**Comment by tomivirkki** [comment]
Related / duplicate issues:
- https://github.com/vaadin/vaadin-grid-flow/issues/846
- https://github.com/vaadin/flow-components/issues/1064

**Comment by web-padawan** [comment]
Note about the scrolling effect: it manifests differently in browsers - see recordings below.

<details>
<summary>HTML snippet to reproduce</summary>

```html
<vaadin-grid style="max-width: 300px">
  <vaadin-grid-column-group header="Person">
    <vaadin-grid-column frozen path="firstName"></vaadin-grid-column>
    <vaadin-grid-column path="lastName"></vaadin-grid-column>
    <vaadin-grid-column path="address.phone"></vaadin-grid-column>
    <vaadin-grid-column path="email"></vaadin-grid-column>
  </vaadin-grid-column-group>
  <vaadin-grid-column path="address.city"></vaadin-grid-column>
</vaadin-grid>

<script type="module">
  import '@vaadin/grid';
  import '@vaadin/grid/vaadin-grid-column-group.js';
  const res = await fetch('https://demo.vaadin.com/demo-data/1.0/people?count=200');
  const data = await res.json();

  const grid = document.querySelector('vaadin-grid');
  grid.items = data.result;
</script>
```


</details>

## Chrome

Scroll width grows infinitely, it's possible to scroll horizontally past the viewport:

https://user-images.githubusercontent.com/10589913/174970407-975d235a-2c9e-4e88-bad7-53bd6d085be1.mp4

## Firefox

Scroll width grows infinitely, but it's not possible to scroll horizontally past the viewport:

https://user-images.githubusercontent.com/10589913/174970628-d1742b7c-bfd7-4c76-b501-3e0444b705f5.mp4

## Safari

Scroll width does not grow, and it's not possible to scroll horizontally at all.

https://user-images.githubusercontent.com/10589913/174970803-88f6fb39-ee06-4fbe-a57e-7a12721fec4e.mp4

**Comment by tomivirkki** [comment]
You can fix the issue in your app by excluding the last column (the frozen one), from the list of columns to join:

Instead of joining every column...
```java
HeaderRow.HeaderCell headerCells = header.join(grid.getColumns().toArray(new Grid.Column[]{}));
```
...only join the columns before the frozen one
```java
HeaderRow.HeaderCell headerCells = header.join(grid.getColumns().subList(0, grid.getColumns().size() - 1).toArray(new Grid.Column[]{}));
```

https://user-images.githubusercontent.com/1222264/193814373-02592cdc-b141-4dd8-97c8-335785acbe5d.mp4
