### ISSUE TITLE
Grid with CallbackDataProvider and identifierGetter looses selection after refreshAll

### ISSUE THREAD

**Issue by simasch** [vaadin/flow-components#3384]
### Description

I have an example that uses jOOQ and uses a CallbackDataProvider with identifierGetter because the jOOQ-generated classes don't have equals and hashCode.

The app has a grid and a form and if I change something in the form the selection in the grid is lost.

### Expected outcome

Selection should not be lost

### Minimal reproducible example

Project: https://github.com/simasch/spring-io-2022-vaadin

### Steps to reproduce

1. Run the project
2. login 
3. go to the employees view
4. change the name and save
5. the selection in the grid is lost

### Environment

Vaadin version(s): 23

### Browsers

Issue is not browser related

**Comment by sissbruecker** [comment]
Can confirm this. `AbstractGridSingleSelectionModel` does not use the data provider identity in `isSelected`, and returns `false` for the selected item if the hash code changes.

**Comment by simasch** [comment]
That was fast thanks.

In which version will this be fixed? @sissbruecker @web-padawan 
Is there a way to know in which release a fix will be included?

**Comment by web-padawan** [comment]
We are going to make a new patch release next week, so this fix should land in Vaadin 23.1.2

**Comment by simasch** [comment]
@web-padawan Thanks!
Do you release always on the same day?

**Comment by web-padawan** [comment]
Generally, we check if there is a need for new patch release every Monday, depending on changes in Flow and components.
Note: we also have a bot automated to comment on delivered issues once the new release is published.

**Comment by web-padawan** [comment]
@simasch Vaadin 23.1.2 is now released with a fix for this issue.

**Comment by simasch** [comment]
Thank you 🥳
