### ISSUE TITLE
[CRUD] cannot move Edit button to left side with CrudGrid

### ISSUE THREAD

**Issue by letrthang** [vaadin/flow-components#3412]
### Description

Vaadin flow 23, java 17, spring boot 2.7.

cannot move Edit button to left side with CrudGrid. Edit button is still in right side with below code:

<img width="766" alt="image" src="https://user-images.githubusercontent.com/13396193/176479687-27a9147d-debf-4210-8037-91f5a3d8d9d0.png">

### Expected outcome

Can move Edit button to left side with CrudGrid

### Minimal reproducible example

code in above photo

### Steps to reproduce

N/A

### Environment

Vaadin version(s): 23
OS: any

**Comment by web-padawan** [comment]
Thanks for the issue. Duplicate of #1114. Please see that issue description for a workaround.
