### ISSUE TITLE
[map] Drag/move a marker (MarkerFeature)

### ISSUE THREAD

**Issue by blafoo** [vaadin/flow-components#3419]
### Describe your motivation

To retrieve coordinates from a map it would be very useful to drag/move a marker on the new Map component. It's a know behaviour of Leaftlet.js
In our use case we a displaying a marker for an address. The user now has the possibility to move this marker to a different position. Afterwards the address (here: longitude/latitude) for the object is updated.

### Describe the solution you'd like

- Add a boolean field 'moveable' to MarkerFeature indicating if the marker can be dragged. Default = false
- Create and register an event 'MapFeatureDragEndEvent
- Update the marker on the map 
- Update the coordinates of the marker

### Describe alternatives you've considered

The alternative would be to use Leaflet.js

**Comment by blafoo** [comment]
@web-padawan If you like you can assigne me this issue ,-) I'm already working on a PR (https://github.com/blafoo/flow-components/tree/master/vaadin-map-flow-parent). The initial version is already working except for the non-send events from the JavaScript code.

**Comment by sissbruecker** [comment]
@blafoo Your changes look pretty good so far, the implementation of the modify interaction might need some work. In general I would suggest to use the [`Translate`](https://openlayers.org/en/latest/apidoc/module-ol_interaction_Translate-Translate.html) interaction instead, as modify also allows to modify the shapes of polygons, which are not supported for now.
It would also make sense to separate the changes to implement #2508 first, which IMO should only cover adding the interactions property to the map configuration, and then adding some of the basic interactions that modify the map's view. After that we could start adding interactions for modifying features.
In general we don't just accept new features unless it has been discussed in the team, and acceptance criteria have been added. I'll see if we can discuss this topic next week with the PO.

In the meantime you can also take a look at this cookbook recipe that implements marker drag and drop. It's more of a workaround, but it doesn't require any changes to the component itself: https://github.com/vaadin/cookbook/pull/262

**Comment by blafoo** [comment]
@sissbruecker Thanks for the feedback and informations. It's no problem to start with the changes for the interactions as part of issue #2508 BTW: what kind of API do you prefer? Customize the behaviour via the constructor of the class Map or via a new method in the class Map like 'map.changeInteraction(DragRotate, false)?

As a beginner to Openlayers i only found the Modify example and not the Translate feature. Seems to be easier to use Translate as you did it in your recipe which seems to fullfill my requirement and is exactly my use case :-) May i use it for my pull request for this issue after your discussions with the POs?

**Comment by sissbruecker** [comment]
> BTW: what kind of API do you prefer? Customize the behaviour via the constructor of the class Map or via a new method in the class Map like 'map.changeInteraction(DragRotate, false)?

This will be clarified in the acceptance criteria.

> May i use it for my pull request for this issue after your discussions with the POs?

Should also end up in the acceptance criteria, but if the use-case is only "move markers", then the Translate interaction would be good enough.

**Comment by yuriy-fix** [comment]
Related acceptance criteria: https://github.com/vaadin/platform/issues/3532
