### ISSUE TITLE
`setValue` doesn't trigger validation for some TB field elements

### ISSUE THREAD

**Issue by vursen** [vaadin/flow-components#3420]
### Description

Currently, Field TestBench elements trigger `blur` and `change` on the component's host rather than the input when setting a value with `setValue()`, which results in validation not running.

https://github.com/vaadin/flow-components/blob/39b52fd4eba14cd4838a72eac5b78bc10e96dfd2/vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/TextFieldElement.java#L35-L40

This is apparently an omission from the a11y slotted refactoring.

### Affected components

- TextFieldElement
- TextAreaElement
- EmailFieldElement
- IntegerFieldElement
- NumberFieldElement
- PasswordFieldElement
- BigDecimalFieldElement

### Expected outcome

`setValue()` of Field TextBench elements should trigger `blur` and `change` on the input rather than the host after a new value is set. 

Note, if `change` and `blur` are triggered on the input, then `setValue()` should also trigger an `input` event before the `change` event as otherwise the input's value won't be synced with the field's `value` property.

### Environment

Vaadin version(s): 21, 22, 23
OS: Mac OS

**Comment by vursen** [comment]
I wonder if it would make sense to introduce a separate method `setInputValue` for emulating setting an input value (that would trigger `blur`, `change`, and so on) while the existing `setValue` would only set the `value` property on the component.

This is inspired by `DatePickerElement`:

https://github.com/vaadin/flow-components/blob/39b52fd4eba14cd4838a72eac5b78bc10e96dfd2/vaadin-date-picker-flow-parent/vaadin-date-picker-testbench/src/main/java/com/vaadin/flow/component/datepicker/testbench/DatePickerElement.java#L130-L140

https://github.com/vaadin/flow-components/blob/39b52fd4eba14cd4838a72eac5b78bc10e96dfd2/vaadin-date-picker-flow-parent/vaadin-date-picker-testbench/src/main/java/com/vaadin/flow/component/datepicker/testbench/DatePickerElement.java#L154-L163

**Comment by yuriy-fix** [comment]
We would probably want to modify `setValue` to not trigger events (i.e. `blur`)

**Comment by vursen** [comment]
The alternative way could be to ensure every field component provides a `sendKeys` method for emulating the user's input. 

It should be mentioned though that using `sendKeys` can be a bit inconvenient and clunky in the situation when you need to replace the whole value at once which is often the case in tests. The way you would currently do that: select the input value,  press <kbd>Backspace</kbd> and only then you can type a new value. Considering that, it might be useful to have a shorthand method for that purpose to avoid repetition.

**Comment by vursen** [comment]
It appears that the `sendKeys` API doesn't suit all the cases. 

**Example:** an input has a `maxlength`, so you can't enter more than the specified number of characters to it. However, you might still want to set the value to something longer in order to test validation. This is when `setInputValue` would be helpful.

**Comment by vursen** [comment]
After a more thorough examination, it turned out that setValue in its default implementation is actually useless at least for components in the `text-field` package. The reason is `ValueChangeMode.ON_CHANGE` which is enabled for the components by default so just updating the value property on the client-side doesn't cause it to sync on the server-side unless a change event is fired on the component. But if we trigger that change event, we end up with two methods doing pretty much the same.

So, it seems that the only reasonable option that remains would be to fix setValue to make it set `value` on the input element and trigger the respective events.
