### ISSUE TITLE
TreeGrid data provider refresh all with new filter when scrolled down shows empty rows

### ISSUE THREAD

**Issue by melihkurtaran** [vaadin/flow-components#3434]
### Description

There is a bug with TreeGrid and getDataProvider().refreshAll() when scrolled towards the bottom with lazy loading several times.

HierarchicalDataProvider is used for the tree grid's dataprovider. It is filtered within the HierarchicalDataProvider. getDataProvider().refreshAll() is called when someone clicks on a checkbox for filtering.

It works when if it is scrolled near the top, but if it is scrolled near the bottom, utilizing the lazy load several times, it ends up with empty rows when refreshAll() is called with filtered results. It shows the correct number of rows, but they are empty.

### Expected outcome

Expected outcome is to see the same results as grid shows also in TreeGrid however filtered samples are not visible in TreeGrid.

### Minimal reproducible example

In a view, following code can be written to reproduce the bug:

     public static class Person {
        private String firstName;
        private String lastName;

        public Person(String firstName, String lastName) {
            this.firstName = firstName;
            this.lastName = lastName;
        }

        public String getFirstName() {
            return firstName;
        }

        public String getLastName() {
            return lastName;
        }
    }

    boolean showAll = true;
    TextField textField = new TextField("Your name");

    List<Person> people = new ArrayList<>();
    TreeGrid<Person> treeGrid = new TreeGrid<>();

    Grid<Person> grid = new Grid<>();

    public void switchShow() {

        showAll = !showAll;
        treeGrid.getDataProvider().refreshAll();
        grid.getDataProvider().refreshAll();
    }

    public EmptyView() {
        Button button = new Button("Say hello", e -> switchShow());
        button.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        button.addClickShortcut(Key.ENTER);
        addClassName("centered-content");

        setMaxWidth("80%");
        add(textField, button);

        for (int i = 0; i <500; ++i) {
            people.add(new Person("First" + i, i + "Last"));
        }

        HierarchicalDataProvider<Person, Void> dataProviderTreeGrid =
                new AbstractBackEndHierarchicalDataProvider<Person, Void>() {
                    @Override
                    public int getChildCount(HierarchicalQuery<Person, Void> query) {
                        int pageNum = query.getPage();
                        int pageSize = query.getPageSize();
                        if (showAll) {
                            return people.size();
                        }
                        else {
                            return 5;
                        }
                    }
                    @Override
                    public boolean hasChildren(Person item) {
                        return false;
                    }

                    @Override
                    protected Stream<Person> fetchChildrenFromBackEnd(
                            HierarchicalQuery<Person, Void> query) {
                        int pageNum = query.getPage();
                        int pageSize = query.getPageSize();
                        if (showAll) {
                            int lastIdx = query.getLimit() + query.getOffset();
                            if (lastIdx >= people.size()) {
                                lastIdx = people.size();
                            }
                            return people.subList(query.getOffset(), lastIdx).stream();
                        }
                        else {
                            return people.subList(5, 10).stream();
                        }
                    }
                };

        treeGrid.setDataProvider(dataProviderTreeGrid);
        treeGrid.addColumn(Person::getFirstName).setHeader("First Name").setKey("firstName");
        treeGrid.addColumn(Person::getLastName).setHeader("Last Name").setKey("lastName");
        add(new Label("TreeGrid Example"));
        add(treeGrid);

        grid.setItems(query -> {
                    int pageNum = query.getPage();
                    int pageSize = query.getPageSize();
                    if (showAll) {
                        int startIdx = pageNum * pageSize;
                        int lastIdx = startIdx + pageSize;
                        if (lastIdx >= people.size()) {
                            lastIdx = people.size();
                        }
                        return people.subList(startIdx, lastIdx).stream();
                    }
                    else {
                        return people.subList(5, 10).stream();
                    }
                },
                query -> {
                    int pageNum = query.getPage();
                    int pageSize = query.getPageSize();
                    if (showAll) {
                        return people.size();
                    }
                    else {
                        return 5;
                    }
                }
        );

        grid.addColumn(Person::getFirstName).setHeader("First Name").setKey("firstName");
        grid.addColumn(Person::getLastName).setHeader("Last Name").setKey("lastName");
        add(new Label(""));
        add(new Label("Grid Example"));
        add(grid);

### Steps to reproduce

When the example code runs,
There will be two grids visible: TreeGrid and normal Grid
1. Scroll towards the bottom at least for 200 samples or above
2. Click the button for filtering
3. Observe if the behavior the same or not for the grids

### Environment

Vaadin version(s): 21.0.2
OS: MacOS
Also replicated this with Vaadin 23.1.2

### Browsers

Chrome

**Comment by sirbris** [comment]
I could reproduce the empty row rendering also with an in memory dataProvider... at the moment only if there was some scrolling (not necessarily the end though) involved
<img width="473" alt="Bildschirmfoto 2022-07-15 um 07 43 42" src="https://user-images.githubusercontent.com/664179/179159270-05011d85-cad9-4892-86fd-3f345ccc3ce7.png">
If the refreshAll is called again (via extra button or so), all seems to be fine.... so I think that the initial refreshAll (although being the last call in a series of other actions like filtering, scrollTo etc.) gets lost (racing condition e.g.) or isn't completely finished
