### ISSUE TITLE
Icons added to disabled div do not inherit disabled attribute

### ISSUE THREAD

**Issue by kiwicodemonkey** [vaadin/flow-components#3459]
### Description of the bug

For part of our UI, the main div is disabled and then more components are added based on the data loaded. However, if the main div is disabled before adding the additional components, then only some of the additional components added have the disabled attribute set.

### Expected behavior

I would expect that all components added to a disabled div should inherit the disabled attribute.

### Minimal reproducible example

```java
VerticalLayout vlMain = new VerticalLayout();
vlMain.setSizeFull();
HorizontalLayout hlOne = new HorizontalLayout(FontAwesome.Solid.BUG.create(), new Button("Testing"));
HorizontalLayout hlTwo = new HorizontalLayout();
hlOne.setEnabled(false);
hlTwo.setEnabled(false);
Button add = new Button("Add");
add.addClickListener(buttonClickEvent -> {
    if(buttonClickEvent.isFromClient()) {
      hlTwo.add(FontAwesome.Solid.BUG.create());
          hlTwo.add(new Button("Testing"));
    }
});
vlMain.add(hlOne, hlTwo, add);
```

When the above is run, hlOne contains 2 disabled controls. Clicking the button adds the additional components, however the icon doesn't inherit the disabled attribute but the button does. Calling hlTwo.setEnabled(false) again then sets everything correctly. This can be verified using the browser inspector.

### Versions

Vaadin: 23.0.10
Flow: 23.0.7
Java: Eclipse Adoptium 17
OS: amd64 Windows 10 10.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36
Live reload: Java active (Spring Boot Devtools): Front end active

Have also tested with  Vaadin 23.1.0.rc1.

**Comment by rolfsmeds** [comment]
Only interactive components have disabled states, and Icon is not intended to be used as an interactive element on its own (a Button with an icon should be used if the icon is intended to work as a button).

(The Icon component does, unfortunately, implement the `ClickNotifier` interface, which in retrospect I think it shouldn't, but we can't remove that now as it would break existing applications.)

If we were to implement HasEnabled, and the disabled state propagation, for Icon, we would need to do the same for _all_ components for consistency, including native HTML elements in the com.vaadin.flow.component.html package, and provide disabled styling for these. And we don't want to do that as they are not interactive elements.

Closing with regard to the above.
