### ISSUE TITLE
Grid: Add an event / listener, if the data provider has changed

### ISSUE THREAD

**Issue by hoshie82** [vaadin/flow-components#3475]
### Describe your motivation

It is not possible to recognize, if the data in a grid has changed, if the method "setItems" is called, because all former data provider listeners are gone when the new data provider is set... 

It would be really useful, if it would be possible to add some listener or similar, that is executed, if data has changed, not especially for a dataprovider

### Describe the solution you'd like
Some kind of listener, after a new data provider has been set
`````
            grid.addDataProviderHasChangedListener(e-> {
                DataProvider dp = e.getDataProvider();
                dp.addDataProviderListener(e-> {
                    doSomething();
                });
            });
`````

sry for the big edit...
my former request is related to some other problems with the grid, but in general all comes to this point of an event, if a new dataprovider is set to the grid...

**Comment by yuriy-fix** [comment]
Dear @hoshie82, could you please provide a use-case where this logic would be useful?
Probably a code snippet with an event usage?

**Comment by hoshie82** [comment]
sorry for the circumstances... I think I will do all the stuff with the 'onDataProviderChange()' method in Grid
