### ISSUE TITLE
Form layout example uses setRequiredIndicatorVisible that has no effect

### ISSUE THREAD

**Issue by lwhite1** [vaadin/flow-components#348]
### Description of the bug
setting the required field indicator for a text field produces no change in the output. 
e.g.:

    TextField name = new TextField();
    name.setRequiredIndicatorVisible(true);

### Minimal reproducible example

The issue is readily viewable in the Vaadin component page for forms.
https://vaadin.com/components/vaadin-form-layout/java-examples

See the example titled "A form layout with fields using Binder"
The first name and last name fields have setRequiredIndicatorVisible set to true, but the example output shown does not indicate in any way that they are required 

### Expected behavior

The fields should look different when they're required

### Actual behavior

They look just like the other fields

### Versions:
    - Vaadin / Flow version: 14.4.1
    - Java version: java 14.0.2 2020-07-14
    - OS version: OSX
    - Browser version (if applicable): Chrome
    - Application Server (if applicable):
    - IDE (if applicable):

**Comment by Legioth** [comment]
`setRequiredIndicatorVisible` on its own works perfectly, as can be seen with this isolated example:

```
public class TestView extends VerticalLayout {
    public TestView() {
        TextField regular = new TextField("Regular");

        TextField required = new TextField("Required");
        required.setRequiredIndicatorVisible(true);

        add(regular, required);
    }
}
```

The reason it doesn't work in the example you're referring to is because the required indicator is shown next to the text field's own label, which is empty in this case since the label is shown through the form layout instead.

**Comment by web-padawan** [comment]
As mentioned above, the root issue is lack of required indicator support in `vaadin-form-item` component.
Closing in favor of https://github.com/vaadin/vaadin-form-layout/issues/122

**Comment by Legioth** [comment]
I'd still suggest that the example is updated to not contain code that has no effect.

**Comment by web-padawan** [comment]
The [new examples](https://vaadin.com/docs/latest/ds/components/form-layout) no longer contain problematic code that was causing confusion. Closing.
