### ISSUE TITLE
[Grid] add maximise button for grid in demo project

### ISSUE THREAD

**Issue by letrthang** [vaadin/flow-components#3485]
### Describe your motivation

In vaadin demo project: https://github.com/letrthang/vaadin23-flow-pro-components. 
Can we add maximise button for grid as example below:

**Normal**:
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/13396193/179989807-ca70276a-a276-4430-b249-15add481a3f5.png">

**Maximise**:
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/13396193/179988062-699ae415-5fd0-48a2-a3e0-25228a680790.png">

I want to add it to grid for demo project:

<img width="1422" alt="image" src="https://user-images.githubusercontent.com/13396193/179988465-edb677f2-cf2f-49c0-9e30-25540bbd1221.png">

I used my code for split layout on the demo and cannot zoom full-screen for the grid.

![telegram-cloud-photo-size-5-6251337312239726338-x](https://user-images.githubusercontent.com/13396193/179988904-4e0a49c7-cea7-4e11-ba11-28cbef73df6f.jpg)

### Describe the solution you'd like

allow maximise grid

### Describe alternatives you've considered

N/A

**Comment by sissbruecker** [comment]
I understand that you are looking for advice on how to implement CSS styles that would allow you to display the grid in full screen. Note that we do not provide support through Github issues, for support please use [Discord](https://discord.com/invite/MYFq5RTbBn), [StackOverflow](https://stackoverflow.com/questions/tagged/vaadin), or check out our [official support](https://vaadin.com/support).
