### ISSUE TITLE
Vaadin 23 VirtualList with 50 or more items is not refreshed, "TypeError: item is undefined" in virtualListConnector.js

### ISSUE THREAD

**Issue by fabst2w** [vaadin/flow-components#3487]
### Description

When there are 50 or more items in a VirtualList, a ClickListener stops working after calling refreshItem and the item that should get refreshed (by refreshItem) is not refreshed.

Firefox says "TypeError: item is undefined" in virtualListConnector.js line 108.

Have a look at the screenshot here: https://stackoverflow.com/questions/73051597/vaadin-23-virtuallist-with-50-or-more-items-loses-clicklistener-and-is-not-refre?noredirect=1#comment129022996_73051597

### Expected outcome

I expect that an item in a VirtualList is refreshed after calling refreshItem.

### Minimal reproducible example

Have a look at https://stackoverflow.com/questions/73051597/vaadin-23-virtuallist-with-50-or-more-items-loses-clicklistener-and-is-not-refre?noredirect=1#comment129022996_73051597

### Steps to reproduce

1. Add the code from https://stackoverflow.com/questions/73051597/vaadin-23-virtuallist-with-50-or-more-items-loses-clicklistener-and-is-not-refre?noredirect=1#comment129022996_73051597 into a view
2. click an item
3. Item should get refreshed, but it is not. (At least not without scrolling the list down and up.)

### Environment

Vaadin version(s): 23.1.3
OS: Ubuntu 22.04

### Browsers

Chrome, Firefox

**Comment by sissbruecker** [comment]
Should be fixed in the next patch release. In the meantime `dataProvider.refreshAll()` should work.

**Comment by fabst2w** [comment]
Works fine in 23.1.6. Thank you, @sissbruecker !
