### ISSUE TITLE
`sendKeys` calls are not delegated to the input element for some TB field elements

### ISSUE THREAD

**Issue by vursen** [vaadin/flow-components#3502]
### Description

Calling `sendKeys` directly on the TestBench element has currently no effect for TextFieldElement and BigDecimalFieldElement. 

### Expected outcome

TextFieldElement and BigDecimalFieldElement should delegate `sendKeys` calls to the input element, similar to other components e.g. PasswordField:

https://github.com/vaadin/flow-components/blob/0cbedd8de6693a6ea9cba21fd035efa3677fa808/vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/PasswordFieldElement.java#L67-L70

### Environment

Vaadin version(s):  23.2
OS: Mac OS

### Browsers

Issue is not browser related

**Comment by vursen** [comment]
Somehow `sendKeys` works even without delegating...

**Comment by yuriy-fix** [comment]
Will it be fixed by https://github.com/vaadin/flow-components/pull/3501?
