### ISSUE TITLE
vaadin-big-decimal-field does not mark invalid input as invalid

### ISSUE THREAD

**Issue by Frettman** [vaadin/flow-components#3504]
### Description

The `<vaadin-big-decimal-field>` does not prevent entering multiple decimal points or minuses at arbitrary locations, but fails to mark the field as invalid as a response. I discovered this using the `BigDecimalField` Flow component.

As somewhat of a side note: I suspect that even if this is changed, there would still be the same issue as the DatePicker has: vaadin/flow-components#1268
The server-side would still not know that the component contains an invalid value. But indicating it to the user would be the first necessary step in any case.

### Expected outcome

I expected the field to be marked as invalid.

### Actual outcome

The component did not indicate that anything was wrong. Server-side is completely unware.

### Steps to reproduce

Add any plain `<vaadin-big-decimal-field>` or BigDecimalField to a layout and enter multiple decimal points or minuses.

### Environment

- v21.0.2
- Windows 10

**Comment by vursen** [comment]
The issue has been resolved by the [new validation mechanism](https://github.com/vaadin/platform/issues/3066) which is enabled by default in Vaadin 24. For any further bugs, please create separate issues.
