### ISSUE TITLE
Vaadin Charts export with setStyledMode(true) not working correctly

### ISSUE THREAD

**Issue by sirbris** [vaadin/flow-components#3508]
### Description

When using styled mode in Vaadin Charts, the export (png, jpeg etc. does not matter here) image is mostly black.

### Expected outcome

Export should work like with not using styled mode

### Minimal reproducible example

```
Configuration conf = chart.getConfiguration();
conf.getChart().setStyledMode(Boolean.TRUE);
conf.setExporting(Boolean.TRUE);
```

### Steps to reproduce

Add a chart with export functionality and export the chart as png via burger menu

### Environment

Vaadin version(s): 23.1.3
OS: Chrome OS

### Browsers

Chrome, Firefox

**Comment by sirbris** [comment]
Export look like this:
![chart(3)](https://user-images.githubusercontent.com/664179/180621055-8e2c3ff3-f24e-4f41-a4ad-f8010c22cd53.png)

**Comment by knoobie** [comment]
I would argue it's not supported, like noted here https://vaadin.com/docs/latest/components/charts/svg-generator/#customizing-svg-generation

> CSS styling is not supported when exporting a chart as SVG.

**Comment by sirbris** [comment]
I could live without svg option... is there a workaround to support exporting charts as png, jpg or pdf?

**Comment by web-padawan** [comment]
The issue can be also reproduced in the web component e.g. [dev page](https://github.com/vaadin/web-components/blob/master/dev/charts/lumo/area.html) by adding the following to `vaadin-chart`

```
additional-options='{
  "chart": {
    "styledMode": true
  },
  "exporting": {
    "enabled": true
  }
}'
```
