### ISSUE TITLE
Grid: Frozen to end does not work well when resizing columns and having no horizontal scrollbar [1 day]

### ISSUE THREAD

**Issue by timbo86** [vaadin/flow-components#3520]
### Description

When there is more space then the columns would consume and the last non frozen column is resized, then the frozen columns are not frozen anymore.

### Expected outcome

The frozen to end columns should still be sticky on the right side.

### Minimal reproducible example

Use this view

```
@Route("grid-button")
public class GridButtonView extends Div {

    public GridButtonView() {
        Grid<User> grid = new Grid<>();
        grid.addThemeVariants(GridVariant.LUMO_COLUMN_BORDERS);
        grid.addColumn(User::getFirstName).setHeader("First name").setWidth("500px").setResizable(true);
        grid.addColumn(User::getLastName).setHeader("Last name").setWidth("500px").setResizable(true);

        grid.addComponentColumn(u -> new Button(
            VaadinIcon.USER.create(),
            e -> new Notification(String.format("User %s clicked", u.getLastName())).setOpened(true))).setFrozenToEnd(true).setWidth("5rem").setFlexGrow(0);

        grid.setItems(new User("First", "User1"), new User("Second", "User2"), new User("Third", "User3"), new User("Fourth", "User4"));

        add(grid);
    }

    private static class User {

        private String firstName;
        private String lastName;

        public User(String firstName, String lastName) {
            this.firstName = firstName;
            this.lastName = lastName;
        }

        public String getLastName() {
            return lastName;
        }

        public String getFirstName() {
            return firstName;
        }

    }

}
```

### Steps to reproduce

Make viewport width smaller than 1110 px. Then scroll all the way to the right and resize second column. 
=> Everything works fine.

Make viewport width bigger then 1110 px. Now the frozen columns changed into something like a inline variant. Resize the second column or make the screen even wider
=> frozen to end columns are not frozen anymore but look like ordinary columns.

### Environment

Vaadin version(s): 23.1.2

### Browsers

Chrome

**Comment by web-padawan** [comment]
> Now the frozen columns changed into something like a inline variant.

This is expected and also happens with `.setFrozen(true)`: when there is no horizontal scroll overflow involved (all the columns fit into the viewport), the border color for frozen colors is set to transparent - see [Lumo styles](https://github.com/vaadin/web-components/blob/b216a802c96bc81b559a6c1ba3c9ced412063b5a/packages/grid/theme/lumo/vaadin-grid-styles.js#L297-L312) for grid.

You can update your custom theme to always show the border for frozen columns as follows:

```css
  [part~='cell'][last-frozen]:not([part~='details-cell']) {
    border-right-color: var(--_lumo-grid-border-color);
  }

  [part~='cell'][first-frozen-to-end]:not([part~='details-cell']) {
    border-left-color: var(--_lumo-grid-border-color);
  }
```

Also note that corresponding [RTL styles](https://github.com/vaadin/web-components/blob/b216a802c96bc81b559a6c1ba3c9ced412063b5a/packages/grid/theme/lumo/vaadin-grid-styles.js#L378-L394) need to be overridden in case if RTL support is needed.

**Comment by timbo86** [comment]
But should that not change back to overlapping variant, when a column is resized, so that the horizontal scrollbar appears again?

**Comment by web-padawan** [comment]
When resizing a column to make it smaller, while grid width is the same, the following happens with column frozen to end:

https://user-images.githubusercontent.com/10589913/181700128-16447bbb-dd39-49bd-bd99-716193020ea7.mp4

This happens because after resizing, the column no longer expands to full available width, even after grid gets resized.
Do I understand the problem correctly that it's the problem that you described?

**Comment by timbo86** [comment]
Yes, that looks like the cells aren't frozen anymore.

Also I found another problem within the scroll calculation in vaadin-grid-scroll-mixin.js function __updateHorizontalScrollPosition:
I'm kind of stuck in that function, because transforming to -1px remaining px would lead the function to be called again with 0 remaining px and then again with -1px and so on.

Currently I can't reproduce in an easified code example, but will try to. Seems like the border width is interfering here and it keeps changing from the variant in your video to sticky and back continously.

**Comment by yuriy-fix** [comment]
Would be good to check existing implementations of this behaviour.

**Comment by ugur-vaadin** [comment]
When a column is resized, it fixes the widths of the resized column and all the columns to its left, setting their `flexGrow` to 0. If the resized column is the last column before the column frozen to the end, the columns cannot widen anymore. Therefore, the column frozen to the end can only go as far as the sum of the widths of the previous columns. This is the case for both the web component and the Flow component.

The solutions I can think of are behaviour altering and require design input. One possible solution is not to set any non-zero `flexGrow` to zero if it will leave no columns with non-zero `flexGrow` if there is a column that is frozen to the end. Another possible solution is to leave at least one column with non-zero `flexGrow` at all times. Some ideas for the column to leave with non-zero `flexGrow`:
- the column just before the column frozen to the end
- the column frozen to the end
- the last remaining column with non-zero `flexGrow` while setting them to zero

What do you think? @jouni @tomivirkki

**Comment by tomivirkki** [comment]
One possible solution/workaround could be to add the following style for `<vaadin-grid>`:

```css
[part~="cell"][first-frozen-to-end] {
    margin-inline-start: auto;
}
```

https://user-images.githubusercontent.com/1222264/199931595-d71aec39-e66f-4e43-ada7-13590ddde519.mp4

**Comment by jouni** [comment]
That workaround looks quite decent to me. At least better than the existing behavior.
