### ISSUE TITLE
Button keeps active state after setVisible(false) and then setVisible(true) again when using keyboard

### ISSUE THREAD

**Issue by mil3stone** [vaadin/flow-components#3552]
### Description

In my scenario, I have two buttons with some (business) logic including setting themselves to ```setVisible(false)``` and the other button to ```true``` when clicked.
If I press the buttons via keyboard (Space/Enter), the soon-to-be hidden button remains active and therefore keeps his styling once it is shown again. 
![image](https://user-images.githubusercontent.com/45229217/182862216-3060d66f-a895-44c8-bc04-154b0f02f177.png)

### Expected outcome

I expect the button to behave the same when using the keyboard like using the mouse and clicking the button. The hidden button should lose his active state.

### Minimal reproducible example

```
public class ButtonBugView extends HorizontalLayout {

    public ButtonBugView() {

        Button firstButton = new Button("first button");
        Button secondButton = new Button("second button");

        secondButton.setVisible(false);

        firstButton.addClickListener(e -> {
            firstButton.setVisible(false);
            secondButton.setVisible(true);
        });

        secondButton.addClickListener(e -> {
            firstButton.setVisible(true);
            secondButton.setVisible(false);
        });

        add(firstButton, secondButton);

    }

}
```

### Steps to reproduce

1. Use the snippet from above and press the first/second button **via keyboard**
2. Inspect the HTML or the style of the buttons

### Environment

Vaadin version(s): 23.1.4

### Browsers

Issue is not browser related

**Comment by web-padawan** [comment]
Thanks for the issue. Confirmed, can be reproduced in the web component using the following code:

```html
<vaadin-button>Button 1</vaadin-button>
<vaadin-button hidden>Button 2</vaadin-button>

<script type="module">
  import '@vaadin/button';

  const buttons = document.querySelectorAll('vaadin-button');

  buttons[0].addEventListener('click', () => {
    buttons[0].setAttribute('hidden', '');
    buttons[1].removeAttribute('hidden');
  });

  buttons[1].addEventListener('click', () => {
    buttons[1].setAttribute('hidden', '');
    buttons[0].removeAttribute('hidden');
  });
</script>
```
