### ISSUE TITLE
Regression: Lock screen when using combobox

### ISSUE THREAD

**Issue by jonasrotilli** [vaadin/flow-components#3553]
### Description of the bug

During normal use of a combobox sometimes the browser screen freezes. It becomes unusable, the browser memory goes up there and only comes back by closing the tab and opening it again.
See the image:

<img width="1304" alt="Captura de Tela 2022-08-04 às 09 44 30" src="https://user-images.githubusercontent.com/8934198/182867382-6855603a-e8c5-49ca-934e-3eccda833581.png">

### Expected behavior

Do not freeze at all.

### Minimal reproducible example

It's random. I've tried anyway to simulate, make different combinations and still haven't found exactly when it happens.
But it happens in production and in development.
It's no connection, no memory (mac 16g) with nothing open. 
Happened on windows, mac, it's not system.
No message in the server log and in the browser nothing appears.
My combobox is fed by a list only once.
It has addValueChangeListener, which shouldn't be a problem since the problem happens while typing without selecting.

### Versions

- Vaadin / Flow version: 23
- Browser version (if applicable): Chrome

**Comment by web-padawan** [comment]
Thanks for the issue. Could you please share a code example of how the ComboBox is populated with the data?

**Comment by jonasrotilli** [comment]
> Obrigado pelo problema. Você poderia compartilhar um exemplo de código de como o ComboBox é preenchido com os dados?

I declare the combobox like this:

`private ComboBox<Entity> cbxEntidadeDetalhe = new ComboBox<>("name");`

Before adding it to the screen, I set this:

```
  cbxEntidadeDetalhe.setItemLabelGenerator(Entity::raz_name);
  cbxEntidadeDetalhe.setRequiredIndicatorVisible(true);
```

And to set data:

`cbxEntidadeDetalhe.setItems(EntidadeList.stream().filter(obj -> obj.isAtivo() && obj.getId_company() != null && obj.getId_company().equals(VaadinSession.getCurrent().getAttribute(Company.class) .getId())).collect(Collectors.toList()));
`

In this combobox they don't have any more code, it doesn't have addValueChangeListener in it.

**Comment by sissbruecker** [comment]
Unfortunately the issue is not reproducable from the provided code snippets. Please provide a full reproduction that demonstrates the issue.

**Comment by jonasrotilli** [comment]
> Infelizmente, o problema não pode ser reproduzido a partir dos trechos de código fornecidos. Forneça uma reprodução completa que demonstre o problema.

If it was something predictable, static I would have fixed it.
But it's not, it's unpredictable.

**Comment by jonasrotilli** [comment]
![WhatsApp Image 2022-08-15 at 14 19 37](https://user-images.githubusercontent.com/8934198/184693028-6d3ac2b5-612c-4f1a-9302-9983af6d73a3.jpeg)
It keeps happening. If anyone else has this problem, please help me and let me know.
I don't do anything different, it shouldn't be my application.

**Comment by knoobie** [comment]
Your code looks really ineffective. Not sure if this is a problem, but you can move the call 

VaadinSession.getCurrent().getAttribute(Company.class) .getId())

out of the stream to improve the performance

**Comment by jonasrotilli** [comment]
> Seu código parece realmente ineficaz. Não tenho certeza se isso é um problema, mas você pode mover a chamada
> 
> VaadinSession.getCurrent().getAttribute(Company.class) .getId()
> 
> fora do fluxo para melhorar o desempenho

I'll move it, but the setItem call only happens the first time it loads on the screen.
The list of items is not changed anymore, it makes no sense to hamper the use of the combobox.

In addition, it happens in several other combobox and randomly and some comobox doesn't even use anything from the Session in the setItem.

Another customer report:

![WhatsApp Image 2022-08-17 at 07 29 49](https://user-images.githubusercontent.com/8934198/185112000-07f1460a-f8e5-4c08-b315-87c90bf20af2.jpeg)
:

**Comment by jonasrotilli** [comment]
Many reports.
Memory left on the server.
Connection ok.
No messages in Log.
I need some direction for the investigation... Please help me!

![WhatsApp Image 2022-08-17 at 08 53 41](https://user-images.githubusercontent.com/8934198/185138375-a8ee0a5b-cfa6-4461-9ac7-762383e423f8.jpeg)

**Comment by rolfsmeds** [comment]
I see that's a public URL – would it be possible for you to provide a login so that the issue could be tested directly in the app?

**Comment by jonasrotilli** [comment]
> Vejo que é uma URL pública. Você poderia fornecer um login para que o problema pudesse ser testado diretamente no aplicativo?

Yes, I will send it to your email.

Aproveitando, mais um relato:

![WhatsApp Image 2022-08-18 at 07 02 40](https://user-images.githubusercontent.com/8934198/185383468-8693b2cb-7631-492b-8ef1-fac85df8c9a8.jpeg)

**Comment by rolfsmeds** [comment]
Seems to be reproducible with 23.1.2 but not 23.1.0, so possibly a regression, possibly caused by https://github.com/vaadin/web-components/pull/4040

**Comment by vursen** [comment]
It is indeed a regression caused by https://github.com/vaadin/web-components/pull/4040. The browser freezes because it seems to fall into an infinite recurring:

<img width="781" alt="image" src="https://user-images.githubusercontent.com/5039436/188881722-6fe8e5cb-aa1e-49b8-8414-b923e5b12bf5.png">

**Comment by jonasrotilli** [comment]
To complete:
I went back to version 23.1.0 and it improved a lot.
But I noticed that it happened again (less often than before).
I haven't made any changes lately and we've received some feedback of the issue reoccurring (infinitely less frequently than before).
I mention this now because maybe it's not only in version 23.1.2.

**Comment by vursen** [comment]
Hey @jonasrotilli!

Please, try out the fix in the upcoming v23.1.8 to see if it solves your issue.

**Comment by jonasrotilli** [comment]
Unfortunately bad news. The problem reoccurred.
I'm using version 23.2.3.


![WhatsApp Image 2022-11-08 at 10 44 54](https://user-images.githubusercontent.com/8934198/200595475-458089aa-29f5-4536-8ec8-b066386da88b.jpeg)

**Comment by web-padawan** [comment]
@jonasrotilli Could you please provide a code example of how you use `ComboBox` so we can investigate further?

**Comment by jonasrotilli** [comment]
> > Obrigado pelo problema. Você poderia compartilhar um exemplo de código de como o ComboBox é preenchido com os dados?
> 
> I declare the combobox like this:
> 
> `private ComboBox<Entity> cbxEntidadeDetalhe = new ComboBox<>("name");`
> 
> Before adding it to the screen, I set this:
> 
> ```
>   cbxEntidadeDetalhe.setItemLabelGenerator(Entity::raz_name);
>   cbxEntidadeDetalhe.setRequiredIndicatorVisible(true);
> ```
> 
> And to set data:
> 
> `cbxEntidadeDetalhe.setItems(EntidadeList.stream().filter(obj -> obj.isAtivo() && obj.getId_company() != null && obj.getId_company().equals(VaadinSession.getCurrent().getAttribute(Company.class) .getId())).collect(Collectors.toList())); `
> 
> In this combobox they don't have any more code, it doesn't have addValueChangeListener in it.

We didn't make any changes, just change the version.
This same example continues.
