### ISSUE TITLE
Dialog loses its focus when clicking inside - focus falling back to body element

### ISSUE THREAD

**Issue by mil3stone** [vaadin/flow-components#3564]
### Description

When opening a ```Dialog```, the focus initially moves to ```vaadin-dialog-overlay#overlay```. After clicking inside on e.g. a label, the focus falls back to ```body``` which causes the focus cylce to be out of order.
I have to press TAB twice to get to the first tabbable control inside the dialog. Please see the attached gif. 

This also affects key listeners whose execution is dependant on the focused view: Main view in background or modal view in ```Dialog```. The listeners from the main view won't fire because of the modal curtain (this is correct behaviour). The listeners inside the ```Dialog``` won't react since the focus isn't placed correctly (this is false behavior).

![2022-08-08_12h51_03](https://user-images.githubusercontent.com/45229217/183406431-877ef781-d403-4993-9b08-50675f1542a5.gif)

### Expected outcome

When clicking inside the ```Dialog``` the focus remains on ```vaadin-dialog-overlay#overlay``` so that I don't have to press TAB more than expected and so that context sensitive listeners will fire.

### Minimal reproducible example

Just use the given example from Vaadin's demo page:
https://vaadin.com/docs/latest/example?embed=dialog-closing-wc.js&import=component/dialog/dialog-closing.ts

### Steps to reproduce

1. click the provided link
2. click button to open the modal window
3. verify the active element inside the dev tools
4. click inside the dialog and re-verify the active element

### Environment

Vaadin version(s): I guess the examples were built with the latest version (?)

### Browsers

Chrome

**Comment by web-padawan** [comment]
Thanks for the issue. This could be workarounded by changing [`mousedown` listener](https://github.com/vaadin/web-components/blob/d24f64f977cc0d2ef2c706c25f6f1aa92ea4719e/packages/vaadin-overlay/src/vaadin-overlay.js#L466-L468) to add the following code:

```js
  if (this._mouseDownInside) {
    event.preventDefault();
  }
```

However, in this case the focus will stay where it previously was (e.g. on the `vaadin-button` element inside the overlay). So we might want to detect if `mousedown` is not on a focusable element, and focus the overlay itself in this case.

**Comment by web-padawan** [comment]
Closing in favor of #5507 which is essentially a duplicate.
