### ISSUE TITLE
When returning from a second Dialog, the parent Dialog isn't the active element anymore.

### ISSUE THREAD

**Issue by mil3stone** [vaadin/flow-components#3565]
### Description

Maybe the cause for this behavior is the same as in #3564, then please ignore/close this bug report.

I got a ```Dialog``` which I open from another ```Dialog```. When closing the second ```Dialog```, the focus/active element falls back to ```body``` instead to the first ```Dialog```.

![2022-08-08_13h50_53](https://user-images.githubusercontent.com/45229217/183411718-b60b575c-064c-4bcb-aca6-2d2652eb959e.gif)

### Expected outcome

When closing the second ```Dialog```, I'd expect the active element falling back to the first ```Dialog```.

### Minimal reproducible example

```java
public class DialogBugView extends HorizontalLayout {

    public DialogBugView() {
        Button firstButton = new Button("open dialog", e -> createAndOpenFirstDialog());
        add(firstButton);
    }

    public void createAndOpenFirstDialog() {
        Dialog dialog = new Dialog();
        Label lbl = new Label("this is some text");
        Button openSecondDialogButton = new Button("open second dialog", e -> createAndOpenSecondDialog());
        Button close = new Button("close", e -> dialog.close());

        dialog.add(lbl, close, openSecondDialogButton);

        dialog.open();
    }

    public void createAndOpenSecondDialog() {
        Dialog dialog = new Dialog();
        Label lbl = new Label("this is some text");
        Button close = new Button("close", e -> dialog.close());

        dialog.add(lbl, close);

        dialog.open();
    }
}
```

### Steps to reproduce

using the given example, click on "open dialog" to open dialog. Next, open the second one and close it.

### Environment

Vaadin version(s): 23.1.4
OS: 

### Browsers

Issue is not browser related

**Comment by web-padawan** [comment]
Restoring focus is kind of a missing feature in the `vaadin-dialog` web component: https://github.com/vaadin/web-components/issues/139
In this particular case, the focus should be probably restored to a button in the first dialog that was clicked.

**Comment by TatuLund** [comment]
I would assume this should be closed by https://github.com/vaadin/web-components/pull/5837 ?

**Comment by mil3stone** [comment]
The comment in [#5837](https://github.com/vaadin/web-components/pull/5837) states that it is targeting release 24.1.0.
Based on this information I have to say this PR does not resolve the focus issue as I can still reproduce it on a fresh start.vaadin.com project with 24.1.0, sadly.

**Comment by vursen** [comment]
I can confirm that it doesn’t work in 24.1.0, despite this version including the web component focus restoration fix. 

It appears there was [another Dialog issue](https://github.com/vaadin/web-components/pull/5995) that had to be resolved to make the focus restoration finally work. In the latest version 24.1.2, everything works as expected, so I'm closing the issue.
