### ISSUE TITLE
Vaadin 23.0.1 checkbox group does not represent the values selected on the edit mode 

### ISSUE THREAD

**Issue by mozau** [vaadin/flow-components#3582]
### Description

the Binder writes correctly the object with all items selected on the CheckboxGroup,

![treatment-form-mode-ADD](https://user-images.githubusercontent.com/110307809/184108876-01ac542a-4f98-494d-96ea-75fbad07f152.png)

The issue is with the Binder at the time of reading the object, does not represent the selected values ​​on the CheckboxGroup.

![treatment-form-mode-EDIT-id-dt-29cea9a9-4704-4f63-97ce-f8987abc4461](https://user-images.githubusercontent.com/110307809/184111113-27099870-7ed9-4173-8dc2-b7543f6d7bed.png)

Versions
Vaadin / Flow version 23.0.2
Java version JDK-11.0.9
OS version Windows 10
Browser version Google Chrome 104.0.5112.81 (Build Officiel) (64 bits)

### Expected outcome

I would expect the CheckboxItem will be checked, instead of that it didn't

### Minimal reproducible example

permissions = new CheckboxGroup<>();
        permissions.setLabel(Translator.translate("page.dataTreatments.permissions.label"));
        permissions.setItems(refDataPermissions);

binder.forField(permissions).withConverter(new StringToRefDataConverter(refDataPermissions)).bind(CategoriesOfPersonsConcerned::getPermissions, CategoriesOfPersonsConcerned::setPermissions);

### Steps to reproduce

Example :
public class form extends VerticalLayout {
 private static final String A = "A";
    private static final String B = "B";
    private static final String C = "C";
    private CheckboxGroup<String> permissions;
private Binder<ObjectExample > binder;
    private void init() {
        permissions = new CheckboxGroup<>();
        permissions.setLabel("Test");
        permissions.setItems(A,B,C);
        permissions.setValue(Set.of(A));
        informationProcessTowardsInvolvedParties = new 
        add(permissions);
    }

    public void setBinder() {
        binder = new Binder<>(ObjectExample.class);
    binder.forField(permissions).bind(ObjectExample::getPermissions, ObjectExample::setPermissions);
    }

    public void read(ObjectExample example) {
            binder.readBean(example);
    }

    public Optional<example> write() {
        ObjectExample example= new ObjectExample ();
        try {
            binder.writeBean(example);
            return Optional.of(example);
        } catch (ValidationException e) {
            log.error("Error bind  item cause : [{}] ", e.getValidationErrors().stream().map(ValidationResult::getErrorMessage).collect(Collectors.joining("|")));
        }
        return Optional.empty();
    }
}

### Environment

Vaadin version(s): 23.0.2
OS: version Windows 10

### Browsers

Chrome

**Comment by ugur-vaadin** [comment]
@mozau Can you please elaborate on the minimal reproducible example? The example code contains incomplete parts and references to other methods and fields. I could not reproduce the issue based on this example.

**Comment by sissbruecker** [comment]
Did test this with a basic example, and it works as expected:

```java
public class CheckBoxGroupBinderRead extends Div {

    public CheckBoxGroupBinderRead() {
        CheckboxGroup<String> permissions = new CheckboxGroup<>("Permissions", "A", "B", "C");
        Entity entity = new Entity();
        Binder<Entity> binder = new Binder<>(Entity.class);
        binder
                .forField(permissions)
                .bind(Entity::getPermissions, Entity::setPermissions);

        Button updatePermissions = new Button("Update Permissions", e -> {
            entity.setPermissions(Set.of("A", "B"));
            binder.readBean(entity);
        });

        add(permissions, updatePermissions);
    }

    private static class Entity {
        private Set<String> permissions = new HashSet<>();

        public Set<String> getPermissions() {
            return permissions;
        }

        public void setPermissions(Set<String> permissions) {
            this.permissions = permissions;
        }
    }
}
```

As the code provided in the OP uses a converter, I would advise to check its implementation, maybe the value mapping is not working correctly.

Otherwise, as mentioned above, please provide a full minimal reproducable example that demonstrates the issue.

**Comment by yuriy-fix** [comment]
Closing as stale.
