### ISSUE TITLE
SplitLayout: Removing and adding a new Component to the Secondary breaks EventListeners in Primary

### ISSUE THREAD

**Issue by simasch** [vaadin/flow-components#3586]
### Description

If I remove the secondary component from the SplitLayout and add a new component the EventListeners in Primary stop working.

### Expected outcome

Removing and adding should not break anything.

### Minimal reproducible example

```
@PageTitle("Split")
@Route(value = "split", layout = MainLayout.class)
public class SplitView extends SplitLayout {

    public SplitView() {
        Grid<String> grid = new Grid<>();

        grid.addColumn(s -> s);
        grid.addComponentColumn(s -> new Button(s, event -> {
            Notification.show("Hello from " + s);
            if (s.equals("C")) {
                remove(getSecondaryComponent());
                addToSecondary(new Span("New Right"));
            }
        }));

        grid.setItems(List.of("A", "B", "C"));

        addToPrimary(grid);
        addToSecondary(new Span("Right"));
    }
}
```

### Steps to reproduce

After clicking the Button on Row C the EventListener of the Button is no longer called

### Environment

Vaadin version(s): 23.1.3
OS: any

### Browsers

Issue is not browser related

**Comment by TatuLund** [comment]
The workaround is to call `refreshAll();`

`@PageTitle("Split")
@Route(value = "split", layout = MainLayout.class)
public class SplitView extends SplitLayout {

    public SplitView() {
        Grid<String> grid = new Grid<>();

        grid.addColumn(s -> s);
        grid.addComponentColumn(s -> new Button(s, event -> {
            Notification.show("Hello from " + s);
            if (s.equals("C")) {
                remove(getSecondaryComponent());
                addToSecondary(new Span("New Right"));
                grid.getDataProvider().refreshAll();
            }
        }));

        grid.setItems(List.of("A", "B", "C"));

        addToPrimary(grid);
        addToSecondary(new Span("Right"));
    }
}
`

**Comment by simasch** [comment]
grid.getDataProvider().refreshAll(); would have side effects depending what the dataprovider does.

A viable workaround is to add a Div to the secondary and remove and add components to that Div

**Comment by TatuLund** [comment]
The culprit is here: https://github.com/vaadin/flow-components/blob/master/vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java#L270

Adding to secondary actually means that primary is detached and re-added. Thus rendered components need to be generated as well as they were detached with the Grid.

**Comment by TatuLund** [comment]
> A viable workaround is to add a Div to the secondary and remove and add components to that Div

This is how it actually works.

**Comment by simasch** [comment]
From a user perspective this is a bug!
How should I know that the component behaves like this?
Exchanging one side of the SplitLayout shouldn't affect the other side.

**Comment by sissbruecker** [comment]
> The culprit is here: https://github.com/vaadin/flow-components/blob/master/vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java#L270
> 
> Adding to secondary actually means that primary is detached and re-added. Thus rendered components need to be generated as well as they were detached with the Grid.

That looks pretty sketchy, I agree that we should not unnecessarily detach / reattach components, which can have several side-effects and performance implications.

**Comment by TatuLund** [comment]
> From a user perspective this is a bug!

Yes. I was just contemplating whether this is a bug in Grid or SplitLayout ... Or perhaps both.
