### ISSUE TITLE
Add java constants for Grid editable cell theme variants

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/flow-components#3613]
### Describe your motivation

Theme variants for distinguishing editable cells were added in https://github.com/vaadin/web-components/pull/2309, but apparently we forgot to add constants to these to the `GridVariant` enum.

### Describe the solution you'd like

Add corresponding constants to `GridVariant`

**Comment by web-padawan** [comment]
These theme variants belong to GridProVariant, not GridVariant. They were added in #2971.
