### ISSUE TITLE
[Grid] In memory Grid with SelectAllCheckboxVisibility.VISIBLE ignores filter on selectAll

### ISSUE THREAD

**Issue by aley2003** [vaadin/flow-components#3614]
### Description

I have a Grid with a ListDataProvider.
I use ListDataView.setFilter() to set a filter.
The SelectAllCheckBox is visible by default.
The filter filters out some items of the ListDataView.
But a click on the selectAll checbox selects all items in the ListDataView. getSelectedItems() returns all items.

### Expected outcome

A click on the SelectAll CheckBox should not select the filtered out items.

### Minimal reproducible example

````java
private Grid<Data> createGrid() {
        final List<Data> data = new ArrayList<>();
        for(int i=1; i<=5; i++) data.add(new Data(i,"Name"+i));

        final Grid<Data> grid = new Grid<>();
        grid.addColumn(Data::getId).setHeader("Id");
        grid.addColumn(Data::getName).setHeader("Name");
        grid.setSelectionMode(Grid.SelectionMode.MULTI);
        ListDataView<Data, ?> dataView = grid.setItems(data);
        dataView.setFilter(d -> d.getId() < 3);
        grid.addSelectionListener(e -> System.out.println("Selected count: " + e.getAllSelectedItems().size()));
        return grid;
    }
````

### Steps to reproduce

1. Add Grid above to view
2. Click on select all CheckBox
3. Console shows 'Selected count: 5' instead of 'Selected count: 2'

### Environment

Vaadin version(s): 23.1.6
OS: Windows

**Comment by franz-stoetzner** [comment]
is there any way to work around this issue?

**Comment by simasch** [comment]
Instead of filtering the Grid you could filter the list and setItems with the filtered list

**Comment by rkovarik** [comment]
Hi @franz-stoetzner,

you can set the filter directly on the data provider like this:
```
var dataProvider = new ListDataProvider<>(data);
dataProvider.setFilter(d -> d.getId() < 3);
GridListDataView<Data> dataView = grid.setItems(dataProvider);
```
Hope that helps 🤞 
Roman

**Comment by franz-stoetzner** [comment]
thanks @rkovarik - gonna try

**Comment by aley2003** [comment]
I have tested with Vaadin 23.2.1. 
SelectAllCheckbox seems to work correctly with ListDataProvider setFilter().
It fails with GridListDataView.setFilter(),
