### ISSUE TITLE
Provide a global API for controlling the stickiness of required indicators.

### ISSUE THREAD

**Issue by johannest** [vaadin/flow-components#3620]
### Describe your motivation

The required indicator in the FormLayout behaves differently in Vaadin 14 and 23. It is sticky in 23 but non sticky in 14. 

### Describe the solution you'd like

For example the following API which is implemented in EnhancedFormLayout (https://github.com/vaadin-component-factory/enhanced-form-layout/blob/master/src/main/java/com/vaadin/componentfactory/EnhancedFormLayout.java#L140)

```
/**
 * Normally required indicator disappears after user gives a value. You can
 * change this by setting stickyIndicator = true.
 * 
 * @param stickyIndicator
 *            A boolean value
 */
public void setStickyIndicator(boolean stickyIndicator)
```

### Describe alternatives you've considered

EnhancedFormLayout has this kind of API already. But customers would benefit of having this in the core FormLayout to minimize the risks of out of date add-on when migrating to upcoming Vaadin versions.

**Comment by web-padawan** [comment]
The change to required indicators landed in 23.1.0 is not specific to FormLayout, see https://github.com/vaadin/web-components/pull/3619.
So, the current behavior applies to all form field components that use Lumo. As per the original PR description:

> I would not provide any explicit API, like a CSS custom property, for controlling this behavior.

**Comment by johannest** [comment]
@web-padawan good point, I'll edit this ticket

**Comment by rolfsmeds** [comment]
Since this is a purely visual feature, a CSS property could suffice as API, provided that FormItem would reflect the `has-value` attribute on the nested input field. E.g.

--vaadin-required-indicator-sticky: 0;  // Non-sticky
--vaadin-required-indicator-sticky: 1;  // Sticky

(The value could be directly used as opacity in the relevant stylesheets.)

**Comment by jouni** [comment]
I haven't heard the need to introduce this API, other than “it exists in `EnhancedFormLayout`” which I assume was for the opposite reason, to keep the indicators always visible. I haven't heard anyone asking for a way to get back the old default behavior. @johannest, have you?

**Comment by jouni** [comment]
That’s all I wanted to hear, that there is at least one user/customer who wants/needs this API.

**Comment by johannest** [comment]
Discussed with my customer, this can be closed since there is good enough instructions for this here: https://vaadin.com/docs/latest/upgrading/essential-steps/#miscellaneous-changes
