### ISSUE TITLE
Testbench: UploadElement#waitForUploads is not working as expected

### ISSUE THREAD

**Issue by AB-xdev** [vaadin/flow-components#3646]
### Description

We've had some random ScriptTimeoutExceptions in the past when trying to upload something with the ``UploadElement`` despite the upload being successful.

There seems to be a problem inside https://github.com/vaadin/flow-components/blob/ed8011f6d12d504d150f52845ce650831d06e604/vaadin-upload-flow-parent/vaadin-upload-testbench/src/main/java/com/vaadin/flow/component/upload/testbench/UploadElement.java#L131-L149

#### Problem description
This method set's Selenium's script timeout to ``maxSeconds`` (default ``60``).
However the whole script that checks if the uploads are finished is executed only once: After 500ms with ``setTimeout``.
So if the upload isn't finished after ``500ms`` (it may be finished after e.g. ``700ms``) the ``callback()`` is never executed, thus Selenium throws ``ScriptTimeoutException``.

#### Applied workaround
```java
public void waitForUploads(final int maxSeconds)
{
      final WebDriver.Timeouts timeouts = this.getDriver().manage().timeouts();
      timeouts.scriptTimeout(Duration.ofSeconds(maxSeconds));
      
      final String script = "var callback = arguments[arguments.length - 1];"
	      + "var upload = arguments[0];"
	      + "function checkUploads(counter) {"
	      + "  if (counter > " + (maxSeconds * 5) + ") return;"
	      + "  window.setTimeout(function() {"
	      + "    var inProgress = upload.files.filter(function(file) { return file.uploading;}).length > 0;"
	      + "    if (!inProgress) {"
	      + "      callback();"
	      + "    } else {"
	      + "      checkUploads(++counter);"
	      + "    }"
	      + "  }, 195);"
	      + "};"
	      + "checkUploads(0);";
      this.getCommandExecutor().getDriver().executeAsyncScript(script, this);
}
```

### Expected outcome

Upload works, even when it takes more than ``500ms``

### Minimal reproducible example

```java
this.$(UploadElement.class).first().upload(file);
```

### Steps to reproduce

Upload anything with ``UploadElement#upload``. The upload should take longer than 1s (e.g. slower PC, bigger file, etc).
Hint: We use [Testcontainers](https://www.testcontainers.org/modules/webdriver_containers/) so a RemoteWebdriver is used.

### Environment

Vaadin version(s): 23.1.7
OS: -

**Comment by mcollovati** [comment]
This issue also randomly affects a test in Flow. The workaround was to similar to the one in the issue description, but using `setInterval`.

```javascript
    private void waitForUploads(UploadElement element, int maxSeconds) {
        WebDriver.Timeouts timeouts = getDriver().manage().timeouts();
        timeouts.scriptTimeout(Duration.ofSeconds(maxSeconds));

        String script = """
                var callback = arguments[arguments.length - 1];
                var upload = arguments[0];
                let intervalId;
                intervalId = window.setInterval(function() {
                  var inProgress = upload.files.filter(function(file) { return file.uploading;}).length >0;
                  if (!inProgress) {
                    window.clearInterval(intervalId);
                    callback();
                  }
                }, 500);
                """;
        getCommandExecutor().getDriver().executeAsyncScript(script, element);
    }
```
