### ISSUE TITLE
error in Vaadin Menu Bar: Cannot read properties of undefined (reading 'generateItemsTree')

### ISSUE THREAD

**Issue by kannan-manickam-idexx** [vaadin/flow-components#3655]
### Description

I added menu bar and it works fine when there's no microsoft azure or spring security authentication but when these auth are in place then I get this error.

error in Vaadin Menu Bar: Cannot read properties of undefined (reading 'generateItemsTree')

When I go directly to those menu url then I get multiple of there undefined error

My vaadin version is 23.1.3

It works in Linus OS though

### Expected outcome

No error and show the page

### Minimal reproducible example

private class MenuComponent : MenuBar() {
    init {
        setId(ID_MENU)
        item("Link 1", {
            navigateTo<Link1>()
        })
        item("Link2", {
            navigateTo<Link2>()
        })
    }
}

### Steps to reproduce

Add the code snippet above and have a Spring basic auth and run gradlew bootRun, after the authentication there will be a js popup with this error

### Environment

Vaadin version(s): 23.1.3
OS: Windows

**Comment by yuriy-fix** [comment]
We could consider adding a context-menu's connector import within menu-bar's connector.

**Comment by vursen** [comment]
Hello @kannan-manickam-idexx!

Could you please guide me on how exactly I should configure Spring Basic Auth for the issue to reproduce? A minimal reproducible example would be helpful. 

Your issue might be caused by a wrong configuration that doesn't allow frontend requests including those to Flow connectors. Did you make sure your auth configuration extends `VaadinWebSecurity`? For more details, check out https://vaadin.com/docs/latest/security/enabling-security.

**Comment by kannan-manickam-idexx** [comment]
Hi @vursen

**Comment by vursen** [comment]
@kannan-manickam-idexx Unfortunately, the cause is still not clear from what you have shared so far. Could you please share an application that we could run locally to reproduce the issue?

**Comment by kannan-manickam-idexx** [comment]
@vursen Are you asking me for a sample application that you can just import in your ide and see the error? As I said I'm using some of our own libraries that takes care of authentication which I cant expose.

**Comment by kannan-manickam-idexx** [comment]
I see this issue is closed, does that mean a fix was released? If so which version of vaadin should I use

**Comment by vursen** [comment]
> I see this issue is closed, does that mean a fix was released? If so which version of vaadin should I use

I made a fix that we guess might solve your issue. It will be included in the upcoming 23.1.11 release. Please, try it out and comment here.

**Comment by kannan-manickam-idexx** [comment]
Thanks @vursen Do you know when this 23.1.11 version will be released?

**Comment by vursen** [comment]
> I guess the version should be 23.2.11, right? 

Sorry for the confusion. I meant the Flow Components 23.1.11 release. 

> Do you know when this 23.2.11 version will be released?

I think this Friday. You can follow [releases](https://github.com/vaadin/flow-components/releases) here.
