### ISSUE TITLE
Description (tooltip) generator for Grid

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/flow-components#3658]
### Describe your motivation

Vaadin 8's Grid has the `DescriptionGenerator`, which allows you to produce a custom tooltip for each row. It would be nice to have a similar feature for Flow. 

### Describe the solution you'd like

It could work similarly to Vaadin 8's `Grid::setDescriptionGenerator`; essentially, the input is the current row's Bean and the output is the text to be displayed when the mouse hovers over the row. Plain text would be the minimum viable product, preformatted or HTML would be nice extras.

### Describe alternatives you've considered

You can kind of do the same with a TemplateRenderer which wraps everything with a `<div title="..."></div>`, but that's a lot of extra work and becomes more complex if you want some other Renderer.

**Comment by web-padawan** [comment]
The PR for web component adding support for `vaadin-tooltip` is now merged: https://github.com/vaadin/web-components/pull/4416
Moved the issue to Flow components so we can use it for adding `setTooltipTextGenerator`, see [prototype](https://github.com/vaadin/flow-components/commit/9f0bd38efa41ee3ef6734f17b1985607347ddfc2#diff-513c3888098b26dd5c8ecf4562dcf57719c971038b94bc75cdcdd8ffb5d651a7R35).

**Comment by tomivirkki** [comment]
Covered by https://github.com/vaadin/flow-components/pull/3718
