### ISSUE TITLE
The dropdown of a read-only MultiSelectComboBox is empty

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/flow-components#3684]
### Description

The dropdown of a read-only `MultiSelectComboBox` is empty

https://user-images.githubusercontent.com/1222264/189130664-f9ae8cbe-b7f1-42b9-ab33-429b0c111ba6.mp4

### Expected outcome

The dropdown should include the list of the selected item

### Minimal reproducible example

https://vaadin.com/docs/latest/components/multi-select-combo-box/#read-only

### Steps to reproduce

1. Open the [read-only example](https://vaadin.com/docs/latest/components/multi-select-combo-box/#read-only) (Java)
2. Open the combo-box's dropdown

### Environment

Vaadin version: 23.2

### Browsers

Issue is not browser related

**Comment by web-padawan** [comment]
> An obvious solution seems to be ignoring clearCache() calls when the field is read-only.

Yes, this sounds like a valid solution to me 👍
