### ISSUE TITLE
Multi-Select ComboBox with a lot of items and chip: selected not easily human readable

### ISSUE THREAD

**Issue by fabst2w** [vaadin/flow-components#3692]
### Description

When in a Multi-Select ComboBox with some hundreds of items a user selects e.g. three items, then the ComboBox shows the first items chipped.
The chipped items are not readable (at least I haven't found an easy way to read them).
When the user opens the ComboBox, all of the the three previously selected items are marked with a check sign (which is correct), but the user has to search for them, which is not easy in a ComboBox with a lot of items.
This is how the ComboBox looks like:
![image](https://user-images.githubusercontent.com/59484106/189494049-a4e2b1c8-b955-4a3e-a15f-d2e62833ae19.png)

### Expected outcome

The user should easily read the selected items.
One approach is to not use the chip and show the selected items multi-row.
Another approach is to order the selected items to the top.
Another approach could be to show the selected items as a tooltip when hovering / clicking the chip.

### Minimal reproducible example

Go to https://vaadin.com/docs/latest/components/multi-select-combo-box
Select some items. Some of them at the beginning of the list, some in the middle and some of them at the end of the itm list.

### Steps to reproduce

Go to https://vaadin.com/docs/latest/components/multi-select-combo-box
Select some items. Some of them at the beginning of the list, some in the middle and some of them at the end of the itm list.

### Environment

Vaadin version(s): 23.2
OS: Ubuntu 22.04, Chromium 105

**Comment by knoobie** [comment]
You can hover over them.

**Comment by fabst2w** [comment]
Oh yes, you are right.
Sorry for that.

**Comment by knoobie** [comment]
The other part of your enhancement request can be found here https://github.com/vaadin/web-components/issues/4185 if you wanna leave an upvote there.

**Comment by fabst2w** [comment]
Done. :-)
