### ISSUE TITLE
Upload component does not show Upload dialog on clicking 'Upload' button

### ISSUE THREAD

**Issue by finaris-cs** [vaadin/flow-components#3699]
### Description

When clicking the 'Upload' button, the dialog to select files from local disk is not shown.
Does not happen always, but sometimes and is very annoying, as Uploading only works via DND then, so the component is not broken, but the dialog opening is.

When debugging this, the following method is entered in both cases (working & broken):

```
        _onAddFilesClick(e) {
            this.maxFilesReached || (e.stopPropagation(),
            this.$.fileInput.value = "",
            this.$.fileInput.click())
        }
```

An interesting observation we made during debugging:
When setting a breakpoint to the last line of the method above, and immediately continuing with execution, the Upload dialog nearly always comes up. When waiting 5 seconds, it NEVER came up. 
So there must be something wrong between entering this method and opening the dialog.

Browsers tested: Chrome and Edge

### Expected outcome

Always show up the file selection dialog

### Minimal reproducible example

Add an Upload control to you app

### Steps to reproduce

See description

### Environment

Vaadin version(s): 23
OS: Red hat linux, Windows

### Browsers

Chrome, Edge

**Comment by web-padawan** [comment]
@finaris-cs Could you please clarify this issue a bit? Does it only happen during debugging?

> When setting a breakpoint to the last line of the method above, and immediately continuing with execution, the Upload dialog nearly always comes up. When waiting 5 seconds, it NEVER came up.

Please keep in mind that browsers generally only react to **synchronouos** click events when opening file dialogs (or new windows using `window.open()`). This is done to ensure user has actually triggered this action.

So, if we change the code that you mentioned to use `setTimeout`, then browser will lose the original `click` event and disallow opening the upload dialog. This is exactly what happens when you wait for 5 seconds.

**Comment by finaris-cs** [comment]
Originally, we observed this problem during normal execution.
As said, it does not occur always, but sometimes. 
And when the functionality is broken, following clicks do not work either.
Affects all Upload components in out application, if one is affected, all are.
Refreshing the browser with F5 makes it work again.

We just entered the debugging to try gathering more information.
So what we can definitely say is that even when the button is not working anymore, the method above is entered, and no dialog comes up. 

Maybe the processing could exceed the timeout under normal circumstances, so that the click is lost?

**Comment by vursen** [comment]
Does it only arise in the recent version? I tried to reproduce it in Chrome / Edge on Windows but everything works fine for me. 

I wonder if the issue might be related to the fact that the input element is completely hidden with `display: none`. As an attempt to fix that, we might try hiding it another way, e.g. with `visibility: hidden` or `opacity: 0`.

**Comment by yuriy-fix** [comment]
Closing as stale. Feel free to open a new issue if still relevant.
