### ISSUE TITLE
[charts] Change SVGGenerator to not use webpack 4 to be compatible with Node 18 [1 day]

### ISSUE THREAD

**Issue by web-padawan** [vaadin/flow-components#3700]
### Describe your motivation

Currently, SVGGenerator runs `webpack` on `postinstall` step to compile `jsdom-exporter.js`

This causes a problem when using Node 18 because of the OpenSSL [compatibility issue](https://github.com/webpack/webpack/issues/14532):

![image](https://user-images.githubusercontent.com/10589913/189851898-1a93b15a-298c-406b-b958-010bf1082a65.png)

### Describe the solution you'd like

Replace webpack 4 with another bundler, e.g. Rollup. This should be a good fit for Vite users:

- it has less dependencies, as Vite uses parts of Rollup internally,
- it would avoid confusion related to webpack in the log output.

### Describe alternatives you've considered

Update to use webpack 5 which does not have this problem (smaller effort).

### Additional context

See internal discussion: https://vaadin.slack.com/archives/C3TGRP4HY/p1662983864606579

**Comment by sissbruecker** [comment]
This has been resolved with https://github.com/vaadin/flow-components/pull/3728
