### ISSUE TITLE
Grid and TreeGrid: Empty item lines after 10 x pageSize items.

### ISSUE THREAD

**Issue by enver-haase** [vaadin/flow-components#3708]
### Description

When I want to see all 600 root items in my demo application, I see only 20 because I set the page size to be 2.

### Expected outcome

I expect the page size to be only performance-related.

### Minimal reproducible example

```
package com.vaadin.qa.views.helloworld;


import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.treegrid.TreeGrid;
import com.vaadin.flow.function.ValueProvider;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.router.RouteAlias;
import org.apache.commons.lang3.RandomStringUtils;

import java.util.ArrayList;
import java.util.Random;

@PageTitle("Hello World")
@Route(value = "hello")
@RouteAlias(value = "")
public class HelloWorldView extends VerticalLayout {

    private class EnverNode {
        private final String eins;
        private final String zwei;

        public EnverNode(){
            eins = RandomStringUtils.randomAlphabetic(15);
            zwei = RandomStringUtils.randomAlphabetic(15);
        }

        public String getEins(){
            return eins;
        }

        public String getZwei(){
            return zwei;
        }
    }

    public HelloWorldView() {
        Random random = new Random();

        setSizeFull();;

        TreeGrid<EnverNode> treeGrid = new TreeGrid<>();
        treeGrid.setWidthFull();
        treeGrid.setAllRowsVisible(true);

        treeGrid.setPageSize(2); // TODO BROKEN: You will only see N * 10 items, followed by blank lines.

        ArrayList<EnverNode> enverNodes = new ArrayList<>();
        for (int i=0; i < 600; i++){
            enverNodes.add(new EnverNode());
        }
        treeGrid.getTreeData().addRootItems(enverNodes);

        for (int i=0; i<12000; i++){
            treeGrid.getTreeData().addItem(enverNodes.get(random.nextInt(enverNodes.size())), new EnverNode());
        }

        ValueProvider<EnverNode, String> textProvider = (EnverNode::getEins);
        treeGrid.addHierarchyColumn(textProvider);

        add(treeGrid);
    }

}

```

### Steps to reproduce

Use Vaadin 23.2 standard demo application, use this view above as the 'hello' view.
`mvn spring-boot:run`

### Environment

Vaadin version(s): 23.2
OS: OSX
Tested: Firefox / Chrome latest

### Browsers

Chrome, Firefox, Issue is not browser related

**Comment by enver-haase** [comment]
Note that the default page size is 50, so I see 500 items then, out of the 600 I should be seeing.

**Comment by enver-haase** [comment]
Spurious(?) in the log:

2022-09-13 15:42:31.494  WARN 26605 --- [nio-8080-exec-8] c.v.flow.data.provider.DataCommunicator  : Attempted to fetch more items from server than allowed in one go: number of items requested '50', maximum items allowed '20'.
2022-09-13 15:42:31.869  WARN 26605 --- [io-8080-exec-10] c.v.flow.data.provider.DataCommunicator  : Attempted to fetch more items from server than allowed in one go: number of items requested '650', maximum items allowed '20'.

**Comment by tomivirkki** [comment]
Looks like a severe issue. Reproduces with 23.0

**Comment by enver-haase** [comment]
This bug reproduces with Vaadin 21.0.9.

**This bug DOES NOT REPRODUCE with Vaadin 21.0.0.**

**Comment by enver-haase** [comment]
I suspect https://github.com/vaadin/flow/pull/12003 to be the culprit. @mshabarov  ?

**Comment by mshabarov** [comment]
@enver-haase yes, https://github.com/vaadin/flow/pull/12003 is a reason why you have a limited amount of items. This was done to have a safeguard against malicious requests. Do you really need a page of 2 items? Do you consider an option to increase the page size?
We can try extend the API and make this limit customisable in the component. It wasn't done before, because we wasn't sure if this would be ever needed.

**Comment by enver-haase** [comment]
@mshabarov the point in the example is to show the bug; the incorrect component has manyfold consequences in the customer project I am working in. In fact, if you set the page size to 500, meaning 5000 items can be transferred in one go, then about 98% of the customer's clients have correct behaviour in the application.
Also, a hotfix is to deliver the number of requested items rather than cutting off at the 'maximum items allowed' boundary by putting your own hacked DataCommunicator.java into the project. Unfortunately, that approach still does not fix #3713 which is somehow related.

**Comment by enver-haase** [comment]
Grid is also broken, not only TreeGrid.

**Comment by enver-haase** [comment]
Grid version:

```
package com.vaadin.qa.views.helloworld;


import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.function.ValueProvider;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.router.RouteAlias;
import org.apache.commons.lang3.RandomStringUtils;

import java.util.ArrayList;

@PageTitle("Hello World")
@Route(value = "hello")
@RouteAlias(value = "")
public class HelloWorldView extends VerticalLayout {

    private class EnverNode {
        private final String eins;
        private final String zwei;

        public EnverNode(){
            eins = RandomStringUtils.randomAlphabetic(15);
            zwei = RandomStringUtils.randomAlphabetic(15);
        }

        public String getEins(){
            return eins;
        }

        public String getZwei(){
            return zwei;
        }
    }

    public HelloWorldView() {

        setSizeFull();;

        Grid<EnverNode> grid = new Grid<>();
        grid.setWidthFull();
        grid.setAllRowsVisible(true);

        grid.getDataCommunicator().setPageSize(2); // TODO BROKEN: You will only see N * 10 items, followed by blank lines.

        ArrayList<EnverNode> enverNodes = new ArrayList<>();
        for (int i=0; i < 23; i++){
            enverNodes.add(new EnverNode());
        }
        grid.setItems(enverNodes);
        
        ValueProvider<EnverNode, String> textProvider = (EnverNode::getEins);
        grid.addColumn(textProvider);

        add(grid);
    }

}
```

**Comment by enver-haase** [comment]
The requestor side obviously should loop until all the required items are there.
Related: https://github.com/vaadin/flow-components/issues/1629 -- it seems that not only is the fetch broken (non-looping) but also too greedy at times (fetching items that are not being rendered, unless someone would start scrolling).

**Comment by tomivirkki** [comment]
Took another look into this. The main issue here is the use of `setAllRowsVisible(true)` together with a large number of items, which is actually [discouraged in the API description](https://vaadin.com/api/platform/23.2.1/com/vaadin/flow/component/grid/Grid.html#setAllRowsVisible(boolean)).

Let's say you have 600 items. With the default page size (50), it requires (600/50 =) 12 pages of data to get all the items. With the default settings, the grid would request for the pages one by one as you scroll it and there would be no issues.

But in this case, you've enabled `setAllRowsVisible` which makes the grid render each row to the DOM immediately and therefore ask the data provider for all the 12 pages at once. For safety reasons, Flow has a limitation that it only supports 10 pages of data to be requested at once, and this causes the issue we're dealing with.

To fix the issue in your app, please consider not using `setAllRowsVisible` when you have a large amount of rows (not only to cover this issue but also to avoid performance issues resulting from rendering thousands of DOM items).

If for some reason this is not an option, you should increase the page size of the grid so that it doesn't need to ask for over 10 pages of data at once (`grid.setPageSize(600);` would result in only a single page to be requested in the above example).

The current warning message you get from the DataCommunicator class (`Attempted to fetch more items from server than allowed in one go: number of items requested '650', maximum items allowed '500'.`) is not very clear on what should be done to fix the issue. We could consider making the grid show an additional warning in case the following conditions:
- `setAllRowsVisible(true)` is in use
- The grid's total item count / grid's page size, exceeds the safety limit of 10 pages

**Comment by enver-haase** [comment]
Can we not agree that obviously the client is not told that it needs another fetch?  It seems that while the server has been restricted for security reasons, the client is not aware that this happened from 21.0.3 to 21.0.4.
In my understanding, **the client algorithm needs to be fixed**, not the user be warned that the performance is sub-optimal.

**Comment by tomivirkki** [comment]
> not the user be warned that the performance is sub-optimal

I'm not suggesting that the warning would say the performance might be sub-optimal but that because of misuse, not all rows will be shown. It would also have instructions on what should be changed in the app to fix the issue.

Grid is a virtual scrolling component and it's not intended for rendering thousands of rows to the DOM. Other options could be to actually throw an exception if the grid is misconfigured or internally make it disable `allRowsVisible` together with a warning message.

**Comment by enver-haase** [comment]
I believe the reason people use setAllRowsVisible(true) is that there's a problem with setHeightFull(). The intention is to have the grid take up all the space it can and then start scrolling if needed and also to not take all vertical space when it has only a few lines to show.
If you go along the route of calling it a misconfiguration then I'd say we set some hard number (500 items perhaps) and throw exception when the number of items is exceeded and setAllRowsVisible(true) is set. (just my opinion)

But then fix the client/server comms still. In case we change the hard-coded ITEMS_MAX=500 above to read 5000 or if the page size is 1 or whatever -> we should still be able to transfer all items. If not in one go, then in multiple goes.

**Comment by tomivirkki** [comment]
> I believe the reason people use setAllRowsVisible(true) is that there's a problem with setHeightFull(). The intention is to have the grid take up all the space it can and then start scrolling if needed and also to not take all vertical space when it has only a few lines to show.

This basically describes the following feature (that doesn't yet exist):

https://github.com/vaadin/web-components/issues/2150
https://github.com/vaadin/flow-components/issues/2941

Using `setAllRowsVisible` to emulate it is not recommended. Maybe the app could have some smart logic that toggles the `allRowsVisible` state based on the active item count or something.

**Comment by enver-haase** [comment]
@tomivirkki I tried both the `TreeGrid` and the `Grid` code example above without `setAllRowsVisible(true);` and the behaviour stays the same.
So maybe we could delete our conversation about that or move it elsewhere.

**Comment by tomivirkki** [comment]
To support extremely small page sizes (< 10), the Flow safety logic _could_ add a fixed minimum for the request count (like, you would always be able to request by minimum 200 items at once, regardless of the page size).

But that doesn't solve the original problem described in this issue (that mentioned 600 root items).

**Comment by enver-haase** [comment]
no, it is needed to expose the bug.

**Comment by tomivirkki** [comment]
To support extremely small page sizes (< 10), the Flow safety logic could add a fixed minimum for the request count (like, you would always be able to request by minimum 200 items at once, regardless of the page size).

But that doesn't solve the original problem described in this issue (that mentioned 600 root items).

**Comment by enver-haase** [comment]
I could talk about 30 root items, and the bug would show.
Nothing to do with extremely huge item numbers and setAllRowsVisible(true) that is supposed not to be used if a huge number is involved.

**Comment by tomivirkki** [comment]
With the default Grid configuration, the bug will not show with 30 or 30000 root items. You will need to adjust the page size to a very small number to produce an issue.

**Comment by enver-haase** [comment]
Leaving the page size at the default 50, and using 600 items, and using grid.setAllRowsVisible(false); then all 600 items show.
Interesting.

**Comment by tomivirkki** [comment]
> Leaving the page size at the default 50, and using 600 items, and using grid.setAllRowsVisible(false); then all 600 items show. Interesting.

I explained what happens in this message https://github.com/vaadin/flow-components/issues/3708#issuecomment-1255954080.

> Makes me assume that the default server config with 10*50 is known and used statically from the client side.

Well, no. The client with a 100% high Grid generates roughly 60 rows in the DOM. That means it requires only (Math.ceil(60 / 50) = ) 2 pages of data to fill the initial viewport. A request of 2 pages is nowhere near the safety limit of 10 pages.

**Comment by enver-haase** [comment]
**There is a bug in the example code.**
It should not read `grid.getDataCommunicator().setPageSize(2);` but intstead `grid.setPageSize(2);` .

Not doing so misses telling the client-side about the new page size and makes the client-side fetch numbers of items way above the page size limit (and even the 10 x page size limit set in the Flow part).

**Comment by enver-haase** [comment]
There is also a dependency on the number of visible rows that can make the client-side fetch **a large number of items in one go**.

This is a similar situation to using `setAllRowsVisible(true)` where **all items in one go** are being fetched.

In order to let small page sizes not trigger the problem so easily one could do:
```
private static final MINIMUM_NUM_ITEMS_ALLOWED_PER_FETCH = 500;
private static final MAXIMUM_NUM_PAGES_ALLOWED_PER_FETCH = 10;
private int getMaximumAllowedItems() {
        return Math.max(MINIMUM_NUM_ITEMS_ALLOWED_PER_FETCH, (MAXIMUM_NUM_PAGES_ALLOWED_PER_FETCH * pageSize));
    }
```

However, we should guard against the client asking for too many items in any one go.

For example, with a page size of 2 the client-side for a full-screen grid can easily ask for 82 items in one go (tested!).
A grid with setAllRowsVisible(true); will still ask for all items, maybe 50000.

I think we should make sure that the client is never asking for more than X pages at any one time, X being 10 or so, definitely X <= MAXIMUM_NUM_PAGES_ALLOWED_PER_FETCH .

**Comment by tomivirkki** [comment]
Reported this as a separate issue https://github.com/vaadin/flow/issues/14630 (fixing this alone will not resolve the original problem described in this issue)
