### ISSUE TITLE
Scroller is missing interface Focusable

### ISSUE THREAD

**Issue by aley2003** [vaadin/flow-components#3766]
### Description

A Scroller component receives focus with tab or mouse clicks but does not implement Focusable.
So it is not possible to forbit focusing a Scroller with setTabIndex(-1) or focus a Scroller with focus(),

### Expected outcome

A Scroller implementing Focusable

### Minimal reproducible example

VerticalLayout layout = new VerticalLayout (
   new TextField(), 
   new Scroller(new Html("<span>Text in Sccroller</span>")));

### Steps to reproduce

Create Layout with a Scroller
Press tab -> Scroller will be focused, no possibility to prevent this from Java

### Environment

Vaadin version(s): 23.2.1
OS: Windows

**Comment by web-padawan** [comment]
Thanks for the issue. This is an oversight from our side, we forgot to add `Focusable` after implementing the corresponding change in the web component: https://github.com/vaadin/web-components/pull/3107. This should be changed, probably in 23.3.
