### ISSUE TITLE
View content is hidden under the NavBar

### ISSUE THREAD

**Issue by echarlus** [vaadin/flow-components#3815]
### Description

I've constructed my app with an AppLayout with both drawer & navbar. 
The primary section is the navBar. 
I'm seeing a weird layout issue when I'm on mobile : the start of the view contained in the layout is hidden under the navbar (You can see this in these [2 videos for mobile & desktop](https://photos.app.goo.gl/mHcR9UN6AkSaAE62A ) ).
On mobile, on the map view the top icon & text content is displayed under  the NavBar, in the chart view, the tabs are  hidden under the navbar : one sees the scrolling arrows of the tabs over the navbar and one can change tab by touching the <> ... 
I've tried to call scrollIntoView on the tabs component for example but it does not fix the issue. 
I'm having the same issue on desktop but only with the chart view, the map view works fine. 

### Expected outcome

Top of view content should be visible when arriving on the page.

### Minimal reproducible example

You can download a demo project [here](https://drive.google.com/file/d/14oJRXkJstkkYSRNl9p3VA_ON9zf_xrDX/view?usp=sharing) 

### Steps to reproduce

Build the project and launch it, open it with chrome desktop or chrome mobile
Observe that the icon & text "5 points supervisés, dont 2 en alerte" is hidden under the navbar. On desktop if you resize the window horizontally, both icon & text appear ...
Select the chart menu item. Observe that on desktop the tabs are visible but on mobile they are hidden under the navbar (only the < > arrows are visible on top of the navbar).

### Environment

Vaadin version(s): 23.2.2
OS: Linux / Tomcat 9
Browser : 
Chrome ( 106.0.5249.61) & firefox (105.0.1 ) , Safari (16.0  - 17614.1.25.9.10, 17614)- desktop mac os
Chrome (105.0.5195.136) & firefox (105.1.0 ) - mobile Android

### Browsers

Chrome, Firefox

**Comment by echarlus** [comment]
It appears that the variable vaadin-app-layout-navbar-offset-size is not computed correctly, which causes the issue.

**Comment by rolfsmeds** [comment]
> It appears that the variable vaadin-app-layout-navbar-offset-size is not computed correctly, which causes the issue.

This is indeed the case, and it's caused by the images in the header. Presumably the header's height is calculated before the images have finished loading.

As a quick fix for now, setting a fixed height (either with css or java) to the images seems to fix it.

**Comment by rolfsmeds** [comment]
Alternatively, you could call the app-layout method that updates the offset when the images finish loading by calling this on each image:
`img.getElement().setAttribute("onload", "document.querySelector('vaadin-app-layout')._updateOffsetSize()");`

**Comment by rolfsmeds** [comment]
So, workarounds luckily exist. Nevertheless, the app-layout should be able to handle this automatically. A ResizeObserver might be the solution (similar to #3374).

**Comment by echarlus** [comment]
@rolfsmeds I've just tested on my app and unfortunately I still have the issue. 
I did check and I indeed have the onload callback set on the two images ...
<img width="576" alt="image" src="https://user-images.githubusercontent.com/7509875/194108705-9c4d127d-3a18-442d-bc31-f8bed959befd.png">

**Comment by rolfsmeds** [comment]
Hmm, it did seem to work for me. Did setting a fixed height on the images work though?

**Comment by echarlus** [comment]
> Hmm, it did seem to work for me. Did setting a fixed height on the images work though?

I'll try and let you know.

**Comment by echarlus** [comment]
@rolfsmeds I've tried with both the onload and setting the height of the image. 
setting the height seems to fix it most of the time, from time to time I still see the issue but it's less frequent.
However I'm now facing this issue : depending on the customer I might not have the second image, to hide the "broken image" in this case I've used this `        icon.getElement().setAttribute("onerror", "this.style.display='none'");`
When the image is hidden it appears I now have an offset below the nav bar. When there is an image, the offset is not there.
See the huge gap between the header and the tabs on this screenshot. When I have the second logo, this is not the case.
![image](https://user-images.githubusercontent.com/7509875/194147443-78919156-06c5-477a-af87-d732b7681210.png)

**Comment by echarlus** [comment]
I can give you access to a test server if you want to see this.

**Comment by echarlus** [comment]
I see. I'll make a build with only the onload changes and give you access to the running app. I found your email on the websiste and will be sending credentials very shortly. 
Thanks for the follow up !

**Comment by echarlus** [comment]
Hi @rolfsmeds did you get the e-mail I sent this morning with info to access the live app ? Are you able to reproduce ? 
Thanks

**Comment by rolfsmeds** [comment]
Tested and reproduced e.g. with Firefox on Android. I'm getting the impression that, in addition to the image loading, the wrapping of the view title also plays a part in messing up the calculation of the header's height.

Note to fixers: the following scenarios should be taken into account in the fix:

- Images (loading potentially slowly) in the header
- Wrapping text in the header
- Media queries
- Dynamically applied css classnames that change the rendering of some header content
