### ISSUE TITLE
Grid: Bug in gridConnector.js

### ISSUE THREAD

**Issue by xdenser** [vaadin/flow-components#3829]
### Description

This line 
808:  for (let i = 0; i < selectedItems; i++) {

does not seem to be ok in gridConnector.js
it has to be 
for (let i = 0; i < selectedItems.length; i++) {

### Expected outcome

Fix the bug

### Minimal reproducible example

no example just review the code.

### Steps to reproduce

Load long grid with many pages of items - selection would mess up.

### Environment

Vaadin version(s): 23.2.0
OS:  no matter

**Comment by sissbruecker** [comment]
@xdenser I agree that the `isSelectedOnGrid` function is broken, and would always return false.

> Load long grid with many pages of items - selection would mess up.

Did try that with several examples, and could not find any issues. Can you please elaborate what is "messed up", and provide a code snippet to reproduce the problematic behavior? There might be a missing test case that we want to add.

**Comment by xdenser** [comment]
I realized that I have some customezations - like mulit select behavior in selection row, but "single select" bahavoir when user clicks on rows. But IMHO even w/o customization it is reproducable as following:
You need grid with lazy loading, select something on first page then scroll down several pages (so it will cal backend) then ask in dev tools grid.selecteItems - you will get empty array - your first selection will be lost.

**Comment by sissbruecker** [comment]
After looking into it a bit more, I think the function can be safely removed, as it always returning false had no impact in the places where it's used.

> You need grid with lazy loading, select something on first page then scroll down several pages (so it will call backend) then ask in dev tools grid.selectedItems - you will get empty array - your first selection will be lost (at least on client side).

That's expected, there is no assumption - and no need - that the client side grid will hold all selected items that it encountered at some point. The grid connector contains logic the remove cached pages when they are scrolled out of the viewport (see `clear` in grid connector), as part of that the items are removed from the `selectedItems` array as well. When scrolling back, the connector will restore the client-side selected items from the items loaded from the server.
