### ISSUE TITLE
[MultiSelectComboBox] Preserve order of programmatically selected items

### ISSUE THREAD

**Issue by esommars** [vaadin/flow-components#3956]
### Describe the bug

When MultiSelectComboBox is used to persist selected values it will not store them or show them in the order they where selected.

### Expected-behavior

When values are selected, example, ONE,TWO,THREE, the same values should be shown with the same order when component gets it's selection loaded again or set with setValue.

### Reproduction

```java
import java.util.List;

import javax.annotation.PostConstruct;
import javax.annotation.security.PermitAll;

import com.vaadin.flow.component.combobox.MultiSelectComboBox;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

@PermitAll
@Route(value = "temp", layout = MainLayout.class)
public class TempView extends VerticalLayout {

    public enum Column {
        SENVEN,
        ONE,
        TWO,
        THREE,
        FOUR,
        FIVE,
        SIX
    };

    private MultiSelectComboBox<Column> columnOrderBy = new MultiSelectComboBox<>("Columns", Column.values());

    @PostConstruct
    private void init() {
        this.add(columnOrderBy);
        columnOrderBy.setWidthFull();
        columnOrderBy.setValue(List.of(Column.THREE, Column.ONE, Column.TWO, Column.SENVEN));
        // expected order: THREE, ONE, TWO, SENVEN
        // found order : THREE, SENVEN, TWO, ONE or some other "hash" order
    }

}
```

### System Info

Windows 10, Firefox 106.01, Vaadin 23.2.6

**Comment by TatuLund** [comment]
To me it looks like this is not an actual bug. 

In all multiselection components we have, the value is defined as Set. And in Java Set is just not promised to preserve order. So what you see can happen.

**Comment by knoobie** [comment]
Grid for example enforces a correct order by using `LinkedHashMap` shouldn't the same also apply to other multi-select components? 

https://github.com/vaadin/flow-components/blob/d0ffddd50f3e8e6ec6e56d82f13423400ee2e203/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java#L73

**Comment by TatuLund** [comment]
@knoobie That `LinkedHashMap `is there for other reasons, originally it was HashSet, but I changed it in the patch that fixed the identity handling of the `GridMultiSelectionModel`

* Change to LinkedHashMap

- This is needed in order to getFirstSelectedItem work properly
- All other contracts do not promise order

**Comment by knoobie** [comment]
Looking back it was `LinkedHashSet` which also guarantee its order, in V8 and V7 as well. Personally I've always relied on the order ;)

**Comment by TatuLund** [comment]
>  Personally I've always relied on the order

But as the API gives you a Set, if there seems to be order, you need to think it as happenstance.

**Comment by knoobie** [comment]
I'm with you about the current API design - looking at the Set interface, somebody should not expect the correct order - I just happened to stumble upon the implementations over the years and always came across `Linked*` and assumed it

**Comment by esommars** [comment]
I'm thinking that why is the multiselect contract then not a List. The other for the MultiSelectListBox probably does not matter when it is determined by showing available items marked as selected. 
In the case for MultiSelectComboBox it would be very useful to be able to use the order of the selected items not regarding why Set was chosen in the first place.
For example, select columns to be included in a csv report and what order the columns should have in the report. 
Or to store the order by clause for said report. Or for the user to just see the same thing as they selected in the first place :)

I guess that java is finally noticing this dilemma: https://openjdk.org/jeps/431

**Comment by cyberoblivion** [comment]
This is a good improvement. But, for most of our use cases it is important for us to order the items, with out order the end user will have to read through every item to figure out if the necessary item is selected.

Here is an example:
![image](https://user-images.githubusercontent.com/1922839/211667012-e171af57-8727-4afb-8964-d592bc1934d1.png)


You can imagine how painful that would be. 

It seems like for us we'll have to always deselect everything and then pragmatically select the items in alphabetical order to achieve our goals of alpha sorting list?

**Comment by TatuLund** [comment]
@cyberoblivion , I am trying to paraphrase your comment. Would you prefer to have selection to appear in the same order as they are in the underlying data provider. Hence if the data provider has sorting provider, the same sorting would be applied to selection as well. If so, then your preference is somewhat opposite what was the intention this ticket, i.e. selection to follow order of the selection being done.

**Comment by cyberoblivion** [comment]
@TatuLund my point is just that the need to be able sort the items is important. Especially when the display is initially populated, prior to any selection. But, as you mentioned, the API being a Set means we shouldn't expect ordering.

With your update my goals are actually completely achievable without a programmatic select() hack.
If I bind to a treeset with a comparator everything works as I want it to.
() -> new TreeSet<>(Comparator.comparing(MultiComboSelectItem::getCaption))

But again the API suggests that this is happenstance and may break in the future. Also I needed to look at the underlying Set implementation to achieve this. 

I don't feel knowledgeable enough to suggest a solution. I'm just trying to express the importance of sorting these things and that the API should probably be changed to support the concept.
