### ISSUE TITLE
Combox dropdown retains the old value as checked when value is changed from java programmatically

### ISSUE THREAD

**Issue by sujoykd** [vaadin/flow-components#4009]
### Description

I added a combo box with a value set by default, and a button to change the value of the combo box on click.
The value change happens as expected.

When I open the dropdown for the first time to view the items, the current value is marked as checked.
However, if I change the value from the button click event and then open the dropdown, the previously observed value is retained as checked along with the current value.

So we now have two items as checked. Combo box getValue function returns the correct value however the UI is confusing because it shows two items as checked.

![image](https://user-images.githubusercontent.com/106066145/199699287-567bdc4c-bf62-4ac3-a549-c9017b02ae27.png)

### Expected outcome

Regardless of when I open the dropdown, I should only see the current value as checked.

### Minimal reproducible example

```java
final List<String> items = IntStream.rangeClosed(1, 10).mapToObj(num -> RandomStringUtils.randomAlphabetic(10, 15)).collect(Collectors.toList());

final ComboBox<String> comboBox = new ComboBox<>();
comboBox.setItems(items);
comboBox.setAllowCustomValue(false);
comboBox.setValue(items.get(5));

this.add(comboBox);

final Button button = new Button("click me");
button.addClickListener(event -> {
    comboBox.setValue(items.get(RandomUtils.nextInt(0, 10)));
    Notification.show(comboBox.getValue(), 5000, Position.TOP_CENTER);
});
this.add(button);
```

### Steps to reproduce

1. Add the snippet above to a view
2. Click the button to change the value of the combo box.
3. Open the combo box dropdown to observe that the current value is marked as checked.
4. Click the button to change the value of the combo box again.
5. Open the combo box dropdown to observer that both the current value and the previous value is now marked as checked.

### Environment

Vaadin version(s): 14.8.20 and 14.9.1
OS: Windows 10 21H1

### Browsers

Issue is not browser related

**Comment by sissbruecker** [comment]
Closing as part of https://github.com/vaadin/flow-components/pull/4033
