### ISSUE TITLE
Dialog server side modality can block opened-changed of previously closed Dialog

### ISSUE THREAD

**Issue by TatuLund** [vaadin/flow-components#4026]
### Description

Consider case of of having two Dialogs. The second Dialog is opened when the user clicks the Close button of the first one.

There will be a small resource leakage on the client side as dialog element wont be cleared.

![image](https://user-images.githubusercontent.com/14309836/200265320-2cb2e317-f8cd-4f14-9d43-149e4dee35a6.png)

This happens because the new dialog adds server side modality, which blocks opened-changed event.

https://github.com/vaadin/flow-components/blob/master/vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java#L119

Workaround is to open the second dialog e.g. in the detach event of the first dialog in order to ensure that opened-changed

```
@Route("dialog")
public class DialogView extends Div {
     public DialogView() {
         Dialog d1 = new Dialog();
         Button b1 = new Button("Close", event -> {
             d1.close();
         });
        d1.add(new Label("Dialog 1"), b1);
        d1.open();
        d1.addDetachListener(e -> {
            Dialog d2 = new Dialog();
            Button b2 = new Button("Close", event2 -> {
                d2.close();
            });
           d2.add(new Label("Dialog 2"), b2);
           d2.open();
         });
    }
}
```

### Expected outcome

Opening a new Dialog should not interfere cleanup of the closing Dialog.

### Minimal reproducible example

```
@Route("dialog")
public class DialogView extends Div {
    public DialogView() {
        Dialog d1 = new Dialog();
        Button b1 = new Button("Close", event -> {
            d1.close();

            Dialog d2 = new Dialog();
            Button b2 = new Button("Close", event2 -> {
                d2.close();
            });
            d2.add(new Label("Dialog 2"), b2);
            d2.open();
        });
        d1.add(new Label("Dialog 1"), b1);
        d1.open();
    }
}
```

### Steps to reproduce

Use the above code.

### Environment

Vaadin version(s): Vaadin 23.2.6

### Browsers

Issue is not browser related

**Comment by ugur-vaadin** [comment]
Was fixed by a [PR](https://github.com/vaadin/flow-components/pull/4778) for #4743.
