### ISSUE TITLE
ComboBox detach/attach cycle loses value rendering

### ISSUE THREAD

**Issue by enver-haase** [vaadin/flow-components#4053]
### Description of the bug

When I detach a ComboBox with a set value, and I attach it again later, I cannot see the set value. Instead, it seems to be unset visually.

### Expected behavior

I would like to see the visuals to be restored upon re-attaching the component to the DOM tree.

### Minimal reproducible example

Use standard Vaadin application, use this view:

```
package com.example.application.views.main;

import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.combobox.ComboBox;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;

@PageTitle("Main")
@Route(value = "")
public class MainView extends HorizontalLayout {

    private TextField name;
    private Button sayHello;

    public MainView() {

        ComboBox<String> comboBox = new ComboBox<>();
        comboBox.setItems("one", "two");
        comboBox.setValue("one");

        add(new Button("detach combo box", e -> {
            MainView.this.remove(comboBox);
        }));

        add(new Button("attach combo box", e -> {
            MainView.this.add(comboBox);
        }));
    }
}
```

### Versions

- Vaadin / Flow version: 23.2.7
- Java version: n/a
- OS version: macOS latest
- Browser version (if applicable): n/a
- Application Server (if applicable): n/a
- IDE (if applicable): n/a

**Comment by willemv** [comment]
I think the impact is underestimated: you also get this when you reuse your route targets, and switch between routes.

This here is an example with multiple views that are reused (by using the `@UIScope` annotation from the spring support) and a nav-bar to switch between them.

[combobox-reattach-repro.tar.gz](https://github.com/vaadin/flow-components/files/10012173/combobox-reattach-repro.tar.gz)

**Comment by sirbris** [comment]
This bug is quite nasty and I would agree with @willemv that the impact is definitely not low

**Comment by F0rce** [comment]
Some additional information:
Reproducable since `23.2.0` (`23.1.11` is **not** affected).

**Comment by sissbruecker** [comment]
Yes, this is likely a regression from introducing `MultiSelectComboBox` in 23.2. This included a significant refactoring which removed the synchronization of the web components `selectedItem` property to the server-side, which is used to determine the label of the combo box.

**Comment by F0rce** [comment]
Thanks for quick fix. 

Is there an ETA / Version where this fix will be included ?

**Comment by sissbruecker** [comment]
Likely in a patch release for 23.2 start of next week.
