### ISSUE TITLE
Moving components between SplitLayouts breaks

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/flow-components#4057]
### Description

Components A and B are in a SplitLayout X. If the original SplitLayout X is discarded and A and B are inserted into a new SplitLayout instance Y during a round trip, A and B are no longer visible - looking at the DOM, it seems that they are child elements of the <vaadin-split-layout>, but they are not inserted into the slots, which are empty. The components should have slot attributes set, but they do not.

### Expected outcome

Components should have slot attributes

### Minimal reproducible example

```java
Span primary = new Span("Primary Content");
Span secondary = new Span("Secondary Content");
splitLayout = new SplitLayout(primary, secondary);
Button magicButton = new Button("Magic Button", e -> {
    remove(splitLayout);
    splitLayout = new SplitLayout(primary, secondary);
    add(splitLayout);
});
add(magicButton, splitLayout);
```

### Steps to reproduce

1. add the snippet into a view
2. click the button
3. SplitLayout is empty

### Environment

Vaadin version(s): 23.2.7
OS: n/a

### Browsers

Chrome

**Comment by sissbruecker** [comment]
Additional details from internal Slack discussion: https://vaadin.slack.com/archives/C3TGRP4HY/p1668085649393659
