### ISSUE TITLE
Remove internal usages and public API of TemplateRenderer

### ISSUE THREAD

**Issue by sissbruecker** [vaadin/flow-components#4059]
`TemplateRenderer` is scheduled to be removed in 24. Context:
- https://github.com/vaadin/flow-components/issues/857
- https://github.com/vaadin/flow-components/issues/916

First remove all internal usages:

- [x] `Crud` - Used for edit button column
- [x] `TreeGrid` - Used for hierarchy column
- [x] `VirtualList` - Used when setting a value provider as renderer
- [x] Unit tests and integration tests
	- [x] ComboBox
	- [x] Grid
	- [x] TreeGrid
	- [x] Virtual List

Then remove the public API from the `vaadin-renderer-flow` module.

Also consider closing the following issues as obsolete:
- https://github.com/vaadin/flow-components/issues/1303
- https://github.com/vaadin/flow-components/issues/1274

**Comment by tomivirkki** [comment]
Closing as complete
