### ISSUE TITLE
TabSheet should provide access to Tab's Component and Component's Tab

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/flow-components#4099]
### Describe your motivation

The TabSheet component maps each Tab to an Element instance. In some cases, it would be useful to be able to access these components/elements after they have been added to the TabSheet given the Tab, and conversely, it should be possible to get the Tab with the Element.

### Describe the solution you'd like

Provide two methods in TabSheet:
```
   Tab tab = tabSheet.getTab(Component component)
```
and
```
   Component component = tabSheet.getComponent(Tab tab)
```

### Describe alternatives you've considered

The method signatures might not want to rely on the Component interface; possibly `Element` or `HasElement` could be better.

**Comment by TatuLund** [comment]
There is such API in TabSheet add-on https://github.com/tatulund/TabSheet/blob/master/src/main/java/org/vaadin/addons/tatu/TabSheet.java#L134

You can find it in Directory https://vaadin.com/directory/component/tabsheet

**Comment by joelpop** [comment]
And analogous to `TabSheet`'s `add()` methods returning the `Tab`, its `remove()` methods should return the `Component`. This is also analogous to how the `Map` works with its key/value.

**Comment by knoobie** [comment]
Push. This is crucial for example to remove the need of double book-keeping of the tab to component reference. 

Simple and common use-case, the component (tab content) has to be notified once it gets selected / opened to e.g. refresh the content. Normally, this should be done within `addSelectedChangeListener` but there is no access to the component, just the tab - enforcing the user to still book-keep the reference to the component (which is close to impossible if the LazyComponent shown within the documentation is used)

**Comment by web-padawan** [comment]
Forwarding a comment by @tomivirkki who asked Copilot to help:

```java
public Tab getTab(Component component) {
    return tabToContent.entrySet().stream()
            .filter(entry -> entry.getValue().equals(component.getElement()))
            .map(Map.Entry::getKey).findFirst().orElse(null);
}

public Component getComponent(Tab tab) {
    return tabToContent.get(tab).getComponent().get();
}
```

@knoobie Would you be willing to submit a PR so that we could get this into Vaadin 24.1?
