### ISSUE TITLE
[RadioButtonGroup] Deprecate and remove implementation of HasItemComponents

### ISSUE THREAD

**Issue by sissbruecker** [vaadin/flow-components#4194]
`RadioButtonGroup` is not intended to be used as a generic component container, and thus should not implement `HasComponents` or `HasItemComponents`.

The interface methods should be deprecated on v23.3, and the implementation of the interfaces removed for v24.

**Comment by Frettman** [comment]
I don't understand why this was removed. I have used this to add dividers, just like in the examples for `Select`: https://vaadin.com/docs/latest/components/select/#dividers
And I also used this to e.g. add an input field to one of the radio button options. How else would I place it near the option it's associated with?
If it makes sense for `Select` and `ListBox` to implement this interface, it makes sense for `RadioButtonGroup`.
And judging by #4251 `CheckboxGroup` just slipped through the cracks for now and will get the same treatment as `RadioButtonGroup` soon enough. In that case I could at least fall back to using individual `Checkbox` components to achieve the same. But there is no individual `RadioButton`s.
