### ISSUE TITLE
AbstractFieldSupport.setValue doesn't fire event for ArrayList at second call

### ISSUE THREAD

**Issue by fabst2w** [vaadin/flow-components#4201]
### Description

An extension of CustomField<ArrayList<MyBusinessObject>> calls updateValue() when the user clicks a button (that adds or removes something to the internal ArrayList) within that CustomField.

When the CustomField calls updateValue() the first time, then the com.vaadin.flow.component.internal.AbstractFieldSupport.setValue(T, boolean, boolean) method fires an event (which is intended) because com.vaadin.flow.component.internal.AbstractFieldSupport.bufferedValue is null.

When the CustomField calls updateValue() the second time, then the com.vaadin.flow.component.internal.AbstractFieldSupport.setValue(T, boolean, boolean) method does not fire an event because com.vaadin.flow.component.internal.AbstractFieldSupport.bufferedValue is the SAME ArrayList.

### Expected outcome

I expected that updateValue() fires the event in both cases because the ArrayList size changed between both updateValue() calls.

As a workaround I changed generateModelValue() in my CustomField so that it returns a new ArrayList instance every time. This works but I guess that setValue fires too often events.

	@Override
	protected ArrayList<MyBusinessObject> generateModelValue() {
		return new ArrayList<>(myValues);
	}

### Minimal reproducible example

public class MyCustomField extends CustomField<ArrayList<MyBusinessObject>> {

private ArrayList<MyBusinessObject> myValues = new ArrayList<>();
private Button buttonInCustomField;

[...]
buttonInCustomField.addClickListener(event -> {
    myValues.add(new MyBusinessObject());
    updateValue();
});
[...]

	@Override
	protected ArrayList<MyBusinessObject> generateModelValue() {
		return myValues;
	}

}

### Steps to reproduce

1. Click button >> Event is fired
2. Click button >> Event is not fired

### Environment

Vaadin version(s): 23.2.8
OS: Ubuntu 22.10

### Browsers

Chrome, Issue is not browser related

**Comment by sissbruecker** [comment]
That is expected, if you pass the component the same instance of the list, then the value has not changed. Your workaround is the appropriate solution here, ensure that the component receives a new instance to compare against. If you want to avoid value change events in case the contents of the two collection instances are the same, then use an appropriate data structure like a `Set`.
