### ISSUE TITLE
Spreadsheet seems to not be serializable

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow-components#4254]
### Description

Start tests report
```
java.io.NotSerializableException: com.vaadin.flow.component.spreadsheet.SpreadsheetHandlerImpl
```

### Expected outcome

The component is serializable so the related UI can be moved between nodes in a cluster

### Minimal reproducible example

The spreadsheet view from Start

### Steps to reproduce

1. Open
2. Restart the dev server

### Environment

Vaadin version(s): 24.0.0.alpha5

**Comment by yuriy-fix** [comment]
@Artur- , do you have an idea if we can do something about that (poi)?

**Comment by Artur-** [comment]
Not apart from making POI serializable or retrieving all data from POI, serialize it and reconstruct the POI data on deserialization..

**Comment by yuriy-fix** [comment]
We should probably mention that the Spreadsheet is not serialisable because of a reason in the documentation.

**Comment by ugur-vaadin** [comment]
Fixed by a Docs [PR](https://github.com/vaadin/docs/pull/2149).
