### ISSUE TITLE
Integration Tests fail

### ISSUE THREAD

**Issue by probert94** [vaadin/flow-components#426]
I tried running the integration tests for `vaadin-grid` using the `run.sh` script .
I selected option 3 (one test  IT - Verify Integration-Tests of one component `mvn verify -pl component -Dit.Test=...`) and module 19 (`vaadin-grid`).
I left the following prompts empty to use the default values and the resulting command looks like this: `mvn verify -q -am -B -pl vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests`.
However, they fail at `com.vaadin.flow.component.tests.BigDecimalFieldTest`with the following error:
[com.vaadin.flow.component.textfield.tests.BigDecimalFieldTest.txt](https://github.com/vaadin/vaadin-flow-components/files/5583470/com.vaadin.flow.component.textfield.tests.BigDecimalFieldTest.txt)

I also tried using `fail-at-end` which reports additional 7 failures in `com.vaadin.flow.component.combobox.dataview.ComboBoxLazyDataViewTest`:
[com.vaadin.flow.component.combobox.dataview.ComboBoxLazyDataViewTest.txt](https://github.com/vaadin/vaadin-flow-components/files/5583464/com.vaadin.flow.component.combobox.dataview.ComboBoxLazyDataViewTest.txt)

**Comment by rolfsmeds** [comment]
Is this still an issue? (There were temporary problems with the build)

**Comment by Springrbua** [comment]
I just updated my fork, but I am still getting the same errors.
The one in the `BigDecimalFieldTest` might be related to the locale, as it says `expected:<1[.]100> but was:<1[,]100>` (note the `comma` instead of the `dot`).

**Comment by manolo** [comment]
what's your locale? (run `locale` in your terminal)

**Comment by Springrbua** [comment]
My locale is `de_DE.UTF-8`

**Comment by web-padawan** [comment]
This was fixed by #1780
