### ISSUE TITLE
Vaadin 23.3 series contains backwards incompatible changes

### ISSUE THREAD

**Issue by mstahv** [vaadin/flow-components#4286]
### Description

Some event changes (SplitterDragendEvent, InvalidChangeEvent, OpenedChangeEvent) are not fully backwards compatible.

### Expected outcome

Minor version update (like 23.3) upgrade should be simple version change and re-compilation if possible, especially if changes happen without deprecation.

### Minimal reproducible example

Checkout Viritin 23 series and try to compile against 23.3.0.beta2. https://github.com/viritin/flow-viritin/commit/cf84f26ade8f0596a57d0262760ec970b4a12c41

### Steps to reproduce

checkout project
update version
compile

### Environment

Vaadin version(s): 
OS: Mac, JDK 11

**Comment by web-padawan** [comment]
From the internal discussion: we will add the generic type param to the new event classes to avoid compilation errors. In V24 we keep them dropped, which means that people will have to deal with this during the upgrade unfortunately.

**Comment by sissbruecker** [comment]
Fixed as part of https://github.com/vaadin/flow-components/pull/4290
