### ISSUE TITLE
GridPro custom editor fields input selection behavior is inconsistent

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/flow-components#4305]
### Description

Default editor fields in GridPro automatically select the contents of the editor input when you navigate between the cells (see https://vaadin.com/docs/latest/components/grid-pro). This makes sense, it's easy to start overriding the contents, you don't need to start erasing the previous values first. If you use a `.custom` editor (even with stock Vaadin components), the input selection occurs inconsistently - sometimes the input content is selected, other times it's not, even when navigating within a single GridPro.

### Expected outcome

The input selection should be consistent, and preferably it should happen always if the editor component supports it. Alternatively, there could be some kind of workaround that would ensure the contents of the input are selected when a cell is navigated into.

### Minimal reproducible example

![gridpro](https://user-images.githubusercontent.com/15027701/206135973-f5c3b3d8-1663-42ad-928f-465f38dad442.gif)

```java
    public static class Bean {

        public Bean(double doubleProp, LocalDate localDateProp, BigDecimal bigDecimalProp) {
            this.doubleProp = doubleProp;
            this.localDateProp = localDateProp;
            this.bigDecimalProp = bigDecimalProp;
        }

        public double getDoubleProp() {
            return doubleProp;
        }

        public void setDoubleProp(double doubleProp) {
            this.doubleProp = doubleProp;
        }

        public LocalDate getLocalDateProp() {
            return localDateProp;
        }

        public void setLocalDateProp(LocalDate localDateProp) {
            this.localDateProp = localDateProp;
        }

        public BigDecimal getBigDecimalProp() {
            return bigDecimalProp;
        }

        public void setBigDecimalProp(BigDecimal bigDecimalProp) {
            this.bigDecimalProp = bigDecimalProp;
        }

        double doubleProp;
        LocalDate localDateProp;
        BigDecimal bigDecimalProp;
    }

      protected void initView() {
        GridPro<Bean> grid = new GridPro<>();
        grid.setEnterNextRow(true);
        List<Bean> beans = new ArrayList<>();
        for (int i = 0; i < 10; i++) {
            beans.add(new Bean(i, LocalDate.ofYearDay(2022, 1+i*20), new BigDecimal(i * 3)));
        }
        grid.addEditColumn(bean -> bean.getDoubleProp()).custom(new NumberField(),
                (bean, s) -> bean.setDoubleProp(s)).setHeader("prop1");
        grid.addEditColumn(bean -> bean.getLocalDateProp())
                .custom(new DatePicker(),
                (bean, s) -> bean.setLocalDateProp(s)).setHeader("prop2");
        Grid.Column<Bean> prop3 = grid.addEditColumn(
                bean -> bean.getBigDecimalProp()).custom(new BigDecimalField(),
                (bean, s) -> bean.setBigDecimalProp(s)).setHeader("prop3");
        grid.setItems(beans);
        add(grid);
 
    }
```

### Steps to reproduce

1. Add the snippet into a view
2. Call the initView method
3. Open the browser
4. Navigate between GridPro cells with tab and enter

### Environment

Vaadin version(s): 23.2.10
OS: Windows 10

### Browsers

Chrome

**Comment by rolfsmeds** [comment]
The issue was triaged and currently added to the backlog priority queue for further investigation.

**Comment by yuriy-fix** [comment]
The issue was triaged and currently added to the backlog priority queue for further investigation.

**Comment by DiegoCardoso** [comment]
The issue was assigned to a developer and is currently being investigated.
