### ISSUE TITLE
Tall Details row breaks Grid rendering

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/flow-components#4306]
### Description

If you have a Details row that is quite tall, this may break Grid's rendering. The required tallness to cause the broken behavior is not clear, but it can be quite easily reproduced with a simple Grid.

### Expected outcome

Even tall Details rows should work normally.

### Minimal reproducible example

```java
    public static class Bean {
        public Integer getProp1() {
            return prop1;
        }

        public void setProp1(Integer prop1) {
            this.prop1 = prop1;
        }

        public Bean(Integer prop1) {
            this.prop1 = prop1;
        }

        Integer prop1;
    }


    protected void initView() {
        Grid<Bean> grid = new Grid<>();

        List<Bean> beans = new ArrayList<>();
        for (int i = 0; i < 100; i++) {
            beans.add(new Bean(i));
        }

        grid.setItemDetailsRenderer(new ComponentRenderer<>(bean -> {
            VerticalLayout vl = new VerticalLayout();
            for (int i = 0; i < bean.prop1; i++) {
                vl.add(new Span("" + i));
            }
            return vl;
        }));
        grid.addColumn(bean -> bean.getProp1() + "");
        grid.setItems(beans);
        add(grid);

    }
```

### Steps to reproduce

1. Add the snippet above into a view
2. Call initView
3. Expand some nodes lower down in the Grid (e.g. row 20 or 30) and scroll up and down
4. Observe rendering doesn't work as expected

### Environment

Vaadin version(s): 23.2.10
OS: Windows 10

### Browsers

Chrome

**Comment by OlliTietavainenVaadin** [comment]
![griddetails](https://user-images.githubusercontent.com/15027701/206427771-18ddd7ff-0f27-42ae-80dd-3013895528d7.gif)
Screen capture of the broken behavior

**Comment by rolfsmeds** [comment]
A bit difficult to see what's going on since the panel's contents look so much like row contents, and you can't quite tell how it's being scrolled, but I presume we're talking about the sudden blank areas?

**Comment by OlliTietavainenVaadin** [comment]
Yes, that's the thing.

**Comment by tomivirkki** [comment]
I started investigating the issue and will work on the fix.
