### ISSUE TITLE
Grid's new Multi sort mode with onShiftClickOnly prevents setting multi sort server side.

### ISSUE THREAD

**Issue by evanzel** [vaadin/flow-components#4362]
### Description

When I set a grid with
grid.setMultiSort(true, Grid.MultiSortPriority.APPEND, true);
and then I try to sort with
grid.sort(GridSortOrder.asc(c1).thenAsc(c2).thenAsc(c3).build());
it does not perform a multisort. It sorts only with the last column.

![image](https://user-images.githubusercontent.com/14309836/210072414-7bf0afc6-1914-4c7d-b593-cbdd58168c79.png)

### Expected outcome

a serverside multisort should be performed.

![image](https://user-images.githubusercontent.com/14309836/210072564-0f50ec03-3507-481b-9853-025123e8a425.png)

### Minimal reproducible example

```
@Route("test")
public class TestView extends Div {
  public TestView() {
    Grid<String> grid = new Grid<>();
    Column<String> col1 = grid.addColumn(String::toLowerCase).setHeader("Column 1");
    Column<String> col2 = grid.addColumn(String::valueOf).setHeader("Column 2");
    grid.setMultiSort(true, MultiSortPriority.APPEND, true);
    grid.setItems(List.of("Data 1", "Data 2", "Data 3", "data 1"));


    grid.sort(GridSortOrder.asc(col1).thenDesc(col2).build());


    add(grid);
  }
}
```
### Steps to reproduce

see description.

### Environment

Vaadin version(s): 23.3.0
OS: 

### Browsers

Issue is not browser related

**Comment by rolfsmeds** [comment]
The issue was triaged and currently added to the backlog priority queue for further investigation.

**Comment by DiegoCardoso** [comment]
The PR fixing the issue was merged and changes will be delivered in the following versions:

- 24.0.0.alpha9 / 24.0.0.beta1
- 23.3.4
