### ISSUE TITLE
Autocapitalize does not work in TextField

### ISSUE THREAD

**Issue by Flaurite** [vaadin/flow-components#4452]
### Description

In the generated demo project from starter, I set `Autocapitalize.CHARACTERS` to `TextField`. Opened application in the Chrome (v108) from my mobile and virtual keyboard does not offer me capitalized letters.

I think, this is due to attribute is added to the `vaadin-text-field` element instead of `input`:
```
<vaadin-text-field autocapitalize="characters" ...
```

If you try to use native input with type="text" and attribute: `autocapitalize="characters"` you will see the right behaviour. For instance:
```
Input input = new Input();
input.getElement().setAttribute("type", "text");
input.getElement().setAttribute("autocapitalize", "characters");
```

### Expected outcome

Expected behavior is all letters in the virtual keyboard are capitalized (while typing).

### Minimal reproducible example

TextField name= new TextField("Your name");
name.setAutocapitalize(Autocapitalize.CHARACTERS);

### Steps to reproduce

1. Download project from https://start.vaadin.com/
2. Vaadin version: 23.3.2
3. Set `Autocapitalize.CHARACTERS` to the `TextField`:
```
name = new TextField("Your name");
name.setAutocapitalize(Autocapitalize.CHARACTERS);
```
4. Launch the app and open application using Chrome from mobile device

### Environment

Vaadin version(s): 23.3.2
Mobile Chrome: 108.0.5359.128

**Comment by web-padawan** [comment]
Thanks for the issue. Actually, `vaadin-text-field` web component [forwards](https://github.com/vaadin/web-components/blob/7a7428317eb2d0eb4b21aa0766c1c2824e8543e2/packages/field-base/src/input-field-mixin.js#L54) this attribute to the `<input>` element.
However, it seems that this logic might not be working correctly in all the cases. I will investigate.

**Comment by web-padawan** [comment]
Confirmed the issue in the web component using the following code:

```html
<vaadin-text-field autocapitalize="characters"></vaadin-text-field>
```

Note, this only happens in Chrome - Safari and Firefox work correctly:

### Chrome

![Screenshot 2022-12-28 at 11 46 40](https://user-images.githubusercontent.com/10589913/209792566-85a2837b-33f6-41a3-8c88-a7ca724776d0.png)

### Firefox

![Screenshot 2022-12-28 at 11 47 12](https://user-images.githubusercontent.com/10589913/209792629-2bdad703-4a3a-473a-b4de-93b33819fabe.png)

### Safari

![Screenshot 2022-12-28 at 11 47 41](https://user-images.githubusercontent.com/10589913/209792719-10265f72-16b3-44a1-b062-2edb889384e6.png)

---

For some reason, in Chrome the initial observer responsible for delegating attributes isn't triggered 🤔
