### ISSUE TITLE
CheckBox in disabled state does not show title

### ISSUE THREAD

**Issue by web-padawan** [vaadin/flow-components#4456]
### Description

Based on #4455, see https://github.com/vaadin/flow-components/issues/4455#issuecomment-1366609975

If the CheckBox is disabled, the `title` attribute is not shown.

### Expected outcome

Expected the `title` to be shown as in case of the `TextField`.

### Minimal reproducible example

```java
CheckBox checkBox = new CheckBox();
checkBox.setDisabled(true);
checkBox.getElement().setAttribute("title", "Test");
```

### Steps to reproduce

See example above.

### Environment

Vaadin version(s): 23.3.2

### Browsers

Issue is not browser related

**Comment by rolfsmeds** [comment]
`pointer-events:none` also disables the native title afaik, so I don't think this is a separate issue?

**Comment by web-padawan** [comment]
Yes, it's expected. But @simasch mentioned that in `TextField` this works. I will take a closer look.

**Comment by simasch** [comment]
@rolfsmeds You are right!
I just noticed that we set TextFields to read-only not disabled and that's why the hint works.

But thanks to your comment I found a workaround and set 

```
:host([disabled]) {
	pointer-events: all;
}
```

@web-padawan  So if pointer-events is set to none on all components, then this is no a bug!

**Comment by web-padawan** [comment]
OK, thanks for double checking. Then I'm closing this issue as working as intended.
Note, we might reconsider this later as part of https://github.com/vaadin/web-components/issues/4585.
