### ISSUE TITLE
Tab inner content display issue

### ISSUE THREAD

**Issue by oilhands** [vaadin/flow-components#4484]
### Description

In response to another issue with the Grid in 23.3.1 it was suggested that I update to 23.3.2. Sure, sounds fine. Anyway, I did this. Now, when I go to my formerly functioning UI the visible elements are not displayed and it seems like it was only partially initialized. However, no errors in the logs and nothing in the Vaadin UI dev mode log thing, either. Decidedly odd. 

### Expected outcome

Well, a functioning UI would be good. I'm really looking for some hints on upping log output or something to get more feedback.

### Minimal reproducible example

N/A

### Steps to reproduce

N/A

### Environment

Vaadin version(s): 23.3.2
OS: Ubuntu 22.04

### Browsers

Issue is not browser related

**Comment by web-padawan** [comment]
Could you please provide a code example so that we could investigate the issue? 

> when I go to my formerly functioning UI the visible elements are not displayed

Can you also reproduce this issue with a project from start.vaadin.com? Or maybe provide a screenshot?
Are there any errors / warnings in the browser console, or is it so that UI looks broken with no errors?

**Comment by oilhands** [comment]
Yeah, I wish I could easily do that. The complexity is pretty crazy. 

There are no warnings, errors, or feedback of any kind. The content of the inner tab is displayed just fine on the primary tab if I click the non-default tab (whose contents display just fine) and then click back on the primary tab. Everything seems to display just fine when I return to the primary tab. 

Like I was saying, in 23.3.1 I get the other issue which I submitted (closed/fixed in 23.3.2) but in 23.3.0 no issues. I'll try to spend a bit more time and see if I can provide any additional info.

**Comment by web-padawan** [comment]
Just to clarify, in Vaadin 23.3.1 we implemented a few performance improvements for grid - see [release notes](https://github.com/vaadin/web-components/releases/tag/v23.3.1).
This introduced a regression that was later fixed in 23.3.2 by this PR: https://github.com/vaadin/web-components/pull/5153

It might be that some of these changes that aimed to reduce DOM operations introduced some instability.
We are really sorry about that, but all our internal tests passed, so this seems like an edge case to me.

**Comment by oilhands** [comment]
Oh, okay. Thanks for the additional info. I understand you all are doing your best. I'm hoping to look at it this afternoon. Thanks.

**Comment by oilhands** [comment]
This is my bug. It looks like, anyway. Too many moving parts on my end. Please close.
