### ISSUE TITLE
Setting an item label generator in CheckboxGroup should override/remove any renderer

### ISSUE THREAD

**Issue by ugur-vaadin** [vaadin/flow-components#4522]
### Description

Setting an itemLabelGenerator in `CheckboxGroup` via doesn't do anything in case a `Renderer` is set.

### Expected outcome

The implementation of `CheckboxGroup.setItemLabelGenerator` should align with [that of RadioButtonGroup](https://github.com/vaadin/flow-components/blob/b5a97698b1fc895bdb64d06c3e6b41abd8c38d0c/vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java#L366). Setting an item label generator to a `CheckboxGroup` should override/remove any renderer if there was one. JavaDocs should also be updated to reflect this change.

### Minimal reproducible example

```
CheckboxGroup<String> group = new CheckboxGroup<>();
group.setItems("Joe", "John", "Bill");
group.setRenderer(new TextRenderer<>(item -> item));
group.setItemLabelGenerator(item -> item + " Updated");
```

### Steps to reproduce

1. Add the snippet above to a view.
2. Notice that the item label generator does not affect the output.

### Environment

Vaadin version(s): 24
OS: MacOS

### Browsers

Issue is not browser related

**Comment by sissbruecker** [comment]
Outcome from grooming: Let's align the behavior with `RadioButtonGroup` if we can manage to do it before v24 beta. Otherwise let's document the different behaviour.
