### ISSUE TITLE
Grid Pro: API for configuring conditionally enabled cell editors 

### ISSUE THREAD

**Issue by taefi** [vaadin/flow-components#4524]
### Describe your motivation

Following [this](https://cookbook.vaadin.com/grid-pro-conditional-edit) cookbook example I found out that it is unnecessarily complicated and repetitive task to configure conditionally enabled cell editors for EditColumns. 

### Describe the solution you'd like

A desired API e.g. called `setCellEditorEnabledProvider` that accepts a `SerializableFunction<T, Boolean>` (where `T` is the generic entity type of the grid) holding the logic for determining the edibility of a cell. 

Then this function could be evaluated automatically any time a `CellEditStartedEvent` raises, or even before that, e.g. upon raising a currently non-existing `BeforeCellEditStarted` event.

**Comment by tomivirkki** [comment]
The API / timing probably needs to be similar to the class name generator APIs because the editability of a cell can also be visually indicated; the information needs to be available when the cell is rendered.

Also related https://github.com/vaadin/web-components/issues/3464

**Comment by alasdairg** [comment]
The API should also make available the row and column to the function which decides one editability - the decision might not be just based on the data value but perhaps the position of the cell within the grid

**Comment by neelu-sarkar** [comment]
+1 for this feature

**Comment by rolfsmeds** [comment]
Just so that it's not forgotten, I want to mention that the `editable-cell` part name applied to cells also needs to match the actual editability of the cell.

**Comment by sissbruecker** [comment]
Some notes from looking into this:

- Web component
	- New `editEnabledProvider` API in `InlineEditingMixin` (naming to be defined)
	- Prevents starting edit on non-editable cells
	- Cell switching logic handles non-editable cells
	- `editable-cell` part name only added for editable cells
- Flow component
	- New `setEditEnabledProvider` API on `EditColumn` (naming to be defined)
	- Item / row data pushed to client includes information for each column whether it is editable
	- Grid Pro connector defines provider function on WC
	- Server-side item updated events are ignored if cell is not editable

**Comment by rolfsmeds** [comment]
Acceptance Criteria for this feature: https://github.com/vaadin/platform/issues/5177

**Comment by web-padawan** [comment]
This feature implemented in #6158 is now available in 24.4 beta. Closing as completed.
