### ISSUE TITLE
[GridPro] Javascript error when tabbing out of edited cell

### ISSUE THREAD

**Issue by sissbruecker** [vaadin/flow-components#4562]
### Description

If a column uses a `ComponentRenderer`, then tabbing out of an edited cell results in Javascript errors like these:
```
Uncaught (in promise) TypeError: parentNode is null
    get parentNode lit-html.js:796
    _$setValue lit-html.ts:1348
    setValue async-directive.ts:366
    update until.ts:90
    promise callback*update until.ts:72
    _$resolve directive.ts:134
    resolveDirective lit-html.ts:1077
    _$setValue lit-html.ts:1353
    _update lit-html.ts:1181
    _commitTemplateResult lit-html.ts:1525
    _$setValue lit-html.ts:1375
    render lit-html.ts:2169
    anonymous lit-renderer.ts line 5 > Function:12
    renderer lit-renderer.ts:87
    _updateItem vaadin-grid.js:1094
    iterateChildren vaadin-grid-helpers.js:21
    _updateItem vaadin-grid.js:1091
    _updateItem gridConnector.js:481
    tryCatchWrapper FlowBootstrap.js:64
    _removeEditor vaadin-grid-pro-edit-column.js:250
    _stopCellEdit vaadin-grid-pro-edit-column.js:298
    _stopEdit vaadin-grid-pro-inline-editing-mixin.js:393
    _switchEditCell vaadin-grid-pro-inline-editing-mixin.js:461
    ready vaadin-grid-pro-inline-editing-mixin.js:93
```

Apart from the error, the cell seems to render fine afterwards. The issue seems to only occur when pressing <kbd>Tab</kbd>.

The issue is a regression in v24 and has been introduced with this PR:
- https://github.com/vaadin/flow-components/pull/4483 

### Expected outcome

There should be no Javascript errors.

### Minimal reproducible example

Use https://github.com/vaadin/flow-components/blob/master/vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/tests/MainView.java

### Steps to reproduce

1. Open the IT page
2. In the first grid, double click on a cell in the "Department" column
3. Press <kbd>Tab</kbd>

### Environment

Vaadin version(s): v24

### Browsers

Issue is not browser related

**Comment by tomivirkki** [comment]
This is somehow related to using the asynchronous `until` directive in the `getNode` [helper function](https://github.com/vaadin/flow-components/blob/3a5d660453fe63294c7391699ec44a8f7b843a29/vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/resources/META-INF/resources/frontend/flow-component-renderer.js#L24-L34). Removing the directive and just returning the node as such resolves the issue.

**Comment by tomivirkki** [comment]
This issue can be reproduced in the `web-components` project's `grid-pro.html` dev page with the following snippet:

```js
import { render, html } from 'lit';
import { until } from 'lit/directives/until.js';

const column = document.querySelector('vaadin-grid-pro-edit-column');
column.renderer = (root, _, model) => {
  const node = document.createElement('div');
  node.innerText = model.item.name.first;
  const result = until(new Promise((resolve) => resolve(node)));
  render(html`${result}`, root);
};
```
