### ISSUE TITLE
[map] Support custom data in a Feature

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow-components#4568]
### Describe your motivation

In many cases when you use markers you map some location data to a marker. When you click on the marker, you want to retrieve the location data and then do something based on that. 

### Describe the solution you'd like

It would be handy if that location data could be stored as part of a Feature (server side only) instead of having to do a separate `Map<Feature,LocationData>` with the data.

**Comment by yuriy-fix** [comment]
Closing as a duplicate of https://github.com/vaadin/flow-components/issues/2681
