### ISSUE TITLE
No display of a Chart component

### ISSUE THREAD

**Issue by provi-dominik** [vaadin/flow-components#4587]
### Description

If I add a Chart component to a part of my application, the chart does not appear. No information is shown in the browser console and the log.
In the HTML DOM the chart element is listed, but it hasn't any child elements.
![image](https://user-images.githubusercontent.com/79461757/214018743-6b182096-545f-4be9-88f0-20628b1981cf.png)
In a simple application the chart is displayed with the same code.

If I add the following code to the root route of the app, the chart is displayed:
_Chart chart = new Chart();
chart.getClass();_
It seems that the the chart isn't integrated into the generated jar, if I don't add this code.

### Expected outcome

The Chart component is displayed.

### Minimal reproducible example

So far I haven't been able to reproduce the issue in a simple example.

### Steps to reproduce

see above

### Environment

Vaadin version(s): 14.9.4
OS: Windows 10 Enterprise (Build 20H2, OS build 19042.1889)

### Browsers

Chrome

**Comment by TatuLund** [comment]
Are you using Chart in your view declaratively? I.e. instead of using it thru Java API, do you have e.g. Lit or Polymer template file, where you have it? If so, then what you see is expected, as in production mode build, the plugin scans the Java code for occurrences of the components. If you use a web component in template, without reference to it in Java, you need to add @Uses(Chart.class) somewhere.

**Comment by provi-dominik** [comment]
I am using the Chart component thru the Java API.
With the @uses annotation it works as expected, but in my opinion it should work without the annotation.

**Comment by provi-dominik** [comment]
I would like to add that this issue appears with the switch from Vaadin version 14.8.20 to 14.9.0.

**Comment by TatuLund** [comment]
Is it possible for you to provide minimal example project that reproduces the problem?

**Comment by provi-dominik** [comment]
Unfortunately, I have not yet been able to reproduce this error in a simple example.

**Comment by yuriy-fix** [comment]
Closing as stale. Please create a new issue if there will be a possibility to create a reproducible example.
