### ISSUE TITLE
DataProvider.refreshAll() should clear Grid selection

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow-components#4592]
### Description

I have a Grid, showing a list of beans loaded from the database. The Grid is multi-select. There is a filter bar above the Grid.

I select a couple of items from the Grid which enables a couple of buttons (e.g. "Delete selected" button). Then I modify the filter value, which calls the `DataProvider.refreshAll()` which populates Grid with a subset of entities. Say that the old entities were filtered out. The problem is that the "Delete selected" button is still enabled and will delete entities that are not even shown in the Grid.

The problem is as follows:

* `Grid.getSelectedItems()` contains a non-empty set of entities, even though when you scroll through the Grid, you'll see that no entities are actually selected. This is most visible when the new filter provides only a handful (20) of entities, none of them appear selected in the Grid.
* The button stays enabled since the set of selected items is not empty.
* The button deletes unknown set of entities on click.

I'd argue that the Grid visual is inconsistent with its state: the Grid shows no rows selected while `Grid.getSelectedItems()` returns a bunch of rows selected.

### Expected outcome

This is tricky. Perhaps the Grid should go through the selection and remove any item which is no longer returned by the DataProvider. This may have horrendous performance and may not even be doable. Also see #3796

Alternatively, the Grid could clear its selection on `refreshAll()`. A new function `Grid.clearSelectionOnRefresh(boolean)` can be called; calling `Grid.clearSelectionOnRefresh(false)` would revert to the original behavior. The function javadoc would clearly state the dangers of such behavior.

### Minimal reproducible example

```java
public class GridBugTest {
    @Test
    public void refreshingDataProviderClearsSelection() {
        final Grid<String> grid = new Grid<>();
        grid.setSelectionMode(Grid.SelectionMode.MULTI);
        final ListDataProvider<String> dp = new ListDataProvider<>(Arrays.asList("a", "b", "c"));
        grid.setDataProvider(dp);
        assertArrayEquals(new Object[0], grid.getSelectedItems().toArray());
        grid.select("a");
        assertArrayEquals(new Object[] { "a" }, grid.getSelectedItems().toArray());

        // setting new filter calls refreshAll() on the data provider.
        dp.setFilter(item -> item.equals("b"));
        assertArrayEquals(new Object[0], grid.getSelectedItems().toArray());
    }
}
```

### Steps to reproduce

1. Run the JUnit test above.

### Environment

Vaadin version(s): 14.8.10
OS: 

### Browsers

Issue is not browser related

**Comment by TatuLund** [comment]
> Vaadin version(s): 14.8.10

Have you tried 14.9.5?

It should have this fix backported: https://github.com/vaadin/flow-components/pull/2947

**Comment by mvysny** [comment]
@TatuLund thank you, just tried 14.9.5 but unfortunately the test also fails on the last line - the selection still contains the "a" item.

I have modified the original example a bit. The last two lines of the original test read as:
```
dp.refreshAll();
assertArrayEquals(new Object[0], grid.getSelectedItems().toArray());
```
and would fail the test.

The new one reads as:
```
dp.setFilter(item -> item.equals("b"));
assertArrayEquals(new Object[0], grid.getSelectedItems().toArray());
```
unfortunately the test still fails.

However, setting a new data provider clears the selection:
```
grid.setDataProvider(new ListDataProvider<>(Arrays.asList("d", "e", "f"));
assertArrayEquals(new Object[0], grid.getSelectedItems().toArray());
```
this passes correctly.

**Comment by mvysny** [comment]
Workaround is to override `onDataProviderChange()`:
```java
public class FixedGrid<T> extends Grid<T> {
    @Override
    protected void onDataProviderChange() {
        super.onDataProviderChange();
        getSelectionModel().deselectAll();
    }
}
```
That fixes the test, but I have to test whether there are no visual glitches in the component itself at runtime.

**Comment by tomivirkki** [comment]
> DataProvider.refreshAll() should clear Grid selection

There is another issue suggesting `refreshAll()` clearing the selection (in `CheckboxGroup`) is a bug https://github.com/vaadin/flow-components/issues/2674

**Comment by TatuLund** [comment]
True, the fix I linked fixes the issue of Grid selection not being updated correctly when underlying dataprovider has identity is overriden. 

Now what you ask is actually change to the intended behavior and hence a breaking change.

**Comment by TatuLund** [comment]
IMHO there should be API to define the behavior, since depending on specific application the both behaviors are justified.

**Comment by mvysny** [comment]
> Now what you ask is actually change to the intended behavior and hence a breaking change.

@TatuLund Depends on the point of view. A bug fix is a breaking change as well, yet we fix those. Would you perhaps consider this a bug?

> There is another issue suggesting 

@tomivirkki yup, I know. I was merely hoping to open a discussion. CheckboxGroup doesn't deal with huge InMemoryDataProviders, and therefore a fix feasible for CheckboxGroup may not be feasible for a Grid.

> IMHO there should be API to define the behavior, since depending on specific application the both behaviors are justified.

Perhaps, if the original behavior is considered not-a-bug. I personally think it to be a bug: the Grid visually shows nothing being selected yet the API returns a non-empty selection.

Truly there are two levels of discussion:
* Is this a bug or not?
* Should we add `Grid.setClearSelectionOnRefresh()` ? I think we both agree that it would be good to have this; the question is what should be the default behavior. The answer to that depends on the answer to the first question.

I've tested `FixedGrid` in a simple `MainView` and the fix seems to be working well, no visual artifacts.

**Comment by TatuLund** [comment]
I just remembered that ticket for new API is here: https://github.com/vaadin/platform/issues/3640

**Comment by Legioth** [comment]
Refreshing should sometimes clear the selection and sometimes not. As a trivial example, adding a filter might invalidate the selection whereas removing filters might not invalidate the selection. But this also depends on application-specific semantics. Selection as a value has different semantics than selection as the target of actions.

It should thus be possible for the application developer to decide. I don't think `Grid::setClearSelectionOnRefresh` makes sense since there are definitely cases where you'd want to set the appropriate configuration before triggering each refresh. It would thus be more natural if this would be an aspect of the refresh action rather than an aspect of the component.

No matter what we do, we still need to pick a default. I suggest that it's a better default to preserve the selection. This is based on how much code is needed for a workaround if the default isn't right. To prevent selection from being cleared, you need one statement before the refresh to fetch the current selection and another statement afterwards to restore it. Forcing selection to be cleared if it isn't does on the other hand just need a statement after refresh but nothing before.

**Comment by Legioth** [comment]
There's actually also a third option between preserving the full selection and completely clearing the selection, and that's to run the filters again against each selected item and preserve the items that match the new filter. This is again something that the component cannot do on the application developer's default unless we add new features such as a new method in `DataProvider` to check if a specific item is "still" present.

If nothing else, this implies that `Grid::setClearSelectionOnRefresh` or something similar associated with a refresh action should not be a `boolean`, but instead an enum (that might initially have two values but with the option that we might add a third one later) or `Predicate<T>` that you can implement as `item -> true` or `item -> false` for the trivial cases but with custom logic if you want to prune the selection based on knowledge that the application has.

**Comment by web-padawan** [comment]
Adding related issues concerning other components for future reference:

- https://github.com/vaadin/flow-components/issues/2593
- https://github.com/vaadin/flow-components/issues/2674
- https://github.com/vaadin/flow-components/issues/3239

**Comment by simasch** [comment]
In my case I need the selection to stay if I filter the grid

**Comment by sephiroth-j** [comment]
My workaround is to call `getSelectionModel().deselectAll()` in the `ValueChangeListener` of the used search field (e.g. `TextField`) when `dataProvider.setFilter(filter)` is called.

```java
var searchfield = new TextField();
searchfield.addValueChangeListener(e -> {
  // ...
  dataProvider.setFilter(filter);

  // clear selections
  grid.getSelectionModel().deselectAll();
});

p.s.
Vaadin 24.4

**Comment by sissbruecker** [comment]
This should now be doable with setting the respective selection preservation mode:
```java
grid.setSelectionPreservationMode(SelectionPreservationMode.DISCARD);
// or
grid.setSelectionPreservationMode(SelectionPreservationMode.PRESERVE_EXISTING); // only for in-memory DPs
```

**Comment by simasch** [comment]
That's cool! @sissbruecker
