### ISSUE TITLE
PiT 24.0: IntegerField does not show controls

### ISSUE THREAD

**Issue by manolo** [vaadin/flow-components#4606]
### Description

When migrating bakery from 23.3 to 24.0 we found that IntegerField does not show +/- controls.
See these two screenshots comparing the storefront editor in both versions

**V23.3**
![Screenshot 2023-01-27 at 09 27 02](https://user-images.githubusercontent.com/161853/215045347-fdb7c819-96e7-4ab0-8a4a-c69a95efbe53.png)

**V24.0**
![Screenshot 2023-01-27 at 09 26 50](https://user-images.githubusercontent.com/161853/215045361-e017366a-9fe7-4acd-9fe3-5a71c917d83d.png)

### Expected outcome

I can use +/- buttons in the view

### Minimal reproducible example

```
git clone https://github.com/vaadin/bakery-app-starter-flow-spring.git
cd bakery-app-starter-flow-spring
git checkout v24
mvn
```

### Steps to reproduce

1. open http://localhost:8080
2. Login as admin
3. Go to storefront view
4. click any card
5. click on Edit Order button
6. In the products section, integer field does not have +/- contros

### Environment

Vaadin version(s): 24.0.0.alpha9

### Browsers

Issue is not browser related

**Comment by sissbruecker** [comment]
This is the result of a breaking change that removed the `has-controls` property: https://github.com/vaadin/flow-components/pull/4046

Pushed a commit to use the new `step-buttons-visible` property: https://github.com/vaadin/bakery-app-starter-flow-spring/commit/7171fafd0d58df2b70d2b9ad3c02d6ae66f295bd

**Comment by manolo** [comment]
Is this mentioned in the migration guide?

**Comment by sissbruecker** [comment]
It's listed in our planning document, so it's going to end up in the upgrade guide.

**Comment by rolfsmeds** [comment]
It's listed for NumberField, where the change was made: https://vaadin.com/docs/next/upgrading/V23-V24-steps/#removed-flow-component-apis
> NumberField::setHasControls renamed setStepButtonsVisible

But IntegerField should probably be mentioned explicitly.
