### ISSUE TITLE
PiT 24.0: Crud shows an extra 'New Item' button

### ISSUE THREAD

**Issue by manolo** [vaadin/flow-components#4607]
### Description

When migrating bakery from 23.3 to 24.0 we found that Crud views show an extra button for new items, breaking tests.
See these two screenshots comparing the same view in both versions

**V23.3**
![Screenshot 2023-01-27 at 09 35 23](https://user-images.githubusercontent.com/161853/215050540-0fa709af-b902-46ba-817b-a026088c5486.png)

**V24.0**
![Screenshot 2023-01-27 at 09 35 05](https://user-images.githubusercontent.com/161853/215050549-177e85fe-463b-4cc3-8756-94326ad152ee.png)

### Expected outcome

One button should be displayed, and test should pass.

### Minimal reproducible example

```
git clone https://github.com/vaadin/bakery-app-starter-flow-spring.git
cd bakery-app-starter-flow-spring
git checkout v24
mvn
```

### Steps to reproduce

1. open http://localhost:8080
2. login as admin
3. go to Users view
4. in the search bar there are two edit buttons
5. only one button has behaviour

### Environment

Vaadin version(s): 24.0.0.alpha9

### Browsers

Issue is not browser related

**Comment by web-padawan** [comment]
Hi, this is actually a result of a breaking change that we made related to using toolbar / "New" button.

- **Before**: in V14 - V23, users had to set `new-button` attribute on the element added to the toolbar,
- **After**: there is now a separate API for providing a "New" button, in addition to `setToolbar` API.

https://github.com/vaadin/flow-components/blob/649dfebd0cf1b32d921ed66bce6fc938099f4afd/vaadin-crud-flow-parent/vaadin-crud-flow/src/main/java/com/vaadin/flow/component/crud/Crud.java#L565-L568

The [following lines](https://github.com/vaadin/bakery-app-starter-flow-spring/blob/eb236610e0bf3713d4d1ed1c913724783587c3c8/src/main/java/com/vaadin/starter/bakery/ui/crud/AbstractBakeryCrudView.java#L58-L60) need to be updated accordingly to remove `getElement().setAttribute("new-button", true)` code.
One note: from now on, a "New" button has to be decoupled from the `SearchBar` - this is a limitation to document.

**Comment by manolo** [comment]
So this breaking change is from 23.3 to 24, there was no deprecation period, right?

**Comment by web-padawan** [comment]
Yes, this is a breaking change. We took the liberty to introduce it because it was related to V24 styling API breaking changes and we will mention it in the upgrade guide.

Originally, the default "New" button was in shadow DOM, this making it impossible to style with global CSS. This is now changed in V24 by moving the default button to the slot.

As the change only concerns custom toolbar, we consider it reasonably small to land without deprecation. Furthermore, the `setToolbar` API is still there, only the attribute logic has been changed.

**Comment by manolo** [comment]
I created this [PR](https://github.com/vaadin/bakery-app-starter-flow-spring/pull/1227) mind to take a look? not sure this is the best approach because there are still couple of issues I couldn't fix properly

**Comment by web-padawan** [comment]
Thanks, I will take a look.

**Comment by sissbruecker** [comment]
IMO the current implementation of the user and product views make this harder than this should be as they abuse the `Crud` as a layout component. I don't think this should be recommended as best practice. 
Instead, I would suggest refactoring these views to uses a proper layout component, hide the `Crud` toolbar completely, and just add the custom search bar component to the view's layout: https://github.com/vaadin/bakery-app-starter-flow-spring/pull/1228

**Comment by sissbruecker** [comment]
Not sure what to make of the tests, the user and product views test pass for me, but I get failures from other views. There might still be some other issues.

**Comment by sissbruecker** [comment]
For completeness sake, here is a more minimal version of a possible migration using the existing approach: https://github.com/vaadin/bakery-app-starter-flow-spring/commit/48e60d8e8c9ad22ad0286b3dbd73ca66a44ca121

I would still recommend to refactor the views though to discourage anyone from adopting this approach.

**Comment by manolo** [comment]
@sissbruecker Problem with assertion is because of https://github.com/vaadin/flow/issues/15763

**Comment by sissbruecker** [comment]
Closing as https://github.com/vaadin/bakery-app-starter-flow-spring/pull/1228 has been merged.
