### ISSUE TITLE
Endless resizing loop when using a grid inside a dialog

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/flow-components#4610]
### Description

Adding a dialog with a grid inside it, with a specific style will produce and endless loop of resizing. This is what I see:

![Twearking](https://user-images.githubusercontent.com/28312758/215154610-5775aed6-e8bb-4380-8e35-a295a5a7ead3.gif)

### Expected outcome

The size of the dialog should be resized accordingly without this twerking effect.

### Minimal reproducible example

I'm attaching a sample project to reproduce the issue:

[dialog-grid-twerking.zip](https://github.com/vaadin/flow-components/files/10521479/dialog-grid-twerking.zip)

### Steps to reproduce

I was able to reproduce this issue in the following environment:

- Windows 10
- Chrome 109.0.5414.120
- Screen resolution: 1920x1080
- Set the scale & layout to 125% like the following image:
![image](https://user-images.githubusercontent.com/28312758/215155448-ed0caa83-6d16-42e5-ac57-c38e2e394898.png)

Steps to reproduce:

1. Start the application and browse to http://localhost:8080
2. Click the "Open" button
3. Set the chrome zoom to 75%
4. Press the "Start twerking" button

After that the grid will try to resize itself in an endless loop

### Environment

Vaadin version(s): 23.2.13
OS: Windows 10
Chrome: 109.0.5414.120

### Browsers

Chrome

**Comment by rolfsmeds** [comment]
The issue was triaged and currently added to the backlog priority queue for further investigation.

**Comment by DiegoCardoso** [comment]
I started investigating the issue and will work on the fix.

**Comment by DiegoCardoso** [comment]
The PR fixing this issue has been merged and is expected to be released on version **24.0.0**, **23.3.7** and **23.2.17**.
