### ISSUE TITLE
TreeGrid: refreshAll shows empty rows if number of items exceeds page size

### ISSUE THREAD

**Issue by paodb** [vaadin/flow-components#4611]
### Description

When calling refreshAll on a TreeGrid empty rows are shown instead of items, as soon as the number of items exceeds the page size value.

### Expected outcome

See all the my TreeGrid items after calling refreshAll.

### Minimal reproducible example

Example project: 
[v23-tree-grid-refresh-issue.zip](https://github.com/vaadin/flow-components/files/10522440/v23-tree-grid-refresh-issue.zip)

There're 2 examples in it, the first one has a page size set to 10 an has 11 items. The second one, has 60 items and it's using the default page size (50). 

### Steps to reproduce

1 - Run attached example project.
2 - In first example (left) select an item and then click "refresh all" button.
3 - Scroll to the bottom of the tree and see last item is missing and an empty row is shown instead. 

![tree-grid-page-size-10](https://user-images.githubusercontent.com/30666649/215180155-a127aa71-431e-497b-9aed-6d3f34b8221f.gif)

4 - In second example (right) select an item and then click "refresh all" button.
5 - Scroll to the bottom of the tree and see last items are missing and empty rows are shown instead.

![tree-grid-default-page-size](https://user-images.githubusercontent.com/30666649/215180203-2fe56dad-10a9-4df6-8313-c972058b067f.gif)

Also, notice that in both examples, when clicking on the empty rows, a item from the tree is selected.

### Environment

Vaadin version(s): 23.3.5
OS: Windows 10

### Browsers

Chrome, Firefox

**Comment by yuriy-fix** [comment]
### Minimal reproducible example (extracted from the app provided)

First (page size = 10): 
```
TreeGrid<String> treegrid = new TreeGrid<>();
TreeData<String> treeData = new TreeData<>();

treegrid.addHierarchyColumn(item -> item);

List<String> rootItems = IntStream.iterate(1, i -> i + 1).limit(11).mapToObj(String::valueOf)
        .collect(Collectors.toList());
treeData.addRootItems(rootItems);

for (String parentItem : rootItems) {
    treeData.addItem(parentItem, "item: " + parentItem);
}

TreeDataProvider<String> provider = new TreeDataProvider<>(treeData);
treegrid.setDataProvider(provider);

treegrid.setPageSize(10);
treegrid.expand(treeData.getRootItems());

Button button = new Button("Refresh All in Tree Grid", e -> provider.refreshAll());
```

Second (default page size):
```
TreeGrid<String> treegrid2 = new TreeGrid<>();
TreeData<String> treeData2 = new TreeData<>();

treegrid2.addHierarchyColumn(item -> item);

List<String> rootItems2 = IntStream.iterate(1, i -> i + 1).limit(60).mapToObj(String::valueOf)
        .collect(Collectors.toList());
treeData2.addRootItems(rootItems2);

for (String parentItem : rootItems2) {
    treeData2.addItem(parentItem, "item: " + parentItem);
}

TreeDataProvider<String> provider2 = new TreeDataProvider<>(treeData2);
treegrid2.setDataProvider(provider2);

treegrid2.expand(treeData2.getRootItems());

Button button2 = new Button("Refresh All in Tree Grid 2", e -> provider2.refreshAll());
```

**Comment by yuriy-fix** [comment]
The issue was triaged and currently added to the backlog priority queue for further investigation.

**Comment by ugur-vaadin** [comment]
I started investigating the issue and will work on the fix.

**Comment by ugur-vaadin** [comment]
A [PR](https://github.com/vaadin/flow-components/pull/4657) is ready for review that should fix this issue.

**Comment by ugur-vaadin** [comment]
The issue has been [fixed](https://github.com/vaadin/flow-components/pull/4657) and [back-ported](https://github.com/vaadin/flow-components/pull/4683) to v23.3.
