### ISSUE TITLE
Grid freezes if one clicks right mouse button while holding a column header

### ISSUE THREAD

**Issue by sujoykd** [vaadin/flow-components#4623]
### Description

There is an option to move a column in order to change the order of columns. To do that one just left clicks at the column header and simply drag the column to the expected position.

However, if one clicks right mouse button while holding a column header this way, the table view gets frozen.  In order to recover one can either click and hold any column or click and drag the frozen header.

### Expected outcome

On right click the drag operation could be considered as complete, and the header re-ordering completed based on the current position.

### Minimal reproducible example

This can be verified from our Column Reordering & Resizing example in the docs - https://vaadin.com/docs/latest/components/grid/#column-reordering-resizing

### Steps to reproduce

This can be verified from our Column Reordering & Resizing example in the docs - https://vaadin.com/docs/latest/components/grid/#column-reordering-resizing

1. Left click on a column header and start dragging to re-order it.
2. Right click the mouse button while dragging

### Environment

Vaadin version(s): 23.3.4
OS: Windows 10

**Comment by yuriy-fix** [comment]
The issue is added to the backlog priority queue for further investigation.

**Comment by tomivirkki** [comment]
The issue has been [fixed](https://github.com/vaadin/web-components/pull/5430) and [backported](https://github.com/vaadin/web-components/pull/5431) to 23.3 -branch. I'd expect the fix to be released with one of the upcoming patch releases (probably Vaadin 23.3.7)
