### ISSUE TITLE
[DatePicker] Reference date not working according to documentation

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow-components#4629]
### Description

Based on the documentation, a reference date of 2000-01-01 should give a range of 1950 up to 2049. The actual outcome is, that it will instead generate a range of 1949 to 2048. 

To have the correct range you have to set a reference date of 2000-12-31. 

Since I am not sure, if it works as intended and the documentation is invalid or if the behavior is invalid, it is up to you guys to decide, what to do.

### Expected outcome

Either the documentation needs to be updated or the reference date handling.

### Minimal reproducible example

```java
DatePicker picker = new DatePicker();
DatePicker.DatePickerI18n i18n = new DatePicker.DatePickerI18n();

i18n.setDateFormats("dd.MM.yyyy", "dd.MM.yy"); // german format, use a proper format you want to :) 
i18n.setReferenceDate(LocalDate.of(2000, 1, 1));

picker.setI18n(i18n);

add(picker);
```

### Steps to reproduce

1. Create a sample app and add the given sample code
2. Open the date picker and enter the value "01.01.49" (or something matching your format, if you used something different)
3. The picker will show 1949 as year.

![image](https://user-images.githubusercontent.com/36725474/216001852-4e0542f7-976a-46f9-8582-95e312009b5a.png)

### Environment

Vaadin version(s): 23.3.5
OS: Windows 10

### Browsers

Chrome

**Comment by stefanuebe** [comment]
Additional test case: When I want to parse all short years to be in 21st century, I have to set "2050-12-31". Using "2050-01-01" will parse "99" to 1999 instead of 2099.

**Comment by sissbruecker** [comment]
Re-labeling this as a bug: When configuring a reference date of `2000-01-01`, the date picker connector converts that into a reference date of `1999-12-01`.

**Comment by sissbruecker** [comment]
Looking further into this, there are two issues, which affect only the Flow component:
- The connector subtracts a month from the date, which for a reference date of `2000-01-01`, results in passing `1999-12-01` to date-fns.
- Even though you have to pass a date instance to date-fns, it seems to ignore the day and month of that date, and only uses the year. So for the case above, `1999-12-01` is effectively treated as `1999-01-01`, which explains why everything in the OP is one year off. 

That also means the component currently only supports a reference year, even though the API requires you have to configure a `LocalDate`.

My results from testing this in the date-fns docs:
<img width="504" alt="Bildschirmfoto 2023-02-15 um 16 44 19" src="https://user-images.githubusercontent.com/357820/219077777-8292a8f2-76f0-4469-86a3-83ea5f4be456.png">

All of the entered dates should result in a year >2000, however only when entering a short year of `48`, this actually happens.
