### ISSUE TITLE
[DatePicker] Provide a method to set a reference year. 

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow-components#4630]
### Describe your motivation

In most cases only the year is relevant for a reference date. Currently it has to be always a `LocalDate` object to set the reference date. 

For a better DX we should also provide an integer based method (either overloading reference date or naming it "referenceYear").
 

### Describe the solution you'd like

```java
i18n.setReferenceYear(2050); // must be a valid year, that can be internally converted to a valid reference date
```

### Describe alternatives you've considered

Using the currently existing method.

**Comment by yuriy-fix** [comment]
Closing as a duplicate of https://github.com/vaadin/flow-components/issues/4327
