### ISSUE TITLE
TreeGrid.defaultUniqueKeyProvider is in no way providing a unique key

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow-components#464]
The implementation here https://github.com/vaadin/vaadin-flow-components/blob/master/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java#L147 is
```
    private final ValueProvider<T, String> defaultUniqueKeyProvider = item -> String.valueOf(item.hashCode());
```

There is no way you can get a unique key by using `hashCode`

**Comment by rolfsmeds** [comment]
Possibly related:
https://github.com/vaadin/vaadin-grid/issues/1925
https://github.com/vaadin/vaadin-grid/issues/1977
