### ISSUE TITLE
Closing Dialog with ComboBox can freeze UI for several minutes

### ISSUE THREAD

**Issue by p-engl** [vaadin/flow-components#4664]
### Description

I randomly encountered the following problem: I opened a Dialog with a ComboBox. When I clicked on the ComboBox and then outside of the dialog, the UI froze. The dialog with the combox was still visible, but I could not interact with anything. The ComboBox was opened (i. e. you could see the dropdown which was empty) and the only thing that was moving was the loading indicator of the ComboBox-dropdown.

I created an example to reproduce the issue, however this problem does not show up consistently. You have to open the Dialog, click into the ComboBox, enter a character and then click outside of the Dialog to close it. After several tries the UI should freeze and the browser tab should become unresponsive. The UI can become unresponsive for a few seconds or even serveral minutes.
![combobox_ui_frozen](https://user-images.githubusercontent.com/104434067/217756902-0fddfe3d-d731-48fb-be67-a2bb92998333.png)

I could repoduce this issue in Chrome, Firefox and Edge using Vaadin 23.3.2.

After the browser becomes responsive again, there are warnings like "[Violation] 'focusout' handler took 925727ms", "[Violation] 'input' handler took 1131988ms" or "[Violation] Forced reflow while executing JavaScript took 755962".
![combobox_page_does_not_respond_2](https://user-images.githubusercontent.com/104434067/217757015-78706c81-096f-4bd8-b24b-9551badeab7b.png)
![dev_tools_combobox](https://user-images.githubusercontent.com/104434067/217760844-01886886-c16b-445b-a795-27024b819c17.png)

 
I already tried to investigate the problem a little bit. I was once able to capture a performance profile in Firefox where the UI froze for about 10 seconds. The strange thing ist that in this case the _onFocusOut function was called several times, each time taking roughly 1 second. 
![firefox_performance_profile](https://user-images.githubusercontent.com/104434067/217757105-a4e06519-348d-4079-96cb-71dd7b158ef2.png)

I also captured a performance profile in Chrome. In that case the UI froze only for a few seconds. This time the _onInput function took 2.6 seconds (causing several style recalculations). The only interesting part I could see in that profile was that there were several animations during that time.
![chrome_performance_profile](https://user-images.githubusercontent.com/104434067/217757157-c77cc127-b89f-43f0-9389-d6b596194bef.png)

One of my workmates encountered a similar problem but in another context: We have a view which displays a Grid. When you click a button on the view, a background process is started and a "Please Wait" dialog with a progressbar is shown. After the process finishes, the dialog is removed and the Grid should refresh. One time, when the dialog should have been closed, the UI froze for several minutes and only the indeterminate progressbar was moving a little bit (more like twitching than moving). After a few minutes the browser tab became responsive again, the dialog disappeared and the Grid refreshed. I'm not sure whether these problems are related, but I wanted to highlight that it seems like the UI can freeze in multiple occasions.

### Expected outcome

The UI should not freeze

### Minimal reproducible example

@Route("test")
public class TestView extends Div{

	public TestView() {
		setSizeFull();
		Button btn = new Button("Test");
		add(btn);
		btn.addClickListener(e -> onClick());
	}
	
	private void onClick() {
		Dialog dialog = new Dialog();
		dialog.setCloseOnOutsideClick(true);
		dialog.setOpened(true);
		ComboBox<String> cb = new ComboBox<>();
		List<String> items = new ArrayList<>();
		for(int i = 0; i < 10000; i++) {
			items.add(UUID.randomUUID().toString());
		}
		cb.setItems(items);
		dialog.add(cb);
		
	}
}

### Steps to reproduce

Click on the Button to open the Dialog
Click on the ComboBox
Press a key
Click outside of the Dialog

Repeat multiple times until the UI freezes.

### Environment

Vaadin version(s): 23.3.2
OS: Windows 10

### Browsers

Chrome, Firefox, Edge

**Comment by yuriy-fix** [comment]
We should investigate if this issue is reproducible in our environment.

**Comment by web-padawan** [comment]
Tested and could not reproduce the issue using latest `23.3` and `main` branches on MacOS Chrome and Firefox.

**Comment by yuriy-fix** [comment]
Dear @p-engl, unfortunately we were not able to reproduce the issue, so we cannot fix it.
Please create a new issue in case you have additional details on how to reproduce it.
