### ISSUE TITLE
Grid.addComponentColumn() renders empty cells if having multiple identical items in the grid

### ISSUE THREAD

**Issue by andreloeffelmann** [vaadin/flow-components#4677]
### Description

When having a `Grid` with multiple items that are equal to each other (according to the `.equals(Object other)` method) and the columns are not created with `.addColumn(ValueProvider<T, ?> valueProvider)` but with `.addComponentColumn(ValueProvider<T, V> componentProvider)`, only one row is rendered correctly in the UI. The other rows have empty cells for these columns.

This is no consistent behaviour since the rows are correctly rendered if the columns are created with `.addColumn(ValueProvider<T, ?> valueProvider)`.

### Expected outcome

All cells in all rows for identical items should be rendered correctly in the UI when a column is created with `.addComponentColumn(ValueProvider<T, V> componentProvider)`.

### Minimal reproducible example

```java
static class Pojo{
        String test;

        public Pojo(String test) {
            this.test = test;
        }

        public String getTest() {
            return test;
        }

        public void setTest(String test) {
            this.test = test;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            Pojo pojo = (Pojo) o;
            return Objects.equals(test, pojo.test);
        }

        @Override
        public int hashCode() {
            return Objects.hash(test);
        }
}

static List<Pojo> createItems() {
        return List.of(new Pojo("test"), new Pojo("test"));
}

Grid<Pojo> grid= new Grid<>();
grid.addComponentColumn(g -> new Span(g.getTest()));
grid.addColumn(g -> g.getTest());
grid.setItems(createItems());

// now add the grid to a component of you choice. you will see that the first column is only rendered in one row whereas the second column is rendered in both rows.
// if you now modify the "equals()" method of "Pojo" and return "false" always (to force non-identical objects), you will see that the first column is rendered correctly in both rows.
this.add(grid);
```

### Steps to reproduce

1. add the snippet above to a view
2. run and see the falsy rendering of the cells

### Environment

Vaadin version: 23.3.2
OS: Windows 10

### Browsers

Issue is not browser related

**Comment by knoobie** [comment]
This is not supported. See https://mvysny.github.io/grid-and-broken-equals/ for more information.

**Comment by andreloeffelmann** [comment]
Well, this is no Vaadin official blog about this issue, is it?
If it is really not supported, it should be mentioned in the docs of `Grid`.
And if so, `addColumn()` shouldn't work either. 

For the user resp. the consumer of the Vaadin API this is no transparent behaviour. 
Had to invest a lot of time to figure out the technical reason behind this issue.

**Comment by knoobie** [comment]
That's an employee of Vaadin 😉 it was mentioned somewhere in the docs if I remember correctly, not sure where tho.

**Comment by TatuLund** [comment]
In our documentation it is mentioned here: https://vaadin.com/docs/latest/components/grid/flow/#binding-to-data

"To function, components such as the Grid and ComboBox require that the assigned items have identifiers that are stable and unique. This usually requires a proper implementation of the hashCode() and equals() methods as described in the [section](https://vaadin.com/docs/latest/binding-data/data-provider#data-binding.data-provider.item-identifiers)."

**Comment by andreloeffelmann** [comment]
Ah I see, my bad.
Coming from Vaadin 14 I never re-read the docs of the Grid for data binding. And I cannot remember that I ever read such information for v14. At least it is not stated here https://vaadin.com/docs/v14/flow/components/tutorial-flow-grid/#binding-to-data
So I guess this can be closed.

**Comment by TatuLund** [comment]
Yes, our documentation is a continuous improvement process.

> So I guess this can be closed.

Ack.
