### ISSUE TITLE
Tabs [Vaadin 24.0.0.beta1]: ClassCastException in public void add(Component... components)

### ISSUE THREAD

**Issue by Frettman** [vaadin/flow-components#4680]
### Description

`Tabs#add(Component... components)` takes a Component[] (as varargs) and tries to cast it to a Tab[] which is doomed to fail. The method is already deprecated (and I'll move away from it), but it should still probably either be fixed or removed.

### Expected outcome

No ClassCastException or remove the method.

### Minimal reproducible example

```java
public static void main(String[] args)
{
  Component[] tabsArray = {new Tab(), new Tab()};
  Tabs tabs = new Tabs();
  tabs.add(tabsArray);
}
```

### Steps to reproduce

Just execute the snippet above.

### Environment

Vaadin version(s): Vaadin 24.0.0.beta1
OS: Windows 10

**Comment by yuriy-fix** [comment]
Even the deprecated method shouldn't throw a `ClassCastException`, so let's fix it for v24.
