### ISSUE TITLE
MenuBar item content is clipped on resize

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/flow-components#4692]
### Description

MenuBar item content is clipped on resize. The issue only produces with the V24 Java example.

https://user-images.githubusercontent.com/1222264/219593570-3bfb5b90-e923-4046-afee-4a0a26408106.mp4

### Expected outcome

The menu bar item content should be fully visible

### Minimal reproducible example

https://vaadin.com/docs/next/components/menu-bar/#overflow

### Steps to reproduce

1. Open the Java example at https://vaadin.com/docs/next/components/menu-bar/#overflow
2. Reduce the width of the component using the splitter handle
3. Open the overflow dropdown menu
4. Increase the width of the component

### Environment

Vaadin version(s): 24.0.0.beta2

### Browsers

Issue is not browser related

**Comment by bwajtr** [comment]
Note that it's purely a web-component problem and can be reproduced without flow by using "component" property when defining menu items:

```
{
        text: 'Share',
        component: 'div',
        children: [{ text: 'Twitter' }, { text: 'Facebook' }],
      }
```
