### ISSUE TITLE
Charts: setPointFormatter doesn't work

### ISSUE THREAD

**Issue by gpsfl** [vaadin/flow-components#4709]
### Description

I added a custom point formatter function to a series tooltip, but it has no effect.

### Expected outcome

The tooltip should be formatted according to the function

### Minimal reproducible example

```java
final Chart myChart = new Chart(ChartType.LINE);

ListSeries series = new ListSeries("Tokyo", 49.9, 71.5, 106.4);

SeriesTooltip seriesTooltip = new SeriesTooltip();
seriesTooltip.setPointFormatter("function() { return this.x + ' km²' }"); // <-- Custom formatter

PlotOptionsSeries options = new PlotOptionsSeries();
options.setTooltip(seriesTooltip);
series.setPlotOptions(options);

// Tooltip element needs to be configured on chart
myChart.getConfiguration().setTooltip(new Tooltip());

myChart.getConfiguration().addSeries(series);
```

### Steps to reproduce

1. Add the example from above
2. Hover over a data point in the chart

### Environment

Vaadin version(s): 23.3.2
OS: Windows 10

### Browsers

Chrome

**Comment by gpsfl** [comment]
Probably related to the following commit:
https://github.com/vaadin/web-components/commit/3402ea3826e99d4cc8b9978bd60f15e9f01f1264

The data series are sent as an array, but the new method will only inflate objects.

**Comment by echarlus** [comment]
I've encountered the same issue. 
If you set the formatter to  a Tooltip configured at the chart, level it works. If you set it at the Series level then it does not work. 
That's a real pain.

**Comment by ugur-vaadin** [comment]
Closing as a [duplicate](https://github.com/vaadin/flow-components/issues/4696).
