### ISSUE TITLE
Tooltips with HTML content

### ISSUE THREAD

**Issue by finaris-cs** [vaadin/flow-components#4741]
### Describe your motivation

The new tooltip APIs (Tooltip.forComponent and tooltip generator for grids) are good, but currently only text content is supported.
Especially for longer tooltips, formatting would be a good feature.

### Describe the solution you'd like

A simple solution could be just to consider \n characters and make to tooltip wrap there (maybe internally replace \ by &lt;br/&gt; and set as innerHtml).

The better solution would be to treat the tooltip as HTML data and set as innerHtml.

**Comment by TatuLund** [comment]
Duplicate of https://github.com/vaadin/web-components/issues/4976

**Comment by web-padawan** [comment]
Closing per above comment.
