### ISSUE TITLE
Tabs scrolling to end does not work always

### ISSUE THREAD

**Issue by rappenze** [vaadin/flow-components#4744]
### Description

When I use tabs with horizontal scrolling and click on the right arrow to scroll to the end, the right arrow is not always hidden when the end is reached. I can see this behaviour only in Chromium based browsers when the zoom is different then 100%.

### Expected outcome

I would expect that on clicking right arrow in tabs and I scrolled to the end the arrow will disappear.

### Minimal reproducible example

You can reproduce this in the component sampler https://vaadin.com/docs/latest/components/tabs.

### Steps to reproduce

1. Use Edge or Chrome browser
1. Open the sampler page and navigate to the horizontal scrolling example https://vaadin.com/docs/latest/components/tabs
2. Set zoom factor to 125%
3. Click on right arrow ->you see that the arrow does not disappear as it should
![image](https://user-images.githubusercontent.com/29733488/221509592-6fb01e8e-2ca4-4d15-863b-ff377bcbd9df.png)

### Environment

Vaadin version(s): 23.3.6
OS: Windows

### Browsers

Chrome, Edge

**Comment by DiegoCardoso** [comment]
Might be related with https://github.com/vaadin/flow-components/issues/4376

**Comment by jouni** [comment]
Probably some sub-pixel rounding issue.

**Comment by xdenser** [comment]
Also observe same issue also in case when new tab is added and scrolled to.

**Comment by rolfsmeds** [comment]
Can confirm this with Chrome: scrolling does not work with e.g. 125%, 175%, but does work with 100%, 200%, and 250%.

**Comment by yuriy-fix** [comment]
The issue is added to the backlog priority queue for further investigation.

**Comment by rolfsmeds** [comment]
I could also imagine that the DPI setting in Windows might affect it. MacOS doesn't do DPI scaling like that, so that would explain why it behaves differently. Doesn't explain the docs-vs-locally difference though.
