### ISSUE TITLE
Details OpenedChangeListener: unregisterListener can only be called inside the event listener

### ISSUE THREAD

**Issue by probert94** [vaadin/flow-components#4802]
### Description

I register a listener for `OpenedChangeEvent`s on a Vaadin `Details` component and inside the listener, I call `event.unregisterListener`.
Since Vaadin 23.3.7 this results in an exception:
> java.lang.IllegalStateException: unregisterListener can only be called inside the event listener
>		at com.vaadin.flow.component.ComponentEvent.unregisterListener(ComponentEvent.java:90)

### Expected outcome

The listener should be unregistered and no exception should be thrown.

### Minimal reproducible example

```
AccordionPanel panel = new AccordionPanel();
// Add panel content
panel.addThemeVariants(DetailsVariant.FILLED, DetailsVariant.REVERSE);
panel.addOpenedChangeListener(e -> {
  if (e.isOpened())
    e.unregisterListener();
});
```

### Steps to reproduce

1. Add an AccordionPanel to a Vaadin  application using the above code
2. Add a few items to the panel
3. Open the webpage and open one of the Details

### Environment

Vaadin version(s):  23.3.7

### Browsers

Issue is not browser related

### Notes
The issue does not occur on 23.3.6 and is related to https://github.com/vaadin/flow-components/pull/4665

**Comment by TatuLund** [comment]
You should use the `Registration `to remove the listener, not the via event.

```
@Route("accordion")
public class AccordionView extends Div {

    private Registration reg;

    public AccordionView() {
        AccordionPanel panel = new AccordionPanel();
        panel.setContent(new Span("Hello"));
        // Add panel content
        panel.addThemeVariants(DetailsVariant.FILLED, DetailsVariant.REVERSE);
        reg = panel.addOpenedChangeListener(e -> {
            if (e.isOpened()) {
                reg.remove();
                Notification.show("Hello once!");
            }
        });
        add(panel);
    }
}
```

**Comment by probert94** [comment]
@TatuLund I don't think, that I should use `Registration#remove`. To use this, I would need a member, which is not always possible (for example in a static context).
Also, the error states, that I have to call this method inside the invokation, which is exactly what I do.
The problem here is, that the `unregisterListenerCommand` is only set inside `ComponentEventBus#fireEventForListener`, which is not invoked anymore as the listeners are notified manually.
In my opinion this is clearly a bug as it is not the intended behavior.
Also this used to work in Vaadin 23.3.6 so if it realy is is the intended behavior, it would be a breaking change.

**Comment by lmorocz** [comment]
I've just upgraded to Vaadin v14.9.7 and it is also affected, v14.9.2 was fine.
