### ISSUE TITLE
Grid::select uses given Item instead of Item in Grid to render

### ISSUE THREAD

**Issue by knoobie** [vaadin/flow-components#4861]
### Description

Using `Grid::select`to select an identical item (equals & hashCode is matching) the Grid uses the wrong item to select the items in an already rendered Grid. 

### Expected outcome

4. The grid selects the forth row and the forth row contains "Field 4" **instead of sending the wrong object to the client to render**.

### Minimal reproducible example

```java

    var grid = new Grid<MyBean>();
    grid.addColumn(MyBean::getField).setHeader("Field");
    grid.setItems(Arrays.asList(
      new MyBean("1", "Field 1"),
      new MyBean("2", "Field 2"),
      new MyBean("3", "Field 3")
    ));

    grid.select(new MyBean("3", null));

    add(grid);
    add(new Button("Click me", e -> {
      grid.setItems(Arrays.asList(
        new MyBean("1", "Field 1"),
        new MyBean("2", "Field 2"),
        new MyBean("3", "Field 3"),
        new MyBean("4", "Field 4")
      ));

      grid.select(new MyBean("4", null));
    }));


  private static class MyBean {

    private final String id;
    private final String field;

    private MyBean(String id, String field) {
      this.id = id;
      this.field = field;
    }

    public String getId() {
      return id;
    }

    public String getField() {
      return field;
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) {return true;}
      if (o == null || getClass() != o.getClass()) {return false;}
      MyBean myBean = (MyBean) o;
      return id.equals(myBean.id);
    }

    @Override
    public int hashCode() {
      return Objects.hash(id);
    }
  }

```

### Steps to reproduce

1. Open a View with the given Code
2. See that `Field 3` is selected
3. Click the Button
4. See that an empty row is created and selected

### Environment

Vaadin version(s): 23.3

### Browsers

Issue is not browser related

**Comment by ugur-vaadin** [comment]
As mentioned in the [PR](https://github.com/vaadin/flow-components/pull/4902#issue-1648217130), the refresh calls on both single and multi selection models will be removed. The client-side `selected` property will be updated for the server-side selection/deselection calls as well. This change should be considered as a possible cause if any regressions regarding selection is encountered.
