### ISSUE TITLE
[MultiSelectComboBox] provide "select / deselect all" functionality

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow-components#4876]
### Describe your motivation

Currently there is no easy way to select a bunch of items in the MSCB despite clicking them all at once. For small item sets, this might be suitable, but for any use case with 10+ items it starts to get tedious.

### Describe the solution you'd like

The MSCB should provide a functionality to select / deselect all items at once. 

This could be realized by showing two buttons at the top of the overlay ("All" / "None"). The buttons should be stylable parts and accessible for changing label and icon (not sure how easy that is doable atM in Lit, but for Java we would need such a feature definitely). 

When filtering the shown values by typing something in the MSCBs input field, the buttons should just (de-) select the filtered items. This way it would be possible to add a set of matching items to already selected items.

### Describe alternatives you've considered

* Providing writing access to the Overlay element (ideally as its own component) to allow adding / modifying its content. But this would feel a bit like DIY, which opposes the FSS principle. Therefore this could be an additional feature
* Adding a "select all" checkbox to the input field. But this would visually overload the mcb, especially when there are already the counter chips, some additional selected chips and maybe also a clear button. Plus it is separated visually from the items to be selected, so it might not be very intuitive to have that.

**Comment by stefanuebe** [comment]
Hacky workaround: 
```
comboBox.getElement().addEventListener("opened-changed", event -> {
        comboBox.getElement().executeJs("" +
                "let o = document.querySelector('vaadin-multi-select-combo-box-overlay');" +
                "if(o && o.children && o.children.length) {" +
                "   if(!o.__selectAllButton) {" +
                "       let button = document.createElement('vaadin-button');" +
                "       button.textContent = 'Select All';" +
                "       button.onclick = e => this.dispatchEvent(new CustomEvent('select-all'));" +
                "       let dbutton = document.createElement('vaadin-button');" +
                "       dbutton.textContent = 'Deselect All';" +
                "       dbutton.onclick = e => this.dispatchEvent(new CustomEvent('deselect-all'));" +
                "       o.__selectAllButton = true;    " +
                "       let hLayout = document.createElement('vaadin-horizontal-layout');" +
                "       hLayout.append(button, dbutton);" +
                "       o.children[0].prepend(hLayout);" +
                "   }" +
                "}");
});

comboBox.getElement().addEventListener("select-all", event -> {
    comboBox.select(comboBox.getGenericDataView().getItems().collect(Collectors.toSet()));
});
comboBox.getElement().addEventListener("deselect-all", event -> {
    comboBox.deselectAll();
});
```

**Comment by stefanuebe** [comment]
I'd not agree that the clear button or the linked issue fulfill the requirements as it also includes the possibility to (de-) select all filtered items only - a function, that we currently have in a custom written mcb and would need in future.

From experiences with users of our custom mcb I also learned, that the clear button of the input field is not necessarily or intuitivly seen as the "deselect all" button by every user, so for a better UX dedicated buttons inside the layout helped here.

I therefore ask to take this issue into consideration. :)

**Comment by rolfsmeds** [comment]
Ah, missed that aspect, sorry. Let's reopen then.

**Comment by jorgheymans** [comment]
Same here, client need for select/deselect all.

**Comment by mkopyczok** [comment]
Select and and deselect all is used very often in applications. It would be valuable feature.

**Comment by rolfsmeds** [comment]
Those who are interested, please add your :+1: to the issue (at the top, not in a comment).
Those upvotes are used to prioritize features.
