### ISSUE TITLE
Grid Pro - Edit column renderer issue

### ISSUE THREAD

**Issue by onuridrisoglu** [vaadin/flow-components#4907]
### Description

In Grid Pro, when moving the focus to a non editable cell, quite randomly, the edible component cannot be removed - which results displaying both non-edible and editable components in the cell. It doesn't happen all the but rather quite randomly.

![gridpro-issue_AdobeExpress](https://user-images.githubusercontent.com/33827141/229122256-b4e2f14f-0626-4fe0-bac5-282a103c7843.gif)

### Expected outcome

The select component should be removed, after cancelling edit.

### Minimal reproducible example

[Here](https://github.com/onuridrisoglu/grid-pro-issue) is a reproducible example.

### Steps to reproduce

- Click on the one of the cells in Mode column
- Select a value
- then click on the previous cell (R/O)

### Environment

Vaadin version(s): 14.9.5
Browser: Chrome Version 109.0.5414.119
OS: MacOS Version 12.6.2

**Note**: 
**I couldn't reproduce the issue in MacBook Pro (2021) with M1 processor, 
but able to produce it MacBook Pro 2017 Intel Core i5**

### Browsers

Chrome

**Comment by yuriy-fix** [comment]
The issue is added to the backlog priority queue for further investigation.
