### ISSUE TITLE
[number field] validation error message is always empty

### ISSUE THREAD

**Issue by KochTobi** [vaadin/flow-components#4923]
### Description

After entering an invalid number into a number field. The field is correctly invalidated but the error message is always empty. The tooltip contains the correct message.

```java
NumberField numberField = new NumberField();
numberField.setMin(1);
```
<img width="209" alt="Screenshot 2023-04-06 at 15 25 46" src="https://user-images.githubusercontent.com/11536497/230392182-fa825d35-0fb5-40d6-80b6-4f49b5e1a1f8.png">
<img width="209" alt="Screenshot 2023-04-06 at 15 26 06" src="https://user-images.githubusercontent.com/11536497/230392192-d2c50669-834c-4dae-8de1-03c6c0e4b09f.png">
Enter by hand:
<img width="209" alt="Screenshot 2023-04-06 at 15 26 13" src="https://user-images.githubusercontent.com/11536497/230392193-c3ebc937-b035-4be7-b1cc-cc3fc56bbb83.png">

The error message is an empty String.

### Expected outcome

The error message contains the reason for failing validation.

### Minimal reproducible example

```java
NumberField numberField = new NumberField();
numberField.setMin(1);
```

### Steps to reproduce

1. Enter a value smaller than 1
2. Empty error message

### Environment

Vaadin version(s): 23.3.6
OS: MacOs

### Browsers

Issue is not browser related

**Comment by knoobie** [comment]
Use the binder if you need to show error messages to the user.

**Comment by KochTobi** [comment]
Does that mean I need an extra bean only to validate a number input?

**Comment by sissbruecker** [comment]
As knoobie mentioned, components don't support error messages for constraints at the moment. Please track #4618 for updates.
