### ISSUE TITLE
PasswordField reveal password breaks PasswordField.getValue in Android chrome

### ISSUE THREAD

**Issue by tommilukkarinen** [vaadin/flow-components#4932]
### Description

1. Use Android Chrome
2. Write password in PasswordField 
3. Reveal
4. Hide
5. StringUtils.isEmpty(newPassword.getValue()) is true

### Expected outcome

getValue would return the actual text written to the field

### Minimal reproducible example

```
Java

PasswordField newPassword = new PasswordField();
Button continue = new Button("continue");
add(newPassword, continue);
continue.addClickListener(e -> {
 System.out.println(newPassword.getValue());
}
```

### Steps to reproduce

1. Add the snippet above to a view
2. Open view in Android Chrome (does not happen in Windows Chrome)
3. Write something to the password
4. Press reveal (shows text)
5. Press reveal (hides text)
6. Press continue button (prints nothing)

### Environment

Vaadin version(s):  23.3.7, 22.x

OS: Android

### Browsers

Chrome

**Comment by web-padawan** [comment]
> this can be reproduced also on Chrome on MacOS by using device emulation (e.g. Galaxy S20 Ultra).

Confirmed. I'll see if we should remove `touchend` listener and will also test this on iOS Simulator.

**Comment by web-padawan** [comment]
Did some testing using Simulator, and current UX looks as expected on iOS in terms of not scrolling the page on reveal button tap - see https://github.com/vaadin/vaadin-text-field/issues/193 where this problem was originally reported:

https://github.com/vaadin/flow-components/assets/10589913/5cb0bfd9-8e85-434a-a17d-e2695b5bace2

This is achieved by cancelling `focusout` event, which is exactly what preventing `touchend` listener does.
As a result, there is no server roundtrip on reveal button click, and the value is not updated on the server.

**Comment by web-padawan** [comment]
Code example that I used to reproduce the bug. Note, with the original steps there seems to be no value change event.

```java
import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.component.html.NativeButton;
import com.vaadin.flow.component.textfield.PasswordField;
import com.vaadin.flow.router.Route;

@Route("vaadin-text-field/password-field-value-test")
public class PasswordFieldValuePage extends Div {

    public PasswordFieldValuePage() {
        PasswordField newPassword = new PasswordField();
        NativeButton test = new NativeButton("test");
        newPassword.getElement().addEventListener("focusout", (event) -> {
            System.out.println("focusout");
        });
        test.addClickListener(e -> {
            System.out.println(String.format("Button clicked, value is '%s'",
                        newPassword.getValue()));
        });
        newPassword.addValueChangeListener((event) -> {
            System.out.println(String.format("Value changed from '%s' to '%s'",
                        event.getOldValue(), event.getValue()));
        });
        add(newPassword, test);
    }
}
```
