### ISSUE TITLE
Grid recalculateColumnWidths doesn't recalculate on first attempt

### ISSUE THREAD

**Issue by ppawlowski15** [vaadin/flow-components#4944]
### Description

Grid's recalculateColumnWidths does not resize the column when clicking a button that executes that code in its click listener. Rather, it resizes the column after a second click of that button. 

### Expected outcome

It should resize columns after the first click also.

### Minimal reproducible example

public class TestGrid extends Div {
    public TestGrid() {

        //GRID INIT
        Grid<TestGridRow> testGrid = new Grid<>(TestGridRow.class, false);
        testGrid.addColumns("a", "b", "c", "d", "e", "f");
        addButton(testGrid, "BUTTONS1");
        addButton(testGrid, "BUTTONS2");
        testGrid.getColumns().forEach(col -> col.setAutoWidth(true));
        add(testGrid);
        //-----------

        // BUTTON INIT
        Button button = new Button("Add Text");
        button.addClickListener(event -> {
            TestGridRow row = new TestGridRow("test", "This very long string is displayed correctly, even first time",
                    "test", "test", "test", "test");
            testGrid.setItems(List.of(row));

            //if testGrid.getDataProvider().refreshAll() does not matter
            //testGrid.getDataProvider().refreshAll();

            testGrid.recalculateColumnWidths();
        });
        add(button);
        //-------------

        setWidthFull();
    }

    private void addButton(Grid<TestGridRow> grid, String label) {
        grid.addComponentColumn(p -> new HorizontalLayout(new Button("b1"), new Button("b2"), new Button("b3"), new Button("b4")))
                .setKey(label)
                .setHeader(new Label(label));
    }
}

### Steps to reproduce

![vaadn](https://user-images.githubusercontent.com/26251056/232768834-7360ca59-c3be-4421-9cdc-28e6b2bfaf42.gif)

1. Click "Add text" button
2. First row is added into grid 
3. Columns BUTTONS1 and BUTTONS2 has four test buttons created but only half of them are visible
5. Second click "Add text" button will recalculate columns correctly
6. As u can see last two columns finally shows rest of buttons

### Environment

Vaadin version(s): 24.0.4 (vaadin-spring-boot-starter)
Java: OpenJDK 17.0.2
Maven: v.3.8.1
OS: Windows 10

### Browsers

Chrome, Firefox, Safari

**Comment by mrgreywater** [comment]
I have had similar issues with the grid, so here is my workaround:

```java
    private void recalculateColumnWidths() {
        grid.getElement().getNode().runWhenAttached(ui -> ui.beforeClientResponse(grid, ctx -> ctx.getUI().getPage().executeJs("requestAnimationFrame(() => { $0.recalculateColumnWidths(); });", grid.getElement())));
    }
```

**Comment by ppawlowski15** [comment]
> I have had similar issues with the grid, so here is my workaround:
> 
> ```java
>     private void recalculateColumnWidths() {
>         grid.getElement().getNode().runWhenAttached(ui -> ui.beforeClientResponse(grid, ctx -> ctx.getUI().getPage().executeJs("requestAnimationFrame(() => { $0.recalculateColumnWidths(); });", grid.getElement())));
>     }
> ```

Thanks, it works indeed, but I wish for native solution

**Comment by mrgreywater** [comment]
Here is another failing example with `Push(Pushmode.MANUAL)`: 

```java
package com.example.application.views.main;

import com.vaadin.flow.component.avatar.Avatar;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;

import java.util.ArrayList;

@PageTitle("Main")
@Route(value = "")
public class MainView extends HorizontalLayout {
    private static class Item {
        public String name;
        public boolean clicked;

        public Item(String s) {
            name = s;
        }
    }

    public MainView() {
        setSizeFull();

        var items = new ArrayList<Item>();

        for (int i = 0; i < 100; i++) {
            items.add(new Item("Item " + i));
        }

        var grid = new Grid<Item>();
        grid.setSizeFull();
        grid.addComponentColumn(item -> new Avatar(item.name)).setAutoWidth(true).setFlexGrow(0);
        grid.addColumn(item -> "column").setHeader("Second").setFlexGrow(1);

        grid.addAttachListener(event -> {
            event.getUI().access(() -> {
                event.getUI().push();
                grid.setItems(items);
                event.getUI().push();
            });
        });


        add(grid);
    }
}
```

**Comment by sissbruecker** [comment]
This is a regression in v24 when using component renderers. Regular columns resize immediately in the first round-trip.
