### ISSUE TITLE
Overflow menu items looses the class name on opening the context menu and then resizing to a point where overflow is not required

### ISSUE THREAD

**Issue by sujoykd** [vaadin/flow-components#4948]
### Description

Overflow menu items looses the class name on opening the context menu and then resizing to a point where overflow is not required.

### Expected outcome

I would expect the class names to stay irrespective of whether the overflow happened or not.

### Minimal reproducible example

```java
    private void menuTest() {
        final Div div = new Div();
        div.setText("Move the splitter to see overflow feature");
        
        final MenuBar responsiveMenu = new MenuBar();
        
        for (final var button : this.buttons()) {
            final MenuItem menuItem = responsiveMenu.addItem(button);
            menuItem.addThemeNames("my-custom-theme-name");
            menuItem.getElement().getStyle().set("font-weight", "bold");
            menuItem.getElement().getClassList().add("my-custom-class-name");
            
            menuItem.addClickListener(e -> {
                System.out.println(e.getSource().getText());
            });
            menuItem.setEnabled(true);
        }
        
        final SplitLayout splitLayout = new SplitLayout(responsiveMenu, div);
        this.add(splitLayout);
    }
    
    private List<Div> buttons() {
        return IntStream.rangeClosed(65, 75).mapToObj(num -> String.valueOf((char) num)).map(Text::new).map(Div::new).toList();
    }
```

### Steps to reproduce

1. Add the snippet above to a view
2. Check that the class names given to the menu items are applied to all the menu items
3. Drag the slider left to trigger responsive behaviour and check that the menu collapses showing the overflow option
4. Open the overflow menu.
5. Check that the class names given to the menu items are applied only to the menu items which didn't go into the overflow section.
6. Menu items that were hidden in overflow, looses the class names.

### Environment

Vaadin version(s): 23.3.11
OS: Windows 10/11

### Browsers

Issue is not browser related

**Comment by roastedcpu** [comment]
Moving to web-components repo
