### ISSUE TITLE
Grid selection working unexpectedly

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/flow-components#4967]
### Description

The select all -checkbox no longer toggles all items if you've done manual item selections. This seems to be a regression from #4902.

Current behavior:

https://user-images.githubusercontent.com/1222264/233565497-f52e1aee-382d-4898-818e-d4c01b20a7e4.mp4

Expected behavior:

https://user-images.githubusercontent.com/1222264/233565487-1c60a64e-8188-44ff-9ab4-a3e10e4b9771.mp4

### Expected outcome

See above

### Minimal reproducible example

Open the "in-memory grid" example in the IT pages

### Steps to reproduce

1. select all items
2. deselect some items
3. toggle "select all" checkbox

### Environment

Vaadin version(s): 24.1-SNAPSHOT

### Browsers

Issue is not browser related

**Comment by vursen** [comment]
Confirmed that the regression is indeed caused by https://github.com/vaadin/flow-components/pull/4902. Before that, deselection would deselect all items as expected.
