### ISSUE TITLE
Draggable dialog does not resize automatically after drag

### ISSUE THREAD

**Issue by cdir** [vaadin/flow-components#4985]
### Description

Create a simple Dialog with:
* dialog.setDraggable(true)
* A checkbox
* An invisible text field
* When the checkbox is activated, the text field gets visible.

The dialog resizes when according to the content. When the dialog was dragged the resize is broken

### Expected outcome

The dialog should resizes according to the content after the dialog was dragged.

### Minimal reproducible example

````java
        Button button = new Button("go");
        add(button);

        button.addClickListener($ -> {
            var layout = new VerticalLayout();
            var checkbox = new Checkbox();
            var textField = new TextField();
            textField.setVisible(false);
            layout.add(checkbox, textField);
            checkbox.addValueChangeListener(e -> textField.setVisible(e.getValue()));

            var dialog = new Dialog(layout);
            dialog.setDraggable(true);
            dialog.open();
        });
````

### Steps to reproduce

* Click the 'go' button.
* Check the checkbox to see that the dialog resizes properly
* Drag the dialog anywhere
* Check the checkbox to see that the dialog does not resizes properly

### Environment

Vaadin 23.3.10 and 24.0.4

**Comment by DiegoCardoso** [comment]
Thanks for the issue.

There's already an open ticket describing this same issue at https://github.com/vaadin/web-components/issues/436, so I am closing it as a duplicate.
