### ISSUE TITLE
Dialog with header parameter in constructor

### ISSUE THREAD

**Issue by mgarciavaadin** [vaadin/flow-components#4987]
### Describe your motivation

Dialog title/header cannot be specified in the constructor as it was in V8 for [Window](https://vaadin.com/api/framework/8.18.0/com/vaadin/ui/Window.html). This is a very common use case of Window component in V8 apps. In upgraded V8 apps Dialog is used as a replacement for Window so it would be great to have constructors Dialog(String) and Dialog(String, Component) that would use the String parameter as the HeaderTitle. This would make the upgrade easier and cleaner. 
Also for new developers It should be helpful as a Dialog is very likely to have always a title/header. 

### Describe the solution you'd like

Add two constructors to Dialog Component to mimic V8 Window constructors.

```java 
public Dialog(String header);
public Dialog(String header, Component... components);
```

The solution would use internally the setHeaderTitle(String) method in addition to current constructors. 

### Describe alternatives you've considered

The approach seems to be straightforward so no alternatives considered.

### Additional context

N/A

**Comment by rolfsmeds** [comment]
Let's call the parameter `title` for clarity (not a big fan of the `headerTitle` name of the property, but we couldn't use `title` as it would clash with the native attribute of the same name)
