### ISSUE TITLE
Change TextField constructor (String label, String placeholder) to (String label, String value)

### ISSUE THREAD

**Issue by knoobie** [vaadin/flow-components#4991]
### Describe your motivation

Migrating applications from V8 to V23+, I just had the delighting experience that the constructor changed from:

https://github.com/vaadin/framework/blob/96fdbf131a188f14d95055c05746185bf8c60f01/server/src/main/java/com/vaadin/ui/TextField.java#L62

to 

https://github.com/vaadin/flow-components/blob/34845448ea809df621fd2446b889056ee89bd057/vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextField.java#L103

which cost me some time to idenfity, because placeholder look kinda similar to real values... 

This is especially annoying, because the other constructor (String label, String initialValue, ValueChangeListener..) has also the value.. just THIS one constructor uses the placeholder.

### Describe the solution you'd like

Change the constructor / breaking change.

**Comment by knoobie** [comment]
Ping @mgarciavaadin because of the modernization PRs.

**Comment by mrgreywater** [comment]
Please do NOT change it back. Otherwise the confusion will be perfect. Everyone who already uses the v14-v24 syntax will then have the same issue you were facing, just in reverse.

**Comment by yuriy-fix** [comment]
Unfortunately, that is the caveat in migration that cannot be easily addressed. This is the desired behaviour for the latest version.
