### ISSUE TITLE
Dialog server side modality can block opened-changed of previously closed Dialog

### ISSUE THREAD

**Issue by probert94** [vaadin/flow-components#4997]
### Description

Consider having a `Dialog` with a `TextField`. The Dialog should close on outside click.
Now a `ValueChangeListener` that opens a new modal `Dialog` (for example a validation message) is added to the `TextField`.
If you now enter a value into the TextField and click outside the Dialog, a `ValueChangeEvent` is triggered (cause of the focus loss) at (almost) the same time as the dialog is closed cause of the outside click.
As the `ValueChangeEvent` occur a little earlier and causes a new modal to open, the `OpenedChangeEvent` is ignored (inert).
This causes the `Dialog` to stay "open" on the server side and if it is modal itself, this causes the whole `UI` to freeze, as all nodes are marked as inert.

The same issue has been reported several times (#4026, #4743) but those issues are closed as solved.
Unfortunately the fix does not seem to solve the issue (Tested with Vaadin 24.0.5 which should include the fix).

### Expected outcome

The `Dialog` should be closed on the server, not only on the client.

### Minimal reproducible example

```java
@PageTitle("Main")
@Route(value = "")
public class MainView extends HorizontalLayout {
    public MainView() {
    Button btnOpenDlg = new Button("Open", e -> openDlg1());
    add(btnOpenDlg);
  }
  private static void openDlg1() {
    Dialog dlg = new Dialog();
    dlg.setModal(true);
    dlg.setCloseOnOutsideClick(true);
    HorizontalLayout toolBar = new HorizontalLayout();
    Span title = new Span("Title");
    toolBar.addAndExpand(title);
    dlg.add(toolBar);
    VerticalLayout content = new VerticalLayout();
    TextField tfValue = new TextField("Value");
    tfValue.addValueChangeListener(e -> openDlg2(e.getValue()));
    content.add(tfValue);
    dlg.add(toolBar);
    dlg.add(content);
    dlg.addOpenedChangeListener(e -> System.out.println(e.isOpened() ? "Opened" : "Closed"));
    dlg.open();
  }
  private static void openDlg2(String value) {
    try {
      Thread.sleep(100);
    }
    catch (InterruptedException e) {
      throw new RuntimeException(e);
    }
    Dialog dlg = new Dialog();
    dlg.setModal(true);
    Div content = new Div();
    content.setText(value);
    dlg.add(content);
    dlg.open();
  }
}
```

Sidenote:
The `Thread.sleep` is necessary as otherwise the `Dialog` won't even be closed on the client.
I tried to find the cause of this and it seems like the `ValueChangeEvent` prevents the `click` event (on the client!), only if the server answers to it fast enough.
Even a click listener I registered using the developer tools (`document.body.addEventListener('click', e => console.warn(e))`) didn't trigger without the `Thread.sleep` on the server.
I created another issue for that (#5006 )

### Steps to reproduce

1. Download a new Vaadin starter (24.0.5)
2. Copy the code above into MainView.java
3. Start the application and open the `Dialog`
4. Insert some text into the `TextField` and click outside the `Dialog` **without** submiting the value first (don't press Enter)
5. The `Dialog` should close and a new `Dialog` which shows the entered value appears
6. Close the second `Dialog` and try to press the "open" `Button` again -> nothing happens as the `Button` is now inert.

### Environment

Vaadin version(s): 24.0.5

### Browsers

Issue is not browser related

**Comment by yuriy-fix** [comment]
The issue is added to the backlog priority queue for further investigation.
