### ISSUE TITLE
DialogElement.isOpen() throws org.openqa.selenium.NoSuchElementException instead of returning false

### ISSUE THREAD

**Issue by enver-haase** [vaadin/flow-components#500]
```
        // Ensure the comment window is closed and the log row was not added
        //assertFalse(commentWindow.isOpen());
        Assert.assertThrows(org.openqa.selenium.NoSuchElementException.class, commentWindow::isOpen);
```

The first assert should work, but it does not.

The code in question is here:
https://github.com/enver-haase/exampleapp/blob/main/src/test/java/org/vaadin/app/CalcViewIT.java
and copied from the usual 'testbench-demo' repo.

**Comment by enver-haase** [comment]
Vaadin 14.4.4

**Comment by brunovianarezende** [comment]
I tested latest testbench-demo https://github.com/vaadin/testbench-demo and it just works. I think this ticket can be closed.

**Comment by vursen** [comment]
Also confirmed that there is not any exceptions in the latest testbench-demo.
