### ISSUE TITLE
addColumn with ValueProvider and Renderer

### ISSUE THREAD

**Issue by mgarciavaadin** [vaadin/flow-components#5004]
### Describe your motivation

In Grid API we have:

- addColumn(Renderer<T> renderer)
- addColumn(ValueProvider<T,?> valueProvider)

but not the combination of them as it was in V8 [addColumn(ValueProvider<T,V> valueProvider, AbstractRenderer<? super T,? super V> renderer)](https://vaadin.com/api/framework/8.18.0/com/vaadin/ui/Grid.html#addColumn-com.vaadin.data.ValueProvider-com.vaadin.ui.renderers.AbstractRenderer-)

### Describe the solution you'd like

Add this new method 

```java
addColumn(ValueProvider<T,?> valueProvider, Renderer<T> renderer)
```

### Describe alternatives you've considered

N/A

### Additional context

Maybe this new method could use the new setRenderer method from [feat: add method to set column renderer #4975](https://github.com/vaadin/flow-components/pull/4975)

**Comment by mgarciavaadin** [comment]
Now we have setRenderer(Renderer) available [PR #4975](https://github.com/vaadin/flow-components/pull/4975) the approach should be something like 
```java 
public Column addColumn(ValueProvider vp, Renderer r) {
         Column c = addColumn(vp) // Existing API method
         c.setRenderer(r) // new available method
}
```
@sissbruecker do you think this approach would be ok? I think it does not have the issue that we discuss for the solution of setRenderer(ValueProvider, Renderer) [here](https://github.com/vaadin/flow-components/pull/4975#pullrequestreview-1409505481). 

/cc @sosa-vaadin

**Comment by sissbruecker** [comment]
I don't think those are equivalent. In V8 we have:
```
public <V> Grid.Column<T,V> addColumn(ValueProvider<T,V> valueProvider,
                                      AbstractRenderer<? super T,? super V> renderer)
```
From what I understand that does:
- Set a value provider that can convert from the grid bean type `T` to the column type `V`
- Set a renderer that can render the column type `V`

The code you suggested for the Flow is not equivalent:
- `addColumn(vp)` creates a text renderer that renders the output of the value provider
- `setRenderer(r)` sets a custom renderer that renders the grid's bean type

So setting the value provider doesn't do anything useful here. 

What you want is to specify a value provider that can convert from the grid bean type to a custom type, and then a renderer that can render the custom type.

**Comment by sosa-vaadin** [comment]
I would argue it does the same as in V8 @sissbruecker 

In [this part](https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/ui/Grid.java#L2952-L2955) we can see the method we're trying to bring to Flow.

```java
public <V> Column<T, V> addColumn(ValueProvider<T, V> valueProvider,
        AbstractRenderer<? super T, ? super V> renderer) {
    return addColumn(valueProvider, ValueProvider.identity(), renderer);
}
```
It just delegates the call to another method, passing an identity value provider as the presentation provider. Look at the signature of [that method](https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/ui/Grid.java#L3009-L3011):
```java
public <V, P> Column<T, V> addColumn(ValueProvider<T, V> valueProvider,
            ValueProvider<V, P> presentationProvider,
            AbstractRenderer<? super T, ? super P> renderer)
```

If our value provider was being used as the presentation provider, I would agree with you; but it doesn't.

**Comment by sissbruecker** [comment]
That just means that there is no presentation provider. It does not explain that the V8 version converts from a bean type `T` to a column value type `V`, and the renderer then takes a value of type `V`, while the suggested Flow version doesn't.

**Comment by sissbruecker** [comment]
I think it would be helpful to have some actual code examples from V8 where this is used, and then see how this can be adapted to Flow. 

To me it looks like V8 had a concept where you could define general purpose renderers that worked with a specific type, and value providers allowed you to convert from the grid's bean type to the type that the renderer works with. In Flow we don't have that. A renderer always takes the grid's bean type, which can be inconvenient if you want to reuse renderers across grids with different bean types. Furthermore, the Flow grid doesn't have a concept of a column value type at all, while the V8 Grid seems to make a distinction between the grid's bean type and the column's value type.

**Comment by mgarciavaadin** [comment]
It seems the approach is completely different in V8 and Flow so in terms of modernization is probably not the solution to add this method to Flow's API as V8's is intended to do different things. Maybe in the future it would be interesting to discuss if the Column type should be available for the user as it was in V8 because it looks like a lack of funcionality/flexibility. So we are closing the issue for now, thanks for the discussion and support!
