### ISSUE TITLE
Vaadin Board layout changes under specific conditions when used in a Dialog

### ISSUE THREAD

**Issue by RhonanMS** [vaadin/flow-components#5005]
### Description

We found a bug where the layout of a Board changes under specific conditions when used in a Dialog.

At the moment, we were able to reduce the the issue to the following conditions:
1. Dialog contains both 
2. at least one Board and
3. at least one Grid (the Grid needs to be wrapped in a VerticalLayout)
4. which are only visible at different times (e.g. when switched with a Tabs component)

When switching visibility of the Board and the Grid, the initial layout of the Grid is disturbed and every item is presented in one row - see below.

In the DOM tree, one can see that the <vaadin-board-row> CSS class changes from "large" to "small" when the view changes to the Grid, and stays this way after the Board is once again displayed.

# Visualization
## Initial state - Board columns presented correctly
<img width="984" alt="board-bug-initial" src="https://user-images.githubusercontent.com/15796648/235099444-4b307692-0ae6-4d7e-a5c1-3c378c709b24.png">

## Initial state - DOM tree
<img width="323" alt="board-bug-dom-initial" src="https://user-images.githubusercontent.com/15796648/235100542-ae7cfa5c-6db3-4520-b8fb-a8f2cc92dba7.png">

## Second state - Switched to Grid
<img width="986" alt="board-bug-grid" src="https://user-images.githubusercontent.com/15796648/235099472-b02c6dab-f7cc-49f2-af25-51cd62e1e14e.png">

## Second state - DOM tree
<img width="341" alt="board-bug-dom-grid" src="https://user-images.githubusercontent.com/15796648/235100687-da54d0af-cdc7-4981-bf30-a5859541892e.png">

## Third state - Return to Board - all columns presents in their own row
<img width="998" alt="board-bug-grid-afterwards" src="https://user-images.githubusercontent.com/15796648/235099500-73c15dc7-cf33-4d59-b914-2ff345e2fd55.png">

## Third state - DOM tree
<img width="344" alt="board-bug-dom-afterwards" src="https://user-images.githubusercontent.com/15796648/235100735-47953eb9-d775-4246-8419-b94d4ad11592.png">

### Expected outcome

I would expect the Board to present the same column layout before and after switching to the Grid view.

### Minimal reproducible example

The attached project contains a reproducible example:
[board-example.zip](https://github.com/vaadin/flow-components/files/11351747/board-example.zip)

### Steps to reproduce

1. Open http://localhost:8282/
2. Click "Open Dialog" button to open the dialog
3. The "Board Tab" is displayed correctly.
4. Switch to the "Table Tab" to display the Grid
5. Return to the "Board Tab" - the columns are one per row.

### Environment

Vaadin version(s): 14.9.8, also tested with 14.10.0.alpha1
OS: Windows
The issue was tested with Edge, Firefox and Chrome and appeared in all of those browsers.

### Browsers

Chrome, Firefox, Edge

**Comment by sissbruecker** [comment]
A workaround is to call `redraw` after making the board visible again:
```java
board.setVisible(true);
board.redraw();
```

**Comment by ugur-vaadin** [comment]
I started investigating the issue and will work on the fix.

**Comment by ugur-vaadin** [comment]
The issue was fixed by the relevant [PR](https://github.com/vaadin/vaadin-board/pull/159) and will be available with the next release.
