### ISSUE TITLE
Clicking Components in summary area of a Details component closes the details

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/flow-components#5026]
### Description

Adding a Button with a click listener inside the Summary area of the details works in an unexpected way: clicking the Button also toggles the Details' open/closed state. While sometimes this may be what's desired, generally it seems like broken behavior.

### Expected outcome

By default, clicking anything inside the Summary area shouldn't toggle the expanded status of the Details. If needed, a click listener can do that manually.

### Minimal reproducible example

Example:
```
        Button button = new Button("See more information", e -> {
            Notification.show("More information");
        });
        HorizontalLayout summary = new HorizontalLayout(new Span("Summary"), button);
        VerticalLayout content = new VerticalLayout(new Span("Content"));
        details = new Details(summary, content);
```

### Steps to reproduce

1. add the snippet to a view
2. click the button

### Environment

Vaadin version(s): 24.0
OS: n/a

**Comment by knoobie** [comment]
Sounds similar to https://github.com/vaadin/web-components/issues/5116

**Comment by OlliTietavainenVaadin** [comment]
Agreed. Closing this one.
