### ISSUE TITLE
Expanded TreeGrid with small page size does not display the correct items

### ISSUE THREAD

**Issue by ugur-vaadin** [vaadin/flow-components#5045]
### Description

I used a TreeGrid with page size 2 and expanded the items recursively. Expanding and scrolling causes unexpected behaviour which can only be corrected after scrolling far down and back up to clear the cache.

https://github.com/vaadin/flow-components/assets/106508695/959c0862-2832-45af-b730-bb0dda7fdc12

`TreeGridScrollToPage` can be used to reproduce the issues. Setting page size small like 2 will produce such results. Using different numbers of items and different combinations of expanding/scrolling will result in various unexpected behaviours. It is likely that the root cause is the same.

### Expected outcome

I would expect the grid to be expanded/scrolled correctly regardless of the page size.

### Minimal reproducible example

```java
@Route("vaadin-grid/treegrid-regression")
public class TreeGridRegressionPage extends Div {

    public TreeGridRegressionPage() {
        TreeGrid<String> grid = new TreeGrid<>();
        grid.setPageSize(2);
        grid.addHierarchyColumn(String::toString).setHeader("Item");

        TreeData<String> data = new TreeGridStringDataBuilder()
                .addLevel("Granddad", 50).addLevel("Dad", 20)
                .addLevel("Son", 20).build();
        grid.setDataProvider(new TreeDataProvider<>(data));

        add(grid);
    }
}
```

### Steps to reproduce

1. Add the above page to `vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests`
2. Open it in the browser
3. Expand `Granddad 0`
4. Try to scroll back and forth
5. See that the grid displays incorrect items and some rows even appear blank.

### Environment

Vaadin version(s): 24.1
OS: MacOS

### Browsers

Issue is not browser related

**Comment by yuriy-fix** [comment]
Let's investigate if it is a regression and what is the biggest page size to reproduce the issue (if it relates to the viewport size)

**Comment by DiegoCardoso** [comment]
The [changes introduced here](https://github.com/vaadin/flow-components/pull/4894) seem to be responsible for this regression. Adding back the code removed by this change "fixes" the issue.

```js
if (!grid.loading) {
  grid.__confirmParentUpdateDebouncer = Debouncer.debounce(
    grid.__confirmParentUpdateDebouncer,
    microTask,
    () => grid.__updateVisibleRows()
  );
}
```

**Comment by tomivirkki** [comment]
> The https://github.com/vaadin/flow-components/pull/4894 seem to be responsible for this regression. Adding back the code removed by this change "fixes" the issue.

The performance improvement of the linked PR was marginal so reverting it shouldn't be a problem.
