### ISSUE TITLE
Opening or closing an overlay re-renders other overlays

### ISSUE THREAD

**Issue by mperktold** [vaadin/flow-components#5069]
### Description

I have a Vaadin dialog that shows an HTML mail editor from a third party vendor (Unlayer) in an iframe.
When I open another dialog (or any other overlay), the iframe tries to reload (and fails to do so, but that is another issue).

See [this issue comment](https://github.com/vaadin/flow-components/issues/4896#issuecomment-1488669369) on issue #4896 for a similar behavior with a rich text editor.

[Another comment](https://github.com/vaadin/flow-components/issues/4896#issuecomment-1536253221) on the same issue presents a workaround, which essentially prevents `requestContentUpdate()` from being called.

We are currently using this workaround, but we're not sure if it has any undesired consequences, as it works by overriding `Dialog::isModal` to return false. In any case, I think this should be handled inside Vaadin so I can eventually remove the workaround.

### Expected outcome

Opening or closing another overlay should leave the other overlays untouched.

### Minimal reproducible example

I created a reproducer here: https://github.com/mperktold/vaadin-25-unlayer-issue-reproducer (I got the name wrong, it's really about Vaadin 24).

### Steps to reproduce

1. Start the reproducer application
2. Open browser at http://localhost:8080
3. Click the "Open alert" button

### Environment

Vaadin version(s): 24.0.5
OS: All

**Comment by web-padawan** [comment]
The issue described in the above comment was fixed by #5635.
