### ISSUE TITLE
Collapsible SideNav without a label is broken

### ISSUE THREAD

**Issue by HerbertsVaadin** [vaadin/flow-components#5090]
### Description

When setting `sideNav.setCollapsible(true);` on SideNav which doesn't have a label, it produces unexpected results. The collapse icon is present, but does not do anything when clicked.
Even though the docummentation for `setCollapsible(..)` mentions that label must be set for it to be collapsible, it doesn't make sense that the icon is there, but it doesn't work. 
![image](https://github.com/vaadin/flow-components/assets/80950643/f5d77da1-0f50-4570-a36d-400650992b0c)

### Expected outcome

Collapse icon collapses the SideNav.

### Minimal reproducible example

```
SideNav nav = new SideNav();
nav.setCollapsible(true);
nav.addItem(new SideNavItem("About", AboutView.class, LineAwesomeIcon.FILE.create()));
```

### Steps to reproduce

1. Add the snippet to your code
2. Click the collapse icon
3. Notice that nothing happens

### Environment

Vaadin version(s): 24.1.beta2
OS: Windows 11

### Browsers

Chrome, Firefox

**Comment by yuriy-fix** [comment]
Closing in favour of https://github.com/vaadin/web-components/issues/5810
