### ISSUE TITLE
Simple SideNavItem without children gets "expanded" attribute

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow-components#5092]
### Description

I have a hierarchical side nav structure with categories and normal items. Every of these items can get the "expanded" attribute, which makes sense for the expandable categories, but not for items without any child.

This can break stylings, that build upon the expanded attribute (e.g. to specially mark expanded categories). In the following screenshot, every item with [expanded] has a gray left border, while the "unexpanded" have a black border. As you can see, the active page also has a gray border. 

![image](https://github.com/vaadin/flow-components/assets/36725474/083ee285-17c3-4197-8f5f-4c6e7e51659d)

Clicking on all items, will change their appearance.

![image](https://github.com/vaadin/flow-components/assets/36725474/2e04e376-ec39-47af-946e-0bdeab6c30de)

### Expected outcome

The expanded Attribute should only be set for expandable nodes, not leaves.

### Minimal reproducible example

```java
        SideNav nav = new SideNav();

        SideNavItem cat1 = new SideNavItem("Category 1");
        nav.addItem(cat1);

        SideNavItem cat1_1 = new SideNavItem("Category 1.1");
        SideNavItem cat1_2 = new SideNavItem("Category 1.2");
        cat1.addItem(cat1_1, cat1_2);

        cat1_1.addItem(new SideNavItem("Page 1", DefaultView1.class));
        cat1_1.addItem(new SideNavItem("Page 2", DefaultView2.class));
        cat1_2.addItem(new SideNavItem("Page 3", DefaultView3.class));
        cat1_2.addItem(new SideNavItem("Page 4", DefaultView4.class));
```

### Steps to reproduce

Use the starter, replace the main layout side nav with the given sample (replace the views). Open the app, click on the leaves and check the DOM.

### Environment

Vaadin version(s): 24.1.0.beta2
OS:  Windows 10

### Browsers

Chrome

**Comment by stefanuebe** [comment]
The css I used for the screenshots. 
```css
vaadin-side-nav-item {
    border-left: 1px solid black;
    margin-left: 10px;
    padding-left: 10px;
}

vaadin-side-nav-item[expanded] {
    border-left: 1px solid lightgray;
}
```

**Comment by stefanuebe** [comment]
Workaround - setup a client side expanded-changed listener from the Java side, that will reset the expanded flag to false. Please note, that there is a requestionAnimationFrame. This is necessary to prevent any lit update issues, since we will change the property during the update phase of lit.

```java
SideNavItem navItem = new SideNavItem(label, view);
navItem.getElement().executeJs("this.addEventListener('expanded-changed', e => requestAnimationFrame(() => e.target.expanded = false));");

return navItem;
```

**Comment by web-padawan** [comment]
Confirmed that the problem still occurs with Vaadin 24.2.0.alpha1. I'll put together a web component only reproduction.
