### ISSUE TITLE
Undesirable behavior of RichTextEditor.

### ISSUE THREAD

**Issue by kostasnrs** [vaadin/flow-components#5098]
### Description

Greetings.

 I have added a RichTextEditor component in a verticalLayout. Binding and  everything works fine. It serves as an e-mail editor so as you can imagine its height might increase, even beyond the page. I believed that setting its height to "100%" it would automatically adjust the height in the remaining available space (with a vertical scrollbar maybe). Instead, if the text is too big, it pushes the richTextEditor bottom limit far beyond the page. I have tried using a Scroller component, but again a height must be set. This is very inconvenient because when the window is resized, or users have different screens, the component messes things up.

Any thoughts or solutions please? 

### Expected outcome

I believed that setting its height to "100%" it would automatically adjust the height in the remaining available space (with a vertical scrollbar maybe).

### Minimal reproducible example

message = new RichTextEditor();
        message.setValueChangeMode(ValueChangeMode.ON_BLUR);
        message.setSizeFull();
        Scroller scrollerMessage = new Scroller(message);
        scrollerMessage.setHeight("100&");
        FormLayout messageFL = new FormLayout();
        messageFL.addFormItem(scrollerMessage, EnglishStatics.CAPTION_MESSAGE);
        messageFL.setHeightFull();
        messageFL.getStyle().set("padding", "10px");
        messageFL.setResponsiveSteps(new FormLayout.ResponsiveStep("0", 1));
        
         VerticalLayout fieldBoard = new VerticalLayout();
        fieldBoard.setPadding(false);
        fieldBoard.add(formLayout);
        fieldBoard.add(new HorizontalLayout(formLayoutAlpha, formLayoutBravo));
        fieldBoard.add(messageFL);
        fieldBoard.add(commentFL);
        fieldBoard.setSizeFull();

### Steps to reproduce

Just add the above code of the Minimal reproducible example to a view.

### Environment

Vaadin version(s): vaadin-23
OS: windows 10

### Browsers

Chrome, Edge

**Comment by sissbruecker** [comment]
Closing as stale
