### ISSUE TITLE
Dialog opened from a Dialog fires OpenedChangeEvent multiple times

### ISSUE THREAD

**Issue by glebfox** [vaadin/flow-components#5103]
### Description

When a dialog is opened from another dialog, it fires `OpenedChangeEvent` multiple times.

### Expected outcome

`OpenedChangeEvent` is fired once even if a dialog is opened from another dialog.

### Minimal reproducible example

```java
import com.example.application.views.MainLayout;
import com.vaadin.flow.component.ClickEvent;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.dialog.Dialog;
import com.vaadin.flow.component.html.Label;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.router.RouteAlias;

@PageTitle("Sandbox")
@Route(value = "sandbox", layout = MainLayout.class)
@RouteAlias(value = "", layout = MainLayout.class)
public class SandboxView extends HorizontalLayout {

    public SandboxView() {
        setMargin(true);

        Button openDialogBtn = new Button("Open a dialog", this::openDialog);

        add(openDialogBtn);
    }

    private void openDialog(ClickEvent<Button> __) {
        Dialog dialog = new Dialog();

        VerticalLayout layout = new VerticalLayout();
        dialog.add(layout);

        Button openDialogBtn = new Button("Open a dialog", this::openDialog);
        layout.add(openDialogBtn);

        dialog.addOpenedChangeListener(openedChangeEvent -> {
            if (openedChangeEvent.isOpened()) {
                layout.add(new Label("OpenedChangeEvent"));
            }
        });

        dialog.open();
    }
}
```

### Steps to reproduce

1. Create a view using snippet above
2. Click **Open a dialog** - `OpenedChangeEvent` is fired once
<img width="295" alt="Screenshot 2023-05-30 at 18 15 31" src="https://github.com/vaadin/flow-components/assets/6077149/d55f5cc8-5507-4ee4-b1bc-b33c1bc643bf">

3. Click **Open a dialog** in a dialog - `OpenedChangeEvent` is fired multiple times
<img width="296" alt="Screenshot 2023-05-30 at 18 15 35" src="https://github.com/vaadin/flow-components/assets/6077149/4c517472-11eb-4fcd-a085-c5bd9b855d24">

### Environment

**Vaadin version(s):** 24.0.5
**OS:** MacOS 13.1, Windows 10
**Browser:** Chrome Version 113.0.5672.126 (Official Build) (x86_64), Safari Version 16.2 (18614.3.7.1.5), FireFox 113.0.2 (64-bit)

### Browsers

Chrome, Firefox, Safari

**Comment by sissbruecker** [comment]
This is might be due to the second dialog being added as a child of the first dialog, and then being moved into the overlay of the first dialog, which causes it to briefly disconnect and then reconnect to the DOM. Dialogs close when being disconnected from the DOM, and reopen when being reconnected. All of those would trigger respective events: first opened from being added to the dialog, then closed from being removed from the dialog, then opened again from being added to the overlay.
