### ISSUE TITLE
Avatar tooltip not displayed on hover

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/flow-components#5105]
### Description

After the page is loaded, hovering the Avatar does not display tooltip. (The tooltip is only visible if the mouse cursor is above the Avatar _when_ the component is first rendered, but after that the tooltip is not displayed again.)
![avatar](https://github.com/vaadin/flow-components/assets/11554739/fc2e5f93-20f4-4f03-94e2-b157e81236da)

### Expected outcome

I would expect that the tooltip is displayed, because the Avatar is configured with `setTooltipEnabled(true)`.

### Minimal reproducible example

```
Avatar avatar = new Avatar();
avatar.setAbbreviation("A");
avatar.setName("name");
avatar.setTooltipEnabled(true);
add(avatar);
```

### Steps to reproduce

1. Add the snippet above to a view
2. Hover on the tooltip
3. Notice how the tooltip is not displayed

### Environment

Vaadin version(s): 23.3.12

**Comment by sissbruecker** [comment]
Started looking into this. The tooltip overlay only shows if the target element (avatar in this case) is considered fully visible. For avatar that can be problematic, as avatar uses a negative margin to compensate for a possible outline. So if the avatar is positioned at the edge of its scroll container it is not considered fully visible and the tooltip doesn't show.

Workarounds should be to either add a margin to the container, or remove the negative margin from the avatar.
