### ISSUE TITLE
[MenuBar] Overflow calculation seems to be broken in 24

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow-components#5115]
### Description

With Vaadin 24 it seems, that the menu bar overflow calculation is broken. Items, that have enough space, to be displayed directly, are instead moved into the overflow dropdown. The issue could be reproduced with Vertical/HorizontalLayout and Div and occurs very "intense" inside a Dialog.

Might be related to https://github.com/vaadin/flow-components/issues/1995. Fixes shown in https://cookbook.vaadin.com/overflowing-menubar are not working.

Initial dialog, complete menu is inside the overflow button.
![image](https://github.com/vaadin/flow-components/assets/36725474/0c86ade9-e1d3-45ec-b855-de57bba8f27f)

After resizing it a bit to the right.
![image](https://github.com/vaadin/flow-components/assets/36725474/a8f1810d-bc08-4054-a86b-d26608eea9f8)

And a bit more
![image](https://github.com/vaadin/flow-components/assets/36725474/9bed112c-88ed-4a2e-9f8e-14c008cb4a2e)

### Expected outcome

Overflow calculation should work :) 

### Minimal reproducible example

```java
Dialog dialog = new Dialog();

MenuBar menuBar = new MenuBar();
menuBar.addItem("Hello");
menuBar.addItem("World");
menuBar.addItem("it's");
menuBar.addItem("me,");
menuBar.addItem("your");
menuBar.addItem("best");
menuBar.addItem("friend");
menuBar.addItem("Vaadin");
menuBar.addItem("from");
menuBar.addItem("Finland");

dialog.setWidth("500px");
dialog.setHeight("300px");

dialog.setResizable(true);
dialog.setDraggable(true);

HorizontalLayout layout = new HorizontalLayout();
layout.setWidthFull();
layout.addAndExpand(menuBar);

//        menuBar.setMinWidth("var(--lumo-size-m)");

dialog.add(layout);
dialog.open();
```

Using a div instead
```java
Div layout = new Div();
layout.setWidthFull();
layout.add(menuBar);
menuBar.setWidthFull();
menuBar.setMinWidth("var(--lumo-size-m)");
```

Using a VerticalLayout instead
```java
VerticalLayout layout = new VerticalLayout();
layout.setDefaultHorizontalComponentAlignment(Alignment.STRETCH);
layout.setWidthFull();
layout.add(menuBar);
menuBar.setMinWidth("var(--lumo-size-m)");
```

### Steps to reproduce

Add the given code to your view. Resize the dialog and see the overflow magic happen.

### Environment

Vaadin version(s): 24.0.5
OS: Windows 10

### Browsers

Chrome

**Comment by stefanuebe** [comment]
After playing around a bit, it seems to be related to how far away the container is from the browser window's left border. 

Taking this sample here
```java
Dialog dialog = new Dialog();

MenuBar menuBar = new MenuBar();
menuBar.setWidthFull();
for (int i = 0; i < 25; i++) {
    menuBar.addItem("Item "+i);
}

dialog.setWidth("500px");
dialog.setHeight("300px");

dialog.setResizable(true);
dialog.setDraggable(true);

VerticalLayout layout = new VerticalLayout();
layout.setDefaultHorizontalComponentAlignment(Alignment.STRETCH);
layout.setWidthFull();
layout.add(menuBar);
menuBar.setMinWidth("var(--lumo-size-m)");

dialog.add(layout);
dialog.open();
```

When moving the dialog to the left, so that it's left border touches the left window border, then the overflow calculation works nearly as expected (resizethe dialog a few times). Now move the dialog, so that it touches the right window side and resize it again. It is obviously, that the white space left in the menu bar seems to be more or less similar to the space between the left window border and the left dialog border.

**Comment by stefanuebe** [comment]
Left side
![image](https://github.com/vaadin/flow-components/assets/36725474/f33351cc-ef8b-4011-9cf0-42fa37c7cab6)


Right side
![image](https://github.com/vaadin/flow-components/assets/36725474/5a03b31c-1145-4086-a0c1-3e09416b2d4b)

**Comment by stefanuebe** [comment]
Setting "position: relative" to the menu bar container seems to fix it.

```java
VerticalLayout layout = new VerticalLayout();
layout.setDefaultHorizontalComponentAlignment(Alignment.STRETCH);
layout.setWidthFull();
layout.getStyle().set("position", "relative");
layout.add(menuBar);
menuBar.setMinWidth("var(--lumo-size-m)");
```

**Comment by sissbruecker** [comment]
Might have been fixed by https://github.com/vaadin/web-components/pull/5849

The fix has not been released yet.

**Comment by sissbruecker** [comment]
Not reproducable anymore with Vaadin 24.0.7, should have been fixed with the issue mentioned above.
