### ISSUE TITLE
TreeGridPro missing

### ISSUE THREAD

**Issue by enver-haase** [vaadin/flow-components#5124]
### Describe your motivation

My customer would like TreeGridPro Java API.

### Describe the solution you'd like

Editor API just like GridPro for TreeGrid.

### Describe alternatives you've considered

DIY... but customer thinks it should be our code for completeness.

### Additional context

Contact me for customer name.

**Comment by tomivirkki** [comment]
Same as https://github.com/vaadin/flow-components/issues/1537

**Comment by yuriy-fix** [comment]
Closing as a duplicate of https://github.com/vaadin/flow-components/issues/1537
