### ISSUE TITLE
Binder validation is triggered when suffix component opens a non-modal Dialog

### ISSUE THREAD

**Issue by knoobie** [vaadin/flow-components#5136]
### Description

If I open a `non-modal`dialog from a `suffix`component of a field, the field's validation are triggered and the field is marked as invalid.

### Expected outcome

Field is not marked as invalid.

### Minimal reproducible example

```java

    var field = new TextField("Field");
    field.setSuffixComponent(new Button("Show", e -> {
      var dialog = new Dialog();
      dialog.setHeaderTitle("Show Recommendation for the field");
      dialog.setModal(false);
      dialog.open();
    }));
   add(field);

    var binder = new Binder<Bean>();
    binder.forField(field).asRequired("Field is not allowed to be empty")
      .bind(Bean::getField, Bean::setField);
    binder.setBean(new Bean());
        
  @Data
  private class Bean {
    private String field;
  }

```

### Steps to reproduce

1. Execute code
2. Click "Show"
3. See field marked as invalid

### Environment

Vaadin version(s): 24
OS: MacOS 

### Browsers

Firefox

**Comment by TatuLund** [comment]
My first thinking is that it is expected as the TextField will be blured, which should trigger value change, which again should trigger validation.

**Comment by knoobie** [comment]
Why should the field be blurred if I don't click inside the field, but the button "next to it"? :)

Note: this only happens with non-modal dialogs.. the modal dialog is probably blocking something (the blur?) in the background and it's not triggered.

**Comment by TatuLund** [comment]
>  is probably blocking something (the blur?) 

Yes

**Comment by rolfsmeds** [comment]
Clicking a button in the prefix or suffix slot does not seem to focus the field. Thus, there seems to be a bug in that validation is triggered as if the field had been focused.

**Comment by vursen** [comment]
I'm currently investigating this issue.

**Comment by vursen** [comment]
The PR containing the fix has been merged. The fix will be included in the following upcoming versions:

- 24.2.0-alpha2
- 24.1.2
- 24.0.10
