### ISSUE TITLE
ClearButton does not work in GridPro custom fields

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/flow-components#5137]
### Describe your motivation

When using a custom field with the clear button visible in GridPro, clicking the button will commit the typed value and exit edition mode.

The behavior is caused by a value change being triggered before on blur of the input field (before the clear button click is processed), which results in *two* value change events. For instance, if I type "123" and then press the clear button, there will be two value change events, one for "123" and other for an empty string.

```
TextField tf = new TextField();
tf.setClearButtonVisible(true);
tf.addValueChangeListener(ev -> System.out.println("Value Change: "+ev.getValue()));
add(tf);
```

Since GridPro leaves the edition mode after a value change, the first event (which changes the value to the typed text) is recognized by GridPro, and the clear-button click has no effect.

### Describe the solution you'd like

I would like that clear button works in custom fields inside of GridPro.

### Describe alternatives you've considered

I could not figure out a workaround for this behavior.

### Additional context

Example
![gridpro](https://github.com/vaadin/flow-components/assets/11554739/7c67a455-d0ec-4728-9fc2-a01f0c77748e)

```  
    GridPro<Bean> grid = new GridPro<>();
    grid.setItems(new Bean());

    TextField tf = new TextField();   
    tf.setClearButtonVisible(true);
    grid.addEditColumn(Bean::getName).custom(tf, Bean::setName);
    add(grid);
```

**Comment by rolfsmeds** [comment]
The same problem also applies to other fields with buttons in them, such as a NumberField with the + and – buttons enabled.
