### ISSUE TITLE
Date Picker popup: Add part/classname to past dates so that they can be styled

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow-components#5165]
### Describe your motivation

We're migrating a Swing app to Vaadin, and we need the past dates to be selectable, but marked grey-ish to indicate that they're past dates and may not be that important for the user.

![image](https://github.com/vaadin/flow-components/assets/254091/01b076b2-603d-4cbb-8d22-dc4cd4c0d9d6)

### Describe the solution you'd like

The `<td>` element for particular day should contain `part="date past"` so that it can be targeted with styles. This should also be documented at https://vaadin.com/docs/latest/components/date-picker/styling

### Describe alternatives you've considered

-

**Comment by knoobie** [comment]
Would like to expand the request with:
- future 
- weekday 
- weekend

**Comment by TatuLund** [comment]
Related to: https://github.com/vaadin/web-components/issues/1925

**Comment by TatuLund** [comment]
Workaround by using aria-labels: https://cookbook.vaadin.com/datepicker-weekend-highlight

**Comment by rolfsmeds** [comment]
Let's add part names `past` and `future` for now.
Weekdays and weekends are somewhat locale-specific, so I wouldn't add those.
