### ISSUE TITLE
[Grid] Cannot read properties of undefined (reading 'dragDisabled')

### ISSUE THREAD

**Issue by jjsteenkamp** [vaadin/flow-components#5177]
### Description

I am making use of the Vaadin Grid Component. In some cases it only has 4 columns - but inside these columns I tend to have components and a few other controls.

I frequently encounter the error :
```
There seems to be an error in Vaadin Grid:
Cannot read properties of undefined (reading 'dragDisabled')
Please submit an issue to https://github.com/vaadin/flow-components/issues/new/choose 
```
But there is no associated error on the server side. Also I am using the @Push mechanism to update it sometimes (using the appropriate UI.access() method etc).

In some cases the application simply carries on. In other cases, the whole session for that user is 'broken'.

Unclear as to how to debug further and give more information here.

### Expected outcome

This error should not occur. 
Or at least if it does - should specify what can be done to remedy.
Certainly should not hang the application.

### Minimal reproducible example

Wish I could provide the application code. But it is quite complex.
Happy to add additional logging as appropriate. Please advise.

### Steps to reproduce

Wish I could provide the application code. But it is quite complex.
Happy to add additional logging as appropriate. Please advise.

### Environment

Vaadin version(s): 23.3.14
OS: Windows and Linux. Chrome Browser primarily. But also Edge.

### Browsers

Chrome, Firefox, Edge

**Comment by silvan-lincan** [comment]
Hello @yuriy-fix 

I could reproduce the issue with both Vaadin v23.3.14 and v23.3.15.
I did not tested with older versions.
<img width="709" alt="Screenshot 2023-06-30 at 18 47 01" src="https://github.com/vaadin/flow-components/assets/47028355/7d684e78-e5fb-4cb3-8920-5b7ade2c00ab">

### Minimal reproducible example: 
[skeleton-starter-flow-23.zip](https://github.com/vaadin/flow-components/files/11918833/skeleton-starter-flow-23.zip)

### Steps to reproduce:
- a Grid with two rows
- `#setRowsDraggable(true)`
- a minimum of two rows (with one row, the error does not appear)

### Browsers
Chrome
Safari
Firefox - I did not tested

I hope/wish this helps in opening an investigation, as we use draggable rows in all our grids.

Thank you.

**Comment by silvan-lincan** [comment]
Hi,

I tested with older versions and it seems that the issue was introduced starting with version 23.3.13.
With version 23.3.12, the issue cannot be reproduced.

**Comment by vursen** [comment]
Here is a simplified reproduction:

```java
@Route("grid")
public class GridView extends Div {
    public class Person {
        private Integer id;
        private String name;

        public Person(Integer id, String name) {
            this.id = id;
            this.name = name;
        }

        public Integer getId() {
            return this.id;
        }

        public void setId(Integer id) {
            this.id = id;
        }

        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }
    }

    public GridView() {
        List<Person> items = new ArrayList<>();
        items.add(new Person(1, "name1"));
        items.add(new Person(2, "name2"));

        Grid<Person> grid = new Grid<>(Person.class, false);
        grid.addColumn(Person::getId).setHeader("ID");
        grid.addColumn(Person::getName).setHeader("Name");

        grid.setSizeFull();
        grid.setAllRowsVisible(true);
        grid.setRowsDraggable(true);
        grid.setItems(DataProvider.ofCollection(items));
        add(grid);
    }
}
```
