### ISSUE TITLE
Login Form -  Validation message triggers before Log in button is clicked

### ISSUE THREAD

**Issue by paodb** [vaadin/flow-components#5181]
### Description

When starting an application from start.vaadin.com that uses the Login Form, validation message triggers on fields before Log in button is clicked.

### Expected outcome

No validation should be triggered until Log in is clicked.

### Minimal reproducible example

Download a starter project from start.vaadin.com and change the default access to "Users who have logged in".

### Steps to reproduce

1. Run the application downloaded from start.vaadin.com.
2. After login is displayed on browser, try to use alt + tab to switch between open programs (on Windows machine). 
3. Validation error on login username field appears. This happens regardless of autocomplete being triggered by the browser or not.
![login1](https://github.com/vaadin/flow-components/assets/30666649/75a6e812-6054-4785-8e35-5e39340c05ec)
![login2](https://github.com/vaadin/flow-components/assets/30666649/ea79247e-11e2-45d3-82df-780d4d65b3e2)

### Environment

Vaadin version(s): 24.1.1
OS: Windows

### Browsers

Chrome, Firefox

**Comment by yuriy-fix** [comment]
The issue is added to the backlog priority queue for further investigation.

**Comment by yuriy-fix** [comment]
Dear @paodb, currently the validation is suppose to happen on blur and that is an expected behaviour. 
Is the problem only for the case of switching tabs / windows or would you expect the error message **NOT** to be shown when navigating between fields (until `Log in` button is clicked)?

**Comment by paodb** [comment]
Hi @yuriy-fix. The problem is in the case of switching tabs/windows. Assuming that I haven't interacted with the login form, I would anticipate that the validation process does not occur upon switching tabs.

**Comment by web-padawan** [comment]
This issue is actually not specific to `vaadin-login-form` and also applies to `vaadin-text-field` or any other field component. The reason is that switching browser tab causes a `focusout` event (which is natural, because of OS focus leaves the tab) and we run validation on focusout. Looks like `document.hasFocus()` could help us to detect this case.
