### ISSUE TITLE
TreeGrid loses items on DataProvider.refreshAll() if item is selected (since 24.1.0)

### ISSUE THREAD

**Issue by finaris-cs** [vaadin/flow-components#5185]
### Description

I have a simple tree grid with multiple levels.
Anytime i have selected a non-root item and call tree.getDataProvider.refreshAll(), all items below the parent of the selection disappear. The disappeared items can only be made visible again by selecting something else (or nothing) and calling refreshAll again.

For multi-selection the problem affects all parent items of all selections.

JS Console shows the following error:
```
There seems to be an error in Vaadin Grid:
Cannot read properties of undefined (reading 'length')
Please submit an issue to https://github.com/vaadin/flow-components/issues/new/choose
```

Our applications uses multiple trees with needs to fully refresh the trees using refreshAll(), so this is a blocker to us preventing the upgrade to Vaadin 24.1

### Expected outcome

Like before Vaadin 24.1.0, i would expect all items to remain visible, no matter which items are selected

### Minimal reproducible example

```
package com.finaris.sqace.frontend.ui.views;

import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.dependency.CssImport;
import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.treegrid.TreeGrid;
import com.vaadin.flow.data.provider.hierarchy.AbstractBackEndHierarchicalDataProvider;
import com.vaadin.flow.data.provider.hierarchy.HierarchicalQuery;
import com.vaadin.flow.router.Route;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.stream.Stream;

@Route(value = "test")
public class TestView extends VerticalLayout {


    public TestView() {
        setSizeFull();
        TreeGrid<Item> tree = new TreeGrid<>();
        tree.setSizeFull();

        tree.addHierarchyColumn(Item::getName);

        tree.setDataProvider(new TreeDataProvider());

        Button button = new Button("Refresh tree");
        button.addClickListener(e -> tree.getDataProvider().refreshAll());
        add(tree, button);
    }

    public static class TreeDataProvider extends AbstractBackEndHierarchicalDataProvider<Item, Void> {

        @Override
        public int getChildCount(HierarchicalQuery<Item, Void> query) {
            return getChildCount(query.getParent());
        }

        private int getChildCount(Item parent) {
            return getChildren(parent).size();
        }

        public List<? extends Item> getChildren(Item parent) {
            if (parent == null) {
                return List.of(new Item("A", 1),
                        new Item("B", 1),
                        new Item("C", 1));
            } else if (parent.getLevel() == 1) {
                List<Item> children = new ArrayList<>();

                for (int i = 1; i <= 8; i++) {
                    children.add(new Item(parent.getName() + "-" + i, parent.getLevel() + 1));
                }

                return children;
            } else {
                return Collections.emptyList();
            }
        }

        @Override
        public boolean hasChildren(Item item) {
            return getChildCount(item) > 0;
        }

        @Override
        protected Stream<Item> fetchChildrenFromBackEnd(HierarchicalQuery<Item, Void> query) {
           List<Item> result = new ArrayList<>(getChildren(query.getParent()));
            return result.subList(query.getOffset(), query.getOffset() + query.getLimit()).stream();
        }
    }

    private static class Item {
        private final String name;
        private final int level;

        public Item(String name, int level) {
            this.name = name + "-" + level;
            this.level = level;
        }

        public int getLevel() {
            return level;
        }

        public String getName() {
            return name;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            Item item = (Item) o;
            return level == item.level && Objects.equals(name, item.name);
        }

        @Override
        public int hashCode() {
            return Objects.hash(name, level);
        }
    }
}

```

### Steps to reproduce

1. Copy the provided code in a Vaadin project, start and navigate to the test page
2. Expand all 3 root items in the tree
3. Select any item below **A-1**, e.g. **A-1-3-2**
4. Click the **Refresh tree** button
==>
The item A-1 looks expanded, but all items below are gone:

![image](https://github.com/vaadin/flow-components/assets/19190710/d2ad742c-33c2-469c-9581-a85b8bb40fde)

Clicking **A-1** just toggles the expand icon, but never shows the child items again
 

### Environment

Vaadin version(s): 24.1.0 24.1.1
OS: 

### Browsers

Issue is not browser related

**Comment by finaris-cs** [comment]
Full error from JS Console if it helps:

FlowBootstrap-feff2646.js:1  There seems to be an error in Vaadin Grid:
Cannot read properties of undefined (reading 'length')
Please submit an issue to https://github.com/vaadin/flow-components/issues/new/choose
(anonymous) @ FlowBootstrap-feff2646.js:1
_loadPage @ generated-flow-imports-45290475.js:3273
(anonymous) @ generated-flow-imports-45290475.js:3471
(anonymous) @ FlowBootstrap-feff2646.js:1
(anonymous) @ generated-flow-imports-45290475.js:3471
(anonymous) @ FlowBootstrap-feff2646.js:1
_getItem @ generated-flow-imports-45290475.js:3273
_updateScrollerItem @ generated-flow-imports-45290475.js:3347
__updateElement @ generated-flow-imports-45290475.js:3249
(anonymous) @ generated-flow-imports-45290475.js:3249
_iterateItems @ generated-flow-imports-45290475.js:3245
_assignModels @ generated-flow-imports-45290475.js:3249
_update @ generated-flow-imports-45290475.js:3245
_render @ generated-flow-imports-45290475.js:3245
(anonymous) @ generated-flow-imports-45290475.js:3245
flush @ generated-flow-imports-45290475.js:952
(anonymous) @ generated-flow-imports-45290475.js:952
flushDebouncers$1 @ generated-flow-imports-45290475.js:952
flush$1 @ generated-flow-imports-45290475.js:952
set size @ generated-flow-imports-45290475.js:3249
set size @ generated-flow-imports-45290475.js:3249
_effectiveSizeChanged @ generated-flow-imports-45290475.js:3347
runMethodEffect @ generated-flow-imports-45290475.js:722
runEffects @ generated-flow-imports-45290475.js:722
_propertiesChanged @ generated-flow-imports-45290475.js:722
E._propertiesChanged @ FlowClient-d5d5e377.js:3
_flushProperties @ generated-flow-imports-45290475.js:696
_invalidateProperties @ generated-flow-imports-45290475.js:722
Object.defineProperty.set @ generated-flow-imports-45290475.js:696
(anonymous) @ generated-flow-imports-45290475.js:3273
(anonymous) @ generated-flow-imports-45290475.js:3471
(anonymous) @ FlowBootstrap-feff2646.js:1
_loadPage @ generated-flow-imports-45290475.js:3273
(anonymous) @ generated-flow-imports-45290475.js:3471
(anonymous) @ FlowBootstrap-feff2646.js:1
(anonymous) @ generated-flow-imports-45290475.js:3471
(anonymous) @ FlowBootstrap-feff2646.js:1
_getItem @ generated-flow-imports-45290475.js:3273
_updateScrollerItem @ generated-flow-imports-45290475.js:3347
__updateElement @ generated-flow-imports-45290475.js:3249
(anonymous) @ generated-flow-imports-45290475.js:3249
update @ generated-flow-imports-45290475.js:3249
update @ generated-flow-imports-45290475.js:3249
__updateVisibleRows @ generated-flow-imports-45290475.js:3347
requestContentUpdate @ generated-flow-imports-45290475.js:3347
__selectedItemsChanged @ generated-flow-imports-45290475.js:3314
runMethodEffect @ generated-flow-imports-45290475.js:722
runEffects @ generated-flow-imports-45290475.js:722
_propertiesChanged @ generated-flow-imports-45290475.js:722
E._propertiesChanged @ FlowClient-d5d5e377.js:3
_flushProperties @ generated-flow-imports-45290475.js:696
_invalidateProperties @ generated-flow-imports-45290475.js:722
Object.defineProperty.set @ generated-flow-imports-45290475.js:696
(anonymous) @ generated-flow-imports-45290475.js:3471
(anonymous) @ FlowBootstrap-feff2646.js:1
(anonymous) @ generated-flow-imports-45290475.js:3471
(anonymous) @ FlowBootstrap-feff2646.js:1
eval @ VM208:3
K3 @ FlowClient-d5d5e377.js:3
kg @ FlowClient-d5d5e377.js:3
Xm @ FlowClient-d5d5e377.js:1
rm @ FlowClient-d5d5e377.js:1
z.gb @ FlowClient-d5d5e377.js:3
zr @ FlowClient-d5d5e377.js:3
eE @ FlowClient-d5d5e377.js:3
z.H @ FlowClient-d5d5e377.js:3
Gu @ FlowClient-d5d5e377.js:1
Fg @ FlowClient-d5d5e377.js:3
Jr @ FlowClient-d5d5e377.js:3
z.ob @ FlowClient-d5d5e377.js:3
z.N @ FlowClient-d5d5e377.js:3
(anonymous) @ FlowClient-d5d5e377.js:1
od @ FlowClient-d5d5e377.js:1
A2 @ FlowClient-d5d5e377.js:3
(anonymous) @ FlowClient-d5d5e377.js:1
XMLHttpRequest.send (async)
e3 @ FlowClient-d5d5e377.js:3
Qd @ FlowClient-d5d5e377.js:1
c3 @ FlowClient-d5d5e377.js:3
Zd @ FlowClient-d5d5e377.js:1
B3 @ FlowClient-d5d5e377.js:3
gf @ FlowClient-d5d5e377.js:3
Vm @ FlowClient-d5d5e377.js:1
z.M @ FlowClient-d5d5e377.js:3
z.H @ FlowClient-d5d5e377.js:3
yf @ FlowClient-d5d5e377.js:3
Jy @ FlowClient-d5d5e377.js:1
z.G @ FlowClient-d5d5e377.js:3
Nl @ FlowClient-d5d5e377.js:1
od @ FlowClient-d5d5e377.js:1
A2 @ FlowClient-d5d5e377.js:3
(anonymous) @ FlowClient-d5d5e377.js:1
E @ FlowClient-d5d5e377.js:1
setTimeout (async)
Yc @ FlowClient-d5d5e377.js:1
j1 @ FlowClient-d5d5e377.js:1
at @ FlowClient-d5d5e377.js:1
O1 @ FlowClient-d5d5e377.js:1
ni @ FlowClient-d5d5e377.js:1
N1 @ FlowClient-d5d5e377.js:1
Kw @ FlowClient-d5d5e377.js:1
Mc @ FlowClient-d5d5e377.js:1
d0 @ FlowClient-d5d5e377.js:1
g1 @ FlowClient-d5d5e377.js:1
tE @ FlowClient-d5d5e377.js:3
dw @ FlowClient-d5d5e377.js:1
z.V @ FlowClient-d5d5e377.js:3
Om @ FlowClient-d5d5e377.js:1
(anonymous) @ FlowClient-d5d5e377.js:1
od @ FlowClient-d5d5e377.js:1
A2 @ FlowClient-d5d5e377.js:3
(anonymous) @ FlowClient-d5d5e377.js:1

**Comment by vursen** [comment]
Here are PRs that could potentially cause this issue:

- https://github.com/vaadin/flow-components/pull/4902
- https://github.com/vaadin/flow-components/pull/5018

**Comment by sissbruecker** [comment]
Managed to narrow it down to this PR:
- https://github.com/vaadin/flow-components/pull/4860

From debugging this, somewhere in the patched `ItemCache` methods it triggers a re-render of nested TreeGrid levels, between `$connector.set` and `$connector.confirmParent`. The issue with that is that while `set` fills the connector cache, only after `confirmParent` a `size` is set on the cache object. That in turn causes the following expression to return `undefined` for the `page`:
https://github.com/vaadin/flow-components/blob/d40a0f0cb7af3323debc7c1c58a73e26ffc4ddc7/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js#L366-L367
