### ISSUE TITLE
Grid.scrollToIndex throws JS Exception since 24.1.0

### ISSUE THREAD

**Issue by finaris-cs** [vaadin/flow-components#5187]
### Description

When calling the scrollToIndex method on a normal grid, JS errors occur and the grid does not show the content.
Might be the same problem as already reported for the treegrid (#5182), but from my point of view not sure it is. 

### Expected outcome

No error as prior to 24.1.0

### Minimal reproducible example

```
package com.finaris.sqace.frontend.ui.views;

import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

@Route(value = "test2")
public class TestView2 extends VerticalLayout {

    private static int nr;

    public TestView2() {
        List<Item> itemList = new ArrayList<>();
        setSizeFull();
        Grid<Item> tree = new Grid<>();
        tree.setSizeFull();

        tree.addColumn(Item::getName).setHeader("Name");

        tree.setItems(itemList);

        Button addWithScroll = new Button("Add item with scrolling");
        addWithScroll.addClickListener(e -> {
            Item item = new Item("A" + nr++);
            itemList.add(item);
            tree.getDataProvider().refreshAll();
            tree.scrollToIndex(itemList.size() - 1);
        });

        Button addWithoutScroll = new Button("Add item without scrolling");
        addWithoutScroll.addClickListener(e -> {
            Item item = new Item("A" + nr++);
            itemList.add(item);
            tree.getDataProvider().refreshAll();
        });

        HorizontalLayout layout = new HorizontalLayout(addWithoutScroll, addWithScroll);

        add(tree, layout);
    }


    private static class Item {
        private final String name;

        public Item(String name) {
            this.name = name;
        }

        public String getName() {
            return name;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            Item item = (Item) o;
            return Objects.equals(name, item.name);
        }

        @Override
        public int hashCode() {
            return Objects.hash(name);
        }
    }
}
```

### Steps to reproduce

1) Run the code above
2) click button "add item with scrolling"

test2:7 There seems to be an error in Vaadin Grid:
undefined
Please submit an issue to https://github.com/vaadin/flow-components/issues/new/choose
console.error @ test2:7
(anonymous) @ FlowBootstrap.js:67
eval @ VM2078:3
Tt @ FlowClient.js:1043
St @ FlowClient.js:997
Qt @ FlowClient.js:614
ur @ FlowClient.js:527
Rr @ FlowClient.js:1053
sB @ FlowClient.js:966
xr @ FlowClient.js:1048
Nr @ FlowClient.js:1053
Tk @ FlowClient.js:445
pr @ FlowClient.js:1051
qr @ FlowClient.js:1033
Ht @ FlowClient.js:1053
TB @ FlowClient.js:1053
(anonymous) @ FlowClient.js:630
Eb @ FlowClient.js:463
Hb @ FlowClient.js:919
(anonymous) @ FlowClient.js:658
XMLHttpRequest.send (async)
RB @ FlowClient.js:962
PB @ FlowClient.js:610
zt @ FlowClient.js:972
_r @ FlowClient.js:619
Wr @ FlowClient.js:1019
as @ FlowClient.js:941
pt @ FlowClient.js:603
tt @ FlowClient.js:1053
xt @ FlowClient.js:1053
$b @ FlowClient.js:996
Tb @ FlowClient.js:724
cc @ FlowClient.js:1053
Yb @ FlowClient.js:228
Eb @ FlowClient.js:463
Hb @ FlowClient.js:919
(anonymous) @ FlowClient.js:658
d @ FlowClient.js:754
setTimeout (async)
_b @ FlowClient.js:755
Vb @ FlowClient.js:751
ko @ FlowClient.js:618
qt @ FlowClient.js:737
gt @ FlowClient.js:554
ct @ FlowClient.js:761
dt @ FlowClient.js:361
Ou @ FlowClient.js:567
wx @ FlowClient.js:777
px @ FlowClient.js:669
zw @ FlowClient.js:1049
Nw @ FlowClient.js:211
By @ FlowClient.js:1053
vC @ FlowClient.js:581
(anonymous) @ FlowClient.js:747
Eb @ FlowClient.js:463
Hb @ FlowClient.js:919
(anonymous) @ FlowClient.js:658

### Environment

Vaadin version(s): 24.1.0, 24.1.1
OS:

**Comment by sissbruecker** [comment]
This regression has been introduced with https://github.com/vaadin/flow-components/pull/4854, however the root of the issue seems to be in the Flow `DataCommunicator`, which doesn't properly handle the sequence of:
- Resetting all data, due to the call to `DataProvider.refreshAll`
- Requesting data for a specific range, due to the call to `Grid.scrollToIndex`

In that case data communicator should resend the full range, but instead it only sends the range requested by `Grid.scrollToIndex`: `[[0,10],1,[1,[{"key":"2","col0":"A1"}]],"return $0.$connector.set($1,$2)"]`. I also don't see how a component like `Grid` could handle this differently, as it can't query from the data communicator whether a full reset has already been called.

Ping @mshabarov , could you please take a look at this?

**Comment by sissbruecker** [comment]
As discovered in #5182 , a similar issue exists when expanding nodes in a `TreeGrid`, and then setting a requested range via `scrollToIndex`.

**Comment by arenk** [comment]
Is there any known workaround except from downgrading Vaadin?
