### ISSUE TITLE
Checkbox click does not always work on mobile devices

### ISSUE THREAD

**Issue by martinisraelsen** [vaadin/flow-components#5190]
### Description

We're experiencing that clicking a checkbox doesn't always work. In extreme circumstances, the user will have to click the checkbox multiple times for it to change the value from unchecked to checked or vice-versa.

I was able to reproduce on a simple page with 20 checkboxes, but it seems that the issue is more pronounced on pages with more controls. The issue does not appear to be related to the speed at which the user clicks or taps the checkboxes. 

In reviewing the logs, I also noticed:
- Click events are always sent as they should (even when the checkbox doesn't register the click).
- Value change events are not sent when the checkbox doesn't register the click.

In the log lines below, notice that checkbox 10 and afterwards 9 are clicked and no value change event happens and the checkboxes remained unchecked.

I have not been able to reproduce it locally, but it can reproduced consistently when running on a remote server.

```
2023-06-22 19:43:03.452  INFO 194484 --- [nio-8080-exec-4] bc.ui.CheckboxBoxes                      : Checkbox[9] ValueChangeEvent value= false
2023-06-22 19:43:03.453  INFO 194484 --- [nio-8080-exec-4] bc.ui.CheckboxBoxes                      : Checkbox[8] ValueChangeEvent value= false
2023-06-22 19:43:03.453  INFO 194484 --- [nio-8080-exec-4] bc.ui.CheckboxBoxes                      : Checkbox[7] ValueChangeEvent value= false
2023-06-22 19:43:03.453  INFO 194484 --- [nio-8080-exec-4] bc.ui.CheckboxBoxes                      : Checkbox[9] ClickEvent
2023-06-22 19:43:03.453  INFO 194484 --- [nio-8080-exec-4] bc.ui.CheckboxBoxes                      : Checkbox[8] ClickEvent
2023-06-22 19:43:03.454  INFO 194484 --- [nio-8080-exec-4] bc.ui.CheckboxBoxes                      : Checkbox[7] ClickEvent
2023-06-22 19:43:03.553  INFO 194484 --- [nio-8080-exec-3] bc.ui.CheckboxBoxes                      : Checkbox[6] ValueChangeEvent value= false
2023-06-22 19:43:03.553  INFO 194484 --- [nio-8080-exec-3] bc.ui.CheckboxBoxes                      : Checkbox[6] ClickEvent
2023-06-22 19:43:04.512  INFO 194484 --- [nio-8080-exec-2] bc.ui.CheckboxBoxes                      : Checkbox[10] ClickEvent
2023-06-22 19:43:04.874  INFO 194484 --- [nio-8080-exec-6] bc.ui.CheckboxBoxes                      : Checkbox[9] ClickEvent
2023-06-22 19:43:05.290  INFO 194484 --- [nio-8080-exec-7] bc.ui.CheckboxBoxes                      : Checkbox[8] ValueChangeEvent value= true
2023-06-22 19:43:05.290  INFO 194484 --- [nio-8080-exec-7] bc.ui.CheckboxBoxes                      : Checkbox[8] ClickEvent
```

### Expected outcome

The checkbox should switch between checked and unchecked when clicked (tapped).

### Minimal reproducible example

```
package bc.ui;

import javax.annotation.PostConstruct;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.config.ConfigurableBeanFactory;
import org.springframework.context.annotation.Scope;

import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.checkbox.Checkbox;
import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.server.auth.AnonymousAllowed;
import com.vaadin.flow.spring.annotation.SpringComponent;

import bc.util.HasLogger;

@Route(value = "/checkboxes")
@SpringComponent
@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)
@AnonymousAllowed
public class CheckboxBoxes extends Composite<Div> implements HasLogger {

	private static final long serialVersionUID = -6505644761241124125L;
	private Div checkboxes = new Div();

	private Logger logger = LoggerFactory.getLogger(getClass());

	public CheckboxBoxes() {
		getContent().add(checkboxes);
	}

	@PostConstruct
	public void init() {
		setupCheckboxes(20);
	}

	private void setupCheckboxes(int count) {

		checkboxes.removeAll();

		for (int i = 0; i < count; i++) {

			final int x = i;

			Checkbox cbx = new Checkbox("Checkbox number " + i);

			cbx.getStyle().set("padding-bottom", "var(--lumo-space-m)");
			cbx.addClickListener(e -> logger.info("Checkbox[" + x + "] ClickEvent"));
			cbx.addValueChangeListener(e -> logger.info("Checkbox[" + x + "] ValueChangeEvent value= " + e.getValue()));
			checkboxes.add(new Div(cbx));
		}
	}

}
```

### Steps to reproduce

- Run the attached code on a remote server (or contact me for mine)
- Open the page in Safari on iOS
- Click and un-click checkboxes and notice if the click is registered or not. I would experience the issue within the first 20 clicks.

### Environment

Vaadin version(s): 23.3.12
OS: Linux 22
Client: Safari iOS 16.5 

### Browsers

Safari on iOS
Other might be affected but haven't tried.

**Comment by mukherjeesudebi** [comment]
The checkboxes in vaadin documentaion also do not register the click always and this is happening quite often.  
I tested it in chrome and safari in iPhone.

**Comment by martinisraelsen** [comment]
> The checkboxes in vaadin documentaion also do not register the click always and this is happening quite often.
> I tested it in chrome and safari in iPhone.

Thanks for the update.

**Comment by rolfsmeds** [comment]
- Is reproducible on both Flow and WC versions at https://vaadin.com/docs/latest/components/checkbox.
- Was not reproducible on WC outside of docs.
- Check if related to animations?

**Comment by rolfsmeds** [comment]
This issue has been added to the backlog priority queue for further investigation.

**Comment by martinisraelsen** [comment]
> > cbx.getStyle().set("padding-bottom", "var(--lumo-space-m)");
> 
> Just to clarify: when clicking on this padding area, there is a visual effect but the `checked` state doesn't change:
> 
>  checkbox-padding.mp4 
> 
> While UX in this case is confusing, the actual behavior is expected as the click does not happen on the `<label>`.

Understood, but I don't think this is the issue. We have pages where the checkboxes are working just fine and other pages where you have to touch 5-6 times for the checkbox to stick. Seems to be related to the number of components on the page.

**Comment by tomivirkki** [comment]
I tried to reproduce the issue without success using an iOS 16.4 simulator, the app uses the view in the description with Vaadin 23.3.12
Used `localtunnel` to simulate a remote server:

https://github.com/vaadin/flow-components/assets/1222264/3cb8f752-2ffe-4317-9e7e-4b180d0d7da8

**Comment by TatuLund** [comment]
@tomivirkki does that it does not happen with simulator imply that the problem is actually in the real device?

**Comment by tomivirkki** [comment]
@TatuLund That's one possibility.

**Comment by mukherjeesudebi** [comment]
I was not able to manually replicate it with the minimal sample provided, in iPhone but could replicate the issue in Checkbox in Vaadin documention. Can the simulator be tried in the checkbox documentation?

**Comment by tomivirkki** [comment]
I wasn't able to reproduce it in the checkbox documentation either using the simulator

**Comment by knoobie** [comment]
I can reproduce it with a real iphone in the docs quite easily. Clicking the label to check the checkboxs works, clicking on the checkbox works only in 10% of the cases.

**Comment by knoobie** [comment]
https://github.com/vaadin/flow-components/assets/3968629/b91be829-b7bc-4b60-a3de-b855761252f6

Here is an example from the docs. You can see the clicking animation when I try to spam click the checkbox

**Comment by DiegoCardoso** [comment]
In Safari for iOS, the `input` is misaligned with the `div` area representing the checkbox visually, which explains why it's hard to click on it:

![image](https://github.com/vaadin/flow-components/assets/262432/fd111a9a-1c37-4d4b-a023-8cfad6bd375b)
