### ISSUE TITLE
Spreadsheet docs say table references in formulas are not supported.  POI supports it.  Is it a documentation bug?

### ISSUE THREAD

**Issue by WoozyG** [vaadin/flow-components#5207]
### Describe your motivation

I added table reference support to POI 4 years ago, and have been using it with an enhanced custom build of Spreadsheet for Vaadin 8 for years.

The Flow documentation lists not handling table references in formulas as a limitation.  Why is that?  Or is it leftover documentation cruft?

If it is no longer working with POI, I'd like to know what broke so I can possibly go fix it, since we need table formulas in order to migrate from V8 to Flow.

### Describe the solution you'd like

Support for table references in Spreadsheet formulas - either verification it does work, and a documentation update, or sample cases showing where it fails, so I can go look at what broke in POI since version 3.18, where I had it working, at least for our use cases.

### Describe alternatives you've considered

Not upgrading yet from Vaadin 8.  Not our preferred plan, I have dev time right now, and want to migrate before needing to add more features to the product, rather than migrate those features as well later.

### Additional context

I'm a POI developer, even though I've been inactive for a while on that project, and could assist if the issue is on the POI side.

**Comment by sissbruecker** [comment]
Did give this a try, and it seems that using both named and table ranges works in formulas. One caveat is that for table ranges specifying columns, the formula gets converted to use absolute cell references. For example setting the formula `SUM(Table_1[Amount])` results in the formula `SUM(Sheet1!D16:D26)`. That could be an issue if the size of the table increases I guess.

I would suggest to update the documentation to remove the disclaimer regarding using tables as named ranges in formulas.
