### ISSUE TITLE
Tabs should gracefully handle selecting tabs

### ISSUE THREAD

**Issue by knoobie** [vaadin/flow-components#5214]
### Description

Currently it's possible that the client sends an invalid / to big selected tab index, resulting in a server exception. 

updateSelectedTab should be refactored so that an selected tab > the currently available tabs doesn't throw an exception.

Example Log (Stacktrace from 23.3 - problem is present even in master)

```log
  java.lang.IllegalArgumentException: The 'index' argument should not be greater than or equals to the number of children components. It was: 5
  at com.vaadin.flow.component.HasOrderedComponents.lambda$getComponentAt$0(HasOrderedComponents.java:126)
  at java.base/java.util.Optional.orElseThrow(Unknown Source)
  at com.vaadin.flow.component.HasOrderedComponents.getComponentAt(HasOrderedComponents.java:126)
  at com.vaadin.flow.component.tabs.Tabs.getSelectedTab(Tabs.java:365)
  at com.vaadin.flow.component.tabs.Tabs.updateSelectedTab(Tabs.java:480)
  at com.vaadin.flow.component.tabs.Tabs.lambda$new$c53a20e4$1(Tabs.java:81)
  at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.lambda$fireEvent$2(ElementPropertyMap.java:465)
  at java.base/java.util.ArrayList.forEach(Unknown Source)

```

### Expected outcome

There is no such exception.

### Environment

Vaadin version(s): 23.3+

**Comment by sissbruecker** [comment]
@knoobie Do you have additional information when the client sends an invalid tab index? This is something we also might want to look into.

Apart from that agree with the general notion that it would make more sense for users to prevent the exception from happening.

**Comment by knoobie** [comment]
Sadly I don't have more information. I just got the stack trace from our production log and no additional ticket from a user.

**Comment by mas4ivv** [comment]
We are facing the same issue with Vaadin 14.11.2, found the stack trace in the production log without any additional information and only vaadin classes in the trace.

This comment seems to be similar: https://github.com/vaadin/flow-components/issues/3838#issuecomment-1449770846

**Comment by vursen** [comment]
I went through the code for any clues but could not find anything that seemed suspicious. I believe we will need more context to address this issue. Could I you provide a code example with the same tab configuration as used in your project?

**Comment by knoobie** [comment]
(I haven't added BFP) 

In my application from last year the tabs are added and removed dynamically based on user input and the user can dismiss tabs themself by clicking a close button added in the tabs name slot. IMHO the fixed might be as simple as adding a proper range check + log a proper error message if that is exceeded.

**Comment by mas4ivv** [comment]
Same for us - the tabs are created dynamically and can be removed by the user. We haven't seen this issue in development, only in production logs, and it seems to happen quite rarely.

**Comment by vursen** [comment]
Testing different scenarios where tabs are dynamically added or removed and simulating network throttling, I managed to reproduce the error. It occurs when the user manages to click on a tab while there is already a round-trip request in progress that will remove that tab. Specifically, the tab click schedules a `selected` property change, but the client sends this change only after receiving the response from the previous request, which removes this tab.

**Comment by vursen** [comment]
We discussed this internally and decided on the following solution: We will replace the exception with a logger warning and also add logic to revert the invalid selected property value to the previous tab to ensure the UI consistency.
