### ISSUE TITLE
[Grid] Restore scrollToIndex performance enhancement

### ISSUE THREAD

**Issue by sissbruecker** [vaadin/flow-components#5229]
We reverted a performance enhancement for `scrollToIndex` as it introduced a regression when using it after adding items:
- https://github.com/vaadin/flow-components/pull/4854
- https://github.com/vaadin/flow-components/issues/5187

The root cause for the regression might actually be in the data communicator as mentioned here: https://github.com/vaadin/flow-components/issues/5187#issuecomment-1607524557. After the Flow team had a chance to take a look at the data communicator issue, we should look into restoring the performance enhancement.

**Comment by sissbruecker** [comment]
Depends on https://github.com/vaadin/flow/issues/17288

**Comment by sissbruecker** [comment]
After further investigation, it turns out this is not related to data communicator, and instead caused by two issues related to the performance enhancement:

**Calling `DataCommunicator.setRequestedRange` with a start index that does not align with the grid's page size**

This one is straightforward, as there is a check in the grid's connector that throws an error if the start index of a data range does not align with the page size:
https://github.com/vaadin/flow-components/blob/b002fbad41ec0207b69ed9d6fc4ef20b9c90e6a6/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js#L642-L644

This was the original cause of the error observed in the bug issue. The fix would be to calculate a proper start index when requesting a range.

**Calling `DataCommunicator.setRequestedRange` on the server does not update the cached requested ranges in the grid's connector**

Even when requesting data from a valid page start index, the grid only displays rows from the page that was scrolled to, but rows from the surrounding pages are empty, and are also not loaded when scrolling up or down. The problem is that calling `setRequestedRange` on the server desynchronizes the range configured in the data communicator with the range configured in the grid connectors `lastRequestedRanges`. So the data communicator will only return data from that range, and the grid connector is still convinced that it has configured the data communicator to return a range that includes additional pages around the one that was scrolled to, so it doesn't trigger another load even though the grid is missing data.

To properly fix this, we would somehow need to make sure that both client and server request the same range for a scroll index. The connector's implementation for that is here: https://github.com/vaadin/flow-components/blob/b002fbad41ec0207b69ed9d6fc4ef20b9c90e6a6/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js#L295-L342

Alternatively the connector's `lastRequestedRanges` could be updated from the server when requesting a range there, though that can lead to additional loading requests if the connector finds that the last requested range does not satisfy the range it wants to have.

**Comment by tomivirkki** [comment]
The latest suggestion seems feasible. Could work if Grid preloaded the target page, and n pages preceding and following the target page, and then cleared `lastRequestedRanges` from the connector. 

In an ideal case, the buffer would be enough to satisfy the range the connector wants. In the worst case, it would cause another request behind the scene.
