### ISSUE TITLE
Add test to be sure that no constructor will be removed unintentionally 

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/flow-components#5243]
### Description

in 24.2.0.alpha3, we found that there is one constructor has been removed unintentionally. 
let us add a test to prevent this for future. 

constructor has been added back in https://github.com/vaadin/flow-components/pull/5242

### Expected outcome

no unexpected changes

### Minimal reproducible example

build docs site will flow-component 24.2.0.alpha3

### Steps to reproduce

clone the docs project
update the vaadin.version to 24.2.0.alpha3/ hilla.version to 2.2.0.alpha3
mvn install

### Environment

Vaadin version(s): 24.2.0.apha3
OS: doesn't matter

**Comment by sissbruecker** [comment]
Resolved with https://github.com/vaadin/flow-components/pull/5248
