### ISSUE TITLE
Calling `Dialog::removeAll` destroys interaction with header and footer of a dialog

### ISSUE THREAD

**Issue by knoobie** [vaadin/flow-components#5263]
### Description

Title says it all. Once `Dialog::removeAll`is called, any action e.g. Button click from a button within the dialog's header or footer is not reaching the server anymore.

### Expected outcome

`Dialog::removeAll` should NOT interfere with the header and footer feature of the grid.

### Minimal reproducible example

```java
new Button("Open Dialog", e -> {
      AtomicReference<Dialog> reference = new AtomicReference<>();
      var dialog = new Dialog();
      reference.set(dialog);
      dialog.getFooter().add(new Button("Click me after clear", ex -> {
        System.out.println("Was I called? :(");
      }));
      dialog.add(new Button("Click me to clear dialog", event -> {
        reference.get().removeAll();
        reference.get().add(new Paragraph("I was cleared!"));
      }));
      dialog.open();
    })
```

### Steps to reproduce

1. Click "Open Dialog"
2. Click "Click me to clear the dialog"
3. Click "Click me after clear"
4. Expectation: "Was I called? :(" in the log.
5. Actual: No log

### Environment

Vaadin version(s): 24.1

### Browsers

Issue is not browser related

**Comment by knoobie** [comment]
Workaround:

```java

  @Override
  public void removeAll() {
    remove(getChildren().filter(component -> !component.getStyle().has("display")
        && !"contents".equals(component.getStyle().get("display")))
      .collect(Collectors.toList()));
  }
```

**Comment by rolfsmeds** [comment]
Agree, removeAll (and similar `HasComponents` methods) should only affect the content area, not elements in the `title`, `header-content` or `footer` slots.

**Comment by rolfsmeds** [comment]
Should also check if ConfirmDialog is broken in a corresponding way.

**Comment by sissbruecker** [comment]
This part looks suspicious:
https://github.com/vaadin/flow-components/blob/832d0ea9c45b5e1f4538855df31c8a32a9b5de70/vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java#L696

This adds the header / footer wrapper elements as a direct children of the dialog, which also means they will be removed there when calling `removeAll`. This also affects other APIs in the dialog such as `getChildren`, `getChildCount` and `addComponentAtIndex`.

One thing to try would be to add the wrappers as virtual children instead.

**Comment by knoobie** [comment]
How can the exact bug be re-introduced in V25? My example from above is broken again.. Luckily I've written a test to verify it.. :( @rolfsmeds

**Comment by knoobie** [comment]
Funny thing - it's even more broken. In the past the footer/header was still visible - now the dialog is empty and broken

**Comment by knoobie** [comment]
Workaround:

```java

  @Override
  public void removeAll() {
    getElement().getChildren().forEach(child -> {
      if (!child.hasAttribute("slot")) {
        child.removeFromParent();
      }
    });
  }
```

**Comment by web-padawan** [comment]
@knoobie Could you please create a new issue for this problem? We are typically using new tickets for regressions.

**Comment by knoobie** [comment]
Done: https://github.com/vaadin/flow-components/issues/8315
