### ISSUE TITLE
Lit renderer shows empty overlay with readonly multiselect combobox

### ISSUE THREAD

**Issue by krasnyt** [vaadin/flow-components#5270]
### Description

I have a multiselect combobox with a custom lit renderer. This renderer works as expected if the MSCB is not read only. I used the lit renderer to render user name on a first line and email and phone just below. However when I set the MSCB to be read only and click the MSCB, I only get a blank overlay.
<img width="649" alt="Screenshot 2023-07-19 at 22 40 20" src="https://github.com/vaadin/web-components/assets/6813833/3d6d8094-0768-4082-830e-b12937c45dd2">
<img width="662" alt="Screenshot 2023-07-19 at 22 52 02" src="https://github.com/vaadin/web-components/assets/6813833/9c05447d-ce35-4ae2-a09d-2e59f571a155">

### Expected outcome

I would expect to see whatever is selected, which works normally if I don't use a custom renderer.

### Minimal reproducible example

```
    public static Renderer<UserDto> userRenderer() {
        final String template = """
                <div style="display: flex;">
                  <div>
                    <div>${item.fullName}</div>
                    <div style="font-size: var(--lumo-font-size-s); color: var(--lumo-secondary-text-color);">${item.email}</div>
                  </div>
                </div>
                        """;

        return LitRenderer.<UserDto>of(template)
                .withProperty("email", UserDto::getEmailWithPhone)
                .withProperty("fullName", UserDto::getFullName);
    }
```

### Steps to reproduce

1. create a multiselect combobox
2. add elements to it
3. select some of the elements
4. set the MSCB to be readonly
5. click the MSCB

### Environment

Vaadin version(s): 24.1.2
OS: Ventura

### Browsers

Chrome

**Comment by sissbruecker** [comment]
Can reproduce this. While the items are rendered using the renderer, it seems the item data is not generated on the server side, so using expressions like `${item.xyz}` in the template does not render anything.

For example, the output for the following renderer:
```java
final String template = """
    <div>Item: ${item.label}</div>
""";

LitRenderer.<String>of(template)
        .withProperty("label", item -> item);
```

Is:

![Bildschirmfoto 2023-07-26 um 15 20 05](https://github.com/vaadin/flow-components/assets/357820/1f9a908c-c26f-4353-8203-24553ebb8446)

**Comment by web-padawan** [comment]
The problem is caused by the fact that `selectedItems` property set on the web component doesn't contain keys using `propertyNamespace` expected by `LitRenderer` (so in addition to `label` it should contain `lr_0_label` etc).

https://github.com/vaadin/flow-components/blob/93bb5b1b9b1acafa4236b8cddac9a446d4050b81/vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/MultiSelectComboBox.java#L358-L359
