### ISSUE TITLE
Components set as headers for a ConfirmDialog are not interactable

### ISSUE THREAD

**Issue by ugur-vaadin** [vaadin/flow-components#5277]
### Description

When a component like a button is set as header to `ConfirmDialog`, it cannot be interacted (cannot be clicked in this case).

Likely related to another [issue](https://github.com/vaadin/flow-components/issues/5275) regarding removing content from a `ConfirmDialog`.

### Expected outcome

I would expect the components to be interactable.

### Minimal reproducible example

```java
ConfirmDialog dialog = new ConfirmDialog();
dialog.setHeader(new NativeButton("Click to close", click -> reference.get().close()));
dialog.open();
```

### Steps to reproduce

1. Add the snippet above to a view
2. Click the close button
3. Observe that the button is not clickable and the dialog is not closed

### Environment

Vaadin version(s): 24.2
OS: MacOS

### Browsers

Issue is not browser related

**Comment by web-padawan** [comment]
Reproduced also with the web component using the following code:

```html
<vaadin-button id="open">Open</vaadin-button>

<vaadin-confirm-dialog>
  <button slot="header">Close</button>
  Do you want to save or discard the changes?
</vaadin-confirm-dialog>

<script type="module">
  import '@vaadin/confirm-dialog';

  const dialog = document.querySelector('vaadin-confirm-dialog');
  const button = document.querySelector('#open');

  dialog._headerNode.addEventListener('click', () => {
    dialog.opened = false;
  });

  button.addEventListener('click', (event) => {
    dialog.opened = true;
  });
</script>
```

**Comment by web-padawan** [comment]
So, this issue is caused by the following CSS:

https://github.com/vaadin/web-components/blob/7072364960f0f5be719b41ae6bbd8f3750bd8fe8/packages/dialog/src/vaadin-dialog-styles.js#L16

There is a workaround for footer, but not header:

https://github.com/vaadin/web-components/blob/7072364960f0f5be719b41ae6bbd8f3750bd8fe8/packages/confirm-dialog/src/vaadin-confirm-dialog-overlay.js#L27-L30
