### ISSUE TITLE
Backport improved disableOnClick for button

### ISSUE THREAD

**Issue by muhammetaltindal** [vaadin/flow-components#5292]
### Ignore

Are there plans to backport the improved handling of disableOnClick for button to Vaadin 14? It has a high impact on performance, see issue [#17286](https://github.com/vaadin/flow/issues/17286) on vaadin/flow repository.

**Comment by yuriy-fix** [comment]
Dear @mukherjeesudebi, we do not currently have plans to backport the change at the moment.
The reason is that the change caused regression in the latest version, so we need to come up with a better approach.
