### ISSUE TITLE
Enhancement: Lazy value change should also be triggered when blur

### ISSUE THREAD

**Issue by steffen-harbich-cognitum** [vaadin/flow-components#530]
The lazy value change mode is a great feature. However, I wonder about the following scenario.

Imagine a TextField with lazy value change mode enabled to input some user data and a "Next" button that processes the data. Now when the user is fast enough to click the button after text input then the last entered value in TextField is not applied to the server-side component, thus the button click event listener is working on outdated user input.

Wouldn't it make sense to listen on the TextField input element focus leave event on the client-side component to intercept the lazy delay in that case? I mean on blur the lazy delay could be canceled and the value change event triggered immediately (which would apply the value to the TextField before the button click event triggers).

I did not try so far but is it possible to workaround this lazy mode drawback using the blur listener? Will the actual text field value be present?

**Comment by denis-anisimov** [comment]
I guess this is text field issue, right ?
Moved to the correct repo.

**Comment by steffen-harbich-cognitum** [comment]
Yes, because lazy value change is only useful in text (area) fields, true. Can you confirm the problem? Is there a workaround or fix?

**Comment by denis-anisimov** [comment]
The confirmation should be done by the proper team who is responsible for the issue.
That's why I've asked and moved the ticket.
Please wait for the response from them.

**Comment by web-padawan** [comment]
Closing in favor of #3071 which describes the same problem.
