### ISSUE TITLE
Grid: allow registering event listeners to notify them when Grid DataProvider change

### ISSUE THREAD

**Issue by flang** [vaadin/flow-components#5324]
### Describe your motivation

Currently there's no way to perform any actions when Grid DataProvider change, other than overriding Grid.setDataProvider() method. If that's not feasible, the alternative would be triggering an event when DataProvider changes.

In order to perform some computations when the DataProvider for Grid is set or changed, it'd be useful to have the possibility to register listeners and notify them when this change occurs.

A use case could be performing some actions on the column header content when Grid DataProvider is set. For example, a column which values are rendered as checkboxes, and has a Select All checkbox on its header.

### Describe the solution you'd like

Consider adding an API to register listeners so they get notified when Grid's DataProvider is set:

```
public Registration addDataProviderChangeListener(
            ComponentEventListener<DataProviderChangeEvent<T>> listener) {
   return addListener(DataProviderChangeEvent.class, (ComponentEventListener) listener);
}

public void setDataProvider(DataProvider<T, ?> dataProvider) {
   ...
   fireEvent(new DataProviderChangeEvent<>(this));
}

```

### Additional context

Grid web component has already a "data-provider-changed" event which is only triggered the first time DataProvider is set from Java.

**Comment by sissbruecker** [comment]
Closing as not planned, see https://github.com/vaadin/flow-components/pull/5329#issuecomment-1667748562 for reasoning.
