### ISSUE TITLE
[DateTimePicker] Inconsistently invalidates when blurring after typing a valid date

### ISSUE THREAD

**Issue by vursen** [vaadin/flow-components#5335]
### Description

`DateTimePicker` invalidates when you type a valid date and then blur. The second blur removes the invalid state.

Note, the issue doesn't occur if you press <kbd>Enter</kbd> before blur.

https://github.com/vaadin/flow-components/assets/5039436/f35b7086-aa30-4a16-9213-46acf9d5744e

### Expected outcome

`DateTimePicker` should be valid after comitting a valid date.

### Minimal reproducible example

```java
@Route("date-time-picker")
public class DateTimePickerView extends Div {
    DateTimePickerView() {
        DateTimePicker dateTimePicker = new DateTimePicker();
        add(dateTimePicker);
    }
}
```

### Steps to reproduce

1. Enter "1/1/2023" into the date picker
2. Blur

### Environment

Vaadin version(s): 24.2 and possibly earlier

### Browsers

Issue is not browser related

**Comment by rolfsmeds** [comment]
I would say that, when the date sub-field is focused, both pressing Enter and clicking outside the overlay should simply close the date picker overlay and _not_ attempt to commit the DTP's value or run validation. The rationale for this is that the user is almost certainly still in the process of entering a date-time value.

Validate and commit should only happen
- When the DTP and its sub-fields are blurred (by tabbing out of the DTP, or by clicking outside it when neither overlay is open)
- When pressing Enter on the time sub-field.

Perhaps @jouni has opinions on this?

**Comment by vursen** [comment]
I agree that the way DateTimePicker validates should be improved in general. However, I'd like to note that the cause for the reported inconsistency is the current implementation of DatePicker. DatePicker currently commits the entered value in the outside click handler rather than the focusout handler. DateTimePicker in its turn expect the value to be available already at the time of the focusout event – setFocused(false) – which goes before the outside click event. It explains why DateTimePicker invalidates on the first outside click: at that point, DatePicker doesn't have a value yet whereas its `_hasInputValue` indicates `true`, which leads to DateTimePicker interpreting that as bad input and marking the field as invalid.

**Comment by vursen** [comment]
The inconsistency has been resolved by two fixes:

- https://github.com/vaadin/web-components/pull/7855
- https://github.com/vaadin/web-components/pull/7846

As a result, the field now validates only on the second click. I'm closing this issue.
