### ISSUE TITLE
ItemClickEvent.getColumn() returns null when a selction column of a grid is clicked.

### ISSUE THREAD

**Issue by MathisDukatz** [vaadin/flow-components#5337]
### Description

An ItemClickListener was added to a grid with multi selection mode enabled . To reduce falsely triggering the click event, when a selection checkbox is slightly missed  the click action shouldn't fire if the column is the selection column. ItemClickEvent.getColumn() returns null for the selection column even though the documentation states otherwise. 

### Expected outcome

ItemClickEvent.getColumn() should either state that it can return null for internal created columns as the multi selection column or the selection column should be reachable and clearly identifiable with functions like grid.getColumns() etc.

### Minimal reproducible example

```java

Grid<Person> grid = new Grid<>(Person.class, false);
grid.setSelectionMode(Grid.SelectionMode.MULTI);
grid.addColumn(Person::getFirstName).setHeader("First name");
grid.addColumn(Person::getLastName).setHeader("Last name");
grid.addColumn(Person::getEmail).setHeader("Email");

List<Person> people = DataService.getPeople();
grid.setItems(people);

dataGrid.addItemClickListener(event -> System.out.println(event.getColumn());

```

### Steps to reproduce

1. Add Multi Selection mode and ItemClickListener to grid.
2. In the Clickevent Action call ItemClickEvent.getColumn
3. Click th selection column beside its checkbox.

### Environment

Vaadin version(s): 23.3.2
OS: Windows

### Browsers

Edge

**Comment by TatuLund** [comment]
For me it looks like null is intentional and should be mentioned in JavaDoc. This method gets the Column from the Grid's internal Map of columns by id. The multi selection column is never added to that Map as it is special fixture in the web component.
