### ISSUE TITLE
RadioButtonGroup.refreshAll() clears value

### ISSUE THREAD

**Issue by SonReimer** [vaadin/flow-components#5385]
### Description

- I apply items to a RadioButtonGroup RadioButtonGroup.
- I select one item
- Then I press a button which calls refreshAll() on the DataView
- The selection has been removed

by the way:
In RadioButtonGroup.setValue() the value is checked against the items for object equality.
Shouldn't this use DataProvider.getId() ?

### Expected outcome

I would expect the selection to not being removed.

### Minimal reproducible example

```
    VerticalLayout layout = new VerticalLayout();
    RadioButtonGroup<String> radioButtonGroup = new RadioButtonGroup<>();
    radioButtonGroup.setItems(DataProvider.ofItems("1","2","3"));
    Button refreshButton = new Button("Refresh", e -> {
      radioButtonGroup.getListDataView().refreshAll();
    });
    layout.add(refreshButton, radioButtonGroup);

```

### Steps to reproduce

1. Add the snippet above to a view
2. Select a radio
3. Click on the refresh button
4. See the selction has gone

### Environment

Vaadin version(s): 23.3.20
OS: Windows

### Browsers

Firefox

**Comment by knoobie** [comment]
Related to https://github.com/vaadin/flow-components/issues/4592#issuecomment-1403309679

**Comment by yuriy-fix** [comment]
@mshabarov , we should plan discussion on this one.

**Comment by yuriy-fix** [comment]
The current logic was implemented by design, but as we've received several requests we need to make a decision on how the API should be changed.

**Comment by sissbruecker** [comment]
This should be doable now with setting the respective selection preservation mode:
```java
radioButtonGroup.setSelectionPreservationMode(SelectionPreservationMode.PRESERVE_EXISTING);
```
