### ISSUE TITLE
Date Picker addOpenedChangeListener not working

### ISSUE THREAD

**Issue by DarioViva42** [vaadin/flow-components#5386]
### Description of the bug

When using a Date-Picker and adding a OpenedChangeListener the Event will not be handled.

### Expected behavior

The added Listener should run the method defined in the lambda.

### Minimal reproducible example

https://github.com/DarioViva42/addOpenedChangeListener
Run the application using mvn.
Checkout branch withVaadin23 to experience the same project, but working.

### Versions

- Vaadin / Flow version: 24
- Java version: 17
- OS version: Windows 10

**Comment by web-padawan** [comment]
This issue appears to be a regression from #4909. See also https://github.com/vaadin/flow-components/pull/4909#discussion_r1168675428

We should also check other components updated in that PR: `ContextMenu`, `Details`, `Dialog`, `Notification`, `Select`, `TimePicker`. Also, the fix should probably be covered by unit test without a need for ITs.
