### ISSUE TITLE
Click shortcuts don't work in ConfirmDialog

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/flow-components#5389]
### Description

Clickshortcuts applied to buttons in a ConfirmDialog don't seem to work at all.

There's no difference between buttons placed in the dedicated button slots, and buttons placed in the dialog's content slot.

Not sure if this is a component issue or a Flow issue. A related fix was done in Flow some time ago: https://github.com/vaadin/flow/issues/13205, but this seems specific to ConfirmDialog.

### Expected outcome

Clickshortcuts on components in ConfirmDialog should work.

### Minimal reproducible example

```
        var confirmDialog = new ConfirmDialog();
        confirmDialog.setConfirmText("Please confirm");
        var confirmButton = new Button("Confirm");
        confirmButton.addClickShortcut(Key.KEY_J);
        confirmButton.addClickListener(e->confirmDialog.close());
        confirmDialog.add(confirmButton);
        confirmDialog.open();
```

### Steps to reproduce

1. Open a page with the above code
2. Click the confirmdialog to make sure it's focused
3. Press J
4. Observe nothing happening

(the exact same code with a Dialog instead of ConfirmDialog works as expected)

### Environment

Vaadin version(s): V24.2.alpha10

### Browsers

Issue is not browser related

**Comment by ankeshKapil** [comment]
is this going to be added to vaadin 23 as well ?

**Comment by web-padawan** [comment]
The PR #5424 was backported to Vaadin 23.

**Comment by ankeshKapil** [comment]
But this still does not work, tried it on 23.3.29

`  var confirmDialog = new ConfirmDialog();
        confirmDialog.setHeader(windowCaption);
        confirmDialog.add("dsdfsd fdsgfsad);
        final var confirmButton = new Button(okCaption);
        confirmDialog.setConfirmButton(confirmButton);
        confirmButton.addClickShortcut(Key.KEY_J);
        final var cancelButton = new Button(cancelCaption);
        confirmDialog.setCancelButton(cancelButton);
        cancelButton.addClickShortcut(Key.KEY_N);
        confirmDialog.setCancelable(true);
        confirmDialog.setCloseOnEsc(true);`

**Comment by web-padawan** [comment]
It could be related to #5507 if you are using Chrome. We are aware of the problem and working on the fix.
