### ISSUE TITLE
Combobox with required-flag set: error not shown/disappears on focus loss

### ISSUE THREAD

**Issue by nittka** [vaadin/flow-components#5409]
### Description

The behaviour wrt. the visibility of the error message for a combobox marked as required is buggy.
* If the box is initialized as invalid, the message is not shown
* If the status is changed from valid to invalid, the message is shown, but disappears on focus loss (without a value change by the user).

If the combobox is NOT marked as required, it behaves as expected. 

### Expected outcome

The error message should be visible whenever the component is invalid.

### Minimal reproducible example

```
HorizontalLayout layout = new HorizontalLayout();

ComboBox<Boolean> cb = new ComboBox<>("Box");
cb.setItems(true, false);
cb.setErrorMessage("Error");
cb.setValue(true);
cb.setInvalid(true);//set explicitly invalid - error not shown
cb.setRequired(true);//without this line the error is shown and remains visible on focus loss
layout.add(cb);

//changing the value is necessary in order to make in valid
Button b = new Button("Set error explicitly (after changing value manually in combobox!))", e -> {
	cb.setInvalid(true);
});
layout.add(b);
```

### Steps to reproduce

1. Add the above snippet to a view
2. note that the error message is not visible, although the component is invalid
3. change the value in the combobox
4. click the button and not that the error message appears
5. open the combobox without changing the value
6. press tab (to lose focus)
7. note that the error message disappears

If the required-flag is removed, the error message behaves as expected.

### Environment

Vaadin version(s): 14.10.3 

### Browsers

Issue is not browser related

**Comment by rolfsmeds** [comment]
Issue has been added to the backlog priority queue for further investigation.

**Comment by vursen** [comment]
The issue comes from the `text-field` web component that `combo-box` uses internally. The `text-field` component tries to revalidate during initialization and on blur when invalid and required. This in turn results in resetting the invalid state which  was delegated to it by `combo-box`.
