### ISSUE TITLE
Clicking the label of a Checkbox inside a ConfirmDialog produces a client-side error

### ISSUE THREAD

**Issue by mlindfors** [vaadin/flow-components#5412]
### Description

If you have a Checkbox added inside a ConfirmDialog, you can only change the state of the Checkbox by clicking the actual checkbox. Clicking the label leads to an error in the browser.

Note that this is also broken in 23.3, but in a different way. The Checkbox value changes on the client, but produces an error, and the server-side value change listener doesn't fire. But this happens only on the first click, subsequent clicks work.

### Expected outcome

When the Checkbox label is clicked, the value should change, even when said Checkbox is inside a ConfirmDialog.

### Minimal reproducible example

```java
Checkbox checkboxInside = new Checkbox("Inside Dialog");
checkboxInside.addValueChangeListener(event -> Notification.show("Value Changed Inside"));
ConfirmDialog dialog = new ConfirmDialog();
dialog.add(checkboxInside);
Button dialogbutton = new Button("Confirm", click -> {
   dialog.open();
});
add(dialogbutton);
```

### Steps to reproduce

1. add the snippet above to a view
2. click the "Confirm" button to open the ConfirmDialog
3. try to change the Checkbox value by clicking the "Inside Dialog" label text

### Environment

Vaadin version(s): 24.1.7, 23.3.21
OS: macOS

### Browsers

Chrome, Firefox, Safari

**Comment by web-padawan** [comment]
Confirmed the issue also with the web component using the following code to initialize the dialog:

```html
<script type="module">
  import '@vaadin/confirm-dialog';
  import '@vaadin/checkbox';

  const dialog = document.createElement('vaadin-confirm-dialog');
  const checkbox = document.createElement('vaadin-checkbox');

  const label = document.createElement('label');
  label.setAttribute('slot', 'label');
  label.textContent = 'Inside Dialog';
  checkbox.appendChild(label);

  dialog.appendChild(checkbox);

  document.body.appendChild(dialog);
  dialog.opened = true;
</script>
```
