### ISSUE TITLE
Rich text editor causes Memory Leak in the frontend / JS Heap

### ISSUE THREAD

**Issue by finaris-cs** [vaadin/flow-components#5422]
### Description

In my application, I sometimes need to add Rich text editors to the UI.
Each time an editor is added, even if no interaction is done with the editor, the required JS Heap increases and is not given free.
Multiple detached elements are referenced and not released:

![image](https://github.com/vaadin/flow-components/assets/19190710/034b4fdd-3fac-4061-9237-ed08a63e1b0e)

### Expected outcome

When the rich text editor is detached from the UI, a cleanup should be done so that the GC can collect all detached data.

### Minimal reproducible example

```
@Route(value = "test")
public class TestView extends VerticalLayout {


    public TestView() {
        setSizeFull();

        Div div = new Div();
        div.setSizeFull();
        Button button = new Button("Click to add new view");

        button.addClickListener(e -> {
            Button htmlButton = new Button("Click to add new HTML Editor");
            Div htmlDiv = new Div();
            htmlDiv.setSizeFull();
            htmlButton.addClickListener(ev -> {
                htmlDiv.removeAll();
                htmlDiv.add(new RichTextEditor());
            });
            div.removeAll();
            div.add(new VerticalLayout(htmlButton, htmlDiv));
        });
        add(button, div);
    }
}
```

### Steps to reproduce

run example code and click the buttons alternating multiple times

### Environment

Vaadin version(s): 24.1
OS: Any

### Browsers

Issue is not browser related

**Comment by web-padawan** [comment]
This should be fixed by #6506 where we added logic to cleanup Quill listeners in `disconnectedCallback()`.
