### ISSUE TITLE
SlotUtils.clearSlot does not remove slot attribute from children

### ISSUE THREAD

**Issue by web-padawan** [vaadin/flow-components#5429]
### Describe your motivation

This was pointed out at https://github.com/vaadin/flow-components/pull/5390#discussion_r1315184509

While `SlotUtils.addToSlot` sets `slot` attribute before adding an element, `SlotUtils.clearSlot` does not remove it.

### Describe the solution you'd like

Remove `slot` attribute before removing an element, to handle cases when developers want to add it somewhere else.

**Comment by ugur-vaadin** [comment]
Reminder for the future assignee: The tests that use `LoginOverlay.removeAll` in `LoginOverlaySlotsTest.java` should probably be updated to check for the presence of the `slot` attribute.
