### ISSUE TITLE
[DatePicker] Allow disabling certain dates

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow-components#5453]
### Describe your motivation

We want users to enter working days using the date picker for work time tracking. To prevent users from entering times for days where they should not work, we want to disallow those days for better UX. Currently it is not possible to do that with the date picker in an easy way. Therefore it would be good to have some api to define days, which may be selected or not.

### Describe the solution you'd like

DatePicker should allow to disallow dates by
* specific dates (e. g. for holidays, like 3rd of October in Germany)
* days of week, (e. g. Saturday and Sunday)
* ranges of dates (e. g. the last week of December, as there are company holidays)

The api could look like:
```
// disallow certain dates
setDisallowedDates(LocalDate... dates)

// disallow certain days of week, using the java.time enum
setDisallowedDaysOfWeek(DayOfWeek... dows)

// disallow certain ranges of dates)
setDisallowedRange(LocalDate start, LocalDate end)
```

Those methods should be combinable, e.g. to disallow certain days, days of week and multiple ranges of week. 

Disallowed days cannot be picked using the overlay and also not entered using the input field. Entering it via the input field should lead to an error message.

Stylings should be extended to style those days (default should be the grayed out text). The default error message should be modifiable.

As an additional feature, it should/could be thinkable to allow setting tooltips for those days. In this case the api could be have the following additional methods

The api could look like:
```
setDisallowedDates(String tooltip, LocalDate... dates)
setDisallowedDaysOfWeek(String tooltip, DayOfWeek... dows)
setDisallowedRange(String tooltip, LocalDate start, LocalDate end)
```

### Describe alternatives you've considered

Doing it dynamically in the DOM using JavaScript on the fly when the overlay is opened. But that is very very complex and error prone.

**Comment by web-padawan** [comment]
Thanks for the issue. Closing in favor of https://github.com/vaadin/web-components/issues/1820 and https://github.com/vaadin/platform/issues/2867.
