### ISSUE TITLE
MultiSelectListBox shows incorrect items selected when applying filter to data view

### ISSUE THREAD

**Issue by drewharvey** [vaadin/flow-components#5465]
### Description

The checkboxes next to selected items don't update when applying a filter to the data view.  If indexes 0 and 3 are selected, after applying a filter it still shows 0 and 3 selected even if the items have changed.

![multiselect-listbox](https://github.com/vaadin/flow-components/assets/2496955/ac45e92a-18a3-4ccc-b4d7-aa6ce8a623c6)

### Expected outcome

I would expect the correct items to appear selected.

### Minimal reproducible example

```
var comp = new MultiSelectListBox<String>();
comp.setItems("John", "Tim", "Brandon", "Luke", "Kevin");

var filter = new TextField("Filter");
filter.addValueChangeListener(e -> {
    var searchPhrase = e.getValue();
    var dataView = comp.getListDataView();
    dataView.removeFilters();
    dataView.addFilter(person ->
            StringUtils.isEmpty(e.getValue())
                    || StringUtils.containsIgnoreCase(person, searchPhrase));
});

var btn = new Button("Show Selected", e -> {
    var names = String.join(",", comp.getSelectedItems());
    Notification.show("Selected: " + names)
            .setDuration(-1);
});

add(filter, comp, btn);
```

### Steps to reproduce

1. Use snippet provided
2. Select some names from list
3. Enter type into the filter and press 'Enter' key to apply filter
4. Optional: click button to display the true selected values

### Environment

Vaadin version(s): 23.3.23
OS: MacOS

### Browsers

Chrome

**Comment by yuriy-fix** [comment]
This issue has been added to the backlog priority queue for further investigation.

**Comment by mshabarov** [comment]
This issue should be fixed by adding `refreshAll()` method call to the filter (and sorting maybe) methods in `DataView`.

**Comment by drewharvey** [comment]
If I add `refreshAll()` after modifying the filters, the selection items are completely lost.

```
filter.addValueChangeListener(e -> {
    var searchPhrase = e.getValue();
    var dataView = comp.getListDataView();
    dataView.removeFilters();
    dataView.addFilter(person ->
            StringUtils.isEmpty(e.getValue())
                    || StringUtils.containsIgnoreCase(person, searchPhrase));
    dataView.refreshAll();
});
```

![list-losing-selection](https://github.com/vaadin/flow-components/assets/2496955/ebf977b2-abd7-4d2e-bed0-9486ca66345a)

**Comment by TatuLund** [comment]
> If I add refreshAll() after modifying the filters, the selection items are completely lost.

@drewharvey Yes, that is a known case, see this ticket https://github.com/vaadin/flow-components/issues/2593

Furthermore, some other components behave same way like CheckBoxGroup, but some others differently, like Grid. Currently the workaround is to get selected items before refreshAll and set the selection programmatically after (as pointed also in the linked ticket).

Since this behavior is sometimes desired and sometimes not, there has been API request to control it https://github.com/vaadin/platform/issues/4486

See also PR https://github.com/vaadin/flow/pull/16650

What is mystery to me is that while this API was already merged and bout be included to Vaadin 24.2, it was reverted, but the revert commit does not explain why.

**Comment by mshabarov** [comment]
It has been reverted because of changed design from having DataProvider methods to a several selection modes on a Component level, see https://github.com/vaadin/platform/issues/4486.

**Comment by ugur-vaadin** [comment]
With the new selection preservation mode API, you can now set `listbox.setSelectionPreservationMode(SelectionPreservationMode.PRESERVE_EXISTING)` and safely call `refreshAll` on filtering. This way the selection will be retained for the items that are still present.

Closing as resolved.
