### ISSUE TITLE
IntegerField can be changed with step buttons when it's set to readOnly

### ISSUE THREAD

**Issue by simasch** [vaadin/flow-components#5490]
### Description

I have an Integer field:

    quantity = new IntegerField(getTranslation("Anzahl"));
    quantity.setId("quantity-" + orderItem.getPosition());
    quantity.setMin(0);
    quantity.setStepButtonsVisible(true);
    quantity.setReadOnly(orderItem.getStatus() != OrderItemStatus.NEW && !readOnly);

When it's set to readOnly the value can not be changed in the input field but I can change it with the step buttons!

### Expected outcome

Step buttons shouldn't work if the filed is set to readOnly.

### Minimal reproducible example

See description

### Steps to reproduce

See description

### Environment

Vaadin version(s): 24.1.10

**Comment by yuriy-fix** [comment]
We couldn't reproduce the issue with the provided code sample (platforms: Safari / Chrome / Firefox)
Is there any additional details we should consider to reproduce the issue?

**Comment by simasch** [comment]
@yuriy-fix I did a small example and in that it works. I'll have to investigate further why in the other app the behavior is different. I'll close the issue for now.
