### ISSUE TITLE
Grid with component column causes an error when added to a layout via a separate thread

### ISSUE THREAD

**Issue by evan-miller-jumpmind** [vaadin/flow-components#5493]
### Description

This error started occurring after upgrading from Vaadin 14 to Vaadin 24. My application generates a grid on a separate thread, and the grid includes a component column containing a button that opens the grid's editor.

When I add a grid with a component column to a layout via a separate thread using `UI.access()`, the component column has no contents and the following error occurs in Chrome and Edge:

```
There seems to be an error in Vaadin Grid:
Cannot read properties of undefined (reading 'getByNodeId')
Please submit an issue to https://github.com/vaadin/flow-components/issues/new/choose
```

The error is different in Firefox:

```
There seems to be an error in Vaadin Grid:
window.Vaadin.Flow.clients[e] is undefined
Please submit an issue to https://github.com/vaadin/flow-components/issues/new/choose
```

If I navigate to a different screen in my application and then go back to the screen containing the grid, then the button becomes visible and no more errors occur.

### Expected outcome

The grid is added without causing an error and the button in the grid's component column is visible right away.

### Minimal reproducible example

I can reproduce this with a grid with 1 component column:

```java
public class TestLayout extends VerticalLayout {
    public TestLayout() {
        Button addGridButton = new Button("Add grid", e -> {
            Runner runner = new Runner(new IRunnerListener() {
                @Override
                public void finished(Component component) {
                    UI ui = getUI().orElse(null);
                    if (ui != null) {
                        ui.access(() -> add(component));
                    }
                }
            });
            runner.start();
        });
        add(addGridButton);
    }
}

public class TestGrid extends Grid<String> {
    public TestGrid() {
        addComponentColumn(item -> new Button("Test"));
        setItems("Test");
    }
}

public class Runner extends Thread {
    private IRunnerListener listener;
    
    public Runner(IRunnerListener listener) {
        this.listener = listener;
    }
    
    @Override
    public void run() {
        listener.finished(new TestGrid());
    }
}

public interface IRunnerListener {
    public void finished(Component component);
}
```

### Steps to reproduce

1. Add the TestLayout above to a view
2. Click the "Add grid" button
3. See the empty grid and the error in the browser's console

### Environment

Vaadin version: 24.1.7
JDK version: 17.0.8.101
OS: Windows 10 Pro
The 3 browsers I tried are Chrome, Firefox, and Edge.

### Browsers

Chrome, Firefox, Edge

**Comment by ugur-vaadin** [comment]
See: Another [issue](https://github.com/vaadin/flow-components/issues/5480) with probably the same root cause.
