### ISSUE TITLE
When sorting a grid with multisort from the backend and hiding a column, the sort order indicator is not updated correctly.

### ISSUE THREAD

**Issue by jencal-essers** [vaadin/flow-components#5513]
### Description

When sorting a grid with multisort from the backend and hiding a column, the sort order indicator is not updated correctly.
The indicator shows that the only applied sort, has order 2.

### Expected outcome

The sort order indicator shows order number 1 or no number.

### Minimal reproducible example

In the bookstore example 
https://github.com/jencal-essers/bookstore-example-sort-order-bug/commit/985b5b1225584732c698439273f246b4efa640dc

### Steps to reproduce

* run the bookstore example (mvn)
* login as admin
* navigate to inventory
* Click the sort 1 button
* Click the sort 2 button 

### Environment

Vaadin version(s): 24.1.12
OS: Windows in wsl ubuntu

### Browsers

Issue is not browser related

**Comment by vursen** [comment]
Confirmed that the issue is reproducible in the latest 24.3. 

Note, the example project is missing `grid.setMultiSort(true, MultiSortPriority.APPEND)`, and the "Sort 2" button isn't added to the page.

**Comment by vursen** [comment]
Here is a more streamlined example for reproduction:

```java
@Route("grid")
public class GridView extends Div {

    public static class Product {

        private final String product;
        private final double price;

        public Product(String product, double price) {
            this.product = product;
            this.price = price;
        }

        public String getProduct() {
            return product;
        }

        public double getPrice() {
            return price;
        }
    }

    public GridView() {
        Grid<Product> grid = new Grid<Product>();
        Grid.Column<Product> product = grid.addColumn(Product::getProduct).setHeader("Product").setSortable(true);
        Grid.Column<Product> price = grid.addColumn(Product::getPrice).setHeader("Price").setSortable(true);

        grid.setMultiSort(true);
        grid.setItems(
                new Product("iPhone", 599.99),
                new Product("iPad", 899.99),
                new Product("MacBook", 1299.99));

        Button sort1 = new Button("sort1");
        sort1.addClickListener(event -> {
            grid.sort(GridSortOrder.asc(product)
                    .thenAsc(price).build());
            price.setVisible(true);
        });

        Button sort2 = new Button("sort2");
        sort2.addClickListener(event -> {
            grid.sort(GridSortOrder.asc(product).build());
            price.setVisible(false);
        });

        add(grid, sort1, sort2);
    }
}
```

**Comment by vursen** [comment]
What happens here is that the sort column gets hidden before its direction property is updated to `null`. When the direction property changes on a hidden sort column, the column doesn't dispatch a `sorter-changed` event. This in turn results in `GridSorterMixin` not updating the sort order indicators.

**Comment by vursen** [comment]
This issue raises a more general question whether hidden sort columns should participate in the sorting or not. 

In the current implementation, sort columns continue participating in the sorting after they get hidden, but their behavior somewhat changes. For instance, they stop notifying the grid about `direction` property changes, which causes issues like the one described in this ticket. The new direction gets applied only when a visible sort column notifies of a change.

- Should sort columns be excluded from the sorting completely when hidden?
- Should sort columns preserve their previous direction while hidden or should they reset it?
- How should sort columns handle direction changes when hidden?
