### ISSUE TITLE
incorrect display of grid rows when sorting ComponentRenderer with Chrome

### ISSUE THREAD

**Issue by gnori-zon** [vaadin/flow-components#5521]
### Description

**incorrect display of grid rows when sorting ComponentRenderer with Chrome (with Edge problem is absent)**

When using sorting, duplicate rows with no "renderer elements" are displayed. And when you select (click the select checkbox) the invalid row, then 2 will be selected, the second one is the original valid row, but the selected quantity is 1

This strange because when using edge this problem is absent!

code: 
```java
grid
    .addColumn(new ComponentRenderer<>((entity) -> {...}))
    .setHeader(VaadinIcon.FILE_TREE.create())
    .setKey("fieldname")
    .setSortProperty("fieldname");
```
_p.s. server loading of objects is used_

### Expected outcome

I think this should work differently (like in edge, i.e. without duplicate empty lines)

### Minimal reproducible example

```java
grid
    .addColumn(new ComponentRenderer<>((entity) -> {...}))
    .setHeader(VaadinIcon.FILE_TREE.create())
    .setKey("fieldname")
    .setSortProperty("fieldname");
```
and vaadin-spring-boot-starter v 22.0.1

### Steps to reproduce

1. Click on the column header with ComponentRender to sort

### Environment

Vaadin version(s): 22.0.1
OS: Windows 10 and Chrome v.117.0.5938.92

### Browsers

Chrome

**Comment by yuriy-fix** [comment]
Dear @gnori-zon, have you had a chance to check if the issue is reproducible in the latest version?

**Comment by gnori-zon** [comment]
@yuriy-fix, no, it wasn't, but I'll try

**Comment by gnori-zon** [comment]
Dear @yuriy-fix! I found the reason for the duplicates. it lies in the fact that when sorting, you must also add an **id** to **setOrderProperty**, thanks to which vaadin can correctly identify the rows in the grid. Problem solved
