### ISSUE TITLE
Tabs with 'equal-width-tabs' theme breaks the layout

### ISSUE THREAD

**Issue by KremnevDmitry** [vaadin/flow-components#5541]
### Description

I'm trying to add `tabs` to the layout, and content that will change depending on the selected tab.
But if I add the `TabsVariant.LUMO_EQUAL_WIDTH_TABS` theme variant, the tabs becomes the wrong height.

This happens if you add the `tab` component to the container with `width=100%` and `height=100%`.

![image](https://github.com/vaadin/flow-components/assets/75516667/c4478bdd-d448-42d1-a6e0-bcdccb5fe890)

### Expected outcome

It was expected that the component would not change its height after adding the style.
Hardcoding the `height` of the `tabs` also did not bring results.

### Minimal reproducible example

```java
        Tab details = new Tab("Details");
        Tab payment = new Tab("Payment");
        Tab shipping = new Tab("Shipping");

        Tabs tabs = new Tabs(details, payment, shipping);
        tabs.setWidthFull();
        tabs.addThemeVariants(TabsVariant.LUMO_EQUAL_WIDTH_TABS);

        HorizontalLayout horizontalLayout = new HorizontalLayout(new Text("Content"));
        horizontalLayout.setAlignItems(Alignment.CENTER);
        horizontalLayout.setJustifyContentMode(JustifyContentMode.CENTER);
        horizontalLayout.setWidthFull();

        setHeightFull();
        add(tabs, horizontalLayout);
        expand(horizontalLayout);
```

### Steps to reproduce

1. Add the snippet above to a view
2. Open the view

### Environment

Vaadin version(s): 
Vaadin: 24.1.10
Flow: 24.1.12
Java: Amazon.com Inc. 19.0.2
OS: amd64 Windows 11 10.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Live reload: Java unavailable (Spring Boot Devtools): Front end active

### Browsers

Issue is not browser related

**Comment by KremnevDmitry** [comment]
# Additional Information:
It looks like the `icon on top` theme doesn't pass theme settings to nested tab.

`icon-on-top` applied to tabs has no effect on the icon position. However, it works for individual tab element.

![image](https://github.com/vaadin/flow-components/assets/75516667/f8c23933-a1de-4486-b14e-e69091d0423b)

**Comment by web-padawan** [comment]
> But if I add the TabsVariant.LUMO_EQUAL_WIDTH_TABS theme variant, the tabs becomes the wrong height.

This is caused by using [`flex: auto`](https://github.com/vaadin/web-components/blob/e0274e8fda6ecdd3c971103bd2c3300b65d274b1/packages/tabs/theme/lumo/vaadin-tabs-styles.js#L178-L181) in `equal-width-tabs` variant. Use `flex-grow: 0` on `vaadin-tabs` to reset it.

> It looks like the icon on top theme doesn't pass theme settings to nested tab.

This is expected, you should set this `theme` attribute on each individual `vaadin-tab` element.

**Comment by KremnevDmitry** [comment]
Thank you for your quick reply!

## For point 1:
Is it expected behavior? Is there any practical meaning in the `flex-grow: 1` property?
Just the name `equal-width-tabs` does not mean that the dimensions of the component can change in height. 

## For point 2: 
`icon on top` theme sets `justify-content: center;`. That's all it does for tabs.
When should the `icon-on-top` theme be placed directly within the `tabs` component?

**Comment by web-padawan** [comment]
> Is it expected behavior? Is there any practical meaning in the flex-grow: 1 property?

As mentioned in the original PR https://github.com/vaadin/vaadin-tabs/pull/78, `flex: 1` is used to ensure tabs are always the same size.


> icon on top theme sets justify-content: center;. That's all it does for tabs.

The `icon-on-top` theme set on `vaadin-tab` element applies the following [styles](https://github.com/vaadin/web-components/blob/2372ed5d0db2b128612646c7e6d47b0efd6c06ed/packages/tabs/theme/lumo/vaadin-tab-styles.js#L169-L188) to the tab and its content.

**Comment by KremnevDmitry** [comment]
OK, thank you!
I think the issue can be closed.
