### ISSUE TITLE
TreeGrid : Wrong initial calculation of hierarchy column width

### ISSUE THREAD

**Issue by SonReimer** [vaadin/flow-components#5595]
### Description

Opening a TreeGrid with all items initially expanded, except for the first not being expanded or having no children, the column width is only as wide as the label of the first item.
This happens when 
- you have the tree grid on the first page an @PreserverOnRefresh annotated and you press F5 or
- you have the treegrid on a page you navigate to

This sounds hard to believe, but it is reproducible.

### Expected outcome

I would expect the column width to be at least as wide as the needed with of the expanded elements. 

### Minimal reproducible example

[example.zip](https://github.com/vaadin/flow-components/files/12999087/example.zip)

### Steps to reproduce

Example:

1. Add the Java-Files to a spring-starter-project (23.3.25)
2. Start the application
3. Open a browser (localhost:8080)
4. -> Tree will be shown expanded
5. Press F5
6. -> Tree will be shown cut off

Alternative scenario:

1. In MainView deactivate
    _@PreserverOnRefresh_ and _add(new PersonGrid());_
2. In MainView activate
    _add(new Button("PersonView", e -> UI.getCurrent().navigate("Person")));_
3. Start the application
4. Open a browser (localhost:8080)
5. Press Person
6. -> Tree will be shown cut off
7. Press F5
8. -> Tree will be shown expanded

Activate the child of the first root item in Class _Person2Grid_ and do both szenarios again.
-> Everything will be fine

### Environment

Vaadin version(s): 23.3.25
OS: Windows

### Browsers

Issue is not browser related

**Comment by SonReimer** [comment]
If I use Vaadin 24.0.2, the issue cannot be reproduced.

**Comment by yuriy-fix** [comment]
We will evaluate the possibility of backporting the fix from the latest version.

**Comment by tomivirkki** [comment]
Even on 24.2, some of the pre-expanded nodes are cut off on refresh

https://github.com/vaadin/flow-components/assets/1222264/d6acae94-112f-414b-a2ee-709d8d2fbcba

**Comment by tomivirkki** [comment]
Fixed by
- https://github.com/vaadin/web-components/pull/6684 (V24)
- https://github.com/vaadin/flow-components/pull/5622 (V23)
