### ISSUE TITLE
Persistent Tooltip in MenuBar

### ISSUE THREAD

**Issue by guttormvik2** [vaadin/flow-components#5614]
### Describe the bug

Given a MenuBar with one MenuItem with a tooltip:

- Hovering over the MenuItem gives the tooltip
- Moving mouse out of the menuItem to the left, right, or up, removes the tooltip
- Moving the mouse down into the tooltip keeps the tooltip open
- Moving the mouse further down, out of the tooltip text does *not* close the tooltip
- Tooltip now stays persistent until I move mouse into the menuItem again and then out

### Expected-behavior

Tooltip should disappear when mouse is moved out of the tooltip again

### Reproduction

```
public PersistentTooltipView() {
    
    var toolbar = new HorizontalLayout();
    var main = new VerticalLayout();
    main.setSizeFull();
    add(toolbar, main);
    
    var menuBar = new MenuBar();
    toolbar.add(menuBar);
    
    menuBar.addItem(VaadinIcon.COG.create(), "This tooltip doesn't disappear when I move mouse down through it and out the other side");
    
}
```

### System Info

Windows 10, Vaadin 24.2, FireFox 118.0.2, Chrome 118.0.5993.89

**Comment by ZheSun88** [comment]
Thanks for the ticket, we will handle this as soon as possible .

**Comment by paodb** [comment]
Issue is also present in **Vaadin 23.3.33**, tooltip doesn't disappear in some cases as seen in attached video taken from [Vaadin23 documentation example](https://vaadin.com/docs/v23/components/menu-bar#tooltips)

![tooltip_test](https://github.com/vaadin/flow-components/assets/30666649/9df32a4e-1e29-42f6-a66e-9f991f13d534)

Doing the same test in Vaadin 24 documentation example shows same behavior.

Seems that using `Tooltip.forComponent(item).withText("Some tooltip")` to define the tooltip prevents this behavior.

**Comment by yuriy-fix** [comment]
This issue has been added to the backlog priority queue for further investigation.
