### ISSUE TITLE
[FormLayout] FormItem requiredIndicator ignores the invalid property

### ISSUE THREAD

**Issue by KremnevDmitry** [vaadin/flow-components#5616]
### Description

When adding a required component to a FormLayout, the `requiredIndicator` is ignored.
This doesn't happen if you add the component directly to the view.

### Expected outcome

Actual:
![image](https://github.com/vaadin/flow-components/assets/75516667/355bd651-aec7-4e49-ab92-041a5a2eed76)

Expected:
![image](https://github.com/vaadin/flow-components/assets/75516667/081a9951-94f3-4f01-9b31-f0488b69a45a)

### Minimal reproducible example

```java
        FormLayout formLayout = new FormLayout();
        formLayout.setResponsiveSteps(
                new FormLayout.ResponsiveStep("0", 1, FormLayout.ResponsiveStep.LabelsPosition.TOP)
        );
        
        // ACTUAL
        EmailField emailField = new EmailField();
        emailField.setInvalid(true);
        emailField.setRequired(true);
        formLayout.addFormItem(emailField, "EmailField");
        
        // EXPECTED
        EmailField emailField2 = new EmailField();
        emailField2.setLabel("EmailField");
        emailField2.setInvalid(true);
        emailField2.setRequiredIndicatorVisible(true);

        add(formLayout, emailField2);
```

### Steps to reproduce

1. Add snippet above to a view
2. Open the view

### Environment

Vaadin version(s): 
Vaadin: 24.1.10
Flow: 24.1.12
Java: Amazon.com Inc. 19.0.2
OS: amd64 Windows 11 10.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Live reload: Java unavailable (Spring Boot Devtools): Front end unavailable

### Browsers

Issue is not browser related

**Comment by yuriy-fix** [comment]
Closing in favour of https://github.com/vaadin/flow-components/issues/1531.
