### ISSUE TITLE
Grids with setAllRowsVisible(true) will render incorrectly as item details in another grid

### ISSUE THREAD

**Issue by sluetge** [vaadin/flow-components#5634]
### Description

I'm using two grids in my view, a main grid with entries and a sub-grid inside a `VerticalLayout` as an `ItemDetailsRenderer`. The main grid contains checkboxes, which trigger a `dataProvider.refreshItem(item)`. When the sub-grid uses `setAllRowsVisible(true)` the currently extended row details will be rendered in the wrong position (shifted up by the height of the table).
Before clicking any checkbox:
![image](https://github.com/vaadin/web-components/assets/105483343/0255beba-2940-49d3-92f3-0c1e82290781)
After:
![image](https://github.com/vaadin/web-components/assets/105483343/805b366a-a964-4a74-8080-b5548f573e1c)
The sub-grid covers up three and a half entries in the main grid (including the original row it belongs under), while leaving blank space where it should be.

### Expected outcome

The sub-grid should render at the correct position.

When using `setAllRowsVisible(false)` (the default), the sub-grid will render correctly.

### Minimal reproducible example

```
@Route("example")
@PermitAll
public class ExampleView extends VerticalLayout {
    public ExampleView() {
        setSizeFull();

        final Grid<Person> grid = new Grid<>(Person.class, false);
        grid.addThemeVariants(GridVariant.LUMO_COMPACT, GridVariant.LUMO_ROW_STRIPES);
        grid.addColumn("email").setHeader("Email");
        grid.addColumn(new ComponentRenderer<>(() -> new Button("Refresh"),
            (button, person) -> button.addClickListener(event -> grid.getDataProvider().refreshItem(person))));
        grid.setHeightFull();
        grid.setItemDetailsRenderer(new ComponentRenderer<>(SubPanel::new,
            ((panel, person) -> panel.setData(person.getSubEntries()))));
        grid.setItems(prepareData());
        add(grid);
    }

    private List<Person> prepareData() {
        return List.of(
            Person.builder().email("user1@example.com").subEntries(List.of(
                SubEntry.builder().id(1).build(), SubEntry.builder().id(2).build()
            )).build(),
            Person.builder().email("user2@example.com").subEntries(List.of(
                SubEntry.builder().id(1).build(), SubEntry.builder().id(2).build()
            )).build(),
            Person.builder().email("user3@example.com").subEntries(List.of(
                SubEntry.builder().id(1).build(), SubEntry.builder().id(2).build()
            )).build(),
            Person.builder().email("user4@example.com").subEntries(List.of(
                SubEntry.builder().id(1).build(), SubEntry.builder().id(2).build()
            )).build(),
            Person.builder().email("user5@example.com").subEntries(List.of(
                SubEntry.builder().id(1).build(), SubEntry.builder().id(2).build()
            )).build()
        );
    }

    public static final class SubPanel extends VerticalLayout {
        private final Grid<SubEntry> grid;

        public SubPanel() {
            setPadding(false);

            grid = new Grid<>(SubEntry.class);
            grid.addThemeVariants(GridVariant.LUMO_COMPACT, GridVariant.LUMO_ROW_STRIPES);
            // Setting this to false will prevent the layout bug, but will waste some amount of space
            grid.setAllRowsVisible(true);
            add(grid);
        }

        public void setData(final List<SubEntry> subEntries) {
            grid.setItems(subEntries);
        }
    }

    @Getter
    @Setter
    @Builder
    public static final class Person {
        private String email;
        private List<SubEntry> subEntries;
    }

    @Getter
    @Setter
    @Builder
    public static final class SubEntry {
        private Integer id;
    }
}
```

### Steps to reproduce

1) Add the above view to an application.
2) Click a row to expand its details.
3) Click the Refresh button of that row.
4) The details will shift upwards.

### Environment

Vaadin version(s): 24.0.14
OS: Windows

### Browsers

Chrome, Firefox

**Comment by yuriy-fix** [comment]
Dear @sluetge, this is not a supported use-case, but would like to leave it open to check if there are any possibilities to make it work possibly with a workaround or internal change.

**Comment by tomivirkki** [comment]
Related https://github.com/vaadin/flow-components/issues/1433

**Comment by sluetge** [comment]
That's unfortunate, as the inner grid wastes a lot of space when setAllRowsVisible is not activated.
Do you happen to have a suggestion how I could solve this differently?
