### ISSUE TITLE
Chart with ChartType Sankey diagram

### ISSUE THREAD

**Issue by imomo0** [vaadin/flow-components#5639]
### Describe your motivation

We need a sankey diagram in our application and it would be great if the chart component would support this type of chart.

### Describe the solution you'd like

That the chart component support this chart type.

### Describe alternatives you've considered

Manually building a custom component for a sankey diagram with either highchart.js or D3.js

**Comment by TatuLund** [comment]
This should be a low hanging fruit as it is already built in in Highcharts. The way our data serialization works in Chart, makes it possible to create a following workaround by extending couple of essential classes.

```
@Route(value = "sankey", layout = MainLayout.class)
public class SankeyView extends Div {
    
    public SankeyView() {
        Chart chart = new Chart(new CustomChartType("sankey"));
        var conf = chart.getConfiguration();
        conf.addSeries(createSankeySeries());
        conf.setTitle("Reporting");
        conf.setSubTitle("data");
        chart.setSizeFull();

        add(chart);
        setWidthFull();
    }

    private static DataSeries createSankeySeries() {
       // TODO
    }

    public static class CustomChartType extends ChartType {
        public CustomChartType(String type) {
            super(type);
        }        
    }

    public static class SankeySeriesItem extends DataSeriesItem {
        private String from;
        private String to;
        private Number weight;

        public String getFrom() {
            return from;
        }
        public void setFrom(String from) {
            this.from = from;
        }
        public String getTo() {
            return to;
        }
        public void setTo(String to) {
            this.to = to;
        }
        public Number getWeight() {
            return weight;
        }
        public void setWeight(Number weight) {
            this.weight = weight;
        }
        
    }
}

```

Full code in my gist

https://gist.github.com/TatuLund/0552d3a7130dfa4a610a29f072e66705

The result

![image](https://github.com/vaadin/flow-components/assets/14309836/e779526f-fa51-4256-b940-f161e6c8e5d8)
