### ISSUE TITLE
Vaadin 24.1.10 -> 24.2.1 update is causing inheritance problems in CustomField

### ISSUE THREAD

**Issue by JohannesLaidler** [vaadin/flow-components#5650]
### Description

After updating from Version `24.1.10` to `24.2.1`, I'm unable to call `super.setReadOnly()` inside `CustomField`.

> Cannot directly invoke the abstract method setReadOnly(boolean) for the type HasValue<AbstractField.ComponentValueChangeEvent<CustomField<String>,String>,String>

That's because in Version 24.2.1 the Mixin Interfaces were moved to the `InputField` interface.

before:
```
public abstract class CustomField<T> extends AbstractField<CustomField<T>, T>
        implements Focusable<CustomField<T>>, HasHelper, HasLabel, HasSize,
        HasStyle, HasTheme, HasTooltip, HasValidationProperties {
[...]
}
```

after:
```
public abstract class CustomField<T> extends AbstractField<CustomField<T>, T>
        implements Focusable<CustomField<T>>, HasHelper,
        InputField<AbstractField.ComponentValueChangeEvent<CustomField<T>, T>, T>,
        HasTheme, HasValidationProperties {
[...]
}
```
```
public interface InputField<E extends HasValue.ValueChangeEvent<V>, V> extends
        HasEnabled, HasLabel, HasSize, HasStyle, HasTooltip, HasValue<E, V> {
}
```

Now `CustomField` implements `HasValue` (from `InputField`) and `HasValueAndElement` (from `AbstractField`), which both contain `setReadonly()`.

Calling super.setReadOnly() now gives a compilation error in Eclipse/VSCode, but when packaging the application with
`mvn package -Pproduction` the application runs without errors.

Example of compilation error in Version `24.2.1`
```
public class TestField extends CustomField<String> {
    private final TextField textField = new TextField("Test");
    
   @Override
    public void setReadOnly(boolean readOnly) {
        textField.setReadOnly(readOnly);

        // does not compile
        super.setReadOnly(readOnly);
    }
}
```

### Expected outcome

I would expect to still be able to call `setReadOnly()` from `HasValueAndElement` inside of `CustomField`, because I want to customize the ReadOnly-behavior of the components inside a `CustomField`.  

Since the `CustomField` is used in a `Binder`, I still want the default behavior from `HasValueAndElement`, which sets the property `readonly` on the `CustomField`.  Setting the property by hand is an option, but any future changes to the default implementation of `setReadOnly`/`isReadOnly `would cause problems with my `CustomFields`.

### Minimal reproducible example

TestView.class
```
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

@Route("test")
public class TestView extends VerticalLayout {

    private static final long serialVersionUID = 1063070440194533837L;

    public TestView() {

        TestField testField = new TestField();

        Button button = new Button("Toggle ReadOnly",
                event -> testField.setReadOnly(!testField.isReadOnly()));

        add(testField, button);
    }

}
```
TestField.class
```
import com.vaadin.flow.component.customfield.CustomField;
import com.vaadin.flow.component.textfield.TextField;

public class TestField extends CustomField<String> {

    private static final long serialVersionUID = 4944062067575958256L;

    private final TextField textField = new TextField("Test");

    public TestField() {
        add(textField);
    }

    @Override
    protected String generateModelValue() {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    protected void setPresentationValue(String newPresentationValue) {
        // TODO Auto-generated method stub
    }

    @Override
    public void setReadOnly(boolean readOnly) {
        textField.setReadOnly(readOnly);
        super.setReadOnly(readOnly);
    }

}
```

### Steps to reproduce

1. Add classes from above to a Vaadin project with Version 24.2.1
2. super.setReadOnly() inside TestField does not compile
3. run mvn package -Pproduction
4. execute jar: java -jar project-name-1.0-SNAPSHOT.jar
5. navigate to localhost:8080/test
6. toggle ReadOnly State

### Environment

Vaadin version(s): 24.2.1
Java: 17
IDE: Eclipse/VSCode
OS: Windows 10

### Browsers

Chrome, Firefox

**Comment by JohannesLaidler** [comment]
CustomField has an additional problem: the read-only property is not synchronized with the client DOM as described in https://github.com/vaadin/flow-components/issues/2953. 
But it was still possible and reliable to confirm the ReadOnly-State by using `isReadOnly()`.

The general inheritance problem also occurs in every field that implements `HasValueAndElement` and `InputField`.
(`TextField`, `TextArea`, `ComboBox`, etc.)

With the new inheritance structure, you cannot extend an existing component and customize its `read-only` behavior.

Here is a simplified example based on the official documentation ([extending component doc](https://vaadin.com/docs/latest/create-ui/creating-components/extending-component)) :
```
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.notification.Notification;
import com.vaadin.flow.component.textfield.TextField;

public class NumericField extends TextField {

    private Button addButton;
    
    public NumericField() {

        addButton = new Button("+");
        addButton.addClickListener(event -> Notification.show("add value"));
        
        addToSuffix(addButton);
    }
    
    @Override
    public void setReadOnly(boolean readOnly) {
        // disable button, if field is readOnly == true
        addButton.setEnabled(!readOnly);

        // does not compile
        super.setReadOnly(readOnly);
    }

}
```

**Comment by yuriy-fix** [comment]
@bennewi, @sosa-vaadin, that is coming from introducing `InputField` interface. Would you be able to address it?

**Comment by Frettman** [comment]
I'm encountering the same issue.

@JohannesLaidler, have you tried compiling it using the regular compiler? E.g. via a local Maven build?

After some experimentation this seems to be a problem of the Eclipse compiler. And AFAIK VSCode uses the Eclipse JDT Language Server, so that would explain why it doesn't work there either.

**Comment by Frettman** [comment]
I'm encountering the same error. Since this seems to be an issue in the Eclipse compiler I created a ticket there: https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1600

**Comment by sissbruecker** [comment]
Closing this as it seems to be an issue in Eclipse, and only affects `setReadOnly`. As a workaround, `super.setReadOnly(readOnly)` can be replaced with:
```java
getElement().setProperty("readonly", readOnly);
```

We can revisit this if it turns out that more APIs are affected.

**Comment by rolpaul** [comment]
Thanks @sissbruecker, we ran into this just yesterday.
Another workaround is to repeat the interface HasValueAndElements (with generics, therefore ugly) or - easier - create and use your own subclass of CustomField like this:

```
public abstract class MyCustomField<T> extends CustomField<T>
        implements HasValueAndElement<AbstractField.ComponentValueChangeEvent<CustomField<T>, T>, T> {
    // empty
}
```
