### ISSUE TITLE
Flow Spreadsheet ignores numeric conditional formatting - regression from v8

### ISSUE THREAD

**Issue by WoozyG** [vaadin/flow-components#5651]
### Description

CustomDataFormatter has some incorrect logic for numbers, that can ignore conditional formatting, while conditional formatting is correctly applied in some cases, primarily where the base cell format is "General".

In particular, the code and behavior do not match the JavaDoc for `CustomDataFormatter.formatCellValue(Cell, FormulaEvaluator, ConditionalFormattingEvaluator)`

The JavaDoc indicates the default behavior is only changed if the formatting contains >=3 segments, but that's not how it behaves.

See the included sample project, and compare the display in Excel vs. Vaadin.

the logic calls `super.formatCellValue()` if the cell's base format is `General`, but that isn't correct.  It should find any conditional format applied, and prefer its format.

Then later, if the cell type is NUMERIC, it should only call `formatNumericValueUsingFormatPart` if the resolved format string actually has enough parts, otherwise just use the default `super` behavior.

I think for now I may have to just eliminate use of `CustomDataFormatter`.  We don't have users with multiple locales, so for now that would be OK, but I'm sure other customers would not have that option. 

### Expected outcome

number formatting in Vaadin would match number formatting in Excel for conditionally formatted cells with a basic base number format that isn't "General"

### Minimal reproducible example

https://github.com/WoozyG/sheet-tables latest commit

### Steps to reproduce

check out and run the specified test project based on Vaadin Start.  Compare the 2nd sheet displayed values with the project XLSX file opened in Excel, and notice that the last column in the table should be formatted with one decimal place, but is not in Vaadin.

### Environment

Vaadin version(s):  tested 24.2.1, probably applies 24+
OS: N/A

### Browsers

Issue is not browser related

**Comment by WoozyG** [comment]
This also affects `CellValueManager.onCellvalueChange()` which creates a new `CustomDataFormatter` to format the evaluated number and set the cell value accordingly.  This runs the risk of retaining the wrong precision if it uses the wrong format.  For that matter, cell values typically shouldn't be formatted along the way specifically because that can lose precision.  Excel tracks full precision, even if it only displays truncated or rounded values.

**Comment by WoozyG** [comment]
There is no way to substitute or avoid the constructor call to CustomDataFormatter in CellValueManager, so I can't fully avoid this bug after all.

**Comment by WoozyG** [comment]
What's more, `CellValueManager.updateLocale()` _recreates_ the formatter value on every call, and is called from `Spreadsheet.onAttach()`.  So even though it exposes a `setDataFormatter()` method, it's useless, as the value is overwritten once the component is attached to a UI.

`updateLocale()` should further only take action if the new locale is different than the current one, and then needs a way to create an instance of the desired DataFormatter subclass.  I should be able to for example subclass Spreadsheet and specify a `createDataFormatter()` override or some such, which would then be used by any code that wants to recreate the retained instance.

**Comment by WoozyG** [comment]
Also, `updateLocale()` can change the private fields `originalValueDecimalFormat` and `localeDecimalSymbols` but nothing else can.  But the constructor and doesn't set these based on the current UI, if there is one, meaning the original values may not match the initial DataFormatter created in the constructor.

**Comment by bwajtr** [comment]
> This also affects `CellValueManager.onCellvalueChange()` which creates a new `CustomDataFormatter` to format the evaluated number and set the cell value accordingly. This runs the risk of retaining the wrong precision if it uses the wrong format. For that matter, cell values typically shouldn't be formatted along the way specifically because that can lose precision. Excel tracks full precision, even if it only displays truncated or rounded values.

Thanks for further investigation into this issue. However, I don't see the creation of a new `CustomDataFormatter` in `onCellValueChange()` - can you maybe please point me to a line that you have in mind?
Nevertheless, Excel does not track _full_ precision but actually truncates numbers to 16 digits (entering "=0,123456789012345678" to a cell in Excel 2019 results to "=0,123456789012345" being in the cell). There is  `CellValueManager.EXCEL_FORMULA_BAR_DECIMAL_FORMAT` which should probably handle this behavior, but number formatting in the Formula Bar seems really to misbehave in `Spreadsheet`. It seems to me that the original precision is kept in the background, but what is shown in the Formula bar does not reflect that -> I'll create a new bug for this, because it seems it's a larger topic.

**Comment by bwajtr** [comment]
> There is no way to substitute or avoid the constructor call to CustomDataFormatter in CellValueManager, so I can't fully avoid this bug after all.

If I'm not mistaken, you can completely substitute `CustomDataFormatter` with your own implementation because all the mentioned methods are protected. You can also override `updateLocale` and provide your own logic there:

```java
public class CustomSpreadsheet extends Spreadsheet {

    public CustomSpreadsheet(InputStream stream) throws IOException {
        super(stream);
    }

    @Override
    protected CellValueManager createCellValueManager() {
        return new CustomCellValueManager(this);
    }

}

class CustomCellValueManager extends CellValueManager {

    public CustomCellValueManager(CustomSpreadsheet customSpreadsheet) {
        super(customSpreadsheet);
        setDataFormatter(new DataFormatter(UI.getCurrent().getLocale()));
    }

    @Override
    protected void updateLocale(Locale locale) {
        super.updateLocale(locale);
        setDataFormatter(new DataFormatter(UI.getCurrent().getLocale()));
    }
}
```

**Comment by bwajtr** [comment]
> Also, `updateLocale()` can change the private fields `originalValueDecimalFormat` and `localeDecimalSymbols` but nothing else can. But the constructor and doesn't set these based on the current UI, if there is one, meaning the original values may not match the initial DataFormatter created in the constructor.

That is totally true... all those locale-specific fields should be always set all at once. I also agreethat there is no way, how to set `localeDecimalSymbols` or `originalValueDecimalFormat` when you override `updateLocale`. I'd say that when `updateLocale` is protected, then you should also have `protected` access to those two fields. I'll try to address that in separate PR.

**Comment by WoozyG** [comment]
Did #5725 also fix the original issue, of numbers not formatting properly?
