### ISSUE TITLE
Exception on MenuItem click when keepOpen=true and dividers exist in the subMenu

### ISSUE THREAD

**Issue by yuriy-khrebtov** [vaadin/flow-components#5653]
### Description

I create a MenuBar with one root item, several checkable subitems and a divider in the submenu of root item. When I click (check) on items which are placed after the divider, I get "Uncaught TypeError":
![image](https://github.com/vaadin/flow-components/assets/142792860/b273ee9c-4df8-409a-a557-bb6dbbc1dbec)

### Expected outcome

No exception raised

### Minimal reproducible example

@PageTitle("Hello World")
@Route(value = "hello", layout = MainLayout.class)
@RouteAlias(value = "", layout = MainLayout.class)
public class HelloWorldView extends HorizontalLayout {

    public HelloWorldView() {
        MenuBar menuBar = new MenuBar();
        MenuItem rootItem = menuBar.addItem("Root");
        SubMenu subMenu = rootItem.getSubMenu();
        createItem(subMenu, "item 1");
        createItem(subMenu, "item 2");
        subMenu.add(new Hr());
        createItem(subMenu, "item 3");
        createItem(subMenu, "item 4");

        add(menuBar);
    }

    private void createItem(SubMenu subMenu, String text) {
        MenuItem item = subMenu.addItem(text);
        item.setCheckable(true);
        item.setChecked(false);
        item.setKeepOpen(true);
    }
}

### Steps to reproduce

1. Create view as in the example
2. Run app, go to the view
3. Click on item 4

### Environment

Vaadin version(s): 24.2.0
OS: Windows 10

### Browsers

Chrome

**Comment by web-padawan** [comment]
Confirmed the issue with the web component. The reason is that we check for [list-box items](https://github.com/vaadin/web-components/blob/b807013acea76779beaedf7aa0d8175a15b7a1b6/packages/context-menu/src/vaadin-contextmenu-items-mixin.js#L317) using `index` from the menu items, and in case of list-box `items` does not contain separators. I will create a PR to use `listBox.children` instead.
