### ISSUE TITLE
Combo box component not functioning properly with case sensitive selections

### ISSUE THREAD

**Issue by Sam-k-Elliott** [vaadin/flow-components#5714]
### Description

When adding a combo box component with items that are case-sensitive selecting an item will always default to the case-insensitive version at the top of the list.

With two options:
```
test
TEST
```

Opening the drop down and selecting `TEST` will set the value to `test`

This only occurs if the combo box is not filtered.  If the combo box is filtered with text the combo box behaves as expected.

### Expected outcome

When selecting an item from the combo box drop down the item that is selected should be set as the value.

### Minimal reproducible example

Kotlin Example:
```
class TestPage(
) : HorizontalLayout() {

    var comboBox = ComboBox<String>().apply {
        this.setItems(
            listOf(
                "thisisatest",
                "THISISATEST"
            ))
    }

    init {
        this.add(comboBox)
    }
}
```

### Steps to reproduce

1. Add the combo box as described above to a view
2. Navigate to the view
3. Open the drop down and select `THISISATEST`
4. Observe that `thisisatest` is set as the value
5. Refresh the view
6. Filter the combo box to `this`
7. selected `THISISATEST`
8. observe the correct value is set

### Environment

Vaadin version(s): 23.3.6, confirmed with vaadin support also 23.3.27 and 24.2
OS: Windows

### Browsers

Chrome

**Comment by knoobie** [comment]
Did you confirm it with the latest 24.2.3? In 24.2.2 was a fix that is similar to this.

**Comment by tomivirkki** [comment]
Fixed by https://github.com/vaadin/web-components/pull/6786
