### ISSUE TITLE
HasMenuItems should be able to reorder menu items

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow-components#5718]
### Describe your motivation

When migrating from Vaadin 8, it's virtually impossible to replicate the old `MenuBar.addItemBefore()` functionality, which allowed to insert a menu item before some other menu item.

### Describe the solution you'd like

It would be good to have either

* a way to reorder menu items after they have been inserted, or
* the `HasMenuItem.addItemBefore()` function

**Comment by web-padawan** [comment]
Closing in favor of #6029 which is a duplicate (and contains a workaround).
