### ISSUE TITLE
Spreadsheet:  Incorrect number formatting in formula - locale and precision is lost

### ISSUE THREAD

**Issue by bwajtr** [vaadin/flow-components#5731]
### Description

When you enter a number with lots of digits to the cell, then the actual value of the number is truncated by `CellValueManager.EXCEL_FORMULA_BAR_DECIMAL_FORMAT`. That is very similar behavior as in Excel 2019, where the number is trucated so it has 16 digits (entering `=0,123456789012345678` to a cell in Excel 2019 turns into `=0,123456789012345` in the formula bar).

This behavior works correctly in `Spreadsheet` only when you enter a plain number to a cell (as shown in the first part of the video). Once you enter the number as a formula (with a leading `=`), then strange things start to happen. The value in the cell is displayed correctly, but when you go to the formula bar then:
1. The number is truncated to only three decimal places in the formula bar. So the precision is lost - you cannot edit the original number!
2. Select the cell and go to another sheet, then return back -> suddenly, the number in the formula bar has the original precision, but it's not formatted using the current UI locale!

See it on this video:

https://github.com/vaadin/flow-components/assets/1890879/854963f9-d0ab-4156-bc9a-fb0414a707c8

### Expected outcome

I'd expect numbers, that are part of formulas, to be always formatted using the current UI locale and I'd expect, that the numbers in the formula bar show maximum possible precision - regardless of whether they are part of a formula or not

### Minimal reproducible example

See the behavior on the attached video

### Steps to reproduce

See the behavior on the attached video

### Environment

Vaadin version(s): 24.3
OS: MacOs
Not browser related

**Comment by ugur-vaadin** [comment]
This can be broken down into two separate issues:
- formula bar displaying the number using the wrong locale when the cell is selected using the address field
- the formula field displaying a truncated number when the number is set using a formula (=...)

There is a [PR](https://github.com/vaadin/flow-components/pull/6208) that should fix the first issue. The second one is still unsolved.
