### ISSUE TITLE
TextField value is not updated before click shortcut in IOS devices

### ISSUE THREAD

**Issue by onuridrisoglu** [vaadin/flow-components#5733]
### Description

In the HelloWorld example if I trigger the button clicking via enter key in the virtual keyboard, the value entered into the textfield is not taken into account, because it's updated after the click handler code is processed.

It works fine in desktop, but problem only exists in Safari in IOS devices. I tried both with iPad and iPhone. 
 
<img width="1074" alt="Screenshot 2023-11-16 at 12 21 50" src="https://github.com/vaadin/flow-components/assets/33827141/a58e5896-3777-4afa-8041-e816682583d7">

### Expected outcome

The textfield value is updated just like in desktop

### Minimal reproducible example

Hello world example can be used:

```
 public MainView(@Autowired GreetService service) {

        // Use TextField for standard text input
        TextField textField = new TextField("Your name");
        textField.addThemeName("bordered");

        // Button click listeners can be defined as lambda expressions
        Button button = new Button("Say hello",
                e -> Notification.show(service.greet(textField.getValue())));

        // Theme variants give you predefined extra styles for components.
        // Example: Primary button has a more prominent look.
        button.addThemeVariants(ButtonVariant.LUMO_PRIMARY);

        // You can specify keyboard shortcuts for buttons.
        // Example: Pressing enter in this view clicks the Button.
        button.addClickShortcut(Key.ENTER);

        // Use custom CSS classes to apply styling. This is defined in
        // shared-styles.css.
        addClassName("centered-content");

        add(textField, button);
    }
```

### Steps to reproduce

1. Open the application in an IOS device
2. Type "onur" for the name field
3. Press the enter key in iPad/iPhone keyboard
4. See that notification say "Hello anonymous user" instead of "Hello onur"

### Environment

Vaadin version(s): 23.3.27
OS: Server runs on MacOS 14.1 and Clients run on iOS 17.1.1 and iOS 16.7.2

### Browsers

Safari on iOS

**Comment by knoobie** [comment]
Sounds related to https://github.com/vaadin/flow/issues/5959

**Comment by yuriy-fix** [comment]
@onuridrisoglu, can we close the issue based on vaadin/flow#5959?
