### ISSUE TITLE
Page down on a grid with filtering

### ISSUE THREAD

**Issue by mgeuer** [vaadin/flow-components#5794]
### Description

As in your filtering example for the grid component (https://vaadin.com/docs/latest/components/grid) when using the page down (or page up) button there are more elements jumped over as shown within the page.
When starting at the top and pressing the down key Anna Myers is selected what is fine to me:
![image](https://github.com/vaadin/flow-components/assets/1890879/74fe35d7-2c33-4136-b855-dbe233b8c8d0)
Pressing again the page down Ryder Turner is selected (and Anna Myers is visible):
![image](https://github.com/vaadin/flow-components/assets/1890879/414f662e-c54a-4fc7-899b-cbe759e5eb40)
Pressing the page down for the third time Jeremiah Foster is selected (Ryder Turner is not visible):
![image](https://github.com/vaadin/flow-components/assets/1890879/aa3c065d-c2a2-4fef-97ff-de8509fa8279)
And going a little bit up we see more names not shown:
![image](https://github.com/vaadin/flow-components/assets/1890879/67a29da3-85ee-4243-afe5-929c7a215cb4)

### Expected outcome

I would have expected to see Ryder Turner or Isaac Jones on top of the grid after pressing the page down for the third time.

### Minimal reproducible example

Please check your code

### Steps to reproduce

I have reproduced it using Chrome (119.0.6045.123) and Firefox (120.0). 

1. Go to the filtering of the grid component https://vaadin.com/docs/latest/components/grid#filtering
2. Press the page down button three times

### Environment

Vaadin version(s): 
OS:

**Comment by yuriy-fix** [comment]
@rolf, whenever <kbd>PageDown</kbd> is pressed following the [documentation](https://vaadin.com/docs/latest/components/grid#cell-focus) (`Moves cell focus down by one page of visible rows`) would it be expected to focus the first item of the next page or the last item of the current page?

In any case the behaviour should probably be consistent regardless of the pressing <kbd>PageDown</kbd> on the first or last visible item.

**Comment by bwajtr** [comment]
@mgeuer I took the liberty to crop the images in the description to increase readability - I hope you don't mind

**Comment by mgeuer** [comment]
@bwajtr that's fine to me ;-)
