### ISSUE TITLE
Splitlayout adds primary/secondary content in reverse order

### ISSUE THREAD

**Issue by erikcsik** [vaadin/flow-components#5799]
### Description

Splitlayout adds primary/secondary content in reverse order in case you add the secondary component first and than the primary.

### Expected outcome

The order of addToPrimary/addToSecondary calls should not matter.

### Minimal reproducible example

        SplitLayout splitLayout = new SplitLayout();
        add(splitLayout);
        splitLayout.addToSecondary(new Button("Secondary"));
        splitLayout.addToPrimary(new Button("Primary"));

### Steps to reproduce

1. Create a new splitlayot.
2. Set secondary component with addToSecondary
3. Set primary component with addToPrimary
4. On the screen the secondary component is going to be placed in the primary slot and the primary component in the secondary slot.

### Environment

Vaadin version(s): 
OS: 23.3.29

**Comment by TatuLund** [comment]
Happens also with 24.3.0.beta1
