### ISSUE TITLE
Support 1password autofill

### ISSUE THREAD

**Issue by muhammetaltindal** [vaadin/flow-components#5811]
### Describe your motivation

1password browser extension allows to autofill. Unfortunately this does not work with the vaadin-password-field component.

I guess it would work once the <input> element would be in the "normal" DOM instead of the shadow root.

https://developer.1password.com/docs/web/compatible-website-design/

### Describe the solution you'd like

When I add a vaadin-password-field, I would like that 1password browser extension is able to autofill passwords.

### Describe alternatives you've considered

```java
@Route("")
public class View extends Div {

  public View() {
    add(new PasswordField());

    var input = new Input();
    input.setType("password");
    add(input);
  }
}
```

Here is an example where the 1password autofill works just fine.
In the case of the simple <input type="password"> it just works fine.

However for vaadin-password-field it does not.

**Comment by web-padawan** [comment]
Could you please clarify which Vaadin version are you using? Since Vaadin 22, we don't place `<input>` in shadow DOM.

**Comment by muhammetaltindal** [comment]
I'm using version 14.10.3

**Comment by web-padawan** [comment]
Thanks. We don't support placing `<input>` elements in light DOM in V14. Consider upgrading to at least Vaadin 23 or 24.
