### ISSUE TITLE
LumoUtility.BoxSizing have incorrect string constants?

### ISSUE THREAD

**Issue by valberico** [vaadin/flow-components#5815]
### Description of the bug

Adding className LumoUtility.BoxSizing.BORDER does not produce expected result of preventing scrollbars.
Manually setting the classNamm as "border-box" achieves the desired result.
It appears that there may be a typo in the string constants.
 public static final class BoxSizing {
   public static final String BORDER = "box-border"; // should be "border-box"
    public static final String CONTENT = "box-content"; // should be "content-box"
    }
https://www.w3schools.com/css/css3_box-sizing.asp

### Expected behavior

Correct string constants should be used for LumoUtility BoxSizing

### Minimal reproducible example

I believe this can be verified by looking at the source code directly.

### Versions

- Vaadin / Flow version: Multiple versions?
- Java version:
- OS version:
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by web-padawan** [comment]
Thanks for the issue. Please note that these constants refer to [CSS class names](https://github.com/vaadin/web-components/blob/25bb2617a12ecdfcacc188fe3d4c16c62a5f0033/packages/vaadin-lumo-styles/utilities/layout.js#L18-L23), not the CSS properties they set. 
While it might look confusing, I believe the reason for this naming to start with `box-` is to make them aligned.
