### ISSUE TITLE
TabSheet: setting an id on a Tab does not work and hangs the view

### ISSUE THREAD

**Issue by jorgheymans** [vaadin/flow-components#5825]
### Description of the bug

When setting an id on a tab, the view will display the loading progress icon forever. Furthermore, the id is overwritten internally in the add() method on TabSheet.

![image](https://github.com/vaadin/flow/assets/193792/6c0a4e25-18fd-433c-8cff-45eeda570fd2)

### Expected behavior

- the page should at least load.
- the id that is set should not be overwritten in the `add()` method.

### Minimal reproducible example

```
@PageTitle("Hello World")
@Route(value = "hello")
@RouteAlias(value = "")
public class HelloWorldView extends HorizontalLayout {

  public HelloWorldView() {
    Tab myTab = new Tab("the tab");
    TabSheet myTabSheet = new TabSheet();
    myTabSheet.add(myTab, new Span("content"));
    // remove below line to make it work
    myTab.setId("new-id");
    add(myTabSheet);
  }
}
```

### Versions

Flow: 24.2.4
Vaadin: 24.2.5
Java: JetBrains s.r.o. 17.0.9
OS: amd64 Linux 6.2.0-37-generic
Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0
Live reload: Java active
          (Spring Boot Devtools): Front end active

**Comment by yuriy-fix** [comment]
Dear @jorgheymans, are you applying id for testing purposes?
The `id` is used for association between content and tab causing this issue.
`setId` should be overridden and have a proper documentation or exception thrown.

**Comment by tomivirkki** [comment]
We could fix this by not [forcing an auto-generated id](https://github.com/vaadin/flow-components/blob/34b9397a953776e31c9e04816bff0f112dfefc3e/vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/TabSheet.java#L143-L144) for a `Tab` in `TabSheet` in case an id has already been provided by the user.

The id generating logic should probably be moved to `beforeClientResponse` because the user may add or remove the `Tab`'s id dynamically.

**Comment by knoobie** [comment]
> are you applying id for testing purposes?

Yes, he did exactly that. The question came up in discord from him

**Comment by jorgheymans** [comment]
- for testing purposes
- but also i'm using it to detect when a tab has been selected i.e. it is the active tab on screen. And the reason why i need to do this if you will ask, is because tab A should display a popup if a value in tab B has changed. But only if tab A is currently visible on screen.   
```
  @Override
  public void onComponentEvent(TabSheet.SelectedChangeEvent event) {
    isThisTabVisible =
        event.getSelectedTab().getClassNames().stream()
            .anyMatch(n -> n.equals("MY_TAB_ID"));
  }
```
