### ISSUE TITLE
24.2.5 Cannot select text in a TextField located in a FormItem

### ISSUE THREAD

**Issue by jflamy** [vaadin/flow-components#5829]
### Description

In the following form layout snippet
![image](https://github.com/vaadin/flow-components/assets/678663/5c608b02-1832-45c8-ac12-4420b838dd86)
it is impossible to select text in any of the text fields.  Clicking in the field brings the cursor at the end of the text, and only backspacing is possible.

There is no focusListener().

This worked normally in version 24.1 and all previous versions.
In the same application, other form layouts work.  I observe that the form layouts that work have the form item labels above and not to the side.

### Expected outcome

It should be possible to use the mouse to select the text in the text fields.

### Minimal reproducible example

I have no clue whether there is a parameter to trigger this "no selection" behavior.
There is no focusListener().
The (unchanged from version 24.1.12) source code is at https://github.com/jflamy/owlcms4/blob/v24/owlcms/src/main/java/app/owlcms/nui/shared/NAthleteRegistrationFormFactory.java

The code that creates the field is 
```
		this.lastNameField = new TextField();
		bindField(this.binder.forField(this.lastNameField), this.lastNameField, Athlete::getLastName, Athlete::setLastName);
		this.lastNameField.setSizeFull();
		layoutAddFormItem(layout, this.lastNameField, Translator.translate("LastName"));
```
and the insertion in the form layout is simply trying to right-align a fake label.
```
		Div label = new Div();
		label.setText(translate);
		label.getStyle().set("text-align", "right");
		FormItem fi = layout.addFormItem(field, label);
```

### Steps to reproduce

No idea where to start.  This looks like behavior internal to the component that I don't know how to trigger.

### Environment

Vaadin version(s): 24.2.5
OS: Windows

Works fine in 22.1.12.

### Browsers

Chrome, Firefox, Edge

**Comment by TatuLund** [comment]
Is your form inside a Dialog? If yes then it is regression from this https://github.com/vaadin/web-components/pull/6850

The fix has been reverted and if you update to 24.2.6 your issue should not appear there.

**Comment by jflamy** [comment]
Yes it was in a dialog, and text fields outside of dialogs did keep working.
Moving to 24.2.6 does indeed fix it.  Let's hope it doesn't break something else...

**Comment by web-padawan** [comment]
Thanks for confirmation. Closing the issue.
