### ISSUE TITLE
ComboBox with custom renderer shows stale items before query finishes

### ISSUE THREAD

**Issue by drewharvey** [vaadin/flow-components#5830]
### Description

When using a custom renderer with a ComboBox, when you open the dropdown you can see stale items before the fetch completes.  In my current project, we've run into multiple situations where this confuses users.

![combobox-stale-render](https://github.com/vaadin/flow-components/assets/2496955/2f6ee1f2-d115-434c-9376-105a350e0dbb)

### Expected outcome

If you do not use a renderer, the prev items are cleared when the dropdown is opened which I would expect to happen with a custom renderer as well.

### Minimal reproducible example

```
var cb = new ComboBox<Person>();
cb.setRenderer(item -> return new new Span(item.getFirstName() + " " + item.getLastName()));
cb.setItems(generateLargePersonBeanList());
```

### Steps to reproduce

1. add above snippet to view
2. open combobox and filter list, scroll down a bit 
3. close combobox
4. open again
5. while the fetch is completing (spinner at top right), you'll be able to see items from your previous filtered list (probably just a split second, longer fetches/slow connection makes longer)

### Environment

Vaadin version(s): 23.3.29
OS: Mac

### Browsers

Chrome, Firefox

**Comment by TatuLund** [comment]
This does not happen with Vaadin 24.3.0

**Comment by rolfsmeds** [comment]
This issue has been added to our backlog for further investigation.

**Comment by ugur-vaadin** [comment]
This issue was fixed and the fix will be available with the next release.
