### ISSUE TITLE
Clicking the stepper buttons won't fire a value change event for an IntegerField, if ValueChangeMode.EAGER is set

### ISSUE THREAD

**Issue by mlindfors** [vaadin/flow-components#5863]
### Description

If you set the value change mode of an IntegerField to be `ValueChangeMode.EAGER`, clicking the stepper buttons won't fire the server side value change listener.

### Expected outcome

When stepping the value, the value change listener should fire.

### Minimal reproducible example

Simply add the following to a view:
```java
IntegerField intfield = new IntegerField();
intfield.setStepButtonsVisible(true);
intfield.setValueChangeMode(ValueChangeMode.EAGER);
intfield.addValueChangeListener(event -> System.out.println("IntegerField value changed!"));
add(intfield);
```

### Steps to reproduce

1. add the snippet above to a view
2. click the stepper buttons to change the value
3. observe the logs to see that the value change event is not firing
4. for posterity you can also just manually type the value into the field, and see that the value change event is fired eagerly

### Environment

Vaadin version(s): 24.3.1
OS: macOS Sonoma 14.2

### Browsers

Issue is not browser related

**Comment by vursen** [comment]
It's a regression from https://github.com/vaadin/flow-components/pull/5592.

**Comment by vursen** [comment]
The reason is that the web component doesn't fire an `input` event on stepper button click. Since #5593, the Flow counterpart listens to input events to synchronize the value in eager mode.
