### ISSUE TITLE
Vaadin Grid Scrolling Issue

### ISSUE THREAD

**Issue by DarioViva42** [vaadin/flow-components#5865]
### Description

When I have a Grid with a lot of Items (Paged) and a user is scrolling really fast, because for example he wants to look at the last elements, I get an Exception thrown. 
> 2023-12-19T17:27:14.987+01:00  WARN 19368 --- [nio-8081-exec-8] c.v.flow.data.provider.DataCommunicator  : Attempted to fetch more items from server than allowed in one go: number of items requested '19100', maximum items allowed '500'.

This results in not all element being loaded, only the first 500 Elements get fetched. My Page Size is 50. So 10 Pages get fetched, but the rest is blocked. The user that scrolled too fast is presented with an empty looking grid.

It seems to work better (or rather worse) the more elements that can be shown in the grid. Also I artificially timeout in the demo, to simulate slower read times from different servers.
In the Demo Project that I have linked to, the bug is not as reliable as in my real project, there I have a lot more data. But with enough scrolling and patience it can be reproduced.

I tried to continue my search on the client side, and it looks to me, that a unordered list in the gridConnector.js seems to be a problem.

Well last time I checked this was the problem. The index property on the elements in the visibleRows array were not ordered.
```js
let start = visibleRows.length > 0 ? visibleRows[0].index : 0;
let end = visibleRows.length > 0 ? visibleRows[visibleRows.length - 1].index : 0;
```
But now I checked again and this does not seem to be the origin of the problem.
![image](https://github.com/vaadin/flow-components/assets/45972949/f0457fb4-9a70-4dba-9d52-194162aba8ce)
As you can see, the breakpoint is configured to only stop when ve is greater than 10.
When the code breaks on this conditional breakpoint, we can know, that the server will run into an exception, as ve is not allowed to be greater than 10
This state is immediately fallowed by this exception on the server:
![image](https://github.com/vaadin/flow-components/assets/45972949/cec3a3cf-a2e0-424f-a6c3-b46accc95eac)
Because as mentioned above, there is a maximum number of pages that is allowed to being fetched.
```java
private int getMaximumAllowedItems() {
        return Math.max(500, 10 * this.pageSize);
}
```
Hopefully this helps analyse the problem better.
The Code uses cryptic variable names, as somehow I was not able to turn of frontend minimization (I know that I was able to do this at some point in time, but either I forgot or its not possible anymore)
This is the source:
```js
grid.$connector.fetchPage = tryCatchWrapper(function (fetch, page, parentKey) {
          // Determine what to fetch based on scroll position and not only
          // what grid asked for

          // The buffer size could be multiplied by some constant defined by the user,
          // if he needs to reduce the number of items sent to the Grid to improve performance
          // or to increase it to make Grid smoother when scrolling
          const visibleRows = grid._getRenderedRows();
          let start = visibleRows.length > 0 ? visibleRows[0].index : 0;
          let end = visibleRows.length > 0 ? visibleRows[visibleRows.length - 1].index : 0;
          let buffer = end - start;

          let firstNeededIndex = Math.max(0, start - buffer);
          let lastNeededIndex = Math.min(end + buffer, grid._flatSize);

          let firstNeededPage = page;
          let lastNeededPage = page;
          for (let idx = firstNeededIndex; idx <= lastNeededIndex; idx++) {
            const { cache, index } = dataProviderController.getFlatIndexContext(idx);
            // Try to match level by going up in hierarchy. The page range should include
            // pages that contain either of the following:
            //   - visible items of the current cache
            //   - same level parents of visible descendant items
            // If the parent items are not considered, Flow would remove the hidden parent
            // items from the current level cache. This can lead to an infinite loop when using
            // scrollToIndex feature.
            const sameLevelPage = grid.$connector._getSameLevelPage(parentKey, cache, index);
            if (sameLevelPage === null) {
              continue;
            }
            firstNeededPage = Math.min(firstNeededPage, sameLevelPage);
            lastNeededPage = Math.max(lastNeededPage, sameLevelPage);
          }

          let firstPage = Math.max(0, firstNeededPage);
          let lastPage =
            parentKey !== root ? lastNeededPage : Math.min(lastNeededPage, Math.floor(grid.size / grid.pageSize));
          let lastRequestedRange = lastRequestedRanges[parentKey];
          if (!lastRequestedRange) {
            lastRequestedRange = [-1, -1];
          }
          if (lastRequestedRange[0] != firstPage || lastRequestedRange[1] != lastPage) {
            lastRequestedRange = [firstPage, lastPage];
            lastRequestedRanges[parentKey] = lastRequestedRange;
            let count = lastPage - firstPage + 1;
            fetch(firstPage * grid.pageSize, count * grid.pageSize);
          }
});
```

### Expected outcome

No matter how fast the user scrolls, he / she will always see the elements he wants to see. When he / she scrolls all the way to the bottom of the page, he / she wants to see the last elements.
Of course the user could scroll up a little and then down again, but this is still an inconvenience.

### Minimal reproducible example

Have a look at the fallowing project (reproducible example):

https://github.com/DarioViva42/grid-scrolling-error

There are already 1000 pages of data as an example. Of course in real project the data source is not from files but this is just for demonstrating purposes.
Note: When you want to have more pages, just use the create endpoint with the count query parameter specifying the number of pages (as files) that should be created.

### Steps to reproduce

1. Start the application.
2. Look at the grid.
3. Scroll up and down the grid, very quickly / fast.
4. Look at the log

### Environment

Vaadin version(s): 24.3.1
OS: Windows (probably does not matter)

**Comment by vursen** [comment]
Thanks for your effort in creating a reproduction project. I was able to reproduce the bug.

Looking for any insights, I noticed that `$connector.fetchPage` always ensures that the last requested page is included in the fetched range:

https://github.com/vaadin/flow-components/blob/a1e500699bd3d592f0db593fda8e6eb92953851a/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js#L257

Looks like this method can receive a page that is far beyond the rendered buffer of items. When this happens, the method extends the fetched range up to that page, sometimes becoming larger than the server can handle.

**Comment by vursen** [comment]
Here is a more streamlined reproduction:

```java
@Route("grid")
public class GridView extends Div {
    public GridView() {
        Grid<String> grid = new Grid<>();
        grid.addColumn(item -> item);
        grid.setItems(generateItems(1000));

        Button scrollToEndAndStart = new Button("scroll to end and start", event -> {
            grid.scrollToIndex(1000);
            grid.scrollToIndex(0);
        });

        add(grid, scrollToEndAndStart);
    }

    private List<String> generateItems(int count) {
        return IntStream.range(0, count).mapToObj(i -> "Item " + i)
                .collect(Collectors.toList());
    }
}
```

1. Click on the button "scroll to end and start"
2. See "Attempted to fetch more items from server..., maximum items allowed '500'" error in the server log
