### ISSUE TITLE
The i18n DatePicker input does not work

### ISSUE THREAD

**Issue by moigalrod** [vaadin/flow-components#5874]
### Description

The i18n DatePicker input does not work, without works in DatePicker itself when you use a DatePicker.DatePickerI18n() with the translations, but when you use a "MMMM yyyy" format, the month is still displayed in English and does not respect the translation.

### Expected outcome

I was hoping that with the months translated in DatePicker.DatePickerI18n, it would come out in the language of the translation and not in English.

![image](https://github.com/vaadin/flow-components/assets/11901337/7218519d-db36-4e28-a4d3-78e95d4888b1)

but when I select a date, it appears in English in the input (Format  "MMMM yyyy"):

![image](https://github.com/vaadin/flow-components/assets/11901337/3b46e5ca-c4da-41d5-88d7-8fc2a38fd1c6)

### Minimal reproducible example

   var fileProcessDatePicker = Form.getDatePicker("Fecha", true, false);
        var i18n = CommonComponent.getDatePickerI18n();
        i18n.setDateFormat("MMMM yyyy");
        fileProcessDatePicker.setI18n(i18n);
        add(fileProcessDatePicker, 2);

public static DatePicker getDatePicker(String label, boolean required, boolean widthFull) {
        var datePicker = new DatePicker();
        datePicker.setLabel(label);
        datePicker.setLocale(Locale.FRANCE);
        datePicker.setClearButtonVisible(true);
        datePicker.setRequired(required);
        datePicker.setRequiredIndicatorVisible(required);

        if (widthFull) {
            datePicker.setWidthFull();
        }

        return datePicker;
    }
        
        
    public static final String JANUARY = "Enero";
    public static final String FEBRUARY = "Febrero";
    public static final String MARCH = "Marzo";
    public static final String APRIL = "Abril";
    public static final String MAY = "Mayo";
    public static final String JUNE = "Junio";
    public static final String JULY = "Julio";
    public static final String AUGUST = "Agosto";
    public static final String SEPTEMBER = "Septiembre";
    public static final String OCTOBER = "Octubre";
    public static final String NOVEMBER = "Noviembre";
    public static final String DECEMBER = "Diciembre";
    

public static DatePicker.DatePickerI18n getDatePickerI18n() {
        return new DatePicker.DatePickerI18n()
                .setToday(CONST.TODAY)
                .setCancel(CONST.CANCEL)
                .setFirstDayOfWeek(1)
                .setMonthNames(Arrays.asList(CONST.JANUARY, CONST.FEBRUARY, CONST.MARCH, CONST.APRIL, CONST.MAY,
                        CONST.JUNE, CONST.JULY, CONST.AUGUST, CONST.SEPTEMBER, CONST.OCTOBER, CONST.NOVEMBER,
                        CONST.DECEMBER))
                .setWeekdays(Arrays.asList(CONST.MONDAY, CONST.TUESDAY, CONST.THURSDAY, CONST.WEDNESDAY, CONST.FRIDAY,
                        CONST.SATURDAY, CONST.SUNDAY))
                .setWeekdaysShort(Arrays.asList(CONST.SUNDAY_SHORT, CONST.MONDAY_SHORT, CONST.TUESDAY_SHORT,
                        CONST.WEDNESDAY_SHORT, CONST.THURSDAY_SHORT, CONST.FRIDAY_SHORT, CONST.SATURDAY_SHORT));
    }
    

### Steps to reproduce

Simply by selecting the date in the datePicker it shows in the input the months in English and not in Spanish, which is the translation that I have made of the months.

### Environment

Vaadin version(s): 23.2.0
OS: Windows 10

**Comment by rolfsmeds** [comment]
As specified in the documentation, the date format API currently only supports a limited set of formats:
https://vaadin.com/docs/latest/components/date-picker#using-custom-date-formats-java-only

For moths, that's M and MM.

**Comment by TatuLund** [comment]
Also duplicate of https://github.com/vaadin/flow-components/issues/2665

**Comment by moigalrod** [comment]
Ok, Thank you!
