### ISSUE TITLE
[MenuBarItem] Submenu Items cannot remove class list entries, when they have been set initially

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow-components#5957]
### Description

We have a menu bar with sub menu items as a grid toolbar. Some of the sub menu items get an initial class name (e.g. "inactive"), that shall be removed, when specific grid items are selected. 

It is currently not possible to remove those initial class names from sub menu items in V24. 

Side note: When a class name is set after the initialization, it works. So, for instance, adding the class name on grid selection and removing it afterwards works fine. Also for root items it works as expected in both cases (initially and on selection). 

Using the JS debugger on the respective menu item also shows on the client side, that there are no items in its class list. Checking the menu bar's client side items instead, it shows the items still containing the "inactive" classes despite having them already removed via the api.

<img width="612" alt="image" src="https://github.com/vaadin/flow-components/assets/36725474/0530f47e-763b-4e7b-9520-d5c965a3ca98">

### Expected outcome

Sub menu item class list modification should work always. Changing the class list using the menu bar item api should update the respective items on the client side.

### Minimal reproducible example

```java
MenuBar menuBar = new MenuBar();
MenuItem hello = menuBar.addItem("Hello", event -> Notification.show(event.getSource().getText()));
menuBar.addItem("World", event -> Notification.show(event.getSource().getText()));

SubMenu sub = menuBar.addItem("Sub").getSubMenu();
MenuItem helloSub = sub.addItem("Hello Sub", event -> Notification.show(event.getSource().getText()));
sub.addItem("World Sub", event -> Notification.show(event.getSource().getText()));

ClassList helloClassList = hello.getElement().getClassList();
ClassList helloSubClassList = helloSub.getElement().getClassList();

helloClassList.add("inactive");
helloSubClassList.add("inactive"); // this is the critical point

add(menuBar, new Button("Switch Classes", event -> {
    if (helloClassList.contains("inactive")) {
        helloClassList.remove("inactive");
        helloSubClassList.remove("inactive");

        Notification.show("Activated");
    } else {
        helloClassList.add("inactive");
        helloSubClassList.add("inactive");

        Notification.show("Deactivated");
    }
}));
```

For easier visualization, you may add this css to your styles. 
```css
vaadin-menu-bar-item.inactive {
    color: red;
    opacity: 0.3;
}
```

### Steps to reproduce

1. Create a new app.
2. Create a simple view with the given sample code. Optionally add the css snippet to your styles
3. Open the app. The root item "Hello" and the item "Sub > Hello Sub" are marked as "inactive" via class names. They are slightly red, if the styles are used.
4. Click on the button "Switch classes". 
5. The root item "Hello" should now be shown a a normal active item. Open the "Sub" menu. The "Hello Sub" is still marked as "inactive" and slightly red.

Remove the initial setting of class names. Now it should work as expected with "activating" and "deactivating" of the sub menu item.

### Workaround
For me it works, when I also update the internal item reference:

```java
menuItem.getElement().executeJs("if(this._item) this._item.className = '';");
```

This removes all class names from the item and will show it as "normal". If other class names shall be kept, the string needs to be updated respectively. In some cases you may also need to add it manually (assigning it using the above snippet). 

For the given issue code sample, it needs to be changed like this

```java
...
add(menuBar, new Button("Switch Classes", event -> {
    if (helloClassList.contains("inactive")) {
        helloClassList.remove("inactive");
        helloSubClassList.remove("inactive");

        helloSub.getElement().executeJs("if(this._item) this._item.className = '';");
...
```

### Environment

Vaadin version(s): 24.3.2

### Browsers

Issue is not browser related

**Comment by yuriy-fix** [comment]
Would using `addClassNames` / `removeClassNames` from the `MenuItem` would be sufficient for this use-case? 
Please take a look at https://vaadin.com/docs/latest/components/menu-bar#styling-menu-items

**Comment by stefanuebe** [comment]
It should not as afaik those are just convenience shortcuts to the api I use in my sample, but I test it.

**Comment by stefanuebe** [comment]
Tested it on alpha20 and it still does not work. Neither for a normal submenu nor for the overflow submenu.
