### ISSUE TITLE
How to add listener to the upload component of vaadin 14 When the X button is clicked

### ISSUE THREAD

**Issue by KimlerJin** [vaadin/flow-components#5965]
### Description

When i want delete some file and upload another instead , i can not find the way to realize it since after i click the X button, The file of the background object always exists( When I upload two, delete one, and then upload another, there will be three file objects in the background.) Like this. And the Upload Component do not have the listener of it.

Give me a way to get the exact file uploaded by the user

### Expected outcome

Give me a way to get the exact file uploaded by the user

### Minimal reproducible example

private Upload upload =new Upload();

### Steps to reproduce

Step1:
private Upload upload =new Upload();
upload.setReceiver(new MultiFileUploader());
add(upload )
Step2:
upload the two files by Upload Component in Vaadin view;
Step3:
click X to delete one file 
Step4:
find that deleted files always exist in upload object.
![image](https://github.com/vaadin/flow-components/assets/32951573/2386303f-0102-4bd9-8fb0-de5931fd75a4)
![image](https://github.com/vaadin/flow-components/assets/32951573/ce09fd4f-0a8e-41c0-85b6-e8affeb8f1f9)

### Environment

Vaadin version(s): 14.8.2
OS: windows 10

**Comment by mstahv** [comment]
The Upload component has very limited Java API. If you want to use the "built-in" filelist, this will not be your last issue.

I suggest to basically disable the file list in the Upload. Or technically use it only for progress bars. Then maintain the file list in your UI code and have your own delete button there that actually deletes the file in your filesystem/db. The V14 version of upload don't have proper API to clear the list, but you can just as well re-create the upload in succeeded listener. Or "steal" [the new clearFileList method](https://github.com/vaadin/flow-components/blob/main/vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java#L737-L742).

**Comment by KimlerJin** [comment]
i get the solution in stackoverflow website .
   upload.getElement().executeJs(
                "this.addEventListener('file-remove', (e) => $0.$server.fileRemove(e.detail.file.name));",
                getElement());
and declare a @ClientCallable method fileRemove to remove a file with that name from your storage.

**Comment by yuriy-fix** [comment]
The feature is already available in the latest version. Unfortunately, v14 is not anymore receiving feature updates.
