### ISSUE TITLE
Vaadin Grid errors in console in dev mode for a Flow application

### ISSUE THREAD

**Issue by andersforsell** [vaadin/flow-components#5984]
### Description

I am getting strange behavior of an application's Vaadin grids during development and noted that there are errors in the browser Console window:
[localhost-1706023538002.log](https://github.com/vaadin/flow-components/files/14026427/localhost-1706023538002.log)

The problem does not occur in production mode.
I have tried rebuilding with mvn vaadin:clean-frontend but with no success.

### Expected outcome

No errors in the Console and Vaadin Grid that behaves in dev like in prod.

### Minimal reproducible example

Can try to create if necessary.

### Steps to reproduce

Expand nodes in the tree.

### Environment

Vaadin version(s): 24.3.3
OS: Windows 

### Browsers

Edge

**Comment by sissbruecker** [comment]
@andersforsell Please provide a code snippet or project that reproduces the issue.

**Comment by yuriy-fix** [comment]
Closing as stale. Feel free to re-open if still valid.
