### ISSUE TITLE
Option in MultiSelectCombobox rendered empty or wrong when using ComponentRenderer

### ISSUE THREAD

**Issue by probert94** [vaadin/flow-components#5985]
### Description

I have a MultiSelectCombobox which is used as a "mail to" field. As the options are collapsed when there is not enough space, I always show the selected entries in the drop down. Now sometimes an option renders empty or sometimes even displays another value.
It seems to happen only when using ComponentRenderer, so the issue might be similar to https://github.com/vaadin/flow-components/issues/1304

### Expected outcome

The options should render correctly.

### Minimal reproducible example

```java
public class MainView extends HorizontalLayout {

    private MultiSelectComboBox<String> values;

    public MainView() {
        values = new MultiSelectComboBox<>("Values");
        values.setItems(this::fetch);
        values.setSelectedItemsOnTop(true);
        values.addCustomValueSetListener(e -> {
           String value = e.getDetail();
           if (value != null) {
               ArrayList<String> accounts = new ArrayList<>(values.getValue());
               accounts.add(value);
               values.setValue(accounts);
           }
        });
        values.setRenderer(new ComponentRenderer<>(i -> new Span(i)));

        add(values);
    }

    private Stream<String> fetch(Query<String, String> query) {
        return values.getValue().stream().skip(query.getOffset()).limit(query.getLimit());
    }
}
```

### Steps to reproduce

1. Download a new Vaadin starter and paste the above code into MainView.java
2. Enter 3 custom values into the ComboBox, so that the drop down shows 3 rows.
3. Deselect the second option by navigating down with the arrow keys and pressing "enter"
4. Close the drop down by pressing "escape" twice
5. Reopen the drop down using the arrow down key

https://github.com/vaadin/flow-components/assets/18258317/baf173cc-e5db-4c50-8d3f-60cd8a40d232

### Environment

Flow: 24.3.3
Vaadin: 24.3.3
Java: Eclipse Adoptium 17.0.6
OS: amd64 Windows 11 10.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

### Browsers

Issue is not browser related

**Comment by ugur-vaadin** [comment]
It looks like the node IDs for selected items are not properly updated.
