### ISSUE TITLE
Grid Multiselect acting strange.

### ISSUE THREAD

**Issue by cyckim** [vaadin/flow-components#5986]
Hello, 

I was using vaadin 24.2.5 and have grid with multiselect functionallity and ListDataProvider, DB is mysql.
Basically my grid is listing data, which can be selected/deselected. When im selecting or deselecting then im updating boolean flag in db true/false.

Im catching selected/deselected rows in:

    private void selectUnselectMethod(SelectionEvent<Grid<SomeModel>, SomeModel> event) {
       MultiSelectionEvent<Grid<SomeModel>, SomeModel> multiSelectionEvent =
            (MultiSelectionEvent<Grid<SomeModel>, SomeModel>) event;
 
      processIncludedOrders(multiSelectionEvent);
      processExcludedOrders(multiSelectionEvent);
   }

What else im doing, before enter or after page refresh/page change I have method to select all rows in the grid base on this flag:

    public void reload() {
       super.reload();
       grid.getListDataView().getItems().forEach(item -> {
          if (item.isIncluded()) {
             grid.select(item);
          }
       });
    }

And I checked that until 24.2.X version everything works as expected. When im going to my grid, base on the data from database reload() method is correctly loading data from DB and base on the flag selecting rows. Also selecting/unselecting worked fine, updates on the DB were done correctly.

But since we switched to version 24.3.X, weird things are happening.

Its happening only after getting to the fresh/after F5 refresh. 
Let's say I have 10 rows, 6 rows are selected 4 rows are unselected, I'm clicking to select one more row then Vaadin in unselecting everything, this should not happen, I should have 7 rows selected. After that action everything is unselected but the functionallity is working fine, just these rows are unselected. Seems like multiselect doesnt take into account that when im loading page im doing:

      grid.getListDataView().getItems().forEach(item -> {
         if (item.isIncluded()) {
            grid.select(item);
         }
         
Can you take a look?
Thanks,
Maciej

**Comment by sissbruecker** [comment]
Reproduction:
```java
@Route("repro")
public class Repro extends Div {
    // Use static list as "database"
    private static List<Item> items = generateItems();

    private Grid<Item> grid;

    public Repro() {
        grid = new Grid<>();
        grid.setItems(items);
        grid.addColumn(Item::getName).setHeader("Name");
        grid.setSelectionMode(Grid.SelectionMode.MULTI);
        grid.addSelectionListener(event -> {
            MultiSelectionEvent<Grid<Item>, Item> multiSelectionEvent =
                    (MultiSelectionEvent<Grid<Item>, Item>) event;

            multiSelectionEvent.getAddedSelection().forEach(item -> {
                item.setSelected(true);
                System.out.println(item.getName() + " selected");
            });
            multiSelectionEvent.getRemovedSelection().forEach(item -> {
                item.setSelected(false);
                System.out.println(item.getName() + " deselected");
            });

            String currentSelection = grid.getSelectedItems().stream().map(Item::getName).collect(Collectors.joining(", "));
            System.out.println("New selection: " + currentSelection);
        });
        initialSelection();
        add(grid);
    }

    private void initialSelection() {
        grid.getListDataView().getItems().forEach(item -> {
            if (item.isSelected()) {
                grid.select(item);
            }
        });
    }

    private static List<Item> generateItems() {
        return IntStream.range(0, 100).mapToObj(i -> new Item("Item " + i, false)).toList();
    }

    private static class Item {
        private String name;
        private boolean selected;

        public Item(String name, boolean selected) {
            this.name = name;
            this.selected = selected;
        }

        public String getName() {
            return name;
        }

        public boolean isSelected() {
            return selected;
        }

        public void setSelected(boolean selected) {
            this.selected = selected;
        }
    }
}
```

Steps:
- Select first three items
- Reload page
- First three items are displayed as selected
- Select fourth item
- Only fourth item is displayed as selected

The good thing is that the selection state on the server is preserved, all items are still selected. But the client-side grid loses the selection state and `selectedItems` only contains the last selected item.

For a workaround, call `grid.getListDataView().refreshAll()` in the selection listener.

**Comment by sissbruecker** [comment]
The problem seems to be that the initial selected items are set before the selection mode is initialized / updated to multi-selection. Adding log statements to the connector results in this output on page load:
```
Updating selection [{"key":"1","col0":"Item 0","selected":true},{"key":"2","col0":"Item 1","selected":true},{"key":"3","col0":"Item 2","selected":true},{"key":"4","col0":"Item 3","selected":true},{"key":"5","col0":"Item 4","selected":true}]
gridConnector.ts:860 Selection mode set to SINGLE
gridConnector.ts:860 Selection mode set to MULTI
gridConnector.ts:860 Selection mode set to MULTI
gridConnector.ts:860 Selection mode set to MULTI
```

Changing the selection mode clears `selectedKeys` in the connector, and on the next selection change the selected items of the grid will be cleared as well.
