### ISSUE TITLE
Details should be also configurable as non closeable

### ISSUE THREAD

**Issue by dex-ds** [vaadin/flow-components#5992]
### Describe your motivation

We are migrate von v8 to v24. Details is offered as the "new Panel" (yes this works but...)
Sometimes/temporarly we need a non closeable Details (e.g. for focus important information for users).
The workaround at this time is to use the openChangeListener and open the Details again. (but this isn't nice)
(Maybe there is a smarter workaround?)
So please enhance the Details with a non closeable.

Thank you.
(Maybe there is better way to vote this as prime user? Thanks for any information about that)

### Describe the solution you'd like

Details as non closeable, cant be closed. The toggle and click-event is removed.

**Comment by rolfsmeds** [comment]
Hi @dex-ds, 
`Details` is _not_ a particularly good replacement for the V7/8 `Panel` component. Could you tell me where you got that information from, so I can make sure it's corrected?

We won't be adding a non-closable feature to Details, as the whole point of the component is to provide a collapsible panel.

If I'm understanding you correctly, you basically want a _box_ with a title and a content area. You can achieve this in many different ways, for example like this:
```java
        H3 boxTitle = new H3("Title");
        boxTitle.addClassNames(LumoUtility.Background.CONTRAST_10, LumoUtility.Padding.SMALL);
        Div contentArea = new Div("Example content");
        contentArea.addClassNames(LumoUtility.Padding.SMALL);
        VerticalLayout box = new VerticalLayout(boxTitle, contentArea);
        box.setDefaultHorizontalComponentAlignment(Alignment.STRETCH);
        box.setPadding(false);
        box.setSpacing(false);
        box.addClassNames(LumoUtility.Border.ALL, LumoUtility.BorderColor.CONTRAST_30);
        box.setWidth("400px");
        box.setHeight("300px");
```

**Comment by dex-ds** [comment]
Hi Rolf, thank you very much for your answer.

Thanks also for your tip, but we are able to handle elements like DIV, SPAN and co. here 😉

DETAILS is the "new Panel" => I can't tell you anymore. That would be too much effort to go through all the guides regarding VAADIN 8+ migration again. 

**Because of the DETAILS extension, I am trying to formulate this more clearly now.**

What VAADIN always lacked was a TASKPANE component. From VAADIN 6 to 8, the TASKPANE addon perfectly compensated for this shortcoming. Simply wrap a PANEL => done => simple and perfect.

With DETAILS, this shortcoming is now the other way around. There is still no TASKPANE in VAADIN => DETAILS is in principle perfectly suited to be a TASKPANE, but you can't prevent it from closing.

TASKPANEs have the task of making complex content visible when required without "overloading" an entire page with information, but are still necessary to be available quickly.
In some use cases, however, it is necessary to prevent a TASKPANE from closing, as elementary data needs to be changed or added. The user should not "overlook" this, so to speak.
Changing the container (the TASKPANE) to a "simple panel" (your suggestion) is extremely counterproductive.

The aim of VAADIN is to make UI work easier for developers and to concentrate on content, not to constantly tinker with UI workarounds. Or have I misunderstood something?

cheers, Daniel

This sample shows the DETAILS work as TASKPANE in v24 (with a small customizing for the summary)

![image](https://github.com/vaadin/flow-components/assets/18628242/26ae39d6-cdd6-4a49-9706-05bfbb85fd9e)

**Comment by rolfsmeds** [comment]
Daniel, there is no way Vaadin (or any other framework or component library) can provide a ready-to-use UI feature for _everything_ developers might need. There will _always_ be things you need to by "tinkering". As you say you are able to handle HTML elements and such, it should be quite trivial for you to build what you need even without using _any_ Vaadin components at all.

That being said, thanks for providing some insight into the use case you're trying to solve with this. Unfortunately I couldn't find an add-on called "TaskPane" in the Vaadin Directory, nor any mention of it online, so I don't know where you took that from in your V8 application. Perhaps it's your own wrapper class for an add-on of some other name?

In any case, I think the [Accordion](https://vaadin.com/docs/latest/components/accordion) component would be a better fit for what you're trying to do here. It currently only allows for a single panel to be open at a time, but there is a [feature request](https://github.com/vaadin/web-components/issues/552) for allowing multiple open panels. There it could actually make sense to have an API for disabling the closing (or opening) of a panel.

Let me know what you think about that, and if you can find a web page describing that TaskPane add-on.

**Comment by dex-ds** [comment]
Hi Rolf, of course, you can't please everyone in UI/whatever frameworks. But simple functions in particular - such as the non-closable functionality for DETAILS - could have been taken into account from the outset. Anyway...

We know ACCORDION, unfortunately it is unsuitable for our purpose.

Sorry for the confusion about TASKPANE addon, I meant [COLLAPSIBLE PANEL](https://vaadin.com/directory/component/collapsiblepanel-add-on) addon, which we have adapted internally as TASKPANE addon.

To prevent closing a panel we simple unwrap the panel temporarily. Later wrap it to have it collapsible again.

**Comment by rolfsmeds** [comment]
> We know ACCORDION, unfortunately it is unsuitable for our purpose.

Are there reasons for this other than the one I already mentioned? (that only one panel can be simultaneously open)

The reason I'm asking is that an Accordion is essentially a stack of Details panels, so where Details is designed to be used standalone, Accordion is designed to be used when there are multiple panels. And with multiple panels, the possibility to force one to stay open or closed seems a lot more natural than with a standalone panel.

**Comment by dex-ds** [comment]
> (that only one panel can be simultaneously open)

yes! in our case this is the showstopper :D

Well, what are we going to do if your team doesn't respond to the simplest customer requests and doesn't understand why non-collapsible in details is a good thing...

The quick&dirty workaround will do for now.
As in the past, when there is a little more time, we will once again add something cleanly to VAADIN. 

Don't misunderstand - we love VAADIN - but VAADIN will only ever be an 80% student ;-)
Thanks for your time and best regards

**Comment by rolfsmeds** [comment]
Um, I'm having this conversation with you specifically to figure out the best way to provide what you need for your use case, but I think I'll just let you get on with your workaround and close this issue. Good luck with everything, I guess.
