### ISSUE TITLE
Add TabSheet.getComponentCount()

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow-components#6015]
### Describe your motivation

In order for TabSheet to provide API consistent with Tabs, it would be good to have `TabSheet.getComponentCount()` to return the number of tabs .

### Describe the solution you'd like

`TabSheet.getComponentCount()`

### Additional context

`TabSheet.getTabCount()` would be better, but that would make the component API inconsistent with Tabs.

**Comment by javier-godoy** [comment]
**Workaround**
```
((Tabs) tabsheet.getChildren().filter(Tabs.class::isInstance).findFirst().get()).getComponentCount()
```

**Comment by rolfsmeds** [comment]
Yeah, I think it would make sense to:
1. Introduce `getTabCount` to both `Tabs` and `Tabsheet`
2. Deprecate `getComponentCount` in `Tabs`
