### ISSUE TITLE
CRUD New Item button can't be hidden

### ISSUE THREAD

**Issue by WoozyG** [vaadin/flow-components#6080]
### Description

Setting `crud.getNewButton().setVisible(false)` has no effect visually - the client code builds a new button anyway.  Similarly, setting the button to `null` does nothing, the client builds a button anyway.  Further, the button displayed still tries to perform the NewItem action.

If the CRUD content type does not have a default constructor, for example a class that should be read-only but have a toolbar, the New Item button can only be hidden via CSS, and if shown, runtime errors occur trying to instantiate a default instance.

### Expected outcome

either setting the button to `null` or visibility to false should stop showing a "New Item" button on the client.

### Minimal reproducible example

create a CRUD, try to remove or set invisible the New Item button.  It won't work without CSS.

### Steps to reproduce

create a CRUD, try to remove or set invisible the New Item button.  It won't work without CSS.

### Environment

Vaadin version(s): 24 (latest)
OS: N/A

### Browsers

Issue is not browser related

**Comment by web-padawan** [comment]
Investigated this a bit. Here is a reproduction case for removal / hiding of the "New item" button:

```java
package com.vaadin.flow.component.crud.tests;

import static com.vaadin.flow.component.crud.tests.Helper.createPersonEditor;

import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.crud.Crud;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

@Route(value = "vaadin-crud/new-button")
public class NewButtonView extends VerticalLayout {

    public NewButtonView() {
        Crud<Person> crud = new Crud<>(Person.class, createPersonEditor());
        crud.setDataProvider(new PersonCrudDataProvider());

        Button reset = new Button("Remove new button", e -> {
            // WORKS
            crud.setNewButton(null);
        });

        Button hide = new Button("Hide new button", e -> {
            // WORKS
            crud.getNewButton().setVisible(false);
        });

        add(crud, reset, hide);

        // DOES NOT WORK
        // crud.setNewButton(null);

        // DOES NOT WORK
        // crud.getNewButton().setVisible(false);
    }
}
```

Based on my understanding, here is what happens in these cases:

- When calling `setNewButton(null)` before the `vaadin-crud` element is first created on the client-side, the server-side `Button` does not get attached. 
- When calling `getNewButton().setVisible(false)`, there is a `vaadin-button` elemen with `hidden` attribute and no `slot` attribute present:

<img width="668" alt="Screenshot 2024-03-05 at 16 07 35" src="https://github.com/vaadin/flow-components/assets/10589913/5db7ae10-b939-481d-a5d6-3efc868a04ed">

As in both cases there is no DOM element in the `new-button` slot, the web component creates its own `vaadin-button` managed by the [controller](https://github.com/vaadin/web-components/blob/461a9a0a7b6e3ecc977ac9af868dcd4362a1a0c9/packages/crud/src/vaadin-crud.js#L663), and that element can't be accessed on the server side.

I'm not sure what is the best approach to fix this. Maybe we should suppress client-side controller completely in Flow.
