### ISSUE TITLE
setHeader on grid columns may trigger sort events

### ISSUE THREAD

**Issue by eberleant** [vaadin/flow-components#6122]
### Description

Calling setHeader on grid columns can trigger sort events. This seems to happen when both of these are true:

- setHeader is called on more than one column
- the grid has a non-empty sort order

This behavior is new in 24.3.0+ and doesn't occur in previous versions I've tested (24.2.11 and below). The number of sort events seems to depend on the number of columns/times setHeader is called.

### Expected outcome

I wouldn't expect setHeader to trigger any sort events since no sorting settings have been changed.

### Minimal reproducible example

Demo: [grid-sort-event-v2.zip](https://github.com/vaadin/flow-components/files/14592901/grid-sort-event-v2.zip)
[Screen recording](https://github.com/vaadin/flow-components/assets/33359250/48f6d410-d1da-4602-9377-8d482c457d35)

### Steps to reproduce

1. Click the "Change Header Text" button
2. Text below each grid shows how many sort events have been triggered for that grid. Notice how the first grid (with 1 column) does not have any sort events after the first one (which sets the grid's initial sort order). However, the number of sort events for grids 2-4 increments by 2, 4, and 6 respectively, each time the button is pressed.

### Environment

Vaadin version(s): 24.3.0-24.3.7
OS: macOS 13.6.4

Tested in Chrome 122.0.6261.112, Safari 16.6, and Firefox 123.0

### Browsers

Chrome, Firefox, Safari

**Comment by web-padawan** [comment]
Confirmed that the issue is not reproducible in 24.2 (including latest 24.2.12) so it is a regression in 24.3. I will investigate.
