### ISSUE TITLE
ColumnPathRenderer cannot be used when Column has an EditorComponent

### ISSUE THREAD

**Issue by probert94** [vaadin/flow-components#6124]
### Description

In a project I am working on, I am using LitRenderer to render most of the columns. Some of them only render a simple text so I would like to optimize them. Unfortunately, I cannot use `ValueProvider` as the API I have to use only supports `Renderer`.
Now I've seen, that columns with a `ValueProvider` actually use `ColumnPathRenderer` and I wanted to use that as well.
Unfortunately this does not work, as soon as my columns have an `EditorComponent`.
The reason for this is probably, that as soons as a column is using an `EditorComponent`, the [client side renderer is changed](https://github.com/vaadin/flow-components/blob/main/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/editor/EditorRenderer.java#L168-L183) and does not take the specified `path` into account.
The `ValueProvider` still works, as it is using the column.id as a path.

### Expected outcome

The `ColumnPathRenderer` should still render the column, even if an editor component is set.

### Minimal reproducible example

```java
@PageTitle("Main")
@Route(value = "")
public class MainView extends VerticalLayout {
    public MainView() {
        Grid<Person> grid = new Grid<>();
        grid.addColumn(Person::firstName)
            .setHeader("First name");
        grid.addColumn(Person::lastName)
            .setHeader("Last name")
            .setEditorComponent(new TextField());
        grid.addColumn(new ColumnPathRenderer<>("address", Person::address))
            .setHeader("Address");
        grid.addColumn(new ColumnPathRenderer<>("birthDay", p -> p.birthDay().format(DateTimeFormatter.ISO_DATE)))
            .setHeader("Birthday")
            .setEditorComponent(new DatePicker());
        grid.setItems(
            new Person(1, "John", "Doe", "Mainstreet 1", LocalDate.of(1980, 1, 1)),
            new Person(1, "Jane", "Doe", "Mainstreet 1", LocalDate.of(1985, 1, 1)),
            new Person(1, "Jack", "Doe", "Mainstreet 1", LocalDate.of(2010, 1, 1))
        );
        add(grid);
    }
    private record Person(long id, String firstName, String lastName, String address, LocalDate birthDay) {
    }
}
```

### Steps to reproduce

1. Create a new Vaadin project and copy the above code into the `MainView.java`
2. Start the application
3. Note that all columns except "Birthday" are rendered.
Note:
Column 1 uses a `ValueProvider` and no `EditorComponent`.
Column 2 uses a `ValueProvider` as well as a `EditorComponent`.
Column 3 uses a `ColumnPathRenderer` and no `EditorComponent`.
Column 2 uses a `ColumnPathRenderer` as well as a `EditorComponent`.

### Environment

Flow: 24.3.7
Vaadin: 24.3.7
Java: Eclipse Adoptium 17.0.6
OS: amd64 Windows 11 10.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 OPR/107.0.0.0

### Browsers

Issue is not browser related

**Comment by yuriy-fix** [comment]
This could be a limitation, we will take a look into it. If it ends up to be a limitation, it should be documented.
