### ISSUE TITLE
binder length check triggers red popup wrongly

### ISSUE THREAD

**Issue by letrthang** [vaadin/flow-components#6175]
### Description

Example below code from https://vaadin.com/docs/latest/binding-data/components-binder-validation#converting-user-input

`binder.forField(nameField)
    // Validator defined based on a lambda
    // and an error message
    .withValidator(
        name -> name.length() >= 3,
        "Name must contain at least three characters")
    .bind(Person::getName, Person::setName);`

If **nameField** is empty, then red popup will show.

### Expected outcome

**Expected**: not show red popup message if the input field is empty.

### Minimal reproducible example

`binder.forField(nameField)
    // Validator defined based on a lambda
    // and an error message
    .withValidator(
        name -> name.length() >= 3,
        "Name must contain at least three characters")
    .bind(Person::getName, Person::setName);`

### Steps to reproduce

create a input filed that enable data binder as https://vaadin.com/docs/latest/binding-data/components-binder-validation#converting-user-input

### Environment

Vaadin version(s): 23/24
Java 17
OS: any

**Comment by knoobie** [comment]
> Name must contain at least three characters

name empty == less than three characters --> field invalid. 

So where is the problem?

**Comment by letrthang** [comment]
> > Name must contain at least three characters
> 
> name empty == less than three characters --> field invalid.
> 
> So where is the problem?

we expect the textbox will be highlighted red but not showing red popup error message.

**Comment by knoobie** [comment]
That's not how error messages work. You specify them; they get shown. It would be a big problem if their wouldn't be shown.

**Comment by letrthang** [comment]
<img width="500" alt="image" src="https://github.com/vaadin/flow-components/assets/13396193/e3ac57b2-223a-4532-80b3-b1b652663538">

As above photo. if the input text field is empty and I clicks outside of the input text field, then it will hightlight red and keep showing bubbles (empty dialog). 
If i put whitespace into the input text field, then empty red dialog will stop. So i think the binder cannot validate a NULL value which causes showing empty red dialog.

**Comment by knoobie** [comment]
All those assumption are not related. You have a problem, with validations that return an empty error message (default is required check) - those somehow(?) show weirdly in your case. This is not a default behavior and a reproduceable test-case is highly recommended. Never seen such a behaviour.

**Comment by letrthang** [comment]
This is my code:
`binder.forField(textAssetName).asRequired().withValidator(new RegexpValidator("only from 3-30 numeric chars", "^[a-zA-Z0-9_\\-. ]{3,30}$"))`

Seem issue is due to my regex incorrect.

Seem

**Comment by letrthang** [comment]
i will close this issue. Thanks @knoobie

**Comment by vursen** [comment]
> When i input the data not match with regex condition, it shows 3 red dialogs at same time.

This has been fixed in 24.3, see https://github.com/vaadin/flow-components/issues/5537.

**Comment by vursen** [comment]
Closing issue as stale.
