### ISSUE TITLE
Add `HasHelper`to `InputField` interface

### ISSUE THREAD

**Issue by knoobie** [vaadin/flow-components#6188]
### Describe your motivation

After Checkbox supports `HasHelper` in the upcoming version, it would be good if `InputField` would also be updated, so that `HasHelper` can be removed from Checkbox and users can remove their cast of `HasHelper` for their usage of `InputField`.

### Describe the solution you'd like

```java
interface InputField implements HasHelper
```

**Comment by web-padawan** [comment]
Thanks for the suggestion. Sounds reasonable to me. I can create a PR based on #6166
