### ISSUE TITLE
Vaadin 24: Dialog shows empty if 'onAttach(AttachEvent)' is overridden.

### ISSUE THREAD

**Issue by enver-haase** [vaadin/flow-components#6189]
### Description of the bug

When you show() the Dialog then it is shown as empty in case the `onAttach(AttachEvent)` method is overridden.

### Expected behavior

Expected, of course, is that the Dialog shows properly as it did in Vaadin 23.3.30 .

### Minimal reproducible example

```
package org.vaadin.example;

import com.vaadin.flow.component.AttachEvent;
import com.vaadin.flow.component.dialog.Dialog;
import com.vaadin.flow.component.html.Span;

import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

@Route
public class MainView extends VerticalLayout {

    public MainView() {

        Button button1 = new Button("Dialog 1", e -> {
            Dialog dialog1 = new Dialog() {
                {add(new Span("Foo"));}

                @Override
                protected void onAttach(AttachEvent attachEvent) {
                    System.out.println("Attached!");
                }
            };
            dialog1.open();
        });

        Button button2 = new Button("Dialog 2", e -> {
            Dialog dialog2 = new Dialog() {
                {add(new Span("Bar"));}
            };
            dialog2.open();
        });



        add(button1, button2);
    }

}

```

### Versions

- Vaadin / Flow version: 24.3.9
- Java version: n/a
- OS version: n/a
- Browser version (if applicable): n/a
- Application Server (if applicable): internal SpringBoot Tomcat
- IDE (if applicable): n/a

**Comment by tomivirkki** [comment]
It's worth noting that even with Vaadin `23.3`, overriding Dialog's `onAttach` method should include a call to `super.onAttach()`. Not doing do would disable some built-in functionalities like using `listenOn(dialog)` for a click shortcut:

```java
someButton.addClickShortcut(Key.ENTER).listenOn(dialog1);
```

Most Vaadin Flow components internally override the `onAttach` method for various purposes so the correct approach here is to update the `onAttach` method's documentation.
