### ISSUE TITLE
Different default value for alignItems property

### ISSUE THREAD

**Issue by Fedoseew** [vaadin/flow-components#6206]
### Description of the bug

AlignItems property has different default value (STRETCH in Java API and START in client)

### Expected behavior

START as default value in Java API.

### Minimal reproducible example

HorizontalLayout, VerticalLayout.

### Versions

- Vaadin / Flow version: 24+
- Java version: 21
- OS version: macOS
- Browser version (if applicable): -
- Application Server (if applicable): -
- IDE (if applicable): -

**Comment by rolfsmeds** [comment]
Apparently, the Flow API does not return the actual default alignment, which is `flex-start`.
