### ISSUE TITLE
Form: Add convenient way to set width of label from Java

### ISSUE THREAD

**Issue by knoobie** [vaadin/flow-components#6223]
### Describe your motivation

To change the default width of label in an aside-based form the usage of a CSS property in CSS or Java is required. This feels "overly" complicated for a simple Java Dev.

### Describe the solution you'd like

```java

public void setLabelAsideWidth(String width);
// or
public void setLabelWidth(String width);

```

Both methods would delegate to `this.getStyle().set("--vaadin-form-item-label-width", width);`

**Comment by rolfsmeds** [comment]
I would propose the method name `setLabelColumnWidth`.
