### ISSUE TITLE
Resetting DateTimePicker's overlayClassName does not work

### ISSUE THREAD

**Issue by JoMWal** [vaadin/flow-components#6274]
### Description

I added a DateTimePicker to a view and set DateTimePicker component's overlayClassName.
Trying to reset overlayClassName property breaks the component:

![image](https://github.com/vaadin/flow-components/assets/25712906/65faf0cb-4a8a-4b7a-ad1a-8566b9349c5a)

- Seems to me as web component's input component is not generated. There are errors in browser console:
![image](https://github.com/vaadin/flow-components/assets/25712906/48744e84-9bb2-4882-8b38-2e3430d04329)
- same with DatePicker

### Expected outcome

After resetting reset overlayClassName property DateTimePicker is displayed as before setting overlayClassName at all.

### Minimal reproducible example

```
@Route
public class MainView extends VerticalLayout {

    public MainView() {

        DateTimePicker dateTimePicker = new DateTimePicker("Default");
        
        DateTimePicker dateTimePicker2 = new DateTimePicker("Reset with setOverlayClassName(null)");
        dateTimePicker2.setOverlayClassName("example");
        dateTimePicker2.setOverlayClassName(null);
        
        DateTimePicker dateTimePicker3 = new DateTimePicker("Reset with setOverlayClassName(\"\")");
        dateTimePicker3.setOverlayClassName("example");
        dateTimePicker3.setOverlayClassName("");
        
        DateTimePicker dateTimePicker4 = new DateTimePicker("Reset with getElement().setProperty(\"overlayClass\", null)");
        dateTimePicker4.setOverlayClassName("example");
        dateTimePicker4.getElement().setProperty("overlayClass", null);

        add(dateTimePicker);
        add(dateTimePicker2);
        add(dateTimePicker3);
        add(dateTimePicker4);
    }
}
```

### Steps to reproduce

1. Create new Vaadin app (Used maven archetype)
2. Edit "MainView" as in "Minimal reproducible example"
3. Start with jetty

### Environment

Vaadin version(s): 24.3.10
OS: Win10

**Comment by web-padawan** [comment]
Thanks for the issue. Confirmed it using the web component. I'll add a check to ensure empty `overlayClass` doesn't throw.
