### ISSUE TITLE
Chrome & body height of 100vh = 💔

### ISSUE THREAD

**Issue by anezthes** [vaadin/flow-components#6320]
### Description

Flow application have `height: 100vh` set on the `body` by default. For some reason, this causes a scrolling issue in Chrome. In views where the content is centred, i.e. there's empty space on the left and right, you cannot scroll when hovering over the 'empty' areas. It works fine in Firefox and Safari.

If you change the `body` element's `height` to `100%`, it works as expected.

### Expected outcome

I would expect to be able to scroll a view that overflows vertically, regardless of where my mouse pointer is, as long as it's over the content that needs scrolling.

### Minimal reproducible example

```
@Route(value = "", layout = MainLayout.class)
public class MyView extends Main {
    public HomeView() {
        Paragraph p = new Paragraph(<Enter a super long text here...>);
        p.addClassName(Margin.Horizontal.AUTO);
        p.setMaxWidth(20, Unit.REM);
        add(p);
    }
}
```

### Steps to reproduce

1. Add the view above.
2. Run the app.
3. Try to scroll, in Chrome, when hovering above the empty area on either side of the paragraph.

### Environment

Vaadin version(s): 24.3.12
OS: macOS Sonoma 14.5

### Browsers

Chrome: 126.0.6478.17
Firefox: 126.0
Safari: 17.4.1

**Comment by anezthes** [comment]
Alternatively to changing the `body` element's `height` to `100%`, you can also set `[content]` to `display: flex` (and `flex-direction: column`).

**Comment by yuriy-fix** [comment]
Dear @anezthes, 

We are closing this issue as stale. If you could come up with a complete reproducible example, feel free to reopen the issue.
