### ISSUE TITLE
RadioButtonGroup Label

### ISSUE THREAD

**Issue by allenvpn312** [vaadin/flow-components#6352]
### Description

Before version 24.3.11, the ratiobuttongroup label alignment defaults to left.  With the latest release it appears the default alignment is set to center.  Anyway to set default to left alignment?

### Expected outcome

![image](https://github.com/vaadin/flow-components/assets/9533785/1578d7c9-310b-464e-9a81-996d212297a3)

Expecting label to align left and not center.

### Minimal reproducible example

filingType = new RadioButtonGroup<>("Filing Type");
			filingType.addThemeVariants(RadioGroupVariant.LUMO_VERTICAL);
			filingType.setItems(FilingType.values());
			filingType.setValue(FilingType.O);

### Steps to reproduce

N/A

### Environment

Vaadin version(s): 24.3.13
OS: Windows 11

**Comment by allenvpn312** [comment]
Sorry, false alarm.  We updated a css property and that was the culprit.  Thank you.

**Comment by DiegoCardoso** [comment]
I'm closing this according to the previous comment.
