### ISSUE TITLE
Weekdays in DatePicker with I18N are not aligned

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/flow-components#6353]
### Description

If I configure I18n in a DatePicker, the weekdays are not stretched. For instance, in the following image (left), "Sun" seems to be displayed above July 1. Compare to a DatePicker instance without further configuration (right)
![image](https://github.com/vaadin/flow-components/assets/11554739/137b785b-6d7a-4d41-b842-0ed44792dd69)

### Expected outcome

I would expect both DatePickers to look similar.

### Minimal reproducible example

```
    DatePicker field1 = new DatePicker();
    DatePicker field2 = new DatePicker();

    DatePickerI18n i18n = new DatePickerI18n();
    DateFormatSymbols dfs = DateFormatSymbols.getInstance(Locale.ENGLISH);
    i18n.setMonthNames(List.of(dfs.getMonths()));
    i18n.setWeekdays(List.of(dfs.getWeekdays()));
    i18n.setWeekdaysShort(List.of(dfs.getShortWeekdays()));
    add(field1, field2);
    field1.setI18n(i18n);
```

### Steps to reproduce

1. Add the snippet above to a view. 
2. Open each `DatePicker` popup. 
3. Notice how "Sun" seems to be displayed above July 1.

### Environment

Vaadin version(s):  24.3.13
Browser: Chrome 125

**Comment by sissbruecker** [comment]
The problem is that converting the result of `DateFormatSymbols.getWeekdays` or `DateFormatSymbols.getShortWeekdays` into a List returns 8 items instead of 7.

For example:
```java
System.out.println(String.join(",", dfs.getWeekdays()));
System.out.println(String.join(",", dfs.getShortWeekdays()));
```

Prints:
```
,Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday
,Sun,Mon,Tue,Wed,Thu,Fri,Sat
```

The JavaDoc mentions that you are supposed to access the results via an index specifically:
> Gets weekday strings. For example: "Sunday", "Monday", etc.
> Returns:
> the weekday strings. Use Calendar. SUNDAY, Calendar. MONDAY, etc. to index the result array.
