### ISSUE TITLE
Vcf-date-range-picker 5.0.0 doesn't work with Vaadin 24.4.1

### ISSUE THREAD

**Issue by EasyMeow** [vaadin/flow-components#6376]
### Description

Hello! We are upgrading our project to Vaadin 24.4.1 and found that vcf-date-range-picker  (5.0.0) does't work with it.
![image](https://github.com/vaadin/flow-components/assets/63020967/3a6c5465-f581-40e5-9987-543acfc63618)

### Expected outcome

Dropdown with calendar is open after clicking on EnhancedDateRangePicker and there is no any errors in console.
![image](https://github.com/vaadin/flow-components/assets/63020967/7c45a2ef-fa1b-4f09-b29b-97523b16aa02)

### Minimal reproducible example

```java
@PageTitle("About")
@Route(value = "about")
@RouteAlias(value = "")
public class AboutView extends VerticalLayout {


    public AboutView() {
        EnhancedDateRangePicker dateRangePicker = new EnhancedDateRangePicker("Picker");
        add(dateRangePicker);
    }

}
```

### Steps to reproduce

1. Run the project
2. Click on EnhancedDateRangePicker

### Environment

Vaadin version(s): 24.4.1
Java version: 17
vcf-date-range-picker: 5.0.0

**Comment by sissbruecker** [comment]
Vcf-date-range-picker is an addon that isn't maintained in this repository. Please file your issue in the repo for the addon itself: https://github.com/vaadin-component-factory/vcf-date-range-picker
