### ISSUE TITLE
CheckboxGroup ItemEnabledProvider not working on value change.

### ISSUE THREAD

**Issue by KonstantinosNeiros** [vaadin/flow-components#6396]
### Describe your motivation

In vaadin 8, by using CheckBoxGroup.setItemEnabledProvider(item -> {}; I was able to decide the status of a checkboxgroup item. In the debugging mode, I saw that each time I click an item, the above code is executed.

In vaadin 23, it seems that the code is executed just to set the initial status. On value change of the checkbox group items the code is not executed.

### Describe the solution you'd like

The itemEnabledProvider should be executed each time the value of a checkbox group item changes.

**Comment by rolfsmeds** [comment]
While automatically "refreshing" the enabled items when items are checked/unchecked is clearly useful for one specific case: where the enabled-state of items is based on the state of other items, it would be unnecessary for all other use cases, so I don't think it should automatically refresh like that (even though it did so in V8).

However, I would expect `refreshAll` to re-run the enabledProvider on all items, so if you do:
```
checkboxGroup.addValueChangeListener(e-> {
  checkboxGroup.getDataProvider().refreshAll();
}
```
I would expect it to work the way you want.

Please leave a comment here if that solution doesn't work for you.

**Comment by rolfsmeds** [comment]
Closing as stale. Feel free to re-open if still valid.
