### ISSUE TITLE
Grid CTRL and SHIFT interaction is buggy

### ISSUE THREAD

**Issue by enver-haase** [vaadin/flow-components#6397]
### Description

When multiselecting with SHIFT then deselecting one row with CTRL and then multiselecting rows with SHIFT again, the deselected line comes back. See video.

### Expected outcome

The deselected row should stay deselected.

### Minimal reproducible example

See video.
Use a multiselect Grid.

### Steps to reproduce

See video.

### Environment

Vaadin version(s): 24.4
OS: n/a

**Comment by enver-haase** [comment]
![image](https://github.com/vaadin/flow-components/assets/7870436/e31ede9a-0f1e-410f-b627-e56c0a184559)

**Comment by enver-haase** [comment]
![MultiSelect](https://github.com/vaadin/flow-components/assets/7870436/df65e94e-21e4-4e0f-8380-22d0c16871b8)

**Comment by web-padawan** [comment]
Please note that support for Shift and Control click selection is actually not yet implemented. See https://github.com/vaadin/web-components/issues/2041

**Comment by sissbruecker** [comment]
As mentioned above, there currently is no multi-selection feature with Shift or Ctrl keys. Closing.
