### ISSUE TITLE
VCF Popup closes on click when a vaadin combobox is open

### ISSUE THREAD

**Issue by jameskerrtaskize** [vaadin/flow-components#6478]
### Description

I have a attached a reproducible example.
There is a button which opens a popup when clicked.
The popup has a single combobox in it.

Click the button to open the popup

Notice that if you click any of the empty space on the popup, it does not close. This is what we want.

Now click the combobox to open the dropdown. Notice that if you now click the whitespace of the popup, it closes. We don't want this.

If you open the down down and then close it again using the toggle. Clicking the whitespace works as expected again.

### Expected outcome

Clicking the popup should never close it

### Minimal reproducible example

[popup-close-issue.zip](https://github.com/user-attachments/files/16373498/popup-close-issue.zip)

### Steps to reproduce

Click the button to open the popup

Notice that if you click any of the empty space on the popup, it does not close. This is what we want.

Now click the combobox to open the dropdown. Notice that if you now click the whitespace of the popup, it closes. We don't want this.

If you open the downdown and then close it again using the toggle. Clicking the whitespace works as expected again.

### Environment

Vaadin version(s): 24.3
OS: OSX

**Comment by web-padawan** [comment]
Thanks for the issue. Please note that VCF popup is not part of Vaadin components.

There was a fix related to closing ComboBox recently released in Vaadin 24.3.16, could you please try if upgrading helps?

**Comment by jameskerrtaskize** [comment]
This still seems to be an issue on 24.3.16 and also 24.4.7

**Comment by jameskerrtaskize** [comment]
I wasn't sure where to raise this ticket but in the end decided that it looks more like a vaadin core issue.

The popup listens for click events on the document but also on the popup itself. When it gets the click event on the popup it preventsDefault.

When the combobox is open and I click the popup. It doesn't get the popup click event.

**Comment by web-padawan** [comment]
UPD: looks like I can't transfer the issue to the different GitHub organization. 

Closing, please submit a new issue to https://github.com/vaadin-component-factory/vcf-popup.
