### ISSUE TITLE
Page jumps to top after opening and closing a submenu by clicking

### ISSUE THREAD

**Issue by eberleant** [vaadin/flow-components#6483]
### Description

If I have a MenuBar with a SubMenu, click to open the menu, scroll down on the page, then click somewhere to close the menu, the page scroll position jumps to the top.

This only seems to happen if the menu item is clicked (not hovered) to open it.

### Expected outcome

The scroll position should stay the same.

### Minimal reproducible example

```java
var menuBar = new MenuBar();
var div = new Div();
div.setHeight(1000, Unit.PIXELS); // so you can scroll down

var container = new Div("Menu");

MenuItem menuItem = menuBar.addItem(container);

SubMenu subMenu = menuItem.getSubMenu();
subMenu.addItem("First");

add(menuBar, div);
```

### Steps to reproduce

1. Add the snippet to the constructor for a view that extends VerticalLayout
2. Click the menu to open it
3. Scroll down
4. Click somewhere on the page
5. The page jumps to the top

### Environment

Vaadin version(s): 24.4.6, 24.4.7; works as expected in 24.1.0
OS: Mac OS X
Tested on Chrome and Firefox.

### Browsers

Issue is not browser related

**Comment by web-padawan** [comment]
Confirmed also in the web component using the following code example:

```html
<vaadin-menu-bar></vaadin-menu-bar>
<div style="height: 1000px"></div>

<script type="module">
  import '@vaadin/menu-bar';

  const menuBar = document.querySelector('vaadin-menu-bar');
  menuBar.items = [
    {
      text: 'Share',
      children: [{ text: 'By email' }, { text: 'Get link' }],
    },
  ];
</script>
```

Note, the issue does not reproduce in 24.0 branch but does affect latest 24.1. I will investigate what caused it.

**Comment by web-padawan** [comment]
Turns out the issue is related to restoring focus on overlay close, see following PRs:

- https://github.com/vaadin/web-components/pull/5881
- https://github.com/vaadin/web-components/pull/5892
