### ISSUE TITLE
TabSheet package and tag name is inconsistent with class name

### ISSUE THREAD

**Issue by vojtapol** [vaadin/flow-components#6530]
### Description of the bug

`TabSheet` should have a tag `vaadin-tab-sheet` and NPM package `tab-sheet`. Or the class should be called `Tabsheet`. This inconsistency is an issue when customizing the component via CSS. The file must be called `vaadin-tabsheet.css` instead of `vaadin-tab-sheet.css` like the class name suggests.

### Expected behavior

`vaadin-tab-sheet.css` should work to customzie `TabSheet` but does not.

### Minimal reproducible example

1. Add `TabSheet` component
2. Add `vaadin-tab-sheet.css` to customize its style
3. Observe the style does not apply
4. Rename `vaadin-tab-sheet.css` to `vaadin-tabsheet.css`
5. Observe the style now does apply

### Versions

- Vaadin / Flow version: 24.4.8
- Java version: 17
- OS version: N/A
- Browser version (if applicable): N/A
- Application Server (if applicable): N/A
- IDE (if applicable): N/A

**Comment by rolfsmeds** [comment]
The Java class name and the Web Component tag and npm package name are indeed inconsistently cased/dashed.

However, relying on the Java class name for styling has never been a recommended approach (and there are many other examples where that would fail).

In fact, styling of Vaadin components by injecting css into their shadow DOM using the `components/component-tag-name.css` approach is no longer the recommended approach as of V24.0.

Please see the documentation on [Styling Vaadin Components](https://vaadin.com/docs/latest/styling/styling-components) for the current recommended approach, and the [css selector reference for the Tabs/Tabsheet component](https://vaadin.com/docs/latest/components/tabs/styling).

In any case, it would not be possible to change the stylesheet-filename mapping to `vaadin-tabsheet.css`, as that would require renaming the Web Component's tagname to `vaadin-tabsheet`, and it would be a major breaking change, affecting every existing application that relies on it, for very little benefit.
