### ISSUE TITLE
InputStreamFactory.createInputStream() should throw IOException

### ISSUE THREAD

**Issue by WoozyG** [vaadin/flow-components#6550]
### Description

I want to create an Anchor to a stream for downloading a file system file not built into the deployment package.  So I will need a `StreamResource`.  Since the file exists and I just want to serve it up, I want to use 

`new StreamResource("file.name", () -> Files.newInputStream(Path.of("/path/to/file.ext")))`

However, `Files.newInputStream` throws `IOException`, as expected, when the Path doesn't exist or isn't available.  However, This signature is not allowed for the functional interface `InputStreamFactory`.  That seems like an oversight, since the use of the class in StreamResource.Pipe is already set up to handle `IOException`.

### Expected outcome

I would expect to be able to create a `StreamResource` as indicated in the description.

### Minimal reproducible example

new StreamResource("file.name", () -> Files.newInputStream(Path.of("/path/to/file.ext")))

that should compile.

### Steps to reproduce

see above

### Environment

Vaadin version(s): 24.4.8
OS:  N/A

### Browsers

Issue is not browser related

**Comment by Legioth** [comment]
Hi. I've also been annoyed by the same omission. The issue is previously described in https://github.com/vaadin/flow/issues/18293.
