### ISSUE TITLE
ListBox should support full form component capabilities

### ISSUE THREAD

**Issue by nbabb** [vaadin/flow-components#6556]
The ListBox component has this documentation

https://vaadin.com/docs/latest/components/list-box#best-practices

And yet the component is listed in the "Data Entry" section. There is nothing inherent in this component that suggests, to me anyway, that it shouldn't be treated as other entry components, and support labels and validation errors.

**Comment by mshabarov** [comment]
Also related https://github.com/vaadin/vaadin-list-box/issues/11

**Comment by yuriy-fix** [comment]
Closing in favour of https://github.com/vaadin/flow-components/issues/1129
