### ISSUE TITLE
Vaadin vaadin-menu-bar component instantly closes upon opening after adding items

### ISSUE THREAD

**Issue by pgould-taskize** [vaadin/flow-components#6580]
### Description

If an item is added to the `SubMenu` of a `MenuBar` after the menu is initially rendered, and the dropdown menu has already been opened and closed, upon opening it again, it immediately closes.

The problem has been introduced with [Vaadin 24.4.7](https://github.com/vaadin/platform/releases/tag/24.4.7). Behaviour was as expected in [24.4.6](https://github.com/vaadin/platform/releases/tag/24.4.6), whereby the menu would continue to open without being closed. [Web components 24.4.3](https://github.com/vaadin/web-components/releases/tag/v24.4.3) does contain a change to the menu-bar, perhaps this is related: [fix: wait for updateComplete before setting positionTarget](https://github.com/vaadin/web-components/pull/7528)

Here is a video that demonstrates the issue: https://github.com/user-attachments/assets/da6640e1-d037-40aa-92df-aa72f2acfc34

I have attached a slightly amended version of the skeleton application with the `MainView` updated to contain the reproduction:

[menu-bar-close-immediately-after-update.zip](https://github.com/user-attachments/files/16762395/menu-bar-close-immediately-after-update.zip)

### Expected outcome

I would expect the menu to stay open upon opening it after a new menu item has been added, as it did in versions prior to `24.4.7`.

### Minimal reproducible example

```
        MenuBar menuBar = new MenuBar();
        menuBar.addItem("Main button", e -> {
        });

        MenuItem dropdown = menuBar.addItem(new Icon(VaadinIcon.CHEVRON_DOWN));
        SubMenu dropdownMenu = dropdown.getSubMenu();
        dropdownMenu.addItem("Option 1", e -> {
        });
        dropdownMenu.addItem("Option 2", e -> {
        });

        add(menuBar);

        add(new Button("add menu item", c -> {
            dropdownMenu.addItem("blah", cl -> {
                remove(menuBar);
                addComponentAsFirst(menuBar);
            });
        }));
```

### Steps to reproduce

1. Add the snippet above to a view
2. Open the sub menu by clicking on the chevron
3. Click the `add menu item` button
4. Open the sub menu by clicking on the chevron

### Environment

Vaadin version(s): 24.4.7 onwards
OS: Mac

### Browsers

Chrome

**Comment by web-padawan** [comment]
Confirmed the issue using the web component (see code example below). I will investigate.

```html
<vaadin-menu-bar></vaadin-menu-bar>

<button>Add item</button>

<script type="module">
  import '@vaadin/menu-bar';

  const menuBar = document.querySelector('vaadin-menu-bar');
  menuBar.items = [
    { text: 'Item 1' },
    {
      text: 'Item 2',
      children: [
        { text: 'Item 2 1' },
        { text: 'Item 2 2' },
      ],
    },
  ];

  const button = document.querySelector('button');
  button.addEventListener('click', () => {
    const items = menuBar.items;
    items[1].children = [...items[1].children, { text: 'Item 3'}];
    menuBar.items = [...items];
  })
</script>
```
