### ISSUE TITLE
Charts: Reference Error and resource leak

### ISSUE THREAD

**Issue by mperktold** [vaadin/flow-components#6607]
### Description

When changing `ChartOptions`, all existing charts are updated accordingly on the client side. But if a chart was updated using `chart.redraw(true)`, changing `ChartOptions` leads to a Reference Error that shows up in the browser console:

```
vaadin.js?v=ca80360c:94687 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'redraw')
    at vaadin.js?v=ca80360c:94687:126
    at Array.forEach (<anonymous>)
    at Chart.__callHighchartsFunction (vaadin.js?v=ca80360c:94687:109)
    at HTMLBodyElement.eval (eval at Qt (FlowClient.js:1044:101), <anonymous>:3:63)
    at Object.eval (eval at Qt (FlowClient.js:1044:101), <anonymous>:3:110)
    at Qt (FlowClient.js:1044:166)
    at Pt (FlowClient.js:995:277)
    at Nt (FlowClient.js:614:57)
    at rr (FlowClient.js:459:18)
    at Nr.Or [as eb] (FlowClient.js:1053:19940)
    at vB (FlowClient.js:964:221)
    at ur (FlowClient.js:1048:296)
    at Jr.Kr [as C] (FlowClient.js:1053:19706)
    at Qk (FlowClient.js:441:29)
    at mr (FlowClient.js:1051:1411)
    at nr (FlowClient.js:1034:403)
    at Ct.Et [as mb] (FlowClient.js:1053:23174)
    at VB.WB [as J] (FlowClient.js:1053:36239)
    at XMLHttpRequest.<anonymous> (FlowClient.js:631:63)
    at Eb (FlowClient.js:450:29)
    at Hb (FlowClient.js:920:56)
    at XMLHttpRequest.<anonymous> (FlowClient.js:650:46)
```

So the error happens here: https://github.com/vaadin/web-components/blob/d8ae51196a1ded333c40e091ab07b184aa317d57/packages/charts/src/vaadin-chart.js#L491

This means that `Highcharts.charts` can contain undefined values. And indeed, this behaviour is even documented in the Highchart code:

> An array containing the current chart objects in the page. A chart's position in the array is preserved throughout the page's lifetime. When a chart is destroyed, the array item becomes `undefined`.

https://github.com/highcharts/highcharts/blob/bce1ab70097a6bf74e5862480b2e0e723464440a/ts/Core/Globals.ts#L248-L256

Calling `chart.redraw(true)` apparently "destroys" the chart and adds a new one to this global array. And `__callHighchartsFunction` does not expect that.

Note that this issue only arises when calling `chart.redraw(true)`. Currently, detaching the chart from the DOM doesn't destroy it, and the gobal charts array will still reference it. This is a resource leak, and you can also reproduce this by switching back and forth between the two views without clicking on the "Update" button.

This is a problem, too. Detaching the chart should clean up all corresponding resources, and the chart should be eligible for garbage collection afterwards.

You could say that these are two issues, but I reported both here since both come down to the same odd behavior of the Highcharts library.

### Expected outcome

1. `__callHighchartsFunction` should ignore destroyed entries in the global charts array, not throw an Error.
2. Detaching a chart should "destroy" it, in Highcharts terminology.

### Minimal reproducible example

I've published a reproducer at https://github.com/mperktold/charts-issue.
It consists of a Dashboard and a dummy view that shows only text.
The dashboard was created by the starter, I only added two things:
- In `onAttach` it sets some `ChartOptions`.
- Below the "View events" chart, there is an "Update" button that calls `chart.redraw(true)`.

### Steps to reproduce

1. Start the application.
2. Open the browser at http://localhost:8080/.
3. Open DevTools.
4. In the Dashboard view, click on the update button.
5. Navigate to "Other view".
6. Navigate back to "Dashboard".
7. You should now see the error in the console.

### Environment

Vaadin version(s): 24.4.11
OS: Windows 10

### Browsers

Chrome, Firefox

**Comment by mperktold** [comment]
In case I wasn't clear, `destroy` is a method on the `Chart` object in Highcharts. The solution to the resource leak is probably to call that method when the chart is detached. This would probably also solve [vaadin/web-components/issues/1796](https://github.com/vaadin/web-components/issues/1796).

On that note, I apologize if I should have posted this issue on web-components. If you prefer, you can move it, or I can repost it there as well.

**Comment by web-padawan** [comment]
Thanks for the detailed issue and helping to investigate the problem. 
The error on redraw will be fixed by https://github.com/vaadin/web-components/pull/7779.

As for the second part (calling `configuration.destroy()` on detach), we could try that in the web component. Currently doing that breaks [one test](https://github.com/vaadin/web-components/blob/d665940d99599dc6005aecff2107687e4aeb1430/packages/charts/test/chart-element.test.js#L401-L404) checking that chart can be updated while disconnected, see https://github.com/vaadin/vaadin-charts/pull/309

> Ensure charts can accept configuration updates even when not connected (essential for supporting chart-flow as a virtual child)
> Ensure that all buffered updates are applied when connected

I will investigate if we can update the logic so that configuration would be correctly preserved after re-attach.

**Comment by web-padawan** [comment]
Fixed by https://github.com/vaadin/web-components/pull/7779 and https://github.com/vaadin/web-components/pull/7785
