### ISSUE TITLE
Calls to grid.sort trigger SortChangeEvent from client

### ISSUE THREAD

**Issue by probert94** [vaadin/flow-components#662]
### Description
I have a `Grid` of `Person`s inside another component.
In the components `onAttach` I programatically sort the `Grid` by the columns "Last name" and "First name".
Also I have a `SortListener` registered which prints the new `SortOrder`, but only if the event comes from the client.

### Expected outcome
Programmatically setting the `SortOrder` in `onAttach` should only trigger a single `SortEvent` with `fromClient` set to `false`.

### Actual outcome
Programmatically setting the `SortOrder` in `onAttach` triggers multiple `SortEvent`s, one with `fromClient` set to false and one for every column in the new `SortOrder` with `fromClient` set to `true`.

### Steps to reproduce
1. Create a `Composite<VerticalLayout>` and add a `Grid` with a few columns to it:
```
grid = new Grid<>();
grid.addColumn(Person::getLastName).setHeader("Last name")
  .setKey("LastName")
  .setSortable(true);
grid.addColumn(Person::getFirstName).setHeader("First name")
  .setKey("FirstName")
  .setSortable(true);
```
2. Add a `SortListener` to the `Grid`, which prints something, if the `SortEvent` is from client:
```
grid.addSortListener(e -> {
  if (e.isFromClient()) {
    System.out.println("SortOrder: " + e.getSortOrder().stream()
      .map(gso -> gso.getSorted().getKey() + ": " + gso.getDirection().name())
      .collect(Collectors.joining(", ")));
  }
});
```
3. In `onAttach` of the component call `grid#sort` to programatically sort by some columns:
```
protected void onAttach(AttachEvent attachEvent) {
  super.onAttach(attachEvent);
  grid.sort(List.of(
    new GridSortOrder<>(grid.getColumnByKey("LastName"), SortDirection.ASCENDING),
    new GridSortOrder<>(grid.getColumnByKey("FirstName"), SortDirection.ASCENDING)
  ));
}
```
4. Open the application and check the console:
```
SortOrder: FirstName: ASCENDING
SortOrder: LastName: ASCENDING, FirstName: ASCENDING
```

### Note
The issue seems to be related to the call of `grid.sort` in `Grid#onAttach`.
This causes 2 almost simultaneous calls to the client side `grid.$connector.setSorterDirections` (one from Grid and one from my component).
This method uses a boolean flag to ensure that sorter changes from the server do not cause a `SortEvent` on the server.
However, in this case a flag is not enough, as it is reset by one of the two calls, before the other call triggers the `SortEvent`.
See gridConnector.js [Line 411](https://github.com/vaadin/vaadin-flow-components/blob/master/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js#L411), [Line 430](https://github.com/vaadin/vaadin-flow-components/blob/master/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js#L430) and [Line 400](https://github.com/vaadin/vaadin-flow-components/blob/master/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js#L400).

Code flow:
1. setSorterDirections call 1 (sorterDirectionsSetFromServer = true)
2. setSorterDirections call 2 (sorterDirectionsSetFromServer = true)
3. sorterChangeListener call 1 (sorterDirectionsSetFromServer = true, nothing to do)
4. setSorterDirections call 1 finished (sorterDirectionsSetFromServer = false)
5. sorterChangeListener call 2 (sorterDirectionsSetFromServer = false, notify server)
6. setSorterDirections call 2 finished (sorterDirectionsSetFromServer = false)

I fixed it by copying the `gridConnector.js` and using a counter instead of a boolean flag.

New code flow:
1. setSorterDirections call 1 (sorterDirectionsSetFromServer = 1)
2. setSorterDirections call 2 (sorterDirectionsSetFromServer = 2)
3. sorterChangeListener call 1 (sorterDirectionsSetFromServer > 0, nothing to do)
4. setSorterDirections call 1 finished (sorterDirectionsSetFromServer = 1)
5. sorterChangeListener call 2 (sorterDirectionsSetFromServer > 0, nothing to do)
6. setSorterDirections call 2 finished (sorterDirectionsSetFromServer = 0)

**Comment by vursen** [comment]
I followed the reproduction steps in latest 24.4 and concluded that the issue is no longer reproducible, as I didn't receive any `SortEvent` from the client when I set the sort order programmatically in `onAttach`. 

Feel free to reopen the issue if it still persists.
