### ISSUE TITLE
Add API to support html in CheckBoxGroup's checkbox labels

### ISSUE THREAD

**Issue by TatuLund** [vaadin/flow-components#671]
It would be relatively straightforward to add html label support for the CheckBoxGroup's checkbox labels by changign updateCheckbox method like follows.

In addition to these API is needed to be added to control `htmlAllowed`. Natural candidates are

`setHtmlAllowed(boolean)`

`isHtmlAllowed()`

or more verbose

`setCheckboxLabelContentMode(CheckboxLabelContentMode.HTML / CheckboxLabelContentMode.TEXT) `

`getCheckboxLabelContentMode()`

```
    private void updateCheckbox(CheckBoxItem<T> checkbox) {
        if (htmlAllowed) {
            checkbox.setLabelAsHtml(getItemLabelGenerator().apply(checkbox.getItem()));
        } else {
            checkbox.setLabel(getItemLabelGenerator().apply(checkbox.getItem()));
        }
        updateEnabled(checkbox);
        checkbox.setValue(getValue().stream().anyMatch(
                selectedItem -> Objects.equals(getItemId(selectedItem),
                        getItemId(checkbox.getItem()))));
    }
```

**Comment by tomivirkki** [comment]
Shouldn't this be covered with `setRenderer`? There's also a [workaround](https://github.com/vaadin/vaadin-checkbox/issues/189#issuecomment-767340722) in the related issue.

**Comment by web-padawan** [comment]
Let's implement `setRenderer` instead of inventing new API indeed. Closing in favor of #1240.
