### ISSUE TITLE
FormLayout ignoring column setting

### ISSUE THREAD

**Issue by miquelD-R** [vaadin/flow-components#6728]
### Description

FormLayout ignores column settings when placed inside an AccordionPanel:
![image](https://github.com/user-attachments/assets/f2cc67d1-55fe-4246-be0a-2387c004f4ec)

### Expected outcome

FormLayout should be displayed in the same way, independently of whether it's inside an AccordionPanel or not

### Minimal reproducible example

@PermitAll
@PageTitle("Form Layout Test")
@Route(value = "formLayoutTest")
public class FormLayoutTestView extends VerticalLayout {

    public FormLayoutTestView() {
        Accordion accordion = new Accordion();
        accordion.getStyle().setBackgroundColor("green");

        FormLayout innerFormLayout = generateFormLayout("inner FormLayoutItem", 10);
        FormLayout outerFormLayout = generateFormLayout("outer FormLayoutItem", 10);

        accordion.add(new AccordionPanel("Panel #1",                new Text("Panel #1 content")));
        AccordionPanel panelWithFL = new AccordionPanel("Panel with FormLayout",   innerFormLayout);
        accordion.add(panelWithFL);
        accordion.add(new AccordionPanel("Panel #3",                new Text("Panel #3 content")));
        add(accordion, outerFormLayout);
    }

    private FormLayout generateFormLayout(String contentPrefix, int numItems){
        FormLayout result = new FormLayout();
        result.setResponsiveSteps(new FormLayout.ResponsiveStep("0", 1,
            FormLayout.ResponsiveStep.LabelsPosition.TOP));
        for(int i = 0; i<numItems; i++){
            FormLayout.FormItem item = new FormLayout.FormItem();
            item.add(new Text(contentPrefix+" #"+i));
            result.add(item);
        }
        return result;
    }
}

### Steps to reproduce

Access the provided 'formLayoutTest' View

### Environment

Vaadin version(s): 24.4.13
OS: Windows 11

### Browsers

Chrome

**Comment by web-padawan** [comment]
Confirmed in the web component using the following example:

```html
<vaadin-accordion>
  <vaadin-accordion-panel>
    <vaadin-accordion-heading slot="summary">Panel 1</vaadin-accordion-heading>
    <div>Panel 1 content</div>
  </vaadin-accordion-panel>
  <vaadin-accordion-panel>
    <vaadin-accordion-heading slot="summary">Panel 2</vaadin-accordion-heading>
    <vaadin-form-layout>
      <vaadin-form-item>
        <label slot="label">Label 1</label>
        <input />
      </vaadin-form-item>

      <vaadin-form-item>
        <label slot="label">Label 2</label>
        <input />
      </vaadin-form-item>
    </vaadin-form-layout>
  </vaadin-accordion-panel>
</vaadin-accordion>

<script type="module">
  import '@vaadin/accordion';
  import '@vaadin/form-layout';

  document.querySelector('vaadin-form-layout').responsiveSteps = [{ columns: 1 }];
</script>
```

Note: this seems to be a regression from #7792 as the problem doesn't happen if I remove the block added in that PR.
We most probably should add `IntersectionObserver` to update `vaadin-form-layout` when it becomes visible.
