### ISSUE TITLE
custom field is missing method _setInputs()

### ISSUE THREAD

**Issue by rappenze** [vaadin/flow-components#6739]
### Description

When I extend the CustomField, I get error in the javascript console like this:
![image](https://github.com/user-attachments/assets/ccec6543-5165-4f6b-902d-2c1c71e59b6e)

The error is only reproducible if `setRequiredIndicatorVisible(false)` is set.

I think the reason is that in the following line
https://github.com/vaadin/web-components/blob/main/packages/custom-field/src/vaadin-custom-field-mixin.js#L267
the method _setInputs() is called but the method does not exist and therefore inputs is undefined.

Be aware that all the logic seems to work afterwards, so it seems that later all is initialized correctly.

### Expected outcome

No error in JavaScript console.

### Minimal reproducible example

```
@Route(value = "test")
public class TestView extends Div {
  public TestView() {
    MyField myField = new MyField();
    myField.setRequiredIndicatorVisible(false);
    add(myField);
  }

  public class MyField extends CustomField<String> {
    public MyField() {
      add(new TextField());
    }

    @Override
    protected String generateModelValue() {
      return "Test";
    }

    @Override
    protected void setPresentationValue(String newPresentationValue) {

    }
  }
}
```

### Steps to reproduce

Use the example and open the view in the browser, you should see immediately the shown error in the browser console.

### Environment

Vaadin version(s): 24.5.0
OS: Windows

### Browsers

Issue is not browser related

**Comment by web-padawan** [comment]
The method `_setInputs()` is created by Polymer, which is done for all properties marked as `readOnly: true`.
I think this is some kind of a timing issue. But the `checkValidity()` should indeed by updated. I'll make a PR.
