### ISSUE TITLE
IllegalStateException: Can't move a node from one state tree to another | within Popover Component using PreserveOnRefresh annotation

### ISSUE THREAD

**Issue by netsrotr** [vaadin/flow-components#6752]
### Description

We use the Popover Component to implement a kind of advanced tooltip (supporting HTML display). Now we considered that Component interfer with the use of the required vaadin annotation `@PreserveOnRefresh`. If a user press the `F5` browser refresh button, the current view containing a Popover Component produce a `IllegalStateException: Can't move a node from one state tree to another`.

### Expected outcome

No Exception, but restored Popover display state.

### Minimal reproducible example

[Popover-issue-with-PreserveOnRefresh.zip](https://github.com/user-attachments/files/17555139/Popover-issue-with-PreserveOnRefresh.zip)

### Steps to reproduce

1. Start the project using mvn spring-boot:run 
2. Got to localhost:8080 
3. Navigate to the /tooltip/preserved using the "Go to TooltipViewPreserved" button on the main page. 
4. Refresh the browser using F5. (Here the mentioned Exception is thrown) 
5. Go to /tooltip/non-preserved using the "Go to TooltipViewNonPreserved" button on the main page. 
6. Refresh the browser using F5 (Here everything works fine) 

### Environment

Vaadin version(s): 24.5.0, reproducable also with 24.5.2
OS: Windows 11

### Browsers

Chrome, Firefox, Safari, Safari on iOS, Edge

**Comment by web-padawan** [comment]
The issue seems to be related to the "auto-attach" logic. Here's a simplified reproduction from the above repo:

```java
import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.component.html.NativeButton;
import com.vaadin.flow.component.popover.Popover;
import com.vaadin.flow.router.PreserveOnRefresh;
import com.vaadin.flow.router.Route;

@PreserveOnRefresh
@Route("vaadin-popover/preserve")
public class PopoverPreservePage extends Div {

    public PopoverPreservePage() {
        NativeButton button = new NativeButton("Target");
        Div popoverContent = new Div("I'm a popover");

        Popover popover = new Popover(popoverContent);
        popover.setTarget(button);

        // add(button, popover); // This works
        add(button); // This does not work
    }
}
```

As a workaround, you could add the popover to the UI manually, then there is no error on refresh.
