### ISSUE TITLE
Inconsistent Rendering Issue in ComboBox with Custom Renderer When pageSize is Larger Than the Item Count

### ISSUE THREAD

**Issue by JefersonSantos06** [vaadin/flow-components#6810]
### Description

I am facing a specific issue with the `ComboBox` component. The problem occurs when using a custom `renderer` and the number of available items is less than the value set for the `pageSize` property of the `ComboBox`.

1. **Textual Search:**
    - When typing in the search field of the `ComboBox`, the display area where the rendered components should appear is blank. Although the items are present, the component from the `renderer` is not displayed correctly.

2. **Item Selection:**
    - Despite the components not being visible after the search, it is still possible to select the items. Clicking in the area where the items should be displayed selects the item correctly, indicating that the items are present but the components are not being rendered.

### Expected outcome

The components from the `renderer` should be displayed correctly after the search, regardless of the `pageSize` value being greater than the number of items.

### Minimal reproducible example

```java
@Route("")
@PageTitle("Example")
public class ExampleView extends VerticalLayout {

    public static final List<Locale> LOCALES = List.of(
            Locale.ENGLISH, Locale.FRENCH, Locale.GERMAN, Locale.ITALIAN,
            Locale.JAPANESE, Locale.KOREAN, Locale.CHINESE, Locale.ITALY,
            Locale.JAPAN, Locale.CANADA
    );

    public ExampleView() {
        setPadding(true);
        setSpacing(true);
        getStyle().setDisplay(Style.Display.FLEX).setAlignItems(Style.AlignItems.CENTER);

        this.add(new H4("Combobox with default pageSize value (50)"));
        this.add(createComboBox());

        this.add(new Hr());
        this.add(new H4("Combobox with pageSize value 11 (1 more than the number of items)"));
        final var comboBoxPageSize11 = createComboBox();
        comboBoxPageSize11.setPageSize(LOCALES.size() + 1);
        this.add(comboBoxPageSize11);

        this.add(new Hr());
        this.add(new H4("Combobox with pageSize value 10 (exact number of items)"));
        final var comboBoxPageSize10 = createComboBox();
        comboBoxPageSize10.setPageSize(LOCALES.size());
        this.add(comboBoxPageSize10);

        this.add(new Hr());
        this.add(new H4("Combobox with pageSize smaller than the number of items"));
        final var comboBoxPageSizeSmaller = createComboBox();
        comboBoxPageSizeSmaller.setPageSize(LOCALES.size() - 1);
        this.add(comboBoxPageSizeSmaller);
    }

    private static ComboBox<Locale> createComboBox() {
        final var comboBox = new ComboBox<Locale>();
        comboBox.setItems(LOCALES);
        comboBox.setRenderer(new ComponentRenderer<>(locale -> {
            final var spanDisplayLanguage = new Span(locale.getDisplayLanguage(locale));
            final var spanLanguage = new Span(locale.getLanguage());
            return new HorizontalLayout(spanLanguage, spanDisplayLanguage);
        }));
        comboBox.setItemLabelGenerator(locale -> locale.getDisplayLanguage(locale));
        return comboBox;
    }
}
```

### Steps to reproduce

1. Create a `ComboBox` and fill it with a list of items.
2. Use `setRenderer` to display the items in the `ComboBox`.
3. Set the `pageSize` of the `ComboBox` to a value greater than the number of items in the list or fewer items than the default value (50).
4. Start typing in the `ComboBox` to trigger the search functionality.

### Environment

Vaadin Flow: 24.5.4 (Issue observed starting from version 24.5, earlier versions not tested)
OS: macOS Sequoia 15.0.1
Java Version: JDK 21 (JetBrains Runtime 21.0.4 and OpenJDK 21)

### Browsers

Chrome, Firefox, Safari

**Comment by sissbruecker** [comment]
Can confirm that this is a regression in 24.5. It seems it was introduced when bumping web components to 24.5-alpha4 (https://github.com/vaadin/flow-components/commit/854b888caaf311766182406a8dba280bad157c95). The [related release](https://github.com/vaadin/web-components/releases/tag/v24.5.0-alpha4) mentions that this changes combo box to use data provider controller, so might be related to that.
