### ISSUE TITLE
popover race condition / thread-unsafe code

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow-components#6838]
### Description

There is a race condition in Popover static functions. If multiple threads call `Popover.setDefaultHideDelay()` at the same time, that can result in multiple calls to `applyConfiguration()` and multiple registrations of UI init listener.

The easiest way is to mark all static `set*()` functions as `synchronized`. Alternatively, you can use `AtomicInteger` for all static fields (don't forget to make them final!) and use `uiInitListenerRegistered.compareAndSet()` in `applyConfiguration()`.

### Expected outcome

The UI Init Listener is registered at most once, regardless of how many threads call Popover static functions at the same time.

Alternatively, tell the programmer to call those static functions in a service init listener (which is called exactly once), or from a Spring singleton - but this is more complex and more demanding on the user.

### Minimal reproducible example

As is the nature of threading bugs, they are not easy to reproduce. I can create an example program though if you need one 👍 

### Steps to reproduce

1. Create an executor with 10 threads; use CountdownLatch to start them at the same time, then start setting the default Focus Delay in a loop. Alternatively, set default focus delay in a session init listener then start DDOS on the web server, but this is harder.
2. Observe that multiple UI init listeners are registered, because of race condition.

### Environment

Vaadin version(s): 24.5.5+

**Comment by DiegoCardoso** [comment]
Hi!

I was looking at this issue, but I wasn't able to reproduce it. Could you share the code that reproduces this issue?

**Comment by mvysny** [comment]
Alrighty, this code reproduces the issue. It looks completely crazy, so please let me explain.

```java
@Route("")
public class MainView extends VerticalLayout {

    public MainView() {
        add(new Button("Reproduce",
                e -> reproduce()));
    }

    private void reproduce() {
        try {
            printNumberOfUIInitListeners();
            final VaadinService current = VaadinService.getCurrent();

            ExecutorService executorService = Executors.newFixedThreadPool(10);
            final CountDownLatch latch = new CountDownLatch(10);
            final Runnable runnable = () -> {
                VaadinService.setCurrent(current);
                latch.countDown();
                for (int i = 0; i < 100000; i++) {
                    Popover.setDefaultFocusDelay(5);
                }
            };
            final List<? extends Future<?>> list = IntStream.range(0, 10).mapToObj(it -> executorService.submit(runnable)).collect(Collectors.toList());
            for (Future<?> future : list) {
                future.get();
            }
            executorService.shutdown();

            printNumberOfUIInitListeners();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

    }

    public static void printNumberOfUIInitListeners() throws Exception {
        final Field field = VaadinService.class.getDeclaredField("uiInitListeners");
        field.setAccessible(true);
        final List<?> list = (List<?>) field.get(VaadinService.getCurrent());
        System.out.println("UI Init listeners = " + list.size());
    }
}
```
I set up an executor with 10 threads, which then call `Popover.setDefaultFocusDelay(5);` a million times. Then they print the current number of UI init listeners. If the code would be thread-safe, the program would print `0 1` (that is, there were 0 UI init listeners and now there is one - the one which Popover registered). The problem is that the program prints:
```
UI Init listeners = 0
UI Init listeners = 4
```
So, Popover adds four new UI init listeners.

Now, to explain the craziness of the test suite: imagine a situation where a Vaadin app would hit heavy load right after it starts; a MainLayout would then call `Popover.setDefaultFocusDelay(5)`. There is a very tiny chance that multiple of `MainLayouts` get initialized at the same time, reproducing the issue.

This test basically emulates a very unlucky case of 10 MainLayouts being instantiated at the same time, each tries to set the focus delay a million times. Unrealistic, I know, but this is in order to prove that there is a race condition.

The chances of this bug happening in production is very close to zero, but it's not zero. There is a race condition and it can be fixed easily.

**Comment by mvysny** [comment]
If you can't reproduce the issue, please increase the number in the for loop to ten million.
