### ISSUE TITLE
Allow to configure the aria-label of a vaadin-grid-sorter

### ISSUE THREAD

**Issue by kevinkendzia** [vaadin/flow-components#6861]
### Describe your motivation

Right now the aria-label of a vaadin-grid-sorter is set automatically to "Sort by " + its containing text when it's created (see definition of setHeaderRenderer in additional context).
For the project I'm working on that causes 2 problems:

- Headers containing Components without text (e.g. Icons, Icon-Buttons) getting no aria-label at all or a label only containing symbols
- Headers containing multiple text-components getting an aria-label containing all texts mashed together

In both situations I'd like to provide a custom aria-label.

### Describe the solution you'd like

In my opinion a good solution on the java-side could be a builder-method "setAriaLabel()" or even "setAriaLabelProvider()" for the Column-class. This method could take the aria-label-base-text (or a provider) which could be used when creating the vaadin-grid-sorter while prepending "Sort by ".
On the other hand the prefix should also be configurable because of i18n.

### Describe alternatives you've considered

Another possibility could be to use a potentionally set aria-label of the child component and copy it to the vaadin-grid-sorter

### Additional context

document.querySelector("#ROOT-2521314 > div > vaadin-vertical-layout > vaadin-grid").$connector.setHeaderRenderer:

```javascript
grid.$connector.setHeaderRenderer = function(column, options) {
        const { content, showSorter, sorterPath } = options;
        if (content === null) {
          column.headerRenderer = null;
          return;
        }
        column.headerRenderer = singleTimeRenderer((root22) => {
          root22.innerHTML = "";
          let contentRoot = root22;
          if (showSorter) {
            const sorter = document.createElement("vaadin-grid-sorter");
            sorter.setAttribute("path", sorterPath);
            const ariaLabel = content instanceof Node ? content.textContent : content;
            if (ariaLabel) {
              sorter.setAttribute("aria-label", `Sort by ${ariaLabel}`);
            }
            root22.appendChild(sorter);
            contentRoot = sorter;
          }
          if (content instanceof Node) {
            contentRoot.appendChild(content);
          } else {
            contentRoot.textContent = content;
          }
        });
      };
```

**Comment by yuriy-fix** [comment]
Closing in favour of https://github.com/vaadin/web-components/issues/3471
