### ISSUE TITLE
Multiline support for tooltip

### ISSUE THREAD

**Issue by Dudeplayz** [vaadin/flow-components#6865]
### Describe your motivation

It would be nice to have multiline / line-break support in tooltips. I have used this addon https://vaadin.com/directory/component/tooltips4vaadin from the directory and I am replacing them now with the standard vaadin API. This addon rendered line-breaks correctly. So in order to replace it, I have to use Popover instead to add multiline html elements.

### Describe the solution you'd like

Rendering of line-breaks.

### Describe alternatives you've considered

Using Popover.

**Comment by Dudeplayz** [comment]
Got it working by specifying it with CSS:
```css
vaadin-tooltip-overlay::part(content) {
    white-space: pre-wrap;
}
```

Question is still, if this should be a default feature?

**Comment by web-padawan** [comment]
This was previously requested in #5120 and yes, setting `white-space` on the `content` is the proper way to handle it.
IMO we could have an example in the docs illustrating how to do that. Not sure if that deserves a theme variant.
