### ISSUE TITLE
[Checkbox] Required-indicator is visible if checkbox has no label

### ISSUE THREAD

**Issue by glebfox** [vaadin/flow-components#6888]
### Description

Checkbox's JavaDoc says:
> NOTE: The required indicator is only visible when the field has a label...

In fact, the **required-indicator** is visible even if Checkbox has no label, which leads to visual issues - **required-indicator** is located below checkbox:

<img width="374" alt="Screenshot 2024-12-05 at 13 54 39" src="https://github.com/user-attachments/assets/483e3bd1-fc39-43a8-8580-e4264c246110">

### Expected outcome

`Checkbox` hides its `required-indicator` if there is no label set.

### Minimal reproducible example

```java
FormLayout formLayout = new FormLayout();
formLayout.setMaxWidth("25em");

TextField textField1 = new TextField();
textField1.setRequired(true);
formLayout.addFormItem(textField1, "First Name");

TextField textField2 = new TextField();
formLayout.addFormItem(textField2, "Last Name");

Checkbox checkbox = new Checkbox();
checkbox.setRequiredIndicatorVisible(true);
formLayout.addFormItem(checkbox, "Active");
```

### Steps to reproduce

1. Add the snippet above
2. Open the view
3. See the result

### Environment

Vaadin version(s): 24.5.7
OS: macOS 15.1.1

### Browsers

Issue is not browser related

**Comment by web-padawan** [comment]
This is a problem related to `vaadin-form-item` as in this case the required indicator originates from there.
