### ISSUE TITLE
[Popover] Hover delay server side default not matching client side default?

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow-components#6889]
### Description

The Javadoc for the Popover says, that the hover delay (`getHoverDelay()/setHoverDelay()`) is 0, but the client side default seems to be a higher value (maybe around 100ms or so).

This means, that, as long a no value is set on the server, the default value on the server and on the client are not in sync. Also the javadoc is incorrect. 

I did not test the other delays, but might be worth to check while fixing this issue, if they also are out of sync.

### Expected outcome

Javadoc and Java default value should match the client side value.

### Minimal reproducible example

```java
Popover popover = new Popover(new Span("Hello World"));
Button button = new Button("Something");

popover.setTarget(button);
popover.setOpenOnHover(true);
// popover.setHoverDelay(0);
add(button);
```

### Steps to reproduce

1. Add the snippet above
2. Open the view.
3. Hover the button > should take some hundred ms before the popover opens.
4. Active the "setHoverDelay(0)" line of code. 
5. Restart the app / hotswap the code and repeat 3). The Popover should now appear immediately.

### Environment

Vaadin version(s): 24.6.0.beta3
OS: Windows 11

### Browsers

Chrome

**Comment by web-padawan** [comment]
Thanks for reporting. Yes, IIRC based on the DX test feedback the default Popover delays were aligned with Tooltip in https://github.com/vaadin/web-components/pull/7682 but we missed to update JavaDoc accordingly.
