### ISSUE TITLE
Grid: Event after calculate column widths

### ISSUE THREAD

**Issue by sveinnetnordic** [vaadin/flow-components#6891]
### Describe your motivation

I have some ugly JS hack to position a Flex above the grid, aligned with the right position of of the grid last column. Max with for flex is 100% (inside view)

![image](https://github.com/user-attachments/assets/39b66915-18da-4291-b734-49a57d2a044d)

Grid vertical scroll is to the right in picture. The last column may not be visible if some text is long or view is small

### Describe the solution you'd like

A grid event when grid columns is calculated. Get element to get dimension/position for a column/cell.

Pseudo:
```kotlin
        grid.addCalculateColumnWidthsListener {
            val elementToGetPositionLaterInExecuteJs = it.cells.last().element // Cannot getElement() today
            setFlexContainerRightPosition(elementToGetPositionLaterInExecuteJs) } //getBoundingClientRect() etc
        }

```

**What I am missing "most" is `grid.addCalculateColumnWidthsListener` because `element.executeJs("").then { element.executeJs("").then {` is not always working.**

### Describe alternatives you've considered

I have working code:
![image](https://github.com/user-attachments/assets/70fb39ad-d78e-4917-96c8-a19721772fd3)
![image](https://github.com/user-attachments/assets/3ee66131-d5ee-446d-b482-5083d179e4e7)

Flex is set when visible to user. After about 5000 rows is leaded, then the element.executeJs("").then { element.executeJs("") runs
![image](https://github.com/user-attachments/assets/f3b7424d-1a2e-4ec3-9592-5e587a416fcd)

### Additional context

Maybe a place to dispatch a CustomEvent: https://github.com/vaadin/web-components/blob/2dc2b6496e11a550b696d4d1f0548c0ea953983d/packages/grid/src/vaadin-grid-mixin.js#L431

**Comment by yuriy-fix** [comment]
Dear @sveinnetnordic,
The use case described appears to be quite niche. Such behavior should be implemented within the application logic. Please consider overriding the `recalculateColumnWidth` method, prepend another header row or use `ResizeObserver`. For now, we will not proceed with this enhancement, but it could be reconsidered if more common use cases are identified in the future.

**Comment by sveinnetnordic** [comment]
OK, now I agree! Found that ResizeObserver fixed "everything". The code is now simpler, and is much more robust.
![image](https://github.com/user-attachments/assets/aa1ea5b2-142b-4b43-beee-e076c01680ce)
