### ISSUE TITLE
Dialog content _blocked_ on opening custom confirmation Dialog and Notification shown (success or failure)

### ISSUE THREAD

**Issue by netsrotr** [vaadin/flow-components#6911]
### Description

We use many Dialogs in our App (called Editor Windows) to enable users to change entities or other things. These Editors often use kind of _Confirmation_ Dialogs (customized in a way vaadin ConfirmDialog does not offer).
Now we considered a unexpected behavior using these custom confirmation dialog windows together with success- or error notifiactions: if a user confirmed such a dialog, usually the dialog closes and the prcessing result is displayed as a notificaction.
Now at the end of such a flow result in a _blocked_ Editor Window. That means: the user cannot type anything in any text field or press any button with the Editor Window - it blocks all user mouse interactions as long the Editor Window itself gets closed (e.g. via ESC key)

### Expected outcome

The Editor Window (Dialog) should still be able to receive user modifications (typing in TextFields, click checkboxes etc.)

### Minimal reproducible example

See attached project zip

### Steps to reproduce

- Start the project
- Click the `Change more...` button.
- In the editor ensure you can type something within the input fields
- press `Delete (confirmed)` that in turn shows a Vaadin ConfirmDialog, press `Confirm`
- note the success notification
- verify you still can type something within the input fields
- press `Delete (dialog)` that in turn shows a customized Vaadin dialog, press `Yes` 
- note the success notification
- now you can **not* type something within the input fields

### Environment

Vaadin version(s): 24.5.7 also tried 24.6.0.beta3
OS: Windows 11
[Dialog-blocked-issue-flow-spring-24.zip](https://github.com/user-attachments/files/18080741/Dialog-blocked-issue-flow-spring-24.zip)

### Browsers

Chrome

**Comment by web-padawan** [comment]
This is already fixed by https://github.com/vaadin/web-components/pull/8291 which will be included in the next 24.5 patch release (the 24.5.9). Sorry for the inconvenience. We will try to get the fix released this week.
