### ISSUE TITLE
LumoUtility.Cursor.POINTER

### ISSUE THREAD

**Issue by sveinnetnordic** [vaadin/flow-components#6956]
### Describe your motivation

I find my shelf setting style cursor: pointer many places. Maybe LumoUtility.Cursor.POINTER and other valid constants could be added?

### Describe the solution you'd like

LumoUtility.Cursor.POINTER

**Comment by StefanPenndorf** [comment]
Did you try to set the `--lumo-clickable-cursor` CSS variable? See https://vaadin.com/docs/latest/styling/lumo/lumo-style-properties/interaction for details.

**Comment by sveinnetnordic** [comment]
I don't think changing the default is the way to go. Other cursor could be handy like: crosshair, not-allowed, copy ...
Not a big deal, but feels that LumoUtility.Cursor.* is missing
Sample: 
![image](https://github.com/user-attachments/assets/2f989985-834d-4b6c-8459-04f1017a1958)

**Comment by rolfsmeds** [comment]
Adding cursor styles to LumoUtilities could certainly be considered.

However, if you do find yourself setting `cursor:pointer` a lot, @StefanPenndorf's suggestion to make buttons use the pointer cursor as default does make sense. After all, why would you want _some_ buttons to have it, but others not?

**Comment by sveinnetnordic** [comment]
For ordinary buttons I will continue to use Vaadin default. For Div/Span/Button-tertiary-inline etc, not obvious clickable - I use cursor: pointer.

I was thinking that LumuUtility should have the most used CSS, but maybe I only should have styling stuff? Not sure then if LumoUtility.Cursor.* should be include...

**Comment by rolfsmeds** [comment]
Well, "the most used css" varies so much from user to user that it's hard to put a finger on what exactly it would be. As an example, I would definitely not have considered cursor styles to be in that category. This is also why it's a bit difficult to decide what to include in LumoUtility. We've also been considering deprecating it entirely in favor of Tailwind, since that's what a lot of people are used to.

**Comment by sveinnetnordic** [comment]
> Well, "the most used css" varies so much from user to user that it's hard to put a finger on what exactly it would be. As an example, I would definitely not have considered cursor styles to be in that category. This is also why it's a bit difficult to decide what to include in LumoUtility. We've also been considering deprecating it entirely in favor of Tailwind, since that's what a lot of people are used to.

OK! Maybe best to not add it then. I am using LumoUtility a lot, and CSS only if I have to. I close this issue then!
