### ISSUE TITLE
flaky tests in flow dialog module

### ISSUE THREAD

**Issue by manolo** [vaadin/flow-components#777]
These two tests are failing frequently, without a clear pattern.

- DialogWithShortcutIT.dialogOpenedWithListenOnShortcut_dialogReopened_oldShortcutStillWorks[ANY_Chrome_]
- DialogWithShortcutIT.twoModelessDialogsOpenedWithSameShortcutKeyOnListenOn_dialogWithFocusExecuted[ANY_Chrome_]

Couple of examples, but there are many
https://teamcity.vaadin.com/buildConfiguration/VaadinFlowComponents_PullRequestValidation/74967
https://teamcity.vaadin.com/buildConfiguration/VaadinFlowComponents_PullRequestValidation/74934?buildTab=log&focusLine=2&linesState=392.7978

**Comment by denis-anisimov** [comment]
This is a known issue in Flow.

**Comment by pleku** [comment]
> This is a known issue in Flow.

Or rather a known issue between Flow & TB. Related to vaadin/flow#10491
