### ISSUE TITLE
Notification has a default different from the Vaadin Fusion version

### ISSUE THREAD

**Issue by enver-haase** [vaadin/flow-components#779]
This repository's issue tracker is reserved mainly for issues related to the monorepo automation. If you want to report a Vaadin component related issue, please use one of the component repositories, such as
- https://github.com/vaadin/vaadin-grid (for Grid related issues)
- https://github.com/vaadin/vaadin-text-field (Text Field, Text Area, Email Field...)
- https://github.com/vaadin/vaadin-ordered-layout (Vertical/Horizontal Layout, Scroller)
...

IS THE ABOVE TRUE (STILL)?  I thought the multi-repo issue reports are now tied to this one here?

In any case - as you can clearly see by looking at a Vaadin 19.0.2 mixed application (Flow / Fusion) side by side, just calling "showNotification(String)" shows it in the middle in TypeScript but bottom left in Java.

I suggest to streamline the experience in the next LTS.

**Comment by vlukashov** [comment]
Will be fixed in scope of https://github.com/vaadin/vaadin-notification/issues/18
