### ISSUE TITLE
Update the `Icon` Flow component to use `vaadin-icon` instead of `iron-icon`

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow-components#883]
The existing Java `Icon` component should be updated to use the new `vaadin-icon` web component, created in https://github.com/vaadin/web-components/issues/310, rather than the `iron-icon` component which it uses currently. This is done without changing the public API of the component, in order to remove the dependency on Polymer.

**Comment by vlukashov** [comment]
This issue might also be relevant: https://github.com/vaadin/flow-components/issues/1763
@tomivirkki, could you please check if it's feasible to address that issue here?

**Comment by tomivirkki** [comment]
> This issue might also be relevant: #1763
@tomivirkki, could you please check if it's feasible to address that issue here?

@vlukashov same observation as [here](https://github.com/vaadin/flow-components/issues/1763#issuecomment-855840190). It requires new API in the Button component. Can't be fixed in Icon.
