### ISSUE TITLE
Upload multiple files with same names

### ISSUE THREAD

**Issue by lennartfricke** [vaadin/flow-components#910]
When Uploading multiple files with the same name using Upload. I do not find any way to tell which upload causes an event.
The only possibility is to implement an OutputStream with overriden close method but than dispatch into the UI is rather difficult.

It would be nice if the OutputStream or some identifying token is passed through the events.

**Comment by vlukashov** [comment]
Could you please tell us more about your use case and which version of Vaadin you are using?
What do you intend to do in the upload events? What leads to the situation where you have multiple files with the same name, yet you need to differentiate between them in the event listener?

**Comment by lennartfricke** [comment]
We are actually still on Vaadin 8 and solve the same problem ourselves.
We are using the Upload component in some kind of document management context.
The users bulk uploads files, that are previewed and the user is allowed to edit some metadata about them. Afterwards they are stored with that metadata.
Our users often upload documents, that are monthly reports and stored with the same name in different folders on their workstation.
We need to differentiate between them to find out which content finished uploading to preview the correct content.

**Comment by sissbruecker** [comment]
Closing this in favor of https://github.com/vaadin/flow-components/issues/2964
