### ISSUE TITLE
Deprecate `TemplateRenderer` in favor of  `LitRenderer` (Java API)

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow-components#916]
The (Polymer-based) Java [`TemplateRenderer`](https://vaadin.com/api/platform/19.0.6/com/vaadin/flow/data/renderer/TemplateRenderer.html) API (used in ComboBox, Grid, TreeGrid, GridPro, IronList) should be deprecated. A new (Lit-based) `LitRenderer` Java API should be added as a replacement for it.

The old `TemplateRenderer` Java API should still work but should be deprecated.

Before
```java
grid.addColumn(TemplateRenderer.<Order> of(
   "<div on-click='onClick'>[[item.lines.0.title]]</div>")
   .withProperty("lines", Order::getLines)
   .withEventHandler("onClick", order ->
       System.out.println(order.getName() + " clicked"))
   .setHeader("Purchase");
```

After:
grid.addColumn(~TemplateRenderer~.<Order> of("..."));

Also after:
```java
grid.addColumn(LitRenderer.<Order> of(
   "<div @click=${onClick}>${item.lines[0].name}</div>")
   .withProperty("lines", Order::getLines)
   .withEventHandler("onClick", order ->
       System.out.println(order.getName() + " clicked"))
   .setHeader("Purchase");
```

Part of: https://github.com/vaadin/web-components/issues/246

**Comment by knoobie** [comment]
Would it be possible, that the upcoming LitRenderer doesn't suffer from the same problem as the old renderer? https://github.com/vaadin/flow/issues/8629 :)
