### ISSUE TITLE
When creating a button with an icon without text-content, I want to be encouraged to set aria-label for them, so my app can be used by blind people

### ISSUE THREAD

**Issue by pekam** [vaadin/flow-components#93]
@pekam commented on [Mon Sep 25 2017](https://github.com/vaadin/flow/issues/2493)

If a button contains only an icon without text, screen-readers can't read it and blind users can't know what the button does. For this reason there is the `aria-label` attribute.

There should be at least a convenience method for setting this value: `Button::setAriaLabel(String)`

Also it would be good to encourage the use of `aria-label` when having a button without visible text-content. Maybe replacing the icon-only constructor with `Button(Component icon, String ariaLabel)` would do the job, but this might be confusing because we have `Button(String text, Component icon)`

---

@Legioth commented on [Mon Sep 25 2017](https://github.com/vaadin/flow/issues/2493#issuecomment-331824363)

@jouni Doesn't `vaadin-button` automatically set its slot contents as the label?

---

@jouni commented on [Mon Sep 25 2017](https://github.com/vaadin/flow/issues/2493#issuecomment-331863531)

Well, define label. It’s rendered inside the button, yes, and screen readers will pick that up nicely. But when there’s only `<iron-icon icon="plus">` what does the screen reader announce?

---

@Legioth commented on [Mon Sep 25 2017](https://github.com/vaadin/flow/issues/2493#issuecomment-331866447)

Oops. I missed the part in the description that said that this applies when there's only an icon but no text.

Does `ariaLabel` make sense in this context, or would it be more natural to refer to this as an `alt` text? 

It's also not clear to me whether the label text should be a feature of the button or a feature of the icon component? What about cases when the icon is used on its own instead of inside a button?

---

@pekam commented on [Mon Sep 25 2017](https://github.com/vaadin/flow/issues/2493#issuecomment-331876749)

At least currently `Icon` by itself is just a decorative component, since it doesn't support click listeners. So I think setting `ariaLabel` for an `Icon` makes sense only when it's inside eg. `Button`.

**Comment by vursen** [comment]
The `setAriaLabel` method was added to the Button component in 24.1 (https://github.com/vaadin/flow-components/pull/4755).
