### ISSUE TITLE
Unintuitive styling of fields after Binder setBean

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/flow-components#954]
When Binder `setBean` is called with an empty bean while `validatorsDisabled`  is true:
- If the field is a `TextField` bound `asRequired`, it will be cleared and it will be styled as valid.
- If the field is a `Select` bound `asRequired` it will be cleared and it will be styled as *invalid*.

Even while Binder ignores the validation (because of validatorsDisabled), `vaadin-select` will do its own client-side validation and style the field as invalid, while TextField won't.

**Example code**

```
@Route
public class HelloWorldView extends HorizontalLayout {
    private TextField name = new TextField();
    private Select<QueueType> type = new Select<>(QueueType.values());
    final Binder<MyBean> binder = new Binder<>(MyBean.class);

    public HelloWorldView() {

        binder.forField(name).asRequired().bind("name");
        binder.forField(type).asRequired().bind("type");
        binder.setBean(new MyBean());

        Button clear = new Button("Clear");
        clear.addClickListener(event -> {
            binder.setValidatorsDisabled(true);
            binder.setBean(new MyBean());
            binder.setValidatorsDisabled(false);
        });

        VerticalLayout layout = new VerticalLayout();
        layout.add(name);
        layout.add(type);
        layout.add(clear);

        add(layout);
    }
}
  ```
  
** Instructions to reproduce and observed behavior **

1. Navigate to the view and fill values in the fields

![image](https://user-images.githubusercontent.com/11554739/117486094-93a81a00-af3f-11eb-8019-821d8b5d629d.png)

2. Then press "Clear"

![image](https://user-images.githubusercontent.com/11554739/117486132-a15d9f80-af3f-11eb-9d95-57096c040686.png)

3. Now press "Clear" again

![image](https://user-images.githubusercontent.com/11554739/117486178-b20e1580-af3f-11eb-9995-22bc855f2642.png)

**Expected behavior**
After pressing clear _once_ it should have displayed (3)

**Workaround**

Explicitely mark the field as valid after setting the value.
```
binder.setBean(new MyBean());
type.getElement().executeJs("this.invalid=false");
```

**Comment by TatuLund** [comment]
Copied to https://github.com/vaadin/vaadin-select/issues/266
