### ISSUE TITLE
Externalize HasLabel interface for all components that support label

### ISSUE THREAD

**Issue by cdir** [vaadin/flow-components#956]
Many components defines the methods `getLabel()`and `setLabel(String)`. But there is no common interface for those components yet.

There should be an interface for all components that support the label feature so we are able to write some generic code without reflection.

**Comment by tarekoraby** [comment]
Integrating `HasLabel` into Flow components would be beneficial for those migrating from Vaadin 8 as it would serve as a replacement for V8's [AbstractComponent](https://github.com/vaadin/framework/blob/e30226a19564c6ee77064e5178a7665554d57466/server/src/main/java/com/vaadin/ui/AbstractComponent.java) `(get/set)Caption`.

**Comment by mvysny** [comment]
Hello? Anybody working on this?
