### ISSUE TITLE
[20.0] OSGi Export-Package declaration in some artifacts

### ISSUE THREAD

**Issue by maho7791** [vaadin/flow-components#957]
Due to the general bnd configuration in vaadin-flow-componentes/pom.xml. There is no correct Export-Package declaration in some artifacts like:
* TextField (artifact vaadin-text-field-flow)
* AppLayout (artifact vaadin-app-layout-flow)
* OrderedLayout (artifact vaadin-ordered-layout-flow)

Instead, there are Private-Package declarations for packages to be exported:
`Private-Package: com.vaadin.flow.component.orderedlayout`

In the first sight, this seems to be a wrong package name replacement. Everything is fine for e.g. Button (artifact: vaadin-button-flow) or Grid (artifact: vaadin-grid-flow)

Obviously all artifacts with a dash in their names e.g. text-field, app-layout are not replaces in a correct manner

**Comment by stbischof** [comment]
Must be here. https://github.com/vaadin/flow-components/blob/8f0a179c43db1480b19774a8e17c2dd6989fb9db/pom.xml#L173
