### ISSUE TITLE
update Grid to work with the vaadin-grid WC after the <template> API removal

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow-components#985]
Run the existing tests for the Grid component against the branch in web-components where the `<template>` API is removed from the `vaadin-grid` component (see https://github.com/vaadin/web-components/issues/326), and fix any failures.

**Comment by tomivirkki** [comment]
Closed by https://github.com/vaadin/flow-components/pull/1775/commits/a1eed8b612a2776b1f4bdd227d26ee3d34069549 and https://github.com/vaadin/flow-components/pull/1775/commits/da4932eae434b05b2817f053763b468f7f0f2c5d
