### ISSUE TITLE
Include a private constructor to ChartSerialization.

### ISSUE THREAD

**Issue by sosa-vaadin** [vaadin/flow-components#992]
The [ChartSerialization](https://github.com/vaadin/flow-components/blob/master/vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/util/ChartSerialization.java) class only has static methods available. As such, there is no need to use instances of this class.

I suggest adding a private constructor to avoid creating instances of this class since they would be pretty much useless.

**Comment by shivansh29** [comment]
Hey @sosa-vaadin can you assign it to me?
